import assert from "node:assert/strict";
import {createSpecificationProject} from "../../dist/data-layer-specification-project.js";
import {createMemoryDurableProjectRepository} from "../../dist/data-layer-durable-project-repository.js";
import {createInstalledTransportPersistence} from "../../dist/data-layer-installed/project-event-transport/persistence.js";
const repository=createMemoryDurableProjectRepository();
let state=createSpecificationProject({name:"Retail",site:"retail.test",id:kind=>kind+":durable"});
await repository.putProject(state,{active:true});
const storage={getItem:()=>null,setItem:()=>{throw new Error("source saves must not publish an optimistic mirror");}};
const controller=createInstalledTransportPersistence({currentProject:()=>state,storage,
  durable:{repository,settled:async()=>{},ensureProject:async()=>{},refreshProject:async()=>{state=(await repository.loadProject(state.project.id)).state;}},capture:next=>{state=next;}});
const first=await controller.sources.load();
assert.equal(first.sources.length,1);assert.equal(first.sources[0].id,"event-history");
assert.equal((await repository.loadProject(state.project.id)).state.project.eventTransport.observationSources.length,1);
assert.deepEqual(await controller.sources.load(),first);
const save=repository.saveDraft.bind(repository);repository.saveDraft=async()=>{throw new Error("Disk full");};
const next=[...first.sources,{id:"app",name:"Application",path:"event.history",enabled:true}];
await assert.rejects(()=>controller.sources.save(state.project.id,next),/Disk full/);
assert.equal((await controller.sources.load()).sources.length,1);
repository.saveDraft=save;
await controller.sources.save(state.project.id,next);
assert.equal((await controller.sources.load()).sources.length,2);
assert.deepEqual((await repository.loadProject(state.project.id)).state.project.releases,[]);
const {createInstalledSourceSettings}=await import("../../dist/data-layer-installed/project-event-transport/source-controller.js");
let reads=0;const loadProject=repository.loadProject.bind(repository);
repository.loadProject=async(...args)=>{reads++;return loadProject(...args);};
const settings=createInstalledSourceSettings({querySelector:()=>null},controller.sources,async()=>undefined,()=>{},()=>{});
await settings.refresh();const initialReads=reads;
state={...state,project:{...state.project,notes:"Unrelated edit"}};
await settings.refresh();await settings.refresh();
assert.equal(reads,initialReads,"unrelated Draft edits do not reload the full project for source settings");
await controller.sources.save(state.project.id,[...next,{id:"third",name:"Third",path:"thirdQueue",enabled:true}]);
await settings.refresh();assert.equal(settings.configuration().sources.length,3,"source edits still refresh the source configuration");
const loadedReads=reads;state=undefined;await settings.refresh();assert.equal(settings.configuration(),undefined,"closing the project clears the source configuration");
assert.equal(reads,loadedReads);
console.log("Observation source durable migration and failure tests passed");

const repairContext=process.env.SWARMFORGE_TIMEOUT_REPAIR_REGRESSION?JSON.parse(process.env.SWARMFORGE_TIMEOUT_REPAIR_REGRESSION):undefined;
await (await import("./browser/source-mount-regression.mjs")).verifySourceMountRegression(repairContext?.causalCategory==="sandbox capability declaration/first-run routing"?repairContext:undefined);
if(repairContext&&repairContext.causalCategory!=="sandbox capability declaration/first-run routing")await (await import("./browser/migration-fixture-regression.mjs")).verifyMigrationFixtureRegression(repairContext);
