import assert from "node:assert/strict";
import {createSpecificationProject, exportSpecificationProjectState, stageProjectImport} from "../../dist/data-layer-specification-project.js";
import {projectObservationSources, saveObservationSource, removeObservationSource, normalizeObservationPath} from "../../dist/data-layer-project-observation-sources/settings.js";
const state=createSpecificationProject({name:"Retail",site:"retail.test",id:kind=>kind+":retail"});
const legacy=projectObservationSources(state.project);
assert.deepEqual(legacy,[{id:"event-history",name:"History array",path:"queue.history",enabled:true}]);
assert.deepEqual(projectObservationSources(structuredClone(state.project)),legacy);
assert.equal(normalizeObservationPath(" window.dataLayer "),"dataLayer");
for(const path of ["","queue..history","__proto__.history","queue[0]","queue.constructor","queue();"])assert.throws(()=>normalizeObservationPath(path),/valid array path/);
let next=saveObservationSource(state,{id:"marketing",name:"Marketing",path:" dataLayer ",enabled:true});
next=saveObservationSource(next,{id:"app",name:"Application",path:"event.history",enabled:true});
assert.equal(projectObservationSources(next.project).length,3);
assert.equal(next.project.eventTransport.defaultPushPath,"dataLayer");
assert.throws(()=>saveObservationSource(next,{id:"duplicate",name:"Duplicate",path:"window.dataLayer",enabled:true}),/already added/);
assert.throws(()=>saveObservationSource(next,{id:"blank",name:" ",path:"newQueue",enabled:true}),/source name/);
const renamed=saveObservationSource(next,{id:"marketing",name:"Analytics",path:"newQueue",enabled:false});
assert.deepEqual(projectObservationSources(renamed.project)[1],{id:"marketing",name:"Analytics",path:"newQueue",enabled:false});
assert.equal(projectObservationSources(next.project)[1].name,"Marketing");
const imported=stageProjectImport(exportSpecificationProjectState(renamed),state,{projectId:"retail-copy"}).state;
assert.deepEqual(projectObservationSources(imported.project),projectObservationSources(renamed.project));
let empty=renamed;
for(const source of projectObservationSources(empty.project))empty=removeObservationSource(empty,source.id);
assert.deepEqual(projectObservationSources(JSON.parse(JSON.stringify(empty.project))),[]);
assert.deepEqual(empty.project.releases,[]);
assert.deepEqual(projectObservationSources(undefined),[]);
assert.throws(()=>removeObservationSource(next,"unknown"),/source no longer exists/);
console.log("Project observation source settings tests passed");
