import {FLOW_GRAPH_GEOMETRY,clone,inferFlowRelationshipKind,legacyBindingOccurrence,relationshipEndpoint,relationshipPorts,storedGraph} from "../data-layer-flow-graph.js";
import type {DocumentaryPageFrameRecord,FlowCatalog,FlowGraph,FlowGraphProjection,FlowConnectionEndpoint,FlowLaneBand,FlowNode,FlowRelationship,FlowObligation,FreePageRegion} from "../data-layer-flow-graph.js";
import type {ProjectEntity,SpecificationProject} from "../utilities/data-layer/schemas.js";
export {flowOutline,flowRelationshipText,inspectFlowGraph} from "./projection-inspection.js";
import {inspectFlowGraph} from "./projection-inspection.js";
export function projectFlowGraph(project:SpecificationProject,flowId:string):FlowGraphProjection{
  const flow=project.collections.flows.find(({id})=>id===flowId);if(!flow)throw new Error(`Unknown Flow ${flowId}`);
  const stored=storedGraph(project,flowId),lanes=stored.sections.map(clone),frameById=new Map(stored.pageFrames.map((frame)=>[frame.id,frame])),freeFrames=stored.pageFrames.filter(({freePageRegion})=>Boolean(freePageRegion)),legacyFreeFrames=stored.occurrences.filter(({freePageFrame})=>freePageFrame),freeFrameById=new Map([...freeFrames,...legacyFreeFrames].map((frame)=>[frame.id,frame])),frameSize=(frame:DocumentaryPageFrameRecord)=>{const children=stored.occurrences.filter(({pageFrameId})=>pageFrameId===frame.id),width=Math.max(FLOW_GRAPH_GEOMETRY.pageFrameMinWidth,...children.map((child)=>Number((child.position as {x?:number}|undefined)?.x??24)+FLOW_GRAPH_GEOMETRY.eventWidth+FLOW_GRAPH_GEOMETRY.pageFrameChildRightPadding)),height=Math.max(FLOW_GRAPH_GEOMETRY.pageFrameMinHeight,...children.map((child)=>Number((child.position as {y?:number}|undefined)?.y??70)+FLOW_GRAPH_GEOMETRY.eventHeight+FLOW_GRAPH_GEOMETRY.pageFrameChildBottomPadding));return{width,height};},laneBands:FlowLaneBand[]=stored.sections.map((section)=>{const bounds=(section.bounds as {x?:number;y?:number;width?:number;height?:number}|undefined)??{};return{id:section.id,name:section.name,x:Number(bounds.x??20),y:Number(bounds.y??40),width:Number(bounds.width??640),height:Number(bounds.height??190)};}),sectionById=new Map(stored.sections.map((section)=>[section.id,section])),namedWidth=Math.max(900,...stored.pageFrames.map((frame)=>Number(frame.position.x??40)+frameSize(frame).width+60));
  const frameEndpoints:FlowConnectionEndpoint[]=stored.pageFrames.map((frame)=>{const page=project.collections.pages.find(({id})=>id===frame.pageId),size=frameSize(frame),section=frame.sectionId?sectionById.get(frame.sectionId):undefined,x=Number(frame.position.x??40),y=Number(frame.position.y??40),lane=section?.name??"Outside Sections",siblings=stored.pageFrames.filter(({pageId})=>pageId===frame.pageId),instance=siblings.findIndex(({id})=>id===frame.id)+1,baseName=page?.name??frame.pageId,name=siblings.length>1?`${baseName} instance ${instance}`:baseName;return{kind:"page-frame",id:frame.id,name,pageId:frame.pageId,...(frame.sectionId?{sectionId:frame.sectionId}:{}),layout:{lane,x,y},width:size.width,height:size.height};}),frameEndpointById=new Map(frameEndpoints.map((endpoint)=>[endpoint.id,endpoint]));
  const nodes:FlowNode[]=stored.occurrences.filter(({freePageFrame})=>!freePageFrame).map((occurrence)=>{
    const page=project.collections.pages.find(({id})=>id===occurrence.pageId),binding=legacyBindingOccurrence(occurrence)?((page?.contextEventBindings as ProjectEntity[]|undefined)??[]).find(({id})=>id===occurrence.contextBindingId):undefined,eventId=String(binding?.eventId??occurrence.eventId??""),event=project.collections.events.find(({id})=>id===eventId),position=occurrence.position as {x?:number;y?:number}|undefined,containingFrame=frameById.get(String(occurrence.pageFrameId??"")),containingEndpoint=frameEndpointById.get(String(occurrence.pageFrameId??"")),parentFree=freeFrameById.get(String(occurrence.pageFrameId??occurrence.freePageFrameId??"")),freePageRegion=(parentFree?.freePageRegion??"after-lanes") as FreePageRegion,layout=containingEndpoint?{lane:containingEndpoint.layout.lane,x:containingEndpoint.layout.x+Number(position?.x??24),y:containingEndpoint.layout.y+Number(position?.y??70)}:position&&typeof position.y==="number"?(parentFree?{lane:freePageRegion,x:Number(position.x??30),y:position.y}:typeof occurrence.lane==="string"?{lane:occurrence.lane,x:Number(position.x??30),y:position.y}:undefined):undefined;void containingFrame;
    return{id:occurrence.id,name:String(event?.name??occurrence.name),eventId,pageId:String(occurrence.pageId??""),...(occurrence.pageFrameId?{pageFrameId:String(occurrence.pageFrameId)}:{}),...(parentFree?{freePageFrameId:parentFree.id,freePageRegion}:{}),role:"interaction",...(typeof occurrence.trigger==="string"?{trigger:occurrence.trigger}:binding?.trigger?{trigger:String(binding.trigger)}:{}),obligation:(typeof occurrence.obligation==="string"?occurrence.obligation:occurrence.optional?"Optional":"Required") as FlowObligation,expectedMinimum:Number(occurrence.minimum??1),...(occurrence.maximum!==undefined?{expectedMaximum:Number(occurrence.maximum)}:{}),...(layout?{layout}:{})};
  }),connectionEndpoints=[...frameEndpoints],relationships:FlowRelationship[]=stored.relationships.flatMap((edge)=>{const sourceEndpoint=relationshipEndpoint(edge,"source"),targetEndpoint=relationshipEndpoint(edge,"target");if(sourceEndpoint?.kind!=="page-frame"||targetEndpoint?.kind!=="page-frame")return[];const{sourcePort,targetPort}=relationshipPorts(edge),kind=inferFlowRelationshipKind(sourcePort,targetPort)??"expected_next";return[{id:edge.id,sourceEndpoint,targetEndpoint,sourceNodeId:sourceEndpoint.id,targetNodeId:targetEndpoint.id,sourcePort,targetPort,kind,...(typeof edge.group==="string"?{group:edge.group}:{}),...(typeof edge.label==="string"&&edge.label?{label:edge.label}:{}),...(typeof edge.documentationCondition==="string"?{documentationCondition:edge.documentationCondition}:{}),...(typeof edge.expectation==="string"?{expectation:edge.expectation}:{})}];}),graph:FlowGraph={id:flow.id,name:flow.name,purpose:String(flow.purpose??flow.description??""),nodes,connectionEndpoints,relationships},catalog:FlowCatalog={propertySets:project.collections.propertySets.map((group)=>clone(group)),pages:project.collections.pages.map((page)=>clone(page)),events:project.collections.events.map((event)=>clone(event))};return{projectName:project.name,lanes,laneBands,graph,catalog,diagnostics:inspectFlowGraph(graph,catalog)};
}
