import {FLOW_GRAPH_GEOMETRY,type FlowPortSide,type FlowLayout} from "../data-layer-flow-graph.js";
export const nodeWidth=FLOW_GRAPH_GEOMETRY.eventWidth;
export const nodeHeight=FLOW_GRAPH_GEOMETRY.eventHeight;
export const q=<T extends Element>(selector:string,root:ParentNode=document):T=>{const element=root.querySelector<T>(selector);if(!element)throw new Error(`Missing ${selector}`);return element;};
export const svg=<K extends keyof SVGElementTagNameMap>(tag:K):SVGElementTagNameMap[K]=>document.createElementNS("http://www.w3.org/2000/svg",tag);
export const button=(text:string,action:()=>void):HTMLButtonElement=>{const control=document.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",action);return control;};
export const entityName=(entities:readonly {id:string;name:string}[],id:unknown,fallback="Unknown"):string=>entities.find((entity)=>entity.id===id)?.name??fallback;
export const elementByData=<T extends HTMLElement|SVGElement>(attribute:string,id:string):T|undefined=>Array.from(document.querySelectorAll<T>(`[${attribute}]`)).find((element)=>element.getAttribute(attribute)===id);
export const flowPortPoint=(layout:{x:number;y:number},size:{width:number;height:number},port:FlowPortSide):{x:number;y:number}=>port==="left"?{x:layout.x,y:layout.y+size.height/2}:port==="right"?{x:layout.x+size.width,y:layout.y+size.height/2}:port==="top"?{x:layout.x+size.width/2,y:layout.y}:{x:layout.x+size.width/2,y:layout.y+size.height};
export function flowEdgeGeometry(source:{x:number;y:number},target:{x:number;y:number},sourceSize:{width:number;height:number}={width:nodeWidth,height:nodeHeight},targetSize:{width:number;height:number}=sourceSize,sourcePort:FlowPortSide="right",targetPort:FlowPortSide="left"):{startX:number;startY:number;endX:number;endY:number;arrow:string}{const start=flowPortPoint(source,sourceSize,sourcePort),end=flowPortPoint(target,targetSize,targetPort),startX=start.x,startY=start.y,endX=end.x,endY=end.y,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),unitX=length<0.001?1:dx/length,unitY=length<0.001?0:dy/length,baseX=endX-unitX*12,baseY=endY-unitY*12,normalX=-unitY*7,normalY=unitX*7;return{startX,startY,endX,endY,arrow:`${baseX+normalX},${baseY+normalY} ${endX},${endY} ${baseX-normalX},${baseY-normalY}`};}
export const ownsPointerDrag=(activePointerId:number|undefined,eventPointerId:number):boolean=>activePointerId!==undefined&&activePointerId===eventPointerId;
export function restorePointerCancellationFocus(target:{readonly isConnected:boolean;focus():void},scheduleMicrotask:(callback:()=>void)=>unknown=(callback)=>queueMicrotask(callback),scheduleSettledTask:(callback:()=>void)=>unknown=(callback)=>setTimeout(callback,0)):void{const restore=()=>{if(target.isConnected)target.focus();};restore();scheduleMicrotask(restore);scheduleSettledTask(restore);}
