import {safeFlowVisualArchivePath} from "../flow-visual-zip.js";
import {validateExcelTemplatePrototype,type ExcelTemplateArea,type ExcelTemplateCell,type ExcelTemplatePrototype} from "./excel-template.js";
import {type DocumentationTemplateKind} from "./template-contract.js";

export interface ExcelWorkbookFinding {location:string;message:string}
interface ZipEntry {name:string;method:number;compressed:number;size:number;offset:number;flags:number}
const decoder=new TextDecoder();
const u16=(bytes:Uint8Array,offset:number)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint16(offset,true);
const u32=(bytes:Uint8Array,offset:number)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(offset,true);
const xmlText=(value:string)=>value.replace(/<[^>]*>/gu,"").replaceAll("&quot;",'"').replaceAll("&apos;","'").replaceAll("&lt;","<").replaceAll("&gt;",">").replaceAll("&amp;","&");

async function directory(source:Blob):Promise<ZipEntry[]>{
  const tailOffset=Math.max(0,source.size-65_557),tail=new Uint8Array(await source.slice(tailOffset).arrayBuffer());let end=-1;
  for(let index=tail.length-22;index>=0;index-=1)if(u32(tail,index)===0x06054b50){end=index;break;}
  if(end<0)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");
  const count=u16(tail,end+10),directorySize=u32(tail,end+12),directoryOffset=u32(tail,end+16);
  if(count>2_000)throw new DOMException("The workbook has too many parts.","QuotaExceededError");
  if(directoryOffset+directorySize>source.size)throw new DOMException("The workbook package is unsafe.","DataError");
  const bytes=new Uint8Array(await source.slice(directoryOffset,directoryOffset+directorySize).arrayBuffer()),entries:ZipEntry[]=[],names=new Set<string>();let cursor=0,total=0;
  while(cursor<bytes.length){
    if(cursor+46>bytes.length||u32(bytes,cursor)!==0x02014b50)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");
    const flags=u16(bytes,cursor+8),method=u16(bytes,cursor+10),compressed=u32(bytes,cursor+20),size=u32(bytes,cursor+24),nameLength=u16(bytes,cursor+28),extraLength=u16(bytes,cursor+30),commentLength=u16(bytes,cursor+32),offset=u32(bytes,cursor+42),name=decoder.decode(bytes.slice(cursor+46,cursor+46+nameLength)),safeName=name.endsWith("/")?name.slice(0,-1):name;
    if(!safeName||!safeFlowVisualArchivePath(safeName)||names.has(name))throw new DOMException("The workbook package is unsafe.","DataError");
    if(flags&1)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");if(method!==0&&method!==8)throw new DOMException(`Unsupported workbook compression in ${name}.`,"NotSupportedError");
    names.add(name);total+=size;if(total>50*1024*1024)throw new DOMException("The workbook expands beyond 50 MiB.","QuotaExceededError");entries.push({name,method,compressed,size,offset,flags});cursor+=46+nameLength+extraLength+commentLength;
  }
  if(entries.length!==count)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");return entries;
}
async function entryBody(source:Blob,entry:ZipEntry):Promise<Uint8Array>{const header=new Uint8Array(await source.slice(entry.offset,entry.offset+30).arrayBuffer());if(header.length!==30||u32(header,0)!==0x04034b50)throw new DOMException(`Workbook part ${entry.name} is broken.`,"DataError");if((u16(header,6)&1)!==0)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");const start=entry.offset+30+u16(header,26)+u16(header,28),compressed=source.slice(start,start+entry.compressed);if(start+entry.compressed>source.size)throw new DOMException(`Workbook part ${entry.name} is broken.`,"DataError");if(entry.method===0){const bytes=new Uint8Array(await compressed.arrayBuffer());if(bytes.length!==entry.size)throw new DOMException(`Workbook part ${entry.name} has an invalid declared size.`,"DataError");return bytes;}const Constructor=DecompressionStream as unknown as new(format:string)=>DecompressionStream,reader=compressed.stream().pipeThrough(new Constructor("deflate-raw")).getReader(),chunks:Uint8Array[]=[];let length=0;for(;;){const{done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>entry.size||length>50*1024*1024){await reader.cancel();throw new DOMException(`Workbook part ${entry.name} exceeds its declared size.`,"DataError");}chunks.push(value);}if(length!==entry.size)throw new DOMException(`Workbook part ${entry.name} has an invalid declared size.`,"DataError");const bytes=new Uint8Array(length);let cursor=0;for(const chunk of chunks){bytes.set(chunk,cursor);cursor+=chunk.length;}return bytes;}

const attributes=(source:string)=>Object.fromEntries([...source.matchAll(/([A-Za-z:]+)=["']([^"']*)["']/gu)].map(([,key,value])=>[key!,value!]));
const relationshipOwner=(name:string)=>name==="_rels/.rels"?"":name.replace(/(^|\/)_rels\/([^/]+)\.rels$/u,"$1$2");
const internalTarget=(relationshipName:string,target:string):string|undefined=>{if(target.startsWith("/"))return target.slice(1);const owner=relationshipOwner(relationshipName),base=owner.includes("/")?owner.slice(0,owner.lastIndexOf("/")+1):"",segments=`${base}${target}`.split("/"),normal:string[]=[];for(const segment of segments){if(!segment||segment===".")continue;if(segment===".."){if(!normal.length)return undefined;normal.pop();}else normal.push(segment);}const value=normal.join("/");return safeFlowVisualArchivePath(value)?value:undefined;};
interface ExcelCell {address:string;value:unknown;style:unknown}
interface ExcelRow {eachCell(options:{includeEmpty:boolean},visit:(cell:ExcelCell)=>void):void}
interface ExcelTable {table:{columns:{name:string}[];rows?:unknown[][];tableRef?:string}}
interface ExcelWorksheet {name:string;state?:string;model?:{merges?:string[]};eachRow(options:{includeEmpty:boolean},visit:(row:ExcelRow)=>void):void;getCell(row:number,column:number):{value:unknown};getTable(name:string):ExcelTable}
interface ExcelWorkbook {worksheets:ExcelWorksheet[];definedNames:{model:{name:string;ranges:string[]}[]};xlsx:{load(bytes:ArrayBuffer):Promise<void>}}
interface ExcelJsGlobal {Workbook:new()=>ExcelWorkbook}
const excelJs=():ExcelJsGlobal=>{const value=(globalThis as typeof globalThis&{ExcelJS?:ExcelJsGlobal}).ExcelJS;if(!value)throw new Error("The packaged Excel template parser is unavailable.");return value;};
const cellValue=(value:unknown):string|number|boolean=>typeof value==="string"||typeof value==="number"||typeof value==="boolean"?value:value==null?"":String(value);
const tableRows=(sheet:ExcelWorksheet,name:string,columns:readonly string[]):unknown[][]=>{let table:ExcelTable;try{table=sheet.getTable(name);}catch{throw new Error(`Template Guide must contain Excel table ${name}.`);}const actual=table.table.columns.map(({name:column})=>column);if(JSON.stringify(actual)!==JSON.stringify(columns))throw new Error(`${name} must have columns ${columns.join(", ")}.`);if(table.table.rows)return table.table.rows;const ref=/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/u.exec(table.table.tableRef??"");if(!ref)return[];const columnNumber=(letters:string)=>[...letters].reduce((value,letter)=>value*26+letter.charCodeAt(0)-64,0),left=columnNumber(ref[1]!),right=columnNumber(ref[3]!),top=Number(ref[2]),bottom=Number(ref[4]),rows:unknown[][]=[];for(let row=top+1;row<=bottom;row+=1)rows.push(Array.from({length:right-left+1},(_,offset)=>sheet.getCell(row,left+offset).value));return rows;};
const normalizeRange=(raw:string):string|undefined=>{const match=/^'?Template'?!(\$?[A-Z]+\$?[1-9]\d*(?::\$?[A-Z]+\$?[1-9]\d*)?)$/u.exec(raw);return match?.[1]?.replaceAll("$","");};
const workbookPrototype=(workbook:ExcelWorkbook,expectedKind?:DocumentationTemplateKind):{prototype?:ExcelTemplatePrototype;findings:ExcelWorkbookFinding[]}=>{
  const findings:ExcelWorkbookFinding[]=[],template=workbook.worksheets.find(({name})=>name==="Template"),guide=workbook.worksheets.find(({name})=>name==="Template Guide");
  if(!template)findings.push({location:"workbook",message:"Template worksheet cannot be found. Download guided starter."});
  if(!guide)findings.push({location:"workbook",message:"Template Guide worksheet cannot be found. Download guided starter."});
  if(!template||!guide)return{findings};if(guide.state==="hidden"||guide.state==="veryHidden")findings.push({location:"Template Guide",message:"Template Guide must remain visible."});
  let settings:unknown[][]=[],areaRows:unknown[][]=[];try{settings=tableRows(guide,"TemplateSettings",["Setting","Value"]);}catch(error){findings.push({location:"Template Guide",message:(error as Error).message});}try{areaRows=tableRows(guide,"TemplateAreas",["Area","Type","Source","Direction"]);}catch(error){findings.push({location:"Template Guide",message:(error as Error).message});}
  const values=new Map(settings.map(row=>[String(row[0]??"").trim(),String(row[1]??"").trim()])),contract=values.get("Contract"),kind=values.get("Kind") as DocumentationTemplateKind|undefined;
  if(contract!=="2")findings.push({location:"TemplateSettings",message:"Contract must be 2. Download guided starter."});
  if(!kind||!["overview","flow","matrix","profile"].includes(kind))findings.push({location:"TemplateSettings",message:"Kind must be overview, flow, matrix, or profile."});
  if(kind&&expectedKind&&kind!==expectedKind)findings.push({location:"TemplateSettings",message:`The workbook declares ${kind}, not ${expectedKind}.`});
  const names=new Map((workbook.definedNames.model??[]).map(item=>[item.name,item.ranges.map(normalizeRange).filter((range):range is string=>Boolean(range))]));
  const areas:ExcelTemplateArea[]=[];
  for(const row of areaRows){const name=String(row[0]??"").trim(),type=String(row[1]??"").trim().toLowerCase(),source=String(row[2]??"").trim(),direction=String(row[3]??"").trim().toLowerCase(),ranges=names.get(name)??[];if(!name)continue;if(ranges.length!==1){findings.push({location:`named area ${name}`,message:`Repeat area ${name} cannot be found. Select the intended Template cells and define the named area ${name}.`});continue;}if(type==="repeat"&&(direction==="across"||direction==="down"))areas.push({name,type:"repeat",source,direction,range:ranges[0]!});else if(type==="image"&&source==="theme.logo"&&!direction)areas.push({name,type:"image",source:"theme.logo",range:ranges[0]!});else findings.push({location:`TemplateAreas ${name}`,message:type==="repeat"?`${name} needs Direction Across or Down.`:`${name} must use supported Type Repeat or Image.`});}
  const cells:ExcelTemplateCell[]=[];template.eachRow({includeEmpty:true},row=>row.eachCell({includeEmpty:true},cell=>{if(cell.value!==null&&cell.value!==undefined||Object.keys(cell.style as object).length)cells.push({address:cell.address,value:cellValue(cell.value),style:structuredClone(cell.style)});}));
  if(!kind)return{findings};const prototype:ExcelTemplatePrototype={kind,contractVersion:2,worksheetName:"Template",cells,areas,merges:[...(template.model?.merges??[])]},geometry=validateExcelTemplatePrototype(prototype);for(const finding of geometry.findings)findings.push({location:finding.cell?`Template ${finding.cell}`:`named area ${finding.area??"setup"}`,message:finding.repair?`${finding.message} ${finding.repair}`:finding.message});return{prototype,findings};
};

export interface ExcelWorkbookInspection {kind?:DocumentationTemplateKind;contractVersion?:2;bindings:string[];areas:{name:string;type:"repeat"|"image";source:string;direction?:"across"|"down";range:string;itemPrefix?:string;parent?:string}[]}
const itemPrefix=(source:string)=>source.endsWith(".pages")?"page":source.endsWith(".events")?"event":source.endsWith(".cells")?"cell":source.endsWith(".concepts")?"concept":source.endsWith(".fields")?"field":"row";
const inspection=(prototype:ExcelTemplatePrototype|undefined):ExcelWorkbookInspection=>{if(!prototype)return{bindings:[],areas:[]};const bindings=[...new Set(prototype.cells.flatMap(cell=>[...String(cell.value).matchAll(/\{\{\s*([a-z][a-zA-Z0-9.]*)\s*\}\}/gu)].map(([,path])=>path!)))],areas=prototype.areas.map(area=>{const parent=prototype.areas.filter(candidate=>candidate.type==="repeat"&&candidate.name!==area.name&&containsRange(candidate.range,area.range)).sort((left,right)=>rangeSize(left.range)-rangeSize(right.range))[0];return{name:area.name,type:area.type,source:area.source,...(area.type==="repeat"?{direction:area.direction,itemPrefix:itemPrefix(area.source)}:{}),range:area.range,...(parent?{parent:parent.name}:{})};});return{kind:prototype.kind,contractVersion:2,bindings,areas};};
const bounds=(range:string)=>{const points=range.split(":").map(value=>{const match=/^([A-Z]+)(\d+)$/u.exec(value)!;let column=0;for(const letter of match[1]!)column=column*26+letter.charCodeAt(0)-64;return{row:Number(match[2]),column};});return{top:points[0]!.row,left:points[0]!.column,bottom:(points[1]??points[0])!.row,right:(points[1]??points[0])!.column};};
const containsRange=(outer:string,inner:string)=>{const left=bounds(outer),right=bounds(inner);return left.top<=right.top&&left.left<=right.left&&left.bottom>=right.bottom&&left.right>=right.right;};
const rangeSize=(range:string)=>{const value=bounds(range);return(value.bottom-value.top+1)*(value.right-value.left+1);};

export async function validateExcelTemplateWorkbook(source:Blob,expectedKind?:DocumentationTemplateKind):Promise<{valid:boolean;kind?:DocumentationTemplateKind;contractVersion?:2;findings:ExcelWorkbookFinding[];entryCount:number;unpackedBytes:number;inspection:ExcelWorkbookInspection}>{
  const findings:ExcelWorkbookFinding[]=[];if(source.size>10*1024*1024)return{valid:false,findings:[{location:"workbook",message:"The Excel template is too large."}],entryCount:0,unpackedBytes:0,inspection:{bindings:[],areas:[]}};let entries:ZipEntry[];try{entries=await directory(source);}catch(error){return{valid:false,findings:[{location:"workbook",message:error instanceof Error?error.message:String(error)}],entryCount:0,unpackedBytes:0,inspection:{bindings:[],areas:[]}};}
  const byName=new Map(entries.map(entry=>[entry.name,entry])),required=["[Content_Types].xml","_rels/.rels","xl/workbook.xml"];for(const name of required)if(!byName.has(name))findings.push({location:name,message:`The workbook is missing ${name}.`});const unsupported=/^(?:xl\/(?:externalLinks|connections|embeddings|charts|pivotTables|pivotCache|slicers|activeX|ctrlProps)|customXml|word|ppt)\//u;for(const{ name }of entries)if(unsupported.test(name)||/vbaProject|activeX|oleObject|signature|\.bin$/iu.test(name))findings.push({location:name,message:"Use inert macro-free workbook content."});
  const readable=entries.filter(({name})=>/\.(?:xml|rels)$/u.test(name)),texts=new Map<string,string>();for(const entry of readable)try{texts.set(entry.name,decoder.decode(await entryBody(source,entry)));}catch(error){findings.push({location:entry.name,message:error instanceof Error?error.message:String(error)});}for(const[name,text]of texts){if(/<f(?:\s|>)/u.test(text))findings.push({location:name,message:"Remove workbook formulas."});if(name.endsWith(".rels")){for(const match of text.matchAll(/<Relationship\b([^>]*)\/?>(?:<\/Relationship>)?/gu)){const attrs=attributes(match[1]!),external=attrs.TargetMode?.toLowerCase()==="external";if(external){findings.push({location:name,message:"Remove external workbook content."});continue;}const target=attrs.Target&&internalTarget(name,attrs.Target);if(!target||!byName.has(target))findings.push({location:name,message:`Relationship ${attrs.Id??"(unnamed)"} has a broken target ${attrs.Target??""}.`});if(/(?:chart|pivot|slicer|connection|oleObject|control|externalLink)/iu.test(attrs.Type??"")||/\/package$/iu.test(attrs.Type??""))findings.push({location:name,message:`Relationship ${attrs.Id??"(unnamed)"} uses unsupported workbook content.`});}}
    if(/xl\/drawings\/drawing\d*\.xml$/u.test(name)&&/<xdr:(?:graphicFrame|sp|cxnSp|contentPart)\b/u.test(text))findings.push({location:name,message:"Use only embedded PNG, JPEG, or GIF worksheet images."});
  }
  const contentTypes=texts.get("[Content_Types].xml")??"";if(/macroEnabled|vbaProject|activeX|oleObject|embeddedPackage|chart|pivot|slicer|addin/iu.test(contentTypes))findings.push({location:"[Content_Types].xml",message:"Use inert macro-free workbook content."});for(const match of contentTypes.matchAll(/<(?:Default|Override)\b([^>]*)\/?>(?:<\/(?:Default|Override)>)?/gu)){const attrs=attributes(match[1]!);if(attrs.Extension&&["png","jpg","jpeg","gif","xml","rels"].includes(attrs.Extension.toLowerCase()))continue;if(attrs.ContentType?.startsWith("image/")&&!/[+\/]?(?:png|jpeg|gif)$/iu.test(attrs.ContentType))findings.push({location:"[Content_Types].xml",message:`Unsupported embedded image content type ${attrs.ContentType}.`});}
  let prototype:ExcelTemplatePrototype|undefined;if(findings.length===0)try{const workbook=new (excelJs().Workbook)();await workbook.xlsx.load(await source.arrayBuffer());const parsed=workbookPrototype(workbook,expectedKind);prototype=parsed.prototype;findings.push(...parsed.findings);}catch(error){findings.push({location:"workbook",message:error instanceof Error?error.message:String(error)});}const inspected=inspection(prototype);
  return{valid:findings.length===0,...(inspected.kind?{kind:inspected.kind,contractVersion:2 as const}:{}),findings,entryCount:entries.length,unpackedBytes:entries.reduce((sum,{size})=>sum+size,0),inspection:inspected};
}
