import {safeFlowVisualArchivePath} from "../flow-visual-zip.js";
import {parseExcelTemplateDirective,validateExcelTemplatePrototype,type ExcelTemplateDirectiveCell} from "./excel-template.js";
import {type DocumentationTemplateKind} from "./template-contract.js";

export interface ExcelWorkbookFinding {location:string;message:string}
interface ZipEntry {name:string;method:number;compressed:number;size:number;offset:number;flags:number}
const decoder=new TextDecoder();
const u16=(bytes:Uint8Array,offset:number)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint16(offset,true);
const u32=(bytes:Uint8Array,offset:number)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(offset,true);
const xmlText=(value:string)=>value.replace(/<[^>]*>/gu,"").replaceAll("&quot;",'"').replaceAll("&apos;","'").replaceAll("&lt;","<").replaceAll("&gt;",">").replaceAll("&amp;","&");

async function directory(source:Blob):Promise<ZipEntry[]>{
  const tailOffset=Math.max(0,source.size-65_557),tail=new Uint8Array(await source.slice(tailOffset).arrayBuffer());let end=-1;
  for(let index=tail.length-22;index>=0;index-=1)if(u32(tail,index)===0x06054b50){end=index;break;}
  if(end<0)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");
  const count=u16(tail,end+10),directorySize=u32(tail,end+12),directoryOffset=u32(tail,end+16);
  if(count>2_000)throw new DOMException("The workbook has too many parts.","QuotaExceededError");
  if(directoryOffset+directorySize>source.size)throw new DOMException("The workbook package is unsafe.","DataError");
  const bytes=new Uint8Array(await source.slice(directoryOffset,directoryOffset+directorySize).arrayBuffer()),entries:ZipEntry[]=[],names=new Set<string>();let cursor=0,total=0;
  while(cursor<bytes.length){
    if(cursor+46>bytes.length||u32(bytes,cursor)!==0x02014b50)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");
    const flags=u16(bytes,cursor+8),method=u16(bytes,cursor+10),compressed=u32(bytes,cursor+20),size=u32(bytes,cursor+24),nameLength=u16(bytes,cursor+28),extraLength=u16(bytes,cursor+30),commentLength=u16(bytes,cursor+32),offset=u32(bytes,cursor+42),name=decoder.decode(bytes.slice(cursor+46,cursor+46+nameLength)),safeName=name.endsWith("/")?name.slice(0,-1):name;
    if(!safeName||!safeFlowVisualArchivePath(safeName)||names.has(name))throw new DOMException("The workbook package is unsafe.","DataError");
    if(flags&1)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");if(method!==0&&method!==8)throw new DOMException(`Unsupported workbook compression in ${name}.`,"NotSupportedError");
    names.add(name);total+=size;if(total>50*1024*1024)throw new DOMException("The workbook expands beyond 50 MiB.","QuotaExceededError");entries.push({name,method,compressed,size,offset,flags});cursor+=46+nameLength+extraLength+commentLength;
  }
  if(entries.length!==count)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");return entries;
}
async function entryBody(source:Blob,entry:ZipEntry):Promise<Uint8Array>{const header=new Uint8Array(await source.slice(entry.offset,entry.offset+30).arrayBuffer());if(header.length!==30||u32(header,0)!==0x04034b50)throw new DOMException(`Workbook part ${entry.name} is broken.`,"DataError");if((u16(header,6)&1)!==0)throw new DOMException("Choose a valid unencrypted .xlsx.","DataError");const start=entry.offset+30+u16(header,26)+u16(header,28),compressed=source.slice(start,start+entry.compressed);if(start+entry.compressed>source.size)throw new DOMException(`Workbook part ${entry.name} is broken.`,"DataError");if(entry.method===0){const bytes=new Uint8Array(await compressed.arrayBuffer());if(bytes.length!==entry.size)throw new DOMException(`Workbook part ${entry.name} has an invalid declared size.`,"DataError");return bytes;}const Constructor=DecompressionStream as unknown as new(format:string)=>DecompressionStream,reader=compressed.stream().pipeThrough(new Constructor("deflate-raw")).getReader(),chunks:Uint8Array[]=[];let length=0;for(;;){const{done,value}=await reader.read();if(done)break;length+=value.byteLength;if(length>entry.size||length>50*1024*1024){await reader.cancel();throw new DOMException(`Workbook part ${entry.name} exceeds its declared size.`,"DataError");}chunks.push(value);}if(length!==entry.size)throw new DOMException(`Workbook part ${entry.name} has an invalid declared size.`,"DataError");const bytes=new Uint8Array(length);let cursor=0;for(const chunk of chunks){bytes.set(chunk,cursor);cursor+=chunk.length;}return bytes;}

const attributes=(source:string)=>Object.fromEntries([...source.matchAll(/([A-Za-z:]+)=["']([^"']*)["']/gu)].map(([,key,value])=>[key!,value!]));
const relationshipOwner=(name:string)=>name==="_rels/.rels"?"":name.replace(/(^|\/)_rels\/([^/]+)\.rels$/u,"$1$2");
const internalTarget=(relationshipName:string,target:string):string|undefined=>{if(target.startsWith("/"))return target.slice(1);const owner=relationshipOwner(relationshipName),base=owner.includes("/")?owner.slice(0,owner.lastIndexOf("/")+1):"",segments=`${base}${target}`.split("/"),normal:string[]=[];for(const segment of segments){if(!segment||segment===".")continue;if(segment===".."){if(!normal.length)return undefined;normal.pop();}else normal.push(segment);}const value=normal.join("/");return safeFlowVisualArchivePath(value)?value:undefined;};
const commentDirectives=(texts:Map<string,string>):ExcelTemplateDirectiveCell[]=>[...texts].filter(([name])=>/xl\/comments\d*\.xml$/u.test(name)).flatMap(([,text])=>[...text.matchAll(/<comment\b([^>]*)>([\s\S]*?)<\/comment>/gu)].flatMap(match=>{const ref=attributes(match[1]!).ref,value=xmlText(match[2]!);return ref&&value.startsWith("tw:")?[{cell:ref,text:value}]:[];}));
const worksheetCells=(text:string,shared:readonly string[])=>[...text.matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/gu)].flatMap(match=>{const attrs=attributes(match[1]!),cell=attrs.r;if(!cell)return[];const body=match[2]!,raw=attrs.t==="s"?shared[Number(/<v>([^<]*)<\/v>/u.exec(body)?.[1]??-1)]??"":xmlText(body);return raw.includes("{{")?[{address:cell,value:raw}]:[];});

export async function validateExcelTemplateWorkbook(source:Blob,expectedKind?:DocumentationTemplateKind):Promise<{valid:boolean;kind?:DocumentationTemplateKind;contractVersion?:1;findings:ExcelWorkbookFinding[];entryCount:number;unpackedBytes:number}>{
  const findings:ExcelWorkbookFinding[]=[];if(source.size>10*1024*1024)return{valid:false,findings:[{location:"workbook",message:"The Excel template is too large."}],entryCount:0,unpackedBytes:0};let entries:ZipEntry[];try{entries=await directory(source);}catch(error){return{valid:false,findings:[{location:"workbook",message:error instanceof Error?error.message:String(error)}],entryCount:0,unpackedBytes:0};}
  const byName=new Map(entries.map(entry=>[entry.name,entry])),required=["[Content_Types].xml","_rels/.rels","xl/workbook.xml"];for(const name of required)if(!byName.has(name))findings.push({location:name,message:`The workbook is missing ${name}.`});const unsupported=/^(?:xl\/(?:externalLinks|connections|embeddings|charts|pivotTables|pivotCache|slicers|activeX|ctrlProps)|customXml|word|ppt)\//u;for(const{ name }of entries)if(unsupported.test(name)||/vbaProject|activeX|oleObject|signature|\.bin$/iu.test(name))findings.push({location:name,message:"Use inert macro-free workbook content."});
  const readable=entries.filter(({name})=>/\.(?:xml|rels)$/u.test(name)),texts=new Map<string,string>();for(const entry of readable)try{texts.set(entry.name,decoder.decode(await entryBody(source,entry)));}catch(error){findings.push({location:entry.name,message:error instanceof Error?error.message:String(error)});}for(const[name,text]of texts){if(/<f(?:\s|>)/u.test(text))findings.push({location:name,message:"Remove workbook formulas."});if(name.endsWith(".rels")){for(const match of text.matchAll(/<Relationship\b([^>]*)\/?>(?:<\/Relationship>)?/gu)){const attrs=attributes(match[1]!),external=attrs.TargetMode?.toLowerCase()==="external";if(external){findings.push({location:name,message:"Remove external workbook content."});continue;}const target=attrs.Target&&internalTarget(name,attrs.Target);if(!target||!byName.has(target))findings.push({location:name,message:`Relationship ${attrs.Id??"(unnamed)"} has a broken target ${attrs.Target??""}.`});if(/(?:chart|pivot|slicer|connection|oleObject|control|externalLink)/iu.test(attrs.Type??"")||/\/package$/iu.test(attrs.Type??""))findings.push({location:name,message:`Relationship ${attrs.Id??"(unnamed)"} uses unsupported workbook content.`});}}
    if(/xl\/drawings\/drawing\d*\.xml$/u.test(name)&&/<xdr:(?:graphicFrame|sp|cxnSp|contentPart)\b/u.test(text))findings.push({location:name,message:"Use only embedded PNG, JPEG, or GIF worksheet images."});
  }
  const contentTypes=texts.get("[Content_Types].xml")??"";if(/macroEnabled|vbaProject|activeX|oleObject|embeddedPackage|chart|pivot|slicer|addin/iu.test(contentTypes))findings.push({location:"[Content_Types].xml",message:"Use inert macro-free workbook content."});for(const match of contentTypes.matchAll(/<(?:Default|Override)\b([^>]*)\/?>(?:<\/(?:Default|Override)>)?/gu)){const attrs=attributes(match[1]!);if(attrs.Extension&&["png","jpg","jpeg","gif","xml","rels"].includes(attrs.Extension.toLowerCase()))continue;if(attrs.ContentType?.startsWith("image/")&&!/[+\/]?(?:png|jpeg|gif)$/iu.test(attrs.ContentType))findings.push({location:"[Content_Types].xml",message:`Unsupported embedded image content type ${attrs.ContentType}.`});}
  const workbook=texts.get("xl/workbook.xml")??"",sheetCount=(workbook.match(/<sheet\b/gu)??[]).length;if(sheetCount!==1)findings.push({location:"xl/workbook.xml",message:"Keep exactly one prototype worksheet."});const directives=commentDirectives(texts),templateDirectives=directives.flatMap(source=>{try{const parsed=parseExcelTemplateDirective(source.text);return parsed.kind==="template"?[parsed]:[];}catch(error){findings.push({location:`worksheet ${source.cell}`,message:error instanceof Error?error.message:String(error)});return[];}}),markers=templateDirectives.map(({templateKind})=>templateKind);if(markers.length!==1)findings.push({location:"worksheet Note",message:`Declare one ${expectedKind?expectedKind[0]!.toUpperCase()+expectedKind.slice(1):"documentation"} contract-version-1 template.`});const kind=markers[0];if(kind&&expectedKind&&kind!==expectedKind)findings.push({location:"worksheet Note",message:`The workbook declares ${kind}, not ${expectedKind}.`});
  const worksheetEntry=[...texts.keys()].find(name=>/^xl\/worksheets\/sheet[^/]*\.xml$/u.test(name)),worksheet=worksheetEntry?texts.get(worksheetEntry)??"":"",sharedText=texts.get("xl/sharedStrings.xml")??"",shared=[...sharedText.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/gu)].map(match=>xmlText(match[1]!)),cells=worksheetCells(worksheet,shared),merges=[...worksheet.matchAll(/<mergeCell\b[^>]*ref=["']([^"']+)["'][^>]*\/?>(?:<\/mergeCell>)?/gu)].map(match=>match[1]!);if(kind){const prototype={kind,contractVersion:1 as const,worksheetName:"Prototype",cells,directives,merges},geometry=validateExcelTemplatePrototype(prototype);for(const finding of geometry.findings)findings.push({location:`worksheet ${finding.cell??"geometry"}`,message:finding.message});}
  return{valid:findings.length===0,...(kind?{kind,contractVersion:1 as const}:{}),findings,entryCount:entries.length,unpackedBytes:entries.reduce((sum,{size})=>sum+size,0)};
}
