import { applyCanonicalCommand, canonicalPropertyPath, savedSchemaCanonicalDocument, setPropertyDocumentation, updateSchemaWorkingDraft, type SchemaDefinition } from "../../utilities/data-layer/schemas.js";
import type { SchemasInstalledPorts } from "./contracts.js";
import { SchemaAssignmentController } from "./assignment-controller.js";
import type { SchemaCanonicalEditorController } from "./canonical-editor-controller.js";
import type { SchemaCanonicalInstalledView } from "./canonical-installed-view.js";
import type { SchemaCanonicalPersistenceWorkflow } from "./canonical-persistence-workflow.js";
import type { SchemaInstalledEditorWorkflow } from "./installed-editor-workflow.js";
import type { SchemaLibraryController } from "./library-controller.js";
import { SchemaPropertyController } from "./property-controller.js";
import type { SchemaPropertyElements } from "./property-installed-view.js";
import { SchemaPropertyRuleWorkflow } from "./property-rule-workflow.js";
import { SchemaPropertyView } from "./property-view.js";
import { SchemaRuleController } from "./rule-controller.js";
import { SchemaRuleInstalledPresentation, type RuleElements } from "./rule-installed-view.js";
import { SchemaRulePickerView } from "./rule-picker-view.js";
import { schemaEditorDraft, schemaPropertyType } from "./schema-model.js";

interface PropertyDomainLinks {
  root:ParentNode;elements:SchemaPropertyElements;ruleElements:RuleElements;library:SchemaLibraryController;canonical:SchemaCanonicalEditorController;canonicalView:SchemaCanonicalInstalledView;canonicalPersistence:SchemaCanonicalPersistenceWorkflow;
  editor():SchemaInstalledEditorWorkflow;active():SchemaDefinition;persistLibrary():void;persistLibraries():void;renderAll():void;renderDraft():void;renderProperty():void;
  createRuleId:SchemasInstalledPorts["createRuleId"];download:SchemasInstalledPorts["downloadSchema"];capturedValue:SchemasInstalledPorts["capturedAssignmentValue"];promotionDialog:SchemasInstalledPorts["localRulePromotionDialog"];
  scheduleFrame:SchemasInstalledPorts["scheduleFrame"];settleCanonical?:SchemasInstalledPorts["settleCanonical"];result:HTMLElement|null;schemaEditor:HTMLElement|null;schemaDetail:HTMLElement|null;document:Document|undefined;
}

/** Owns complete property, rule, and assignment composition. */
export function createSchemaPropertyRuleAssignmentDomain(storage:Pick<Storage,"getItem"|"setItem">,ruleElements:RuleElements,schemas:()=>readonly SchemaDefinition[],assignmentPorts:ConstructorParameters<typeof SchemaAssignmentController>[0]) {
  const property=new SchemaPropertyController(),rule=new SchemaRuleController(storage),rulePresentation=new SchemaRuleInstalledPresentation(rule,ruleElements,schemas),assignment=new SchemaAssignmentController(assignmentPorts);
  let propertyView:SchemaPropertyView,rulePicker:SchemaRulePickerView,workflow:SchemaPropertyRuleWorkflow;
  return { property,rule,rulePresentation,assignment,
    connect(p:PropertyDomainLinks) {
      rule.configure({elements:p.ruleElements,presentation:rulePresentation,schemas:() => p.library.schemas,replaceSchemas:(schemas) => {p.library.schemas=schemas;},persistRules:() => rule.persist(),persistLibrary:p.persistLibrary,renderAll:p.renderAll,renderDraft:p.renderDraft,createId:p.createRuleId,download:p.download,createRuleId:p.createRuleId,capturedValue:p.capturedValue,editableSchema:() => p.library.draft??schemaEditorDraft(p.active()),propertyType:schemaPropertyType,draft:() => p.library.draft,replaceDraft:(schema) => {p.library.draft=schema;},presentDraft:schemaEditorDraft,activeSchemaId:() => p.library.activeSchemaId,promotionDialog:p.promotionDialog,detail:p.schemaDetail,root:p.root,scheduleFrame:p.scheduleFrame,result:(message) => {if(p.result)p.result.textContent=message;},commitPromotion:(...args) => p.canonicalPersistence.promote(...args),...(p.settleCanonical?{settleCanonical:p.settleCanonical}:{})});
      rulePicker=new SchemaRulePickerView(rule,{picker:p.elements.schemaPropertyRulePicker,active:p.active,draft:() => p.library.draft,capturedValue:() => p.capturedValue("payload"),propertyType:schemaPropertyType,incrementRender:() => {property.renderSequence+=1;},close:() => workflow.close(),closeForCommit:() => workflow.closeForCommit(),createConfigured:() => workflow.createConfigured()});
      property.configure({root:p.root,active:p.active,schemas:() => p.library.schemas,ruleIds:() => rule.rules.map(({id}) => id),replaceActive:(schema) => p.library.replaceActive(schema),replaceSchemas:(schemas) => {p.library.schemas=structuredClone([...schemas]);},persist:p.persistLibrary,renderAll:p.renderAll,renderView:p.renderProperty,renderRules:() => rule.render(),openRulePicker:(path,trigger) => workflow.open(path,trigger),queuePersistence:(id) => p.canonicalPersistence.queueLibraryPersistence(id),canonicalUndo:() => {if(!p.canonical.editor?.onUndo)return false;p.canonical.editor.onUndo();return true;},removeCanonicalDocumentation:(schema,path) => {const draft=schema.workingDraft!,documentation=setPropertyDocumentation(draft.documentation??{},path,{displayName:"",description:""}),base=p.canonical.savedSchemaId(p.canonical.editor)===schema.id?p.canonical.savedDocument:draft.canonicalSchema,node=base&&Object.values(base.nodes).find((candidate) => canonicalPropertyPath(base,candidate.id)===path),result=base&&node?applyCanonicalCommand(base,{kind:"set",baseRevision:base.revision,propertyId:node.id,patch:{documentation:{displayText:"",description:"",comments:"",example:{method:"blank"}}}}):undefined,canonical=result?.status==="applied"||result?.status==="rebased"?result.document:undefined;if(canonical&&p.canonical.savedSchemaId(p.canonical.editor)===schema.id)p.canonical.savedDocument=canonical;return updateSchemaWorkingDraft(schema,{documentation,...(canonical?{canonicalSchema:canonical}:{})},`Remove property documentation ${path}`);},addManualCanonical:(schema,document,path) => {const previous=schema.workingDraft?.canonicalSchema;if(!previous)return;const draft=schema.workingDraft!,projected={...schema,document,name:draft.name??schema.name,assignments:draft.assignments,...(draft.attachedRules?{attachedRules:draft.attachedRules}:{}),...(draft.documentation?{documentation:draft.documentation}:{})},canonical=savedSchemaCanonicalDocument(projected,(kind) => `schema:${kind}:${++p.canonical.idSequence}`,{id:previous.id,contributorId:previous.contributorId,contributorName:previous.contributorName});canonical.revision=previous.revision+1;const selected=Object.values(canonical.nodes).find((node) => canonicalPropertyPath(canonical,node.id)===path)?.id;if(selected)canonical.selectedPropertyId=selected;return canonical;},scheduleFrame:p.scheduleFrame,...(p.settleCanonical?{settle:p.settleCanonical}:{})});
      propertyView=new SchemaPropertyView({root:p.root,document:p.document,library:p.library,property,rules:rule,canonical:p.canonical,active:p.active,editorDraft:schemaEditorDraft,parentDocuments:() => property.parentDocuments(),normalizedPath:(path) => workflow.normalizedPath(path),replaceActive:(schema) => p.library.replaceActive(schema),persistLibrary:p.persistLibrary,persistLibraries:p.persistLibraries,queuePersistence:(id) => p.canonicalPersistence.queueLibraryPersistence(id),renderAll:p.renderAll,createId:p.createRuleId,settleCanonical:Boolean(p.settleCanonical),openCanonicalActions:(path,trigger) => {p.canonicalView.openPropertyActions(path,trigger);},openCanonicalRule:(path,trigger) => {p.canonicalView.openRule(path,trigger);},openManual:(path,trigger) => property.openManual(path,trigger),openRulePicker:(path,trigger) => workflow.open(path,trigger),openSpecificIndex:(path,trigger) => property.openSpecificIndex(path,trigger),openCopy:(path,trigger) => property.openCopy(path,trigger),requestRemoval:(path,trigger) => property.requestRemoval(path,trigger),requestDocumentationRemoval:(path,trigger) => property.requestDocumentationRemoval(path,trigger),updateAttachedRule:(schemaId,ruleId,enabled) => {rule.updateAttached(schemaId,ruleId,enabled);},openAttachedRule:(schemaId,ruleId,path,trigger) => {workflow.openAttached(schemaId,ruleId,path,trigger);},promoteRule:(path,ruleId) => {rule.openPromotion(path,ruleId);}});
      workflow=new SchemaPropertyRuleWorkflow({rule,property,canonical:p.canonical,canonicalView:p.canonicalView,pickerView:rulePicker,picker:p.elements.schemaPropertyRulePicker,propertyTree:p.elements.schemaPropertyTree,schemaEditor:p.schemaEditor,schemaDetail:p.schemaDetail,document:p.document,active:p.active,activeSchemaId:() => p.library.activeSchemaId,draft:() => p.library.draft,schemas:() => p.library.schemas,renderSchemas:p.renderAll,showSubview:(subview) => p.editor().showSubview(subview),attach:(schemaId,ruleId,path,supplied) => rule.attach(schemaId,ruleId,path,supplied),propertyType:(schema,path) => rule.typeForAttachment(schema,path)});
      return {propertyView,rulePicker,workflow};
    },
    views:() => ({propertyView,rulePicker,workflow}),
    dispose:() => {propertyView?.dispose();rulePresentation.dispose();rule.dispose();property.dispose();assignment.dispose();}
  };
}
