import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {mkdtemp,rm} from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import {headlessChromeArguments,stopHeadlessChrome} from "../support/headless-chrome.mjs";

const wait=(milliseconds)=>new Promise((resolve)=>setTimeout(resolve,milliseconds));
class DevtoolsSocket{
  constructor(url){this.url=new URL(url);this.nextId=1;this.pending=new Map();this.buffer=Buffer.alloc(0);}
  async connect(){await new Promise((resolve,reject)=>{this.socket=net.createConnection({host:this.url.hostname,port:Number(this.url.port)});this.socket.once("error",reject);this.socket.once("connect",()=>{const key=Buffer.from(String(Math.random())).toString("base64");this.socket.write([`GET ${this.url.pathname}${this.url.search} HTTP/1.1`,`Host: ${this.url.host}`,"Upgrade: websocket","Connection: Upgrade",`Sec-WebSocket-Key: ${key}`,"Sec-WebSocket-Version: 13","\r\n"].join("\r\n"));});let handshake="";const receive=(chunk)=>{handshake+=chunk.toString("binary");const end=handshake.indexOf("\r\n\r\n");if(end<0)return;this.socket.off("data",receive);if(!handshake.startsWith("HTTP/1.1 101"))return reject(new Error("DevTools WebSocket upgrade failed"));const remaining=Buffer.from(handshake.slice(end+4),"binary");this.socket.on("data",(data)=>this.receive(data));if(remaining.length)this.receive(remaining);resolve();};this.socket.on("data",receive);});}
  receive(chunk){this.buffer=Buffer.concat([this.buffer,chunk]);while(this.buffer.length>=2){const first=this.buffer[0];let length=this.buffer[1]&0x7f,offset=2;if(length===126){if(this.buffer.length<4)return;length=this.buffer.readUInt16BE(2);offset=4;}else if(length===127){if(this.buffer.length<10)return;length=Number(this.buffer.readBigUInt64BE(2));offset=10;}if(this.buffer.length<offset+length)return;const payload=this.buffer.subarray(offset,offset+length);this.buffer=this.buffer.subarray(offset+length);if((first&15)!==1)continue;const message=JSON.parse(payload.toString("utf8")),pending=this.pending.get(message.id);if(!pending)continue;this.pending.delete(message.id);message.error?pending.reject(new Error(message.error.message)):pending.resolve(message.result);}}
  send(payload){const body=Buffer.from(JSON.stringify(payload)),mask=Buffer.from([1,2,3,4]);let header;if(body.length<126)header=Buffer.from([0x81,0x80|body.length]);else{header=Buffer.alloc(4);header[0]=0x81;header[1]=0x80|126;header.writeUInt16BE(body.length,2);}for(let index=0;index<body.length;index+=1)body[index]^=mask[index%4];this.socket.write(Buffer.concat([header,mask,body]));}
  call(method,params={}){const id=this.nextId++;this.send({id,method,params});return new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject}));}
  close(){this.socket?.destroy();}
}
const profile=await mkdtemp(path.join(os.tmpdir(),"layered-schema-")),extensionRoot=path.resolve("dist"),chromeArguments=headlessChromeArguments(profile,extensionRoot);chromeArguments.splice(-1,0,`--load-extension=${extensionRoot}`);const chrome=spawn("google-chrome",chromeArguments,{stdio:["ignore","ignore","pipe"]});
const debuggingPort=()=>new Promise((resolve,reject)=>{let output="";const timeout=setTimeout(()=>reject(new Error(`Chrome did not expose a debugging port: ${output}`)),15000);chrome.stderr.on("data",(chunk)=>{output+=chunk;const match=output.match(/ws:\/\/127\.0\.0\.1:(\d+)\//);if(match){clearTimeout(timeout);resolve(Number(match[1]));}});chrome.once("error",reject);});
async function extensionId(port){for(let attempt=0;attempt<100;attempt+=1){const targets=await fetch(`http://127.0.0.1:${port}/json/list`).then((response)=>response.json()),worker=targets.find(({type,url})=>type==="service_worker"&&url.startsWith("chrome-extension://")&&new URL(url).pathname==="/background.js");if(worker)return new URL(worker.url).hostname;await wait(20);}throw new Error("Unpacked extension did not load");}
async function evaluate(socket,expression){const result=await socket.call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result.value;}
async function ready(socket){for(let attempt=0;attempt<200;attempt+=1){if(await evaluate(socket,"document.readyState==='complete'&&Boolean(document.querySelector('#create-project-form'))"))return;await wait(25);}throw new Error("Specification Builder did not become ready");}
let socket;
try{
  const port=await debuggingPort(),id=await extensionId(port),page=await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`chrome-extension://${id}/specification-builder.html`)}`,{method:"PUT"}).then((response)=>response.json());socket=new DevtoolsSocket(page.webSocketDebuggerUrl);await socket.connect();await socket.call("Runtime.enable");await socket.call("Page.enable");await ready(socket);
  const evidence=await evaluate(socket,`(async()=>{const q=(selector)=>{const value=document.querySelector(selector);if(!value)throw new Error('Missing '+selector);return value;},pause=()=>new Promise((resolve)=>setTimeout(resolve,0)),set=(selector,value)=>{const input=typeof selector==='string'?q(selector):selector;input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));};set('#project-name','Layered schema');set('#project-site','shop.example');q('#create-project-form').requestSubmit();await pause();set('#entity-name','Sitewide');q('#add-entity-form').requestSubmit();await pause();q('#workspace-content .entity-row button').click();await pause();const summary=q('[aria-label="Schema constraints summary"]'),humanSummary=summary.textContent.includes('Sitewide')&&summary.textContent.includes('Shared Profile');summary.querySelector('button').click();await pause();const editor=q('[aria-label="Shared schema constraints editor"]'),completeEditor=['Inherited constraints','Local contributions','Effective results','Superseded expectations','Blocking conflicts'].every((text)=>editor.textContent.includes(text)),form=editor.querySelector('form');set(form.querySelector('[name="path"]'),'/funnel_step');set(form.querySelector('[name="type"]'),'string');set(form.querySelector('[name="allowedValues"]'),'["3a","3b"]');set(form.querySelector('[name="presence"]'),'optional');set(form.querySelector('[name="enforcement"]'),'invariant');set(form.querySelector('[name="target"]'),'all');set(form.querySelector('[name="documentation"]'),'Funnel step');set(form.querySelector('[name="examples"]'),'["3b"]');form.requestSubmit();await pause();const stored=JSON.parse(localStorage.getItem('my-chrome-utilities.specification-project.v1')),profile=stored.project.collections.profiles[0],saved=profile.schemaConstraints?.[0],consequential=q('[aria-label="Shared schema constraints editor"] [role="status"]').textContent.includes('compiled targets stale')&&stored.history.undo.at(-1).label.includes('schema constraint');return{installedBoundary:location.protocol==='chrome-extension:'&&chrome.runtime.id===location.hostname,humanSummary,completeEditor,structuredControl:Boolean(editor.querySelector('[aria-label="Add constraint inherited property search"]')),saved:Boolean(saved?.path==='/funnel_step'&&saved.allowedValues.join(',')==='3a,3b'&&saved.documentation==='Funnel step'),consequential};})()`);
  await socket.call("Page.reload",{ignoreCache:true});await ready(socket);const reload=await evaluate(socket,`(async()=>{const pause=()=>new Promise((resolve)=>setTimeout(resolve,0));document.querySelector('#project-tree button[data-kind="profiles"]').click();await pause();document.querySelector('#workspace-content .entity-row button').click();await pause();return document.querySelector('[aria-label="Schema constraints summary"]')?.textContent.includes('Local 1');})()`);evidence.persistenceReload=reload;assert.equal(Object.values(evidence).every(Boolean),true,JSON.stringify(evidence));console.log(JSON.stringify({layeredSchema:evidence}));
}finally{socket?.close();await stopHeadlessChrome(chrome);await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
