import type {CompiledLayeredSchema,EffectiveProperty,LayerConflict,LayerConstraint,LayerContext,LayerContributor} from "../data-layer-layered-schema.js";
import {branch,clone,constraintWithStructuredRules,included,origin,parallelMismatch} from "./compile-context.js";
import {mergeLayeredProperty} from "./compile-merge.js";
import {constraintWithPeerRules,peerConstraintForCompile,peerMismatch,peerSetMismatch} from "./peer-constraints.js";
export function compileLayeredSchema(contributors:readonly LayerContributor[],context:LayerContext):CompiledLayeredSchema{
  const selected=contributors.filter(({active})=>active!==false),peerQueues=new Map<string,LayerContributor[]>();for(const contributor of selected)if(contributor.peerGroup){const queue=peerQueues.get(contributor.peerGroup)??[];queue.push(contributor);peerQueues.set(contributor.peerGroup,queue);}for(const queue of peerQueues.values())queue.sort((left,right)=>left.id.localeCompare(right.id));const activeContributors=selected.map((contributor)=>contributor.peerGroup?peerQueues.get(contributor.peerGroup)!.shift()!:contributor),properties:Record<string,EffectiveProperty>={},conflicts:LayerConflict[]=activeContributors.flatMap((contributor)=>(contributor.inheritanceConflicts??[]).map(({path,sourceRuleId,dependencyPropertyId})=>({path,message:`selective inheritance rule ${sourceRuleId} needs excluded property ${dependencyPropertyId}; include, exclude, or replace the rule`,contributors:[contributor.name]}))),provenance=activeContributors.map(origin),exclusions:CompiledLayeredSchema["exclusions"]=contributors.filter(({active})=>active===false).flatMap((contributor)=>contributor.constraints.length?contributor.constraints.map(({path})=>({contributorId:contributor.id,contributorName:contributor.name,path,target:contributor.exclusionReason??"applicability did not match"})):[{contributorId:contributor.id,contributorName:contributor.name,path:"/",target:contributor.exclusionReason??"applicability did not match"}]);
  const conflict=(path:string,message:string,names:string[],details:Partial<LayerConflict>={})=>conflicts.push({path,message,contributors:names,...details});
  const active=activeContributors.flatMap((contributor)=>contributor.constraints.map(constraintWithStructuredRules).filter((constraint)=>included(constraint.target,context)).map((constraint)=>({contributor,constraint}))),blockedParallel=new Set<string>(),blockedPeers=new Set<string>(),resolvedParallel=new Set<string>(),conflictingPolicyGroups=new Set<string>();
  const peersByGroup=new Map<string,LayerContributor[]>();for(const contributor of activeContributors)if(contributor.peerGroup){const peers=peersByGroup.get(contributor.peerGroup)??[];peers.push(contributor);peersByGroup.set(contributor.peerGroup,peers);}for(const [peerGroup,peers] of peersByGroup){const policies=new Set(peers.flatMap(({onlyDefinedFields})=>onlyDefinedFields===undefined?[]:[onlyDefinedFields]));if(policies.size>1)conflictingPolicyGroups.add(peerGroup);}
  const peerEntries=new Map<string,{contributor:LayerContributor;constraint:LayerConstraint}[]>();for(const entry of active)if(entry.contributor.peerGroup){const key=`${entry.contributor.peerGroup}\u0000${entry.constraint.path}`,entries=peerEntries.get(key)??[];entries.push(entry);peerEntries.set(key,entries);}for(const [key,entries] of peerEntries){const peerGroup=key.split("\u0000")[0]!,policyConflict=conflictingPolicyGroups.has(peerGroup),algebra=entries.map(({contributor,constraint})=>({contributor,constraint:peerConstraintForCompile(constraint)}));let incompatible=policyConflict||peerSetMismatch(algebra.map(({constraint})=>constraint));for(let left=0;left<algebra.length;left+=1)for(let right=left+1;right<algebra.length;right+=1)incompatible||=peerMismatch(algebra[left]!.constraint,algebra[right]!.constraint);if(!incompatible)continue;const path=entries[0]!.constraint.path,names=policyConflict?peersByGroup.get(peerGroup)!.map(({name})=>name):algebra.map(({contributor})=>contributor.name);blockedPeers.add(path);conflict(path,"parallel Shared Profile peers conflict; add an explicit contextual resolution",[...new Set(names)]);}
  for(const peerGroup of conflictingPolicyGroups)if(![...peerEntries.keys()].some((key)=>key.startsWith(`${peerGroup}\u0000`)))conflict("/","parallel Shared Profile closed-field policies conflict; add an explicit contextual resolution",activeContributors.filter((contributor)=>contributor.peerGroup===peerGroup).map(({name})=>name));
  for(const page of active.filter(({contributor})=>branch(contributor.scope)==="page"))for(const event of active.filter(({contributor})=>branch(contributor.scope)==="event")){if(page.constraint.path!==event.constraint.path||!parallelMismatch(page.constraint,event.constraint))continue;const references=active.filter(({contributor,constraint})=>branch(contributor.scope)==="occurrence"&&constraint.path===page.constraint.path).flatMap(({constraint})=>constraint.overrideReferences??[]),pageId=page.constraint.definitionId,eventId=event.constraint.definitionId,resolved=Boolean(pageId&&eventId&&references.includes(pageId)&&references.includes(eventId));if(resolved)resolvedParallel.add(page.constraint.path);else if(!blockedParallel.has(page.constraint.path)){blockedParallel.add(page.constraint.path);conflict(page.constraint.path,"parallel Page and Event branches conflict; add an explicit contextual resolution",[page.contributor.name,event.contributor.name]);}}
  const contributorById=new Map(activeContributors.map((contributor)=>[contributor.id,contributor]));for(const contributor of activeContributors)for(const rawConstraint of contributor.constraints){const constraint=contributor.peerGroup?constraintWithPeerRules(rawConstraint):constraintWithStructuredRules(rawConstraint);if(!included(constraint.target,context)){exclusions.push({contributorId:contributor.id,contributorName:contributor.name,path:constraint.path,target:constraint.target??"all"});continue;}if(blockedParallel.has(constraint.path)||blockedPeers.has(constraint.path))continue;const prior=properties[constraint.path],priorContributor=prior?contributorById.get(prior.origins.at(-1)!.contributorId):undefined,parallelPair=Boolean(prior&&resolvedParallel.has(constraint.path)&&new Set([branch(prior.origins.at(-1)!.scope),branch(contributor.scope)]).has("page")&&new Set([branch(prior.origins.at(-1)!.scope),branch(contributor.scope)]).has("event")),parallelPeer=Boolean(priorContributor?.peerGroup&&priorContributor.peerGroup===contributor.peerGroup),merged=mergeLayeredProperty(prior,constraint,contributor,parallelPair,parallelPeer,conflict);if(contributor.peerGroup)merged.peerContributions=[...(prior?.peerContributions??[]),{contributorId:contributor.id,contributorName:contributor.name,constraint:clone(rawConstraint)}];else if(prior?.peerContributions?.length)merged.downstreamContributions=[...(prior.downstreamContributions??[]),{contributorId:contributor.id,contributorName:contributor.name,scope:contributor.scope,...(contributor.inheritanceRoutes?.length?{inheritanceRoutes:[...contributor.inheritanceRoutes]}:{}),...(parallelPair?{parallelPair:true}:{}),constraint:clone(rawConstraint)}];properties[constraint.path]=merged;}
  const onlyDefinedFields=conflictingPolicyGroups.size?undefined:[...activeContributors].reverse().find((contributor)=>contributor.onlyDefinedFields!==undefined)?.onlyDefinedFields;
  return{status:conflicts.length?"blocked":"ready",properties,conflicts,provenance,exclusions,...(onlyDefinedFields!==undefined?{onlyDefinedFields}:{})};
}
