import type {CompiledLayeredSchema,EffectiveProperty,LayerConflict,LayerConstraint,LayerContext,LayerContributor} from "../data-layer-layered-schema.js";
import {branch,clone,constraintWithStructuredRules,included,origin,parallelMismatch,peerMismatch} from "./compile-context.js";
import {mergeLayeredProperty} from "./compile-merge.js";
export function compileLayeredSchema(contributors:readonly LayerContributor[],context:LayerContext):CompiledLayeredSchema{
  const selected=contributors.filter(({active})=>active!==false),peerQueues=new Map<string,LayerContributor[]>();for(const contributor of selected)if(contributor.peerGroup){const queue=peerQueues.get(contributor.peerGroup)??[];queue.push(contributor);peerQueues.set(contributor.peerGroup,queue);}for(const queue of peerQueues.values())queue.sort((left,right)=>left.id.localeCompare(right.id));const activeContributors=selected.map((contributor)=>contributor.peerGroup?peerQueues.get(contributor.peerGroup)!.shift()!:contributor),properties:Record<string,EffectiveProperty>={},conflicts:LayerConflict[]=[],provenance=activeContributors.map(origin),exclusions:CompiledLayeredSchema["exclusions"]=contributors.filter(({active})=>active===false).flatMap((contributor)=>contributor.constraints.length?contributor.constraints.map(({path})=>({contributorId:contributor.id,contributorName:contributor.name,path,target:contributor.exclusionReason??"applicability did not match"})):[{contributorId:contributor.id,contributorName:contributor.name,path:"/",target:contributor.exclusionReason??"applicability did not match"}]);
  const conflict=(path:string,message:string,names:string[])=>conflicts.push({path,message,contributors:names});
  const active=activeContributors.flatMap((contributor)=>contributor.constraints.map(constraintWithStructuredRules).filter((constraint)=>included(constraint.target,context)).map((constraint)=>({contributor,constraint}))),blockedParallel=new Set<string>(),blockedPeers=new Set<string>(),resolvedParallel=new Set<string>();
  const peerEntries=new Map<string,{contributor:LayerContributor;constraint:LayerConstraint}[]>();for(const entry of active)if(entry.contributor.peerGroup){const key=`${entry.contributor.peerGroup}\u0000${entry.constraint.path}`,entries=peerEntries.get(key)??[];entries.push(entry);peerEntries.set(key,entries);}for(const entries of peerEntries.values()){let incompatible=false;for(let left=0;left<entries.length;left+=1)for(let right=left+1;right<entries.length;right+=1)incompatible||=peerMismatch(entries[left]!.constraint,entries[right]!.constraint);if(!incompatible)continue;const path=entries[0]!.constraint.path;blockedPeers.add(path);conflict(path,"parallel Shared Profile peers conflict; add an explicit contextual resolution",[...new Set(entries.map(({contributor})=>contributor.name))]);}
  for(const page of active.filter(({contributor})=>branch(contributor.scope)==="page"))for(const event of active.filter(({contributor})=>branch(contributor.scope)==="event")){if(page.constraint.path!==event.constraint.path||!parallelMismatch(page.constraint,event.constraint))continue;const references=active.filter(({contributor,constraint})=>branch(contributor.scope)==="occurrence"&&constraint.path===page.constraint.path).flatMap(({constraint})=>constraint.overrideReferences??[]),pageId=page.constraint.definitionId,eventId=event.constraint.definitionId,resolved=Boolean(pageId&&eventId&&references.includes(pageId)&&references.includes(eventId));if(resolved)resolvedParallel.add(page.constraint.path);else if(!blockedParallel.has(page.constraint.path)){blockedParallel.add(page.constraint.path);conflict(page.constraint.path,"parallel Page and Event branches conflict; add an explicit contextual resolution",[page.contributor.name,event.contributor.name]);}}
  const contributorById=new Map(activeContributors.map((contributor)=>[contributor.id,contributor]));for(const contributor of activeContributors)for(const rawConstraint of contributor.constraints){const constraint=constraintWithStructuredRules(rawConstraint);if(!included(constraint.target,context)){exclusions.push({contributorId:contributor.id,contributorName:contributor.name,path:constraint.path,target:constraint.target??"all"});continue;}if(blockedParallel.has(constraint.path)||blockedPeers.has(constraint.path))continue;const prior=properties[constraint.path],priorContributor=prior?contributorById.get(prior.origins.at(-1)!.contributorId):undefined,parallelPair=Boolean(prior&&resolvedParallel.has(constraint.path)&&new Set([branch(prior.origins.at(-1)!.scope),branch(contributor.scope)]).has("page")&&new Set([branch(prior.origins.at(-1)!.scope),branch(contributor.scope)]).has("event")),parallelPeer=Boolean(priorContributor?.peerGroup&&priorContributor.peerGroup===contributor.peerGroup);properties[constraint.path]=mergeLayeredProperty(prior,constraint,contributor,parallelPair,parallelPeer,conflict);}
  const onlyDefinedFields=[...activeContributors].reverse().find((contributor)=>contributor.onlyDefinedFields!==undefined)?.onlyDefinedFields;
  return{status:conflicts.length?"blocked":"ready",properties,conflicts,provenance,exclusions,...(onlyDefinedFields!==undefined?{onlyDefinedFields}:{})};
}
