import {applyCanonicalCommand,canonicalPredicateWithStableIds,canonicalTableRows,createCanonicalSchema,type CanonicalPredicate,type CanonicalPropertyNode,type CanonicalPropertyType,type CanonicalProvenance,type CanonicalRule,type CanonicalSchemaDocument} from "../data-layer-canonical-schema.js";
import type {EffectiveProperty,LayerConstraint,LayerValueProvenance} from "../data-layer-layered-schema.js";
import {layeredContributorPath,layeredContributorsForPath} from "../data-layer-layered-schema-project.js";
import type {ProjectEntity,ProjectState} from "../data-layer-specification-project.js";
import {composedSchemaWorkspace} from "./workspace-model.js";

const clone=<T>(value:T):T=>structuredClone(value);
const entities=(state:ProjectState):ProjectEntity[]=>(Object.values(state.project.collections) as ProjectEntity[][]).flat();
const canonicalTypes=new Set<CanonicalPropertyType>(["string","number","integer","boolean","null","object","array"]);
const stableValueIdentity=(owner:string,value:unknown):string=>{let hash=2166136261;for(const char of JSON.stringify(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return `allowed-value:${owner}:${(hash>>>0).toString(16)}`;};
const propertyIdFor=(entity:ProjectEntity,path:string,effective:EffectiveProperty,used:Set<string>):string=>{const preferred=effective.definitionId??`property:${entity.id}:${encodeURIComponent(path)}`;if(!used.has(preferred)){used.add(preferred);return preferred;}const scoped=`property:${entity.id}:${encodeURIComponent(path)}`;used.add(scoped);return scoped;};
const provenanceSource=(value:unknown):CanonicalProvenance["source"]=>["created","saved-schema","requirements","structured-schema","structured-draft","path-constraint"].includes(String(value))?value as CanonicalProvenance["source"]:"path-constraint";
const itemProvenance=(value:unknown,fallback:CanonicalProvenance&{state:NonNullable<CanonicalProvenance["state"]>}):CanonicalProvenance=>{const source=value&&typeof value==="object"?value as Record<string,unknown>:{};return{...fallback,...source,source:provenanceSource(source.source??fallback.source),state:fallback.state};};
const ownershipProvenance=(row:{local:LayerConstraint;provenance:{contributorId:string;contributorName:string;scope:CanonicalProvenance["scope"];state:CanonicalProvenance["state"]}[]},entity:ProjectEntity,itemId:string,raw:unknown,localIds:ReadonlySet<string>):CanonicalProvenance=>{
  const local=localIds.has(itemId),origin=local?row.provenance.find(({contributorId})=>contributorId===entity.id)??row.provenance.at(-1):row.provenance.find(({state})=>state==="inherited")??row.provenance.at(-1);
  return itemProvenance(raw,{source:"path-constraint",...(origin?.contributorId?{sourceId:origin.contributorId,contributorId:origin.contributorId}:{}),...(origin?.contributorName?{contributorName:origin.contributorName}:{}),...(origin?.scope?{scope:origin.scope}:{}),state:local?"local":raw&&typeof raw==="object"&&(raw as Record<string,unknown>).state==="shadowed"?"shadowed":"inherited"});
};
const ruleFor=(value:Record<string,unknown>,fallbackId:string,provenance:CanonicalProvenance):CanonicalRule=>({id:String(value.id??fallbackId),kind:( ["pattern","range","cardinality","condition","custom"].includes(String(value.kind))?String(value.kind):"custom") as CanonicalRule["kind"],...(typeof value.pattern==="string"?{pattern:value.pattern}:{}),...(typeof value.minimum==="number"?{minimum:value.minimum}:{}),...(typeof value.maximum==="number"?{maximum:value.maximum}:{}),...(typeof value.minItems==="number"?{minItems:value.minItems}:{}),...(typeof value.maxItems==="number"?{maxItems:value.maxItems}:{}),...(value.condition?{condition:canonicalPredicateWithStableIds(value.condition as CanonicalPredicate,kind=>`${fallbackId}:${kind}`)!}:{}),severity:value.severity==="warning"?"warning":"error",message:String(value.message??"Constraint mismatch"),...(typeof value.reusableRuleId==="string"?{reusableRuleId:value.reusableRuleId}:{}),provenance});
const addDerivedRules=(row:{effective:EffectiveProperty;local:LayerConstraint;provenance:any[]},entity:ProjectEntity,id:string,rules:CanonicalRule[]):void=>{const localPatterns=new Set(row.local.patterns??[]),derived=(rule:CanonicalRule,local:boolean):CanonicalRule=>({...rule,provenance:ownershipProvenance(row,entity,rule.id,undefined,local?new Set([rule.id]):new Set())});for(const[at,pattern]of(row.effective.patterns??[]).entries())if(!rules.some((rule)=>rule.kind==="pattern"&&rule.pattern===pattern)){const ruleId=`rule:${id}:pattern:${at}`;rules.push(derived({id:ruleId,kind:"pattern",pattern,severity:"error",message:"Pattern mismatch"},localPatterns.has(pattern)));}if((row.effective.minimum!==undefined||row.effective.maximum!==undefined)&&!rules.some(({kind})=>kind==="range")){const ruleId=`rule:${id}:range`;rules.push(derived({id:ruleId,kind:"range",...(row.effective.minimum!==undefined?{minimum:row.effective.minimum}:{}),...(row.effective.maximum!==undefined?{maximum:row.effective.maximum}:{}),severity:"error",message:"Outside range"},row.local.minimum!==undefined||row.local.maximum!==undefined));}if((row.effective.minItems!==undefined||row.effective.maxItems!==undefined)&&!rules.some(({kind})=>kind==="cardinality")){const ruleId=`rule:${id}:cardinality`;rules.push(derived({id:ruleId,kind:"cardinality",...(row.effective.minItems!==undefined?{minItems:row.effective.minItems}:{}),...(row.effective.maxItems!==undefined?{maxItems:row.effective.maxItems}:{}),severity:"error",message:"Outside cardinality"},row.local.minItems!==undefined||row.local.maxItems!==undefined));}};

export function composedCanonicalSchema(state:ProjectState,entity:ProjectEntity,scope:"Page"|"Page Group"|"Event"|"Event-occurrence"):CanonicalSchemaDocument {
  const workspace=composedSchemaWorkspace(state,entity,scope),document=createCanonicalSchema({id:`canonical:effective:${entity.id}`,contributorId:entity.id,contributorName:entity.name}),used=new Set<string>(),byPath=new Map<string,string>(),rows=[...workspace.rows].sort((left,right)=>left.path.split("/").length-right.path.split("/").length||left.path.localeCompare(right.path));
  for(const row of rows){
    const segments=row.path.split("/").filter(Boolean),parentPath=`/${segments.slice(0,-1).join("/")}`,parentId=segments.length>1?byPath.get(parentPath):undefined,type=canonicalTypes.has(row.effective.type as CanonicalPropertyType)?row.effective.type as CanonicalPropertyType:"string",id=propertyIdFor(entity,row.path,row.effective,used),localRuleIds=new Set((row.local.rules??[]).map((rule)=>String(rule.id??""))),rules=(row.effective.rules??[]).map((rule,index)=>{const ruleId=String(rule.id??`rule:${id}:${index}`);return ruleFor(rule,ruleId,ownershipProvenance(row,entity,ruleId,rule.provenance,localRuleIds));});addDerivedRules(row,entity,id,rules);
    const localValueIds=new Set([...(row.local.allowedValueIds??[]),...(row.local.allowedValueProvenance??[]).filter(({state})=>state!=="inherited").map(({id})=>id)]),valueProvenance=new Map((row.effective.allowedValueProvenance??[]).map((value)=>[value.id,value] as const));
    const node:CanonicalPropertyNode={id,name:segments.at(-1)!,...(parentId?{parentId}:{}),order:Object.values(document.nodes).filter((candidate)=>candidate.parentId===parentId).length,type,...(row.effective.itemType?{itemType:row.effective.itemType as CanonicalPropertyType}:{}),presence:{mode:row.effective.presence==="required"?(row.effective.condition?"required-when":"required"):row.effective.presence==="forbidden"?(row.effective.condition?"forbidden-when":"forbidden"):"optional",...(row.effective.condition?{condition:canonicalPredicateWithStableIds(row.effective.condition as unknown as CanonicalPredicate,kind=>`${id}:${kind}`)!}: {})},allowedValues:(row.effective.allowedValues??[]).map((value,index)=>{const valueId=row.effective.allowedValueIds?.[index]??stableValueIdentity(id,value),source=valueProvenance.get(valueId);return{id:valueId,value:clone(value),provenance:[ownershipProvenance(row,entity,valueId,source,localValueIds)]};}),rules,documentation:{displayText:"",description:row.effective.documentation??"",comments:"",example:row.effective.examples?.length?{method:"custom",value:clone(row.effective.examples[0])}:{method:"blank"}},provenance:row.provenance.map(({contributorId,contributorName,scope:originScope,state:originState})=>({source:"path-constraint" as const,sourceId:contributorId,contributorId,contributorName,scope:originScope,state:originState})),overrideReferences:[...(row.effective.overrideReferences??[])],...(row.effective.expectedValue!==undefined?{expectedValue:clone(row.effective.expectedValue)}:{}),...(row.effective.enforcement?{enforcement:row.effective.enforcement}:{}),...(row.effective.target?{target:row.effective.target}:{})};
    document.nodes[id]=node;byPath.set(row.path,id);
  }
  document.rootIds=Object.values(document.nodes).filter(({parentId})=>!parentId).sort((left,right)=>left.order-right.order).map(({id})=>id);document.revision=Math.max(1,...layeredContributorsForPath(state,layeredContributorPath(state,entity,scope)).map((contributor)=>Number((entities(state).find(({id})=>id===contributor.id)?.canonicalSchema as CanonicalSchemaDocument|undefined)?.revision??0)))+((entity.localSchemaContributions as LayerConstraint[]|undefined)?.length??0);document.changes=[];document.source={identity:entity.id,revision:document.revision,provenance:"project-composed-effective"};if(document.rootIds[0])document.selectedPropertyId=document.rootIds[0];return document;
}

export function resetCanonicalRow(canonical:CanonicalSchemaDocument|undefined,path:string,next:ProjectEntity):ProjectEntity {const row=canonical&&canonicalTableRows(canonical).find((candidate)=>candidate.path===path);if(row){const result=applyCanonicalCommand(canonical,{kind:"delete",baseRevision:canonical.revision,propertyId:row.id});if(result.status==="applied"||result.status==="rebased")next.canonicalSchema=result.document;}return next;}
