import type {LayerConstraint} from "../data-layer-layered-schema.js";
import type {ComposedFacetDraft,ComposedCondition,ConditionGroup} from "./builder-types.js";
const clone=<T>(value:T):T=>structuredClone(value);
const same=(left:unknown,right:unknown):boolean=>JSON.stringify(left)===JSON.stringify(right);
const normalizedCondition=(condition:Record<string,unknown>):ComposedCondition=>{if(condition.kind==="predicate")return clone(condition) as unknown as ComposedCondition;if(["all","any","not"].includes(String(condition.kind)))return{kind:condition.kind as ConditionGroup["kind"],children:((condition.children as Record<string,unknown>[]|undefined)??[]).map(normalizedCondition)};return{kind:"predicate",propertyId:String(condition.propertyId??condition.field??"/property"),operator:String(condition.operator??(condition.equals!==undefined?"Equals":"Exists")),...(condition.value!==undefined?{value:clone(condition.value)}:condition.equals!==undefined?{value:clone(condition.equals)}:{})};};
const conditionGroup=(condition:LayerConstraint["condition"]):ConditionGroup=>condition&&["all","any","not"].includes(String(condition.kind))?normalizedCondition(condition) as ConditionGroup:{kind:"all",children:condition?[normalizedCondition(condition)]:[]};
const persistedCondition=(condition:ComposedCondition):ComposedCondition=>condition.kind==="predicate"?clone(condition):{...clone(condition),children:condition.children.map((child)=>persistedCondition(child))};
export function composedFacetDraft(local:LayerConstraint,effective:LayerConstraint):ComposedFacetDraft{const examples=local.examples??effective.examples??[],allowedValues=clone([...(effective.allowedValues??local.allowedValues??[])]),allowedValueIds=effective.allowedValueIds??local.allowedValueIds,allowedValueProvenance=effective.allowedValueProvenance??local.allowedValueProvenance,exampleMethod:ComposedFacetDraft["exampleMethod"]=!examples.length?"blank":allowedValues.some((value)=>same(value,examples[0]))?"allowed-value":"custom";return{type:local.type??effective.type,itemType:local.itemType??effective.itemType,presence:local.presence??effective.presence,expectedValue:Object.hasOwn(local,"expectedValue")?clone(local.expectedValue):clone(effective.expectedValue),allowedValues,...(allowedValueIds?{allowedValueIds:[...allowedValueIds]}:{}),...(allowedValueProvenance?{allowedValueProvenance:clone([...allowedValueProvenance])}:{}),condition:conditionGroup(local.condition??effective.condition),rules:clone([...(effective.rules??local.rules??[])]),documentation:String(local.documentation??effective.documentation??""),exampleMethod,...(examples.length?{exampleValue:clone(examples[0])}:{})};}
export function overrideComposedAllowedValue(draft:ComposedFacetDraft,index:number,localId:string):ComposedFacetDraft{if(index<0||index>=draft.allowedValues.length)return draft;const ids=[...(draft.allowedValueIds??draft.allowedValues.map((_,candidate)=>`allowed-value:${candidate}`))];ids[index]=localId;const provenance=[...(draft.allowedValueProvenance??[]).filter(({id})=>id!==localId),{id:localId,state:"overridden" as const,source:"focused-editor"}];return{...draft,allowedValueIds:ids,allowedValueProvenance:provenance};}
export function addComposedRule(draft:ComposedFacetDraft,rule:Record<string,unknown>):ComposedFacetDraft{return{...draft,rules:[...draft.rules,clone(rule)]};}
/** Return a draft with the explicitly removed, identity-bearing items omitted. */
export function composedFacetDraftWithoutRemovedItems(draft:ComposedFacetDraft,removedRuleIds:ReadonlySet<string>=new Set(),removedValueIds:ReadonlySet<string>=new Set()):ComposedFacetDraft{
  const valueIds=draft.allowedValueIds;
  const keptValues=draft.allowedValues.map((value,index)=>({value,index,id:valueIds?.[index]})).filter(({id})=>!id||!removedValueIds.has(id));
  return {...draft,allowedValues:keptValues.map(({value})=>clone(value)),...(valueIds?{allowedValueIds:keptValues.map(({id})=>id!).filter(Boolean)}:{}),rules:draft.rules.filter((rule)=>!removedRuleIds.has(String(rule.id??"")))};
}
export function overrideComposedRule(draft:ComposedFacetDraft,index:number,id:string):ComposedFacetDraft{const rule=draft.rules[index];if(!rule)return draft;const replacement=clone(rule);replacement.id=id;replacement.provenance={source:"created",state:"effective"};return{...draft,rules:draft.rules.map((candidate,candidateIndex)=>candidateIndex===index?replacement:candidate)};}
export function composedRuleIssue(rule:Record<string,unknown>):string|undefined{if(!String(rule.message??"").trim())return"Enter an issue message.";if(rule.kind==="pattern"&&!String(rule.pattern??"").trim())return"Enter a regular expression.";if(rule.kind==="range"&&rule.minimum===undefined&&rule.maximum===undefined)return"Enter a minimum or maximum.";if(rule.kind==="cardinality"&&rule.minItems===undefined&&rule.maxItems===undefined)return"Enter minimum or maximum items.";if(rule.kind==="condition"&&!rule.condition)return"Build a condition before adding a condition rule.";return undefined;}
export function sparseComposedFacets(draft:ComposedFacetDraft,inherited:LayerConstraint):Omit<LayerConstraint,"path">{if(draft.exampleMethod!=="blank"&&draft.exampleValue===undefined)throw new Error(draft.exampleMethod==="allowed-value"?"Choose an allowed-value example.":"Enter a custom typed example.");if(draft.exampleMethod==="allowed-value"&&!draft.allowedValues.some((value)=>same(value,draft.exampleValue)))throw new Error("Choose an example from the current allowed values.");const candidate:Omit<LayerConstraint,"path">={...(draft.type?{type:draft.type}:{}),...(draft.itemType?{itemType:draft.itemType}:{}),...(draft.presence?{presence:draft.presence}:{}),...(draft.expectedValue!==undefined?{expectedValue:clone(draft.expectedValue)}:{}),...(draft.allowedValues.length?{allowedValues:clone(draft.allowedValues),...(draft.allowedValueIds?{allowedValueIds:clone(draft.allowedValueIds)}:{}),...(draft.allowedValueProvenance?{allowedValueProvenance:clone(draft.allowedValueProvenance)}:{})}:{}),...(draft.condition.children.length?{condition:persistedCondition(draft.condition) as unknown as Record<string,unknown>}:{ }),...(draft.rules.length?{rules:clone(draft.rules)}:{}),...(draft.documentation?{documentation:draft.documentation}:{}),...(draft.exampleMethod!=="blank"?{examples:[clone(draft.exampleValue)]}:{})};return Object.fromEntries(Object.entries(candidate).filter(([key,value])=>!same(value,inherited[key as keyof LayerConstraint]))) as Omit<LayerConstraint,"path">;}
