import type {LayerConstraint} from "../data-layer-layered-schema.js";
import {focusedRuleIssue} from "../data-layer-focused-rule-policy.js";
import type {ComposedFacetDraft,ComposedCondition,ConditionGroup} from "./builder-types.js";
const clone=<T>(value:T):T=>structuredClone(value);
const same=(left:unknown,right:unknown):boolean=>JSON.stringify(left)===JSON.stringify(right);
const normalizedCondition=(condition:Record<string,unknown>):ComposedCondition=>{if(condition.kind==="predicate")return clone(condition) as unknown as ComposedCondition;if(["all","any","not"].includes(String(condition.kind))){const normalized=clone(condition) as unknown as ConditionGroup;normalized.kind=condition.kind as ConditionGroup["kind"];normalized.children=((condition.children as Record<string,unknown>[]|undefined)??[]).map(normalizedCondition);return normalized;}return{kind:"predicate",propertyId:String(condition.propertyId??condition.field??"/property"),operator:String(condition.operator??(condition.equals!==undefined?"Equals":"Exists")),...(condition.value!==undefined?{value:clone(condition.value)}:condition.equals!==undefined?{value:clone(condition.equals)}:{})};};
const conditionGroup=(condition:LayerConstraint["condition"]):ConditionGroup=>condition&&["all","any","not"].includes(String(condition.kind))?normalizedCondition(condition) as ConditionGroup:{kind:"all",children:condition?[normalizedCondition(condition)]:[]};
const persistedCondition=(condition:ComposedCondition):ComposedCondition=>condition.kind==="predicate"?clone(condition):{...clone(condition),children:condition.children.map((child)=>persistedCondition(child))};
export function composedFacetDraft(local:LayerConstraint,effective:LayerConstraint):ComposedFacetDraft{const examples=local.examples??effective.examples??[],allowedValues=clone([...(local.allowedValues??effective.allowedValues??[])]),allowedValueIds=local.allowedValueIds??effective.allowedValueIds,allowedValueProvenance=local.allowedValueProvenance??effective.allowedValueProvenance,exampleMethod:ComposedFacetDraft["exampleMethod"]=!examples.length?"blank":allowedValues.some((value)=>same(value,examples[0]))?"allowed-value":"custom";return{concept:local.concept??effective.concept,type:local.type??effective.type,itemType:local.itemType??effective.itemType,...(local.itemSchema??effective.itemSchema?{itemSchema:clone(local.itemSchema??effective.itemSchema)}:{}),presence:local.presence??effective.presence,expectedValue:Object.hasOwn(local,"expectedValue")?clone(local.expectedValue):clone(effective.expectedValue),allowedValues,...(allowedValueIds?{allowedValueIds:[...allowedValueIds]}:{}),...(allowedValueProvenance?{allowedValueProvenance:clone([...allowedValueProvenance])}:{}),condition:conditionGroup(local.condition??effective.condition),rules:clone([...(local.rules??[])]),displayText:String(local.displayText??effective.displayText??""),documentation:String(local.documentation??effective.documentation??""),comments:String(local.comments??effective.comments??""),exampleMethod,...(examples.length?{exampleValue:clone(examples[0])}:{})};}
export function overrideComposedAllowedValue(draft:ComposedFacetDraft,index:number,localId:string):ComposedFacetDraft{if(index<0||index>=draft.allowedValues.length)return draft;const ids=[...(draft.allowedValueIds??draft.allowedValues.map((_,candidate)=>`allowed-value:${candidate}`))];ids[index]=localId;const provenance=[...(draft.allowedValueProvenance??[]).filter(({id})=>id!==localId),{id:localId,state:"overridden" as const,source:"focused-editor"}];return{...draft,allowedValueIds:ids,allowedValueProvenance:provenance};}
export function addComposedRule(draft:ComposedFacetDraft,rule:Record<string,unknown>):ComposedFacetDraft{return{...draft,rules:[...draft.rules,clone(rule)]};}
/** Return a draft with the explicitly removed, identity-bearing items omitted. */
export function composedFacetDraftWithoutRemovedItems(draft:ComposedFacetDraft,removedRuleIds:ReadonlySet<string>=new Set(),removedValueIds:ReadonlySet<string>=new Set()):ComposedFacetDraft{
  const valueIds=draft.allowedValueIds;
  const keptValues=draft.allowedValues.map((value,index)=>({value,index,id:valueIds?.[index]})).filter(({id})=>!id||!removedValueIds.has(id));
  return {...draft,allowedValues:keptValues.map(({value})=>clone(value)),...(valueIds?{allowedValueIds:keptValues.map(({id})=>id!).filter(Boolean)}:{}),rules:draft.rules.filter((rule)=>!removedRuleIds.has(String(rule.id??"")))};
}
export function overrideComposedRule(draft:ComposedFacetDraft,index:number,id:string):ComposedFacetDraft{const rule=draft.rules[index];if(!rule)return draft;const replacement=clone(rule),sourceId=String(rule.id??"");replacement.id=id;replacement.replacesRuleId=sourceId;replacement.provenance={source:"created",state:"overridden",sourceId};return{...draft,rules:draft.rules.map((candidate,candidateIndex)=>candidateIndex===index?replacement:candidate)};}
export const composedRuleIssue=focusedRuleIssue;
export function sparseComposedFacets(draft:ComposedFacetDraft,inherited:LayerConstraint):Omit<LayerConstraint,"path">{if(draft.exampleMethod!=="blank"&&draft.exampleValue===undefined)throw new Error(draft.exampleMethod==="allowed-value"?"Choose an allowed-value example.":"Enter a custom typed example.");if(draft.exampleMethod==="allowed-value"&&!draft.allowedValues.some((value)=>same(value,draft.exampleValue)))throw new Error("Choose an example from the current allowed values.");const localValueOwnership=draft.allowedValueProvenance?.some(({state})=>state!=="inherited")===true,candidate:Omit<LayerConstraint,"path">={...(draft.concept?.trim()?{concept:draft.concept.trim()}:{}),...(draft.type?{type:draft.type}:{}),...(draft.itemType?{itemType:draft.itemType}:{}),...(draft.itemSchema?{itemSchema:clone(draft.itemSchema)}:{}),...(draft.presence?{presence:draft.presence}:{}),...(draft.expectedValue!==undefined?{expectedValue:clone(draft.expectedValue)}:{}),...(draft.allowedValues.length?{allowedValues:clone(draft.allowedValues),...(draft.allowedValueIds?{allowedValueIds:clone(draft.allowedValueIds)}:{}),...(draft.allowedValueProvenance?{allowedValueProvenance:clone(draft.allowedValueProvenance)}:{})}:{}),...(draft.condition.children.length?{condition:persistedCondition(draft.condition) as unknown as Record<string,unknown>}:{ }),...(draft.rules.length?{rules:clone(draft.rules)}:{}),...(draft.displayText?{displayText:draft.displayText}:{}),...(draft.documentation?{documentation:draft.documentation}:{}),...(draft.comments?{comments:draft.comments}:{}),...(draft.exampleMethod!=="blank"?{examples:[clone(draft.exampleValue)]}:{})};return Object.fromEntries(Object.entries(candidate).filter(([key,value])=>localValueOwnership&&(key==="allowedValues"||key==="allowedValueIds"||key==="allowedValueProvenance")||!same(value,inherited[key as keyof LayerConstraint]))) as Omit<LayerConstraint,"path">;}
