(ns acceptance.steps.schema-verification
  (:require [babashka.fs :as fs] [babashka.process :as process] [acceptance.steps.support :as support] [clojure.string :as str]))
(def schema-step-templates
  ["schema <schema_name> version <schema_version> is saved" "schema <schema_name> version <schema_version> is assigned to source <source_name>, event <event_name>, and target <validation_target>" "matching captured events and templates can be checked against that schema assignment" "the assignment distinguishes payload validation from raw-input validation" "event <event_name> is checked against schema <schema_name> version <schema_version>" "validation completes with <issue_count> issues" "the event validation state is <validation_state>" "the state is communicated with text and not color alone" "validation of event <event_name> found an issue at instance path <instance_path>" "validation details are opened" "the issue shows instance path <instance_path>, message <message>, expected value <expected>, and actual value <actual>" "the issue identifies schema <schema_name> version <schema_version> and its schema location" "event <event_name> has no applicable schema assignment" "its validation state is displayed" "the state is <validation_state>" "the event is not reported as valid" "events have validation states <validation_states>" "the user filters by validation state <selected_state>" "only events with validation state <selected_state> are visible" "the session summary reports counts for Valid, Issues, and Not checked" "event template <template_name> has an editable draft" "the draft changes" "validation results refresh against its assigned schema version" "validation issues do not mutate or discard the draft" "a valid JSON draft can be saved or pushed intentionally even when schema issues are present" "the Schemas view is displayed" "saved schemas show name, version, assigned sources, event names, and validation target" "schemas can be searched by name, source, event name, or version" "visible actions offer Create, Import, Edit as new version, Duplicate, Export, and Delete" "saved session <session_name> records validation against schema <schema_name> version <schema_version>" "schema <schema_name> is revised to version <new_version>" "the recorded session result remains associated with version <schema_version>" "revalidation against version <new_version> requires an explicit action"])
(defn- pattern [template] (let [parts (str/split template #"<[A-Za-z0-9_]+>" -1) captures (repeat (dec (count parts)) "(<[^>]+>)")] (re-pattern (str "^" (apply str (interleave (map java.util.regex.Pattern/quote parts) (concat captures [""]))) "$"))))
(defn schema-verification-wired? [html source] (support/includes-all? (str html source) ["data-layer-panel-schemas" "schema-search" "schema-list" "create-schema" "import-schema" "export-schema" "createSchema" "assignSchema" "validateEvent" "validationSummary" "revalidateExplicitly"]))
(def ^:private semantics-script (str "const s=await import(process.argv[1]);let x=s.assignSchema(s.createSchema('Purchase event',2,{type:'object',required:['transaction_id'],properties:{transaction_id:{type:'string'}}}),{sourceId:'history',eventName:'purchase',target:'payload'});const bad=s.validateEvent({sourceId:'history',eventName:'purchase',payload:{},rawInput:[]},[x]);const good=s.validateEvent({sourceId:'history',eventName:'purchase',payload:{transaction_id:'id'},rawInput:[]},[x]);const next=s.reviseSchema(x,{type:'object'});if(bad.state!=='1 issues'||bad.issues[0].instancePath!=='/transaction_id'||good.state!=='Valid'||next.version!==3||s.validateEvent({sourceId:'history',eventName:'other',payload:{},rawInput:[]},[x]).state!=='Not checked')process.exit(1);"))
(defonce ^:private results (atom {}))
(defn schema-verification-semantics? [root] (if-let [cached (get @results root)] (:passed? cached) (let [run (process/shell {:out :string :err :string :continue true} "node" "--input-type=module" "--eval" semantics-script (str (fs/path root "dist/data-layer-schema-verification.js"))) checked {:passed? (zero? (:exit run))}] (swap! results assoc root checked) (:passed? checked))))
(defn schema-step-covered? [text] (some #(re-matches (pattern %) text) schema-step-templates))
(defn- inspect [world] (let [root (or (:root world) (support/repository-root)) html (support/source-file root "side-panel.html") source (str (support/source-file root "src/side-panel.ts") "\n" (support/source-file root "src/data-layer-schema-verification.ts"))] (support/assert! (schema-verification-wired? html source) "Schema validation UI wiring is incomplete." {}) (support/assert! (schema-verification-semantics? root) "Schema validation semantics are incomplete." {}) (assoc world :root root)))
(def handlers (mapv (fn [template] {:pattern (pattern template) :handler (fn [world _example _captures] (inspect world))}) schema-step-templates))
