import {createSpecificationProject,type ProjectState} from "../data-layer-specification-project.js";
import {PROJECT_LIBRARY_STORAGE_KEY,serializeProjectLibrary,type ProjectLibrary,type ProjectLibraryRecord} from "../data-layer-project-library.js";
import {CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY,serializeCanonicalProjectState} from "../data-layer-specification-repository.js";
import type {DurableLoadedProject,DurableProjectRoute} from "../data-layer-durable-project-repository.js";
export const same=(left:unknown,right:unknown)=>JSON.stringify(left)===JSON.stringify(right);
export const cleanState=(state:ProjectState):ProjectState=>({...structuredClone(state),history:{undo:[],redo:[]}});
export const historyLabel=(state:ProjectState):string|undefined=>state.history.undo.at(-1)?.label;
export const cleanRecord=(value:ProjectLibraryRecord):ProjectLibraryRecord=>({...structuredClone(value),state:cleanState(value.state)});
export const cleanLibrary=(value:ProjectLibrary):ProjectLibrary=>({...structuredClone(value),projects:Object.fromEntries(Object.entries(value.projects).map(([projectId,entry])=>[projectId,cleanRecord(entry)]))});
export const routeWithRetainedHydration=(previous:DurableProjectRoute|undefined,next:DurableProjectRoute):DurableProjectRoute=>previous&&previous.collectionKind===next.collectionKind&&previous.entityId===next.entityId?{...next,collectionKinds:[...new Set([...(previous.collectionKinds??[]),...(next.collectionKinds??[])])],includeFlowGraphs:Boolean(previous.includeFlowGraphs||next.includeFlowGraphs),includeFixtures:Boolean(previous.includeFixtures||next.includeFixtures),includeReleases:Boolean(previous.includeReleases||next.includeReleases)}:next;
export function placeholder(metadata:{projectId:string;name:string;site:string;owner:string;draftSequence:number;publishedRevision:number;lastSavedAt:string;navigation?:ProjectLibraryRecord["navigation"]}):ProjectLibraryRecord{const state=createSpecificationProject({name:metadata.name,site:metadata.site,id:(kind)=>kind==="project"?metadata.projectId:`placeholder:${kind}:${metadata.projectId}`});state.project.owner=metadata.owner;state.project.placeholder=true;return{state:cleanState(state),revision:metadata.draftSequence??0,publishedRevision:metadata.publishedRevision,createdAt:metadata.lastSavedAt,lastModifiedAt:metadata.lastSavedAt,...(metadata.navigation?{navigation:structuredClone(metadata.navigation)}:{})};}
export function record(loaded:DurableLoadedProject):ProjectLibraryRecord{return{state:cleanState(loaded.state),revision:loaded.draftSequence,publishedRevision:loaded.publishedRevision,createdAt:loaded.lastSavedAt,lastModifiedAt:loaded.lastSavedAt,...(loaded.navigation?{navigation:structuredClone(loaded.navigation)}:{})};}
export function writeProjectLibrary(memory:Map<string,string>,library:ProjectLibrary):void{memory.set(PROJECT_LIBRARY_STORAGE_KEY,serializeProjectLibrary(library));}
export function writeCanonicalState(memory:Map<string,string>,projectId:string,active:DurableLoadedProject|undefined):void{if(active?.state.project.id===projectId)memory.set(CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY,serializeCanonicalProjectState(active.state,active.draftSequence));}
