import {openIndexedDbProjectRepository,type DurableDraftCommand,type DurableProjectRepository} from "./data-layer-durable-project-repository.js";
import {createDurableRepositoryPresentation,installDurableRepositoryStartupFailurePresentation,type DurableRepositoryPresentation} from "./data-layer-durable-project-repository-presentation-ui.js";

interface DurableRecoveryInput{kind?:"project"|"saved-schema";projectId?:string;projectName:string;command:Pick<DurableDraftCommand,"label">;retry:()=>Promise<void>;reject?:()=>Promise<void>;exportUnsaved:()=>void;originControl?:HTMLElement;}
export interface DurableProjectRepositoryUi{repository:DurableProjectRepository;refresh():Promise<void>;reportSaveFailure(input:DurableRecoveryInput,error:unknown):Promise<void>;}

const text=(error:unknown)=>error instanceof Error?error.message:String(error);

export function installDurableRepositoryStartupFailure(root:Document,error:unknown):void{
  const message=`Durable project storage unavailable: ${text(error)}`;
  installDurableRepositoryStartupFailurePresentation(root,message);
}

export async function mountDurableProjectRepositoryUi(root:ParentNode,factory:IDBFactory=globalThis.indexedDB,existing?:DurableProjectRepository):Promise<DurableProjectRepositoryUi>{
  const repository=existing??await openIndexedDbProjectRepository(factory),statusHost=root.querySelector<HTMLElement>("#durable-repository-status");
  if(!statusHost)throw new Error("Missing durable repository control #durable-repository-status.");
  let failure:DurableRecoveryInput|undefined,presentation:DurableRepositoryPresentation;
  const estimate=async()=>{const value=await navigator.storage?.estimate?.();return typeof value?.usage==="number"&&typeof value?.quota==="number"?{usage:value.usage,quota:value.quota}:undefined;};
  const refresh=async(includeDiagnostics=false)=>{const projects=await repository.listProjectMetadata(),active=projects.find(({active})=>active),backup=includeDiagnostics?await repository.migrationBackup():undefined;if(!failure)presentation.status(`Durable project storage ready · ${projects.length} project${projects.length===1?"":"s"}${active?` · Active ${active.name}`:""}`);presentation.recoveryAvailable(Boolean(active||failure));if(backup)presentation.backupAvailable(backup.sources.length>0);if(active&&includeDiagnostics)presentation.diagnostics(await repository.storageDiagnostics(active.projectId,await estimate(),failure?.command.label));};
  const show=async(origin:HTMLElement)=>{await refresh(true);presentation.show(origin);};
  presentation=createDurableRepositoryPresentation(root,{
    open:(origin)=>show(origin),close:()=>presentation.close(),
    async diagnose(){await refresh(true);presentation.result("Storage diagnostics refreshed without deleting project data.",true);},
    async retry(){const activeFailure=failure;if(!activeFailure)return;try{await activeFailure.retry();presentation.result(activeFailure.kind==="saved-schema"?`${activeFailure.command.label} committed to the Saved Schema Library.`:`${activeFailure.command.label} saved. Project switching and publication are available.`,true);failure=undefined;presentation.recoveryControls({retry:false,reject:false,exportUnsaved:false});await refresh(true);}catch(error){presentation.result(activeFailure.kind==="saved-schema"?`Retry was not committed; the durable Saved Schema Library remains unchanged. ${text(error)}`:`Retry was not committed; the last Saved Draft remains unchanged. ${text(error)}`,true);}},
    async reject(){const activeFailure=failure;if(!activeFailure?.reject)return;try{await activeFailure.reject();presentation.result(`Rejected ${activeFailure.command.label}. The last Saved Draft was restored and the unsaved command was discarded.`,true);failure=undefined;presentation.recoveryControls({retry:false,reject:false,exportUnsaved:false});await refresh(true);}catch(error){presentation.result(`Reject could not restore the last Saved Draft. The unsaved command remains available. ${text(error)}`,true);}},
    exportUnsaved(){failure?.exportUnsaved();presentation.result(failure?failure.kind==="saved-schema"?`Exported the exact unsaved schema batch for ${failure.projectName}.`:`Exported unsaved Draft for ${failure.projectName}.`:"There is no unsaved operation to export.",true);},
    async exportBackup(){const bundle=await repository.exportRepositoryRecoveryBundle(),serialized=JSON.stringify(bundle),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([serialized],{type:"application/json"}));link.download="durable-repository-recovery.json";link.click();URL.revokeObjectURL(link.href);presentation.result(`Exported parseable recovery data for ${bundle.projects instanceof Array?bundle.projects.length:0} projects, all saved schemas, immutable revisions, fixtures, releases, and migration sources.`,true);},
    reviewDeleteBackup(){presentation.showDeleteReview();},
    cancelDeleteBackup(){presentation.hideDeleteReview();presentation.result("Cancelled. The retained legacy migration backup remains available; current projects are unchanged.",true);},
    async confirmDeleteBackup(){try{const deleted=await repository.deleteMigrationBackup({backupId:"legacy-v1",label:"Delete retained legacy migration backup"});presentation.hideDeleteReview();presentation.result(deleted?"Deleted only the retained legacy migration backup. Current projects, saved schemas, fixtures, releases, and Published revisions are unchanged.":"No retained legacy migration backup was present; current projects are unchanged.",true);await refresh(true);}catch(error){presentation.showDeleteReview();presentation.result(`Migration backup deletion was not committed. The retained backup and current projects remain unchanged. ${text(error)}`,true);}},
  });
  const ui:DurableProjectRepositoryUi={repository,refresh,async reportSaveFailure(input,error){failure=input;const schema=input.kind==="saved-schema";presentation.status(schema?`Save failed for ${input.projectName}: ${input.command.label}. The durable Saved Schema Library is unchanged. ${text(error)}`:`Save failed for ${input.projectName}: ${input.command.label}. Last Saved Draft is unchanged. ${text(error)}`);presentation.recoveryControls({retry:true,reject:Boolean(input.reject),exportUnsaved:true});if(input.projectId)presentation.diagnostics(await repository.storageDiagnostics(input.projectId,await estimate(),input.command.label));await show(input.originControl??statusHost);presentation.result(schema?`${input.command.label} was not committed. Retry the exact batch or export it for recovery.`:`${input.command.label} was not committed. Retry, reject, or export the unsaved Draft.`);}};repository.subscribe(()=>{void refresh();});repository.subscribeProjectMetadata(()=>{void refresh();});repository.subscribeActiveContext(()=>{void refresh();});await refresh();return ui;
}
