import {compileLayeredSchema,exportLayeredSchema,resolveLayeredTarget,validateLayeredObservation,type LayerActivation,type LayerConstraint,type LayerPredicate,type LayerScope,type LayerTarget} from "./data-layer-layered-schema.js";
import {confirmCanonicalMigration,redoProjectTransaction,transactProject,undoProjectTransaction,type ProjectEntity,type ProjectEntityKind,type ProjectState} from "./data-layer-specification-project.js";
import {applyCanonicalCommand,canonicalSchemaWithConstraint,canonicalTableRows,createCanonicalSchema,migrateLegacyProfile,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import {mountCanonicalSchemaEditor} from "./data-layer-canonical-schema-ui.js";
import {mountComposedSchemaFacetBuilder} from "./data-layer-composed-schema-builders.js";
import {composedSchemaWorkspace,resetComposedSchemaLocalProperty,saveComposedSchemaLocalFacets} from "./data-layer-composed-schema-workspace.js";
import {flowPageFrameContributor,layeredContributionDetails,layeredContributorPath,layeredContributorsForPath} from "./data-layer-layered-schema-project.js";
import {resolveSidePanelSchemaContributor,type SidePanelContributorSelection} from "./data-layer-side-panel-schema-editor.js";
import {CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY} from "./data-layer-specification-repository.js";

export {layeredContributionDetails,layeredContributorPath,layeredContributorsForPath} from "./data-layer-layered-schema-project.js";

interface LayeredSchemaUiOptions{context:()=>{state?:ProjectState;kind:ProjectEntityKind;entityId?:string};persist:(state:ProjectState)=>void}
const q=<T extends Element>(selector:string):T=>{const value=document.querySelector<T>(selector);if(!value)throw new Error(`Missing ${selector}`);return value;};
const scopeFor=(kind:ProjectEntityKind):LayerScope=>({profiles:"Shared Profile",events:"Event",pageGroups:"Page Group",pages:"Page",flows:"Flow Page-instance"} as Partial<Record<ProjectEntityKind,LayerScope>>)[kind]??"Event-occurrence";
export const canonicalLayerEditorSurface=(kind:ProjectEntityKind):"Builder"|"Flow workspace"=>kind==="flows"?"Flow workspace":"Builder";
const structuredPaths=(document:unknown,prefix=""):string[]=>{if(!document||typeof document!=="object")return[];const properties=(document as {properties?:Record<string,unknown>}).properties??{};return Object.entries(properties).flatMap(([name,value])=>{const path=`${prefix}/${name}`;return[path,...structuredPaths(value,path)];});};
export function composeStructuredRules(rules:Record<string,unknown>[],reusableRules:Record<string,unknown>[],structured:{field?:string;operator?:string;value?:string;reusableRuleId?:string}){return{rules:[...rules,...(structured.field?[{field:structured.field,operator:structured.operator||"equals",...(structured.value?{value:structured.value}:{})}]:[])],reusableRules:[...reusableRules,...(structured.reusableRuleId?[{id:structured.reusableRuleId}]:[])]};}
const profileStructuredDocument=(profile:ProjectEntity):unknown=>(profile.canonicalSchema as CanonicalSchemaDocument|undefined)?.sourceContent?.document??profile.structuredSchema??(profile.structuredDraft as {document?:unknown}|undefined)?.document;
export const sharedProfilePropertyPaths=(profile:ProjectEntity):string[]=>{const canonical=profile.canonicalSchema as CanonicalSchemaDocument|undefined;return canonical?canonicalTableRows(canonical).map(({path})=>path):[...new Set([...structuredPaths(profileStructuredDocument(profile)),...((profile.schemaConstraints as LayerConstraint[]|undefined)??[]).map(({path})=>path)])];};
export type LayeredRevisionChoice="source"|"draft";
export function compareLayeredRevisions(entity:ProjectEntity,from:LayeredRevisionChoice,to:LayeredRevisionChoice){const canonical=entity.canonicalSchema as CanonicalSchemaDocument|undefined,sourcePaths=structuredPaths(profileStructuredDocument(entity)),draftPaths=sharedProfilePropertyPaths(entity),pathsFor=(choice:LayeredRevisionChoice)=>choice==="source"?sourcePaths:draftPaths,labelFor=(choice:LayeredRevisionChoice)=>choice==="source"?`Source revision ${String(entity.sourceRevision??canonical?.source?.revision??"new")}`:"Current draft",fromPaths=pathsFor(from),toPaths=pathsFor(to),fromSet=new Set(fromPaths),toSet=new Set(toPaths);return{fromLabel:labelFor(from),toLabel:labelFor(to),addedPaths:toPaths.filter((path)=>!fromSet.has(path)),removedPaths:fromPaths.filter((path)=>!toSet.has(path)),retainedPaths:toPaths.filter((path)=>fromSet.has(path)),constraintChanges:from===to?0:canonical?.changes.length??((entity.schemaConstraints as LayerConstraint[]|undefined)??[]).length};}
const appendRevisionComparisonControls=(host:HTMLElement,entity:ProjectEntity,ariaLabel:string):void=>{const from=document.createElement("select"),to=document.createElement("select"),compare=document.createElement("button"),result=document.createElement("output"),labeled=(text:string,control:HTMLElement)=>{const label=document.createElement("label");label.append(text,control);return label;},option=(choice:LayeredRevisionChoice)=>new Option(choice==="source"?`Source revision ${String(entity.sourceRevision??"new")}`:"Current draft",choice);host.setAttribute("aria-label",ariaLabel);from.setAttribute("aria-label",`${ariaLabel} from`);to.setAttribute("aria-label",`${ariaLabel} to`);from.append(option("source"),option("draft"));to.append(option("source"),option("draft"));from.value="source";to.value="draft";compare.type="button";compare.textContent="Compare revisions";result.setAttribute("aria-label",`${ariaLabel} result`);result.textContent="Choose revisions, then compare.";compare.addEventListener("click",()=>{const comparison=compareLayeredRevisions(entity,from.value as LayeredRevisionChoice,to.value as LayeredRevisionChoice),paths=(values:string[])=>values.length?values.join(", "):"none";result.textContent=`${comparison.fromLabel} → ${comparison.toLabel} · Added: ${paths(comparison.addedPaths)} · Removed: ${paths(comparison.removedPaths)} · Retained: ${comparison.retainedPaths.length} · Draft constraint changes: ${comparison.constraintChanges}`;});host.append(labeled("Compare from",from),labeled("Compare to",to),compare,result);};
export function appendSharedProfileConstraint(state:ProjectState,profileId:string,constraint:LayerConstraint):ProjectState{const profile=state.project.collections.profiles.find(({id})=>id===profileId);if(!profile)throw new Error(`Shared Profile ${profileId} is unavailable.`);const canonical=(profile.canonicalSchema as CanonicalSchemaDocument|undefined)??migrateLegacyProfile(profile,{id:(kind)=>`${kind}:${crypto.randomUUID()}`}).document,next=canonicalSchemaWithConstraint(canonical,constraint,(kind)=>`${kind}:${crypto.randomUUID()}`);return transactProject(state,`Save canonical schema contribution for ${profile.name}`,(project)=>({...project,collections:{...project.collections,profiles:project.collections.profiles.map((candidate)=>{if(candidate.id!==profileId)return candidate;const updated:ProjectEntity={...candidate,requirements:[],canonicalSchema:next,compiledTargetsStale:true};delete updated.structuredSchema;delete updated.structuredDraft;delete updated.schemaConstraints;return updated as typeof candidate;})}}));}

interface SidePanelLayeredProfileEditorOptions{host:HTMLElement;legacyEditor?:HTMLElement|null;emptyHost?:HTMLElement|null;load:()=>ProjectState|undefined;persist:(state:ProjectState)=>void}
const writeSidePanelCanonical=(state:ProjectState,selection:SidePanelContributorSelection,canonical:CanonicalSchemaDocument):ProjectState=>transactProject(state,`Save canonical schema for ${selection.entity.name}`,(project)=>{if(selection.collectionKind){const collection=project.collections[selection.collectionKind] as ProjectEntity[];return{...project,collections:{...project.collections,[selection.collectionKind]:collection.map((candidate)=>candidate.id===selection.entity.id?{...candidate,canonicalSchema:canonical,...(selection.collectionKind==="profiles"?{requirements:[]}:{})}:candidate)}} as typeof project;}const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences?:ProjectEntity[];relationships?:ProjectEntity[]}>,graph=graphs[selection.flowId!]!,key=selection.scope==="Flow Page-instance"?"pageFrames":"occurrences",entries=graph[key]??[];return{...project,documentationFlowGraphs:{...graphs,[selection.flowId!]:{...graph,[key]:entries.map((candidate)=>candidate.id===selection.entity.id?{...candidate,canonicalSchema:canonical}:candidate)}}};});
export function renderSidePanelComposedSchemaContext(options:{host:HTMLElement;load:()=>ProjectState|undefined;key:string;persist:(state:ProjectState)=>void;render:()=>void}):void{
  const state=options.load(),selection=state?resolveSidePanelSchemaContributor(state,options.key):undefined;if(!state||!selection||(selection.collectionKind!=="pages"&&selection.collectionKind!=="pageGroups"))return;const scope=selection.collectionKind==="pages"?"Page":"Page Group",model=composedSchemaWorkspace(state,selection.entity,scope),facets=document.createElement("section"),propertyChoices=model.rows.flatMap(({path,effective})=>effective.definitionId?[{path,definitionId:effective.definitionId,type:effective.type}]:[]);facets.setAttribute("aria-label","Inherited and sparse local schema facets");for(const row of model.rows){const article=document.createElement("article"),summary=document.createElement("p"),builder=document.createElement("section"),reset=document.createElement("button");article.dataset.sidePanelEffectivePath=row.path;summary.textContent=`${row.path} · inherited ${row.inherited?effectivePropertySummary(row.inherited):"none"} · local ${Object.keys(row.local).length>1?"present":"none"} · effective ${effectivePropertySummary(row.effective)} · ${row.validationState} · provenance ${row.provenance.map(({contributorName})=>contributorName).join(" → ")}`;mountComposedSchemaFacetBuilder({host:builder,path:row.path,local:row.local,effective:row.effective,inherited:row.inherited,propertyChoices,onSave:(next)=>{const live=options.load(),selected=live?resolveSidePanelSchemaContributor(live,options.key):undefined;if(live&&(selected?.collectionKind==="pages"||selected?.collectionKind==="pageGroups"))options.persist(saveComposedSchemaLocalFacets(live,selected.collectionKind,selected.entity.id,row.path,next));options.render();}});reset.type="button";reset.textContent=row.action==="override"?"Override here":"Reset to parents";reset.addEventListener("click",()=>{if(row.action==="override"){builder.querySelector<HTMLElement>("input,select,button")?.focus();return;}const live=options.load(),selected=live?resolveSidePanelSchemaContributor(live,options.key):undefined;if(live&&(selected?.collectionKind==="pages"||selected?.collectionKind==="pageGroups"))options.persist(resetComposedSchemaLocalProperty(live,selected.collectionKind,selected.entity.id,row.path));options.render();});article.append(summary,reset,builder);facets.append(article);}options.host.append(facets);
}
export function mountSidePanelLayeredProfileEditor(options:SidePanelLayeredProfileEditorOptions):{render():void;select(key:string):boolean;close():void}{
  let selectedKey:string|undefined;
  const current=()=>{const state=options.load(),selection=state&&selectedKey?resolveSidePanelSchemaContributor(state,selectedKey):undefined;return{state,selection};};
  const close=()=>{selectedKey=undefined;options.host.hidden=true;options.host.replaceChildren();};
  const render=()=>{const {state,selection}=current();options.host.replaceChildren();if(!state||!selection){options.host.hidden=true;return;}options.host.hidden=false;if(options.legacyEditor)options.legacyEditor.hidden=true;if(options.emptyHost)options.emptyHost.hidden=true;options.host.setAttribute("aria-label","Side panel schema editor region");options.host.dataset.schemaContributorKey=selectedKey!;const heading=document.createElement("h4"),identity=document.createElement("p"),inheritance=document.createElement("section"),order=document.createElement("ol"),compiled=compileLayeredSchema(layeredContributorsForPath(state,layeredContributorPath(state,selection.entity,selection.scope,selection.flowId)),{eventId:String(selection.entity.eventId??selection.entity.id),eventRole:layeredEventRole(selection.entity),occurrenceId:selection.entity.id}),contributors=layeredContributorsForPath(state,layeredContributorPath(state,selection.entity,selection.scope,selection.flowId));heading.textContent=selection.entity.name;identity.textContent=`Role ${selection.scope} · scope ${selection.scope} · lineage ${contributors.map(({name})=>name).join(" → ")||"Project root"} · revision ${(selection.entity.canonicalSchema as CanonicalSchemaDocument|undefined)?.revision??0} · Draft`;inheritance.setAttribute("aria-label","Canonical inheritance and provenance");for(const[at,contributor]of contributors.entries()){const item=document.createElement("li");item.textContent=`${contributor.scope} ${contributor.name} · ${at===contributors.length-1?"local and effective":"inherited"} · provenance ${contributor.id}`;order.append(item);}const status=document.createElement("p");status.textContent=`Effective ${Object.keys(compiled.properties).length} · shadowed ${Object.values(compiled.properties).reduce((count,property)=>count+property.superseded.length,0)} · conflicting ${compiled.conflicts.length}`;inheritance.append(order,status);options.host.append(heading,identity,inheritance);
    const canonical=selection.entity.canonicalSchema as CanonicalSchemaDocument|undefined;if(!canonical){const review=document.createElement("section"),summary=document.createElement("p"),confirm=document.createElement("button"),migration=selection.scope==="Shared Profile"?migrateLegacyProfile(selection.entity,{id:(kind)=>`${kind}:${crypto.randomUUID()}`}):undefined;review.setAttribute("aria-label","Canonical schema migration review");summary.textContent=migration?`Migration review: ${Object.keys(migration.document.nodes).length} properties · ${migration.conflicts.length} conflicts.`:"Initialize one canonical contribution for this schema role.";confirm.type="button";confirm.textContent=migration?"Confirm canonical migration":"Initialize canonical contribution";confirm.disabled=Boolean(migration?.conflicts.length);confirm.addEventListener("click",()=>{options.persist(migration?confirmCanonicalMigration(state,migration):writeSidePanelCanonical(state,selection,createCanonicalSchema({id:`canonical-schema:${crypto.randomUUID()}`,contributorId:selection.entity.id,contributorName:selection.entity.name})));render();});review.append(summary,confirm);options.host.append(review);return;}
    const editorHost=document.createElement("section");options.host.append(editorHost);mountCanonicalSchemaEditor({host:editorHost,surface:"Side panel",load:()=>current().selection!.entity.canonicalSchema as CanonicalSchemaDocument,id:(kind)=>`${kind}:${crypto.randomUUID()}`,dispatch:(command)=>{const live=current(),document=live.selection!.entity.canonicalSchema as CanonicalSchemaDocument,result=applyCanonicalCommand(document,command);if((result.status==="applied"||result.status==="rebased")&&live.state)options.persist(writeSidePanelCanonical(live.state,live.selection!,result.document));return result;},onUndo:()=>{const live=current();if(live.state){options.persist(undoProjectTransaction(live.state));render();}},onRedo:()=>{const live=current();if(live.state){options.persist(redoProjectTransaction(live.state));render();}}});
    if(selection.collectionKind==="pages"||selection.collectionKind==="pageGroups")renderSidePanelComposedSchemaContext({host:options.host,load:options.load,key:selectedKey!,persist:options.persist,render});
  };
  const select=(key:string):boolean=>{const state=options.load();if(!state||!resolveSidePanelSchemaContributor(state,key))return false;selectedKey=key;render();return true;};
  close();window.addEventListener("storage",(event)=>{if(event.storageArea===localStorage&&event.key===CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY&&selectedKey)render();});return{render,select,close};
}
export const layeredEventRole=(entity:ProjectEntity):"context"|"interaction"=>entity.role==="context-setting"?"context":entity.role==="interaction"?"interaction":entity.contextBindingId||entity.occurrenceType==="page-context"?"context":"interaction";
export const effectivePropertySummary=(property:ReturnType<typeof compileLayeredSchema>["properties"][string]):string=>[property.type?`type ${property.type}`:undefined,property.allowedValues?`allowed ${JSON.stringify(property.allowedValues)}`:undefined,property.presence?`presence ${property.presence}`:undefined,property.expectedValue!==undefined?`expected ${JSON.stringify(property.expectedValue)}`:undefined,property.patterns?.length?`patterns ${JSON.stringify(property.patterns)}`:undefined,property.minimum!==undefined||property.maximum!==undefined?`range ${String(property.minimum??"−∞")}..${String(property.maximum??"∞")}`:undefined,property.minItems!==undefined||property.maxItems!==undefined?`cardinality ${String(property.minItems??0)}..${String(property.maxItems??"∞")}`:undefined,property.rules?.length?`rules ${property.rules.length}`:undefined,property.reusableRules?.length?`reusable ${property.reusableRules.length}`:undefined].filter(Boolean).join(" · ");

export function installLayeredSchemaUi(options:LayeredSchemaUiOptions):{render():void;openGraphOccurrenceSchema(occurrenceId:string,path?:string):boolean}{
  const inspector=q<HTMLElement>("#project-inspector"),workspace=q<HTMLElement>("#workspace-content"),editorHost=q<HTMLElement>("#layered-schema-editor-host"),summary=document.createElement("section"),editor=document.createElement("section");let graphSelection:ProjectEntity|undefined,graphSelectionScope:LayerScope|undefined,returnFocus:HTMLElement|undefined,flowReturn:{selector:string;scrollLeft:number;scrollTop:number;viewBox:string}|undefined;
  summary.setAttribute("aria-label","Schema constraints summary");editor.setAttribute("aria-label","Shared schema constraints editor");editor.hidden=true;inspector.insertBefore(summary,inspector.firstChild?.nextSibling??null);editorHost.append(editor);
  const current=()=>{const {state,kind,entityId}=options.context(),collectionEntity=state&&entityId?(state.project.collections[kind] as ProjectEntity[]).find(({id})=>id===entityId):undefined,entity=graphSelection??(kind==="flows"?undefined:collectionEntity);return{state,kind,entity,scope:graphSelectionScope??scopeFor(kind)};};
  const id=(kind:string)=>`${kind}:${crypto.randomUUID()}`;
  const writeCanonical=(state:ProjectState,entity:ProjectEntity,scope:LayerScope,canonical:CanonicalSchemaDocument):ProjectState=>transactProject(state,`Save canonical schema for ${entity.name}`,(project)=>{if(graphSelection&&(scope==="Event-occurrence"||scope==="Flow Page-instance")){const flowId=options.context().entityId!,graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences:ProjectEntity[];relationships:ProjectEntity[]}>,graph=graphs[flowId]!,ownsPageFrame=scope==="Flow Page-instance"&&Boolean(graph.pageFrames?.some(({id})=>id===entity.id));return{...project,documentationFlowGraphs:{...graphs,[flowId]:ownsPageFrame?{...graph,pageFrames:graph.pageFrames!.map((candidate)=>candidate.id===entity.id?{...candidate,canonicalSchema:canonical}:candidate)}:{...graph,occurrences:graph.occurrences.map((candidate)=>candidate.id===entity.id?{...candidate,canonicalSchema:canonical}:candidate)}}};}const collectionKind:ProjectEntityKind=scope==="Page"?"pages":scope==="Page Group"?"pageGroups":scope==="Event"?"events":scope==="Shared Profile"?"profiles":"flows";return{...project,collections:{...project.collections,[collectionKind]:(project.collections[collectionKind] as ProjectEntity[]).map((candidate)=>candidate.id===entity.id?{...candidate,canonicalSchema:canonical,...(collectionKind==="profiles"?{requirements:[]}:{})}:candidate)}} as typeof project;});
  const ensureCanonical=():void=>{const {state,entity,scope}=current();if(!state||!entity||entity.canonicalSchema)return;const legacy=Boolean(entity.requirements||entity.structuredSchema||entity.structuredDraft||entity.schemaConstraints),canonical=legacy?migrateLegacyProfile(entity,{id}).document:createCanonicalSchema({id:id("canonical-schema"),contributorId:entity.id,contributorName:entity.name});if(graphSelection)graphSelection={...graphSelection,canonicalSchema:canonical};options.persist(writeCanonical(state,entity,scope,canonical));};
  const renderCanonicalLayerEditor=(state:ProjectState,entity:ProjectEntity,scope:LayerScope):boolean=>{const canonical=entity.canonicalSchema as CanonicalSchemaDocument|undefined;if(!canonical)return false;const title=document.createElement("h2"),identity=document.createElement("p"),areas=document.createElement("nav"),host=document.createElement("section"),back=document.createElement("button"),compiled=compileLayeredSchema(layeredContributorsForPath(state,layeredContributorPath(state,entity,scope,options.context().kind==="flows"?options.context().entityId:undefined)),{eventId:String(entity.eventId??entity.id),eventRole:layeredEventRole(entity),occurrenceId:entity.id});title.tabIndex=-1;title.textContent="Shared canonical schema editor";identity.textContent=`Contributor: ${entity.name} · Scope: ${scope}`;areas.textContent=`Inherited constraints · Local contributions · Effective results · Blocking conflicts (${compiled.conflicts.length})`;back.type="button";back.textContent="Return to Flow";back.addEventListener("click",()=>{editor.hidden=true;editorHost.hidden=true;workspace.hidden=false;returnFocus?.focus({preventScroll:true});});editor.append(title,identity,areas,host,renderRuntimeControls(state,entity,scope,compiled),back);mountCanonicalSchemaEditor({host,surface:canonicalLayerEditorSurface(options.context().kind),load:()=>current().entity!.canonicalSchema as CanonicalSchemaDocument,id,dispatch:(command)=>{const live=current(),document=live.entity!.canonicalSchema as CanonicalSchemaDocument,result=applyCanonicalCommand(document,command);if((result.status==="applied"||result.status==="rebased")&&live.state){if(graphSelection)graphSelection={...graphSelection,canonicalSchema:result.document};options.persist(writeCanonical(live.state,live.entity!,live.scope,result.document));queueMicrotask(renderEditor);}return result;}});return true;};
  const contributorsFor=(state:ProjectState,entity:ProjectEntity,scope:LayerScope)=>layeredContributorsForPath(state,layeredContributorPath(state,entity,scope,options.context().kind==="flows"?options.context().entityId:undefined));
  type StoredTarget={id:string;name:string;contributorId:string;activation:LayerActivation;priority:number;applicability:LayerPredicate[];eventId:string;eventRole:"context"|"interaction";occurrenceId?:string;revision:number;flowName?:string;pageName?:string;eventName?:string;profileId?:string;pageGroupId?:string;pageId?:string;flowId?:string};
  const storedTargets=(state:ProjectState):StoredTarget[]=>(state.project.layeredSchemaTargets as StoredTarget[]|undefined)??[];
  const executableTargets=(state:ProjectState):LayerTarget[]=>storedTargets(state).map((target)=>({...target,compiled:compileLayeredSchema(layeredContributorsForPath(state,target),{eventId:target.eventId,eventRole:target.eventRole,...(target.occurrenceId?{occurrenceId:target.occurrenceId}:{})})}));
  function renderRuntimeControls(state:ProjectState,entity:ProjectEntity,scope:LayerScope,compiled:ReturnType<typeof compileLayeredSchema>):HTMLElement{
    const section=document.createElement("section"),heading=document.createElement("h3"),propertyTree=document.createElement("ol"),targetEvent=document.createElement("select"),targetRole=document.createElement("select"),activation=document.createElement("select"),priority=document.createElement("input"),applicability=document.createElement("textarea"),saveTarget=document.createElement("button"),observation=document.createElement("textarea"),test=document.createElement("button"),assignmentResult=document.createElement("pre"),manual=document.createElement("select"),payload=document.createElement("textarea"),validate=document.createElement("button"),validationResult=document.createElement("pre"),developerExport=document.createElement("button"),exportResult=document.createElement("pre"),existing=storedTargets(state).find(({contributorId})=>contributorId===entity.id),path=layeredContributorPath(state,entity,scope,options.context().kind==="flows"?options.context().entityId:undefined);
    const effectivePathButton=(propertyPath:string,text:string)=>{const choose=document.createElement("button");choose.type="button";choose.dataset.propertyId=propertyPath;choose.setAttribute("aria-current","false");choose.textContent=text;choose.addEventListener("click",()=>{propertyTree.querySelectorAll<HTMLElement>("[data-property-id]").forEach((candidate)=>candidate.setAttribute("aria-current",String(candidate===choose)));choose.focus();});return choose;};
    section.setAttribute("aria-label","Effective schema operations");heading.textContent="Compiled effective schema and activation";propertyTree.setAttribute("aria-label","Compiled layered property tree");for(const[propertyPath,property]of Object.entries(compiled.properties)){const item=document.createElement("li"),effective=effectivePropertySummary(property);item.append(effectivePathButton(propertyPath,`${propertyPath}${effective?` · ${effective}`:""} · ${property.origins.map(({scope:originScope,contributorName})=>`${originScope}: ${contributorName}`).join(" → ")}${property.superseded.length?` · superseded ${property.superseded.map(({contributorName,value})=>`${contributorName} ${String(value)}`).join(", ")}`:""}`));propertyTree.append(item);}for(const conflict of compiled.conflicts){const item=document.createElement("li"),left=document.createElement("button"),right=document.createElement("button");item.className="error";left.type=right.type="button";left.textContent=conflict.contributors[0]??"Earlier contributor";right.textContent=conflict.contributors[1]??entity.name;item.append(effectivePathButton(conflict.path,`${conflict.path}: ${conflict.message}`)," · ",left," ↔ ",right);propertyTree.append(item);}
    targetEvent.setAttribute("aria-label","Layered target Event");targetEvent.append(new Option("Choose Event",""),...state.project.collections.events.map((event)=>new Option(event.name,event.id)));targetEvent.value=existing?.eventId??path.eventId??"";targetEvent.required=true;targetRole.setAttribute("aria-label","Layered target Event role");targetRole.append(new Option("Context Event","context"),new Option("Interaction Event","interaction"));targetRole.value=existing?.eventRole??layeredEventRole(entity);for(const value of["automatic","manual","documentation-only"] as const)activation.append(new Option(value==="documentation-only"?"Documentation only":value,value));activation.setAttribute("aria-label","Layered target activation");activation.value=existing?.activation??"manual";priority.type="number";priority.value=String(existing?.priority??10);priority.setAttribute("aria-label","Layered target priority");applicability.setAttribute("aria-label","Layered applicability predicates");applicability.value=JSON.stringify(existing?.applicability??[],null,2);saveTarget.type="button";saveTarget.textContent="Save activation target";
    saveTarget.addEventListener("click",()=>{const liveState=current().state??state,liveEntity=current().entity??entity,liveExisting=storedTargets(liveState).find(({contributorId})=>contributorId===liveEntity.id),predicates=JSON.parse(applicability.value||"[]") as LayerPredicate[],eventName=predicates.find(({field,operator})=>field==="eventName"&&operator==="equals")?.value,selectedEvent=liveState.project.collections.events.find(({id,name})=>id===targetEvent.value||!targetEvent.value&&eventName===name);if(!selectedEvent)throw new Error("Choose the Event for this layered target.");const flow=liveState.project.collections.flows.find(({id})=>id===path.flowId),page=liveState.project.collections.pages.find(({id})=>id===path.pageId),context={eventId:selectedEvent.id,eventRole:targetRole.value as "context"|"interaction",...(scope==="Event-occurrence"?{occurrenceId:liveEntity.id}:{})},target:StoredTarget={id:liveExisting?.id??`layered-target:${liveEntity.id}`,name:liveEntity.name,contributorId:liveEntity.id,activation:activation.value as LayerActivation,priority:Number(priority.value),applicability:predicates,...path,...context,revision:(liveExisting?.revision??0)+1,flowName:flow?.name??liveEntity.name,pageName:page?.name??String(liveEntity.pageName??liveEntity.pageId??"Page"),eventName:selectedEvent.name},next=transactProject(liveState,`Save layered activation for ${liveEntity.name}`,(project)=>({...project,layeredSchemaTargets:[...((project.layeredSchemaTargets as StoredTarget[]|undefined)??[]).filter(({contributorId})=>contributorId!==liveEntity.id),target]}));options.persist(next);renderEditor();});
    observation.setAttribute("aria-label","Applicability test observation");observation.value='{"pathname":"/checkout/shipping","page_name":"shipping","checkout_variant":"alternative","eventName":"Purchase"}';test.type="button";test.textContent="Test automatic applicability";assignmentResult.setAttribute("aria-label","Layered assignment evidence");test.addEventListener("click",()=>{const result=resolveLayeredTarget(executableTargets(current().state!),JSON.parse(observation.value));assignmentResult.textContent=JSON.stringify({selectionMode:result.selectionMode,winner:result.winner?.name,ties:result.ties,candidates:result.candidates},null,2);});
    manual.setAttribute("aria-label","Manual layered target");manual.append(new Option("Choose Flow / Page / Event target",""),...storedTargets(state).filter(({activation:mode})=>mode==="manual").map((target)=>new Option(`${target.flowName} / ${target.pageName} / ${target.eventName}`,target.id)));payload.setAttribute("aria-label","Layered validation payload");payload.value='{"funnel_step":"3a","funnel_name":"checkout"}';validate.type="button";validate.textContent="Validate selected layered target";validationResult.setAttribute("aria-label","Layered validation result");validate.addEventListener("click",()=>{const targets=executableTargets(current().state!),manualResolution=manual.value?resolveLayeredTarget(targets,{}, {manualTargetId:manual.value}):undefined,automaticResolution=manual.value?undefined:resolveLayeredTarget(targets,JSON.parse(observation.value)),winner=manualResolution?.winner??automaticResolution?.winner;if(!winner){validationResult.textContent=JSON.stringify({blocked:true,ties:automaticResolution?.ties??[],automaticWinnerClaim:false});return;}const stored=storedTargets(current().state!).find(({id})=>id===winner.id)!;validationResult.textContent=JSON.stringify({...validateLayeredObservation({targetId:winner.id,targetName:winner.name,revision:stored.revision,compiled:winner.compiled},JSON.parse(payload.value)),selectionMode:manualResolution?"manual":"automatic",automaticWinnerClaim:Boolean(automaticResolution?.winner)},null,2);});
    developerExport.type="button";developerExport.textContent="Generate effective schema developer export";exportResult.setAttribute("aria-label","Effective schema developer export");developerExport.addEventListener("click",()=>{const target=storedTargets(current().state!).find(({contributorId})=>contributorId===entity.id);exportResult.textContent=exportLayeredSchema({targetName:target?.flowName??entity.name,pageName:target?.pageName??String(entity.pageId??"Page"),eventName:target?.eventName??String(entity.eventId??"Event"),activation:target?.activation??"manual",compiled});});
    const labeled=(text:string,control:HTMLElement)=>{const label=document.createElement("label");label.append(text,control);return label;};section.append(heading,propertyTree,labeled("Target Event",targetEvent),labeled("Event role",targetRole),labeled("Activation",activation),labeled("Priority",priority),labeled("Applicability",applicability),saveTarget,labeled("Test observation",observation),test,assignmentResult,labeled("Manual Flow / Page / Event",manual),labeled("Validation payload",payload),validate,validationResult,developerExport,exportResult);return section;
  }
  function renderSummary():void{const context=options.context(),{state,entity,scope}=current();summary.replaceChildren();summary.dataset.contextKind=context.kind;summary.dataset.contextEntityId=context.entityId??"";if(!state||!entity){summary.hidden=true;delete summary.dataset.eventRole;return;}summary.hidden=false;const title=document.createElement("h3"),counts=document.createElement("p"),open=document.createElement("button"),eventRole=layeredEventRole(entity),compiled=compileLayeredSchema(contributorsFor(state,entity,scope),{eventId:String(entity.eventId??entity.id),eventRole,...(entity.id?{occurrenceId:entity.id}:{})}),local=((entity.schemaConstraints as LayerConstraint[]|undefined)??[]).length+((entity.localSchemaContributions as LayerConstraint[]|undefined)??[]).length,activation=String(entity.activation??"manual"),directWorkspace=scope==="Page"||scope==="Page Group";summary.dataset.eventRole=eventRole;title.textContent=`Schema constraints · ${entity.name} · ${scope}`;counts.textContent=`Inherited ${Math.max(0,compiled.provenance.length-1)} · Local ${local} · Effective ${Object.keys(compiled.properties).length} · Conflict ${compiled.conflicts.length} · ${eventRole==="context"?"Context Event":"Interaction Event"} · Activation ${activation}`;open.type="button";open.textContent="Open complete schema editor";open.addEventListener("click",()=>{returnFocus=open;if(directWorkspace){const target=document.querySelector<HTMLElement>(`[aria-label="${CSS.escape(`Effective schema at ${entity.name}`)}"]`);target?.scrollIntoView({block:"start"});target?.querySelector<HTMLElement>('[aria-label$="canonical schema editor"] [data-property-id], button')?.focus();return;}editor.hidden=false;ensureCanonical();renderEditor();editorHost.hidden=false;workspace.hidden=true;editor.querySelector<HTMLElement>("h2")?.focus();});summary.append(title,counts,open);}
  function renderEditor():void{const {state,entity,scope}=current();editor.replaceChildren();if(!state||!entity)return;if(!renderCanonicalLayerEditor(state,entity,scope)){const unavailable=document.createElement("p");unavailable.textContent="Initialize the canonical contribution before editing.";editor.append(unavailable);}}
  editor.addEventListener("submit",()=>queueMicrotask(()=>{const output=editor.querySelector<HTMLElement>('[role="status"]'),scope=current().scope;if(output)output.textContent=`Affected scope: ${scope} · compiled targets stale · Draft · Undo available`;}));
  const graphContributorSelector='[data-occurrence-id],[data-page-frame-id],[aria-label="Interactive directional Flow canvas"] [data-page-group-id]';
  const selectGraphContributor=(target:HTMLElement)=>{const {state,kind,entityId:flowId}=options.context();if(!state||kind!=="flows"||!flowId)return;const graphs=state.project.documentationFlowGraphs as Record<string,{occurrences?:ProjectEntity[]}>,occurrenceId=target.dataset.occurrenceId,pageFrameId=!occurrenceId?target.dataset.pageFrameId:undefined,pageGroupId=!occurrenceId&&!pageFrameId?target.dataset.pageGroupId:undefined,pane=q<HTMLElement>("#workspace-pane"),graph=document.querySelector<SVGSVGElement>('[aria-label="Interactive directional Flow canvas"]');if(occurrenceId){graphSelection=graphs[flowId]?.occurrences?.find(({id})=>id===occurrenceId);graphSelectionScope=graphSelection?.freePageFrame?"Flow Page-instance":"Event-occurrence";}else if(pageFrameId){graphSelection=flowPageFrameContributor(state,flowId,pageFrameId);graphSelectionScope="Flow Page-instance";}else if(pageGroupId&&pageGroupId!=="ungrouped"){graphSelection=state.project.collections.pageGroups.find(({id})=>id===pageGroupId);graphSelectionScope="Page Group";}else return;if(!graphSelection)return;const stableSelectorId=occurrenceId??pageFrameId??pageGroupId!,id=CSS.escape(stableSelectorId),selector=occurrenceId?`[data-occurrence-id="${id}"]`:pageFrameId?`[data-page-frame-id="${id}"]`:`[aria-label="Interactive directional Flow canvas"] [data-page-group-id="${id}"]`;flowReturn={selector,scrollLeft:pane.scrollLeft,scrollTop:pane.scrollTop,viewBox:graph?.getAttribute("viewBox")??""};renderSummary();};
  document.addEventListener("click",(event)=>{const target=(event.target as Element).closest<HTMLElement>(graphContributorSelector);if(target)selectGraphContributor(target);});
  document.addEventListener("keydown",(event)=>{if(event.key!=="Enter"&&event.key!==" ")return;const target=(event.target as Element).closest<HTMLElement>(graphContributorSelector);if(target)selectGraphContributor(target);});
  const openGraphOccurrenceSchema=(occurrenceId:string,path?:string):boolean=>{const {state,kind,entityId:flowId}=options.context(),graphs=state?.project.documentationFlowGraphs as Record<string,{occurrences?:ProjectEntity[]}>|undefined,occurrence=flowId?graphs?.[flowId]?.occurrences?.find(({id})=>id===occurrenceId):undefined;if(!state||kind!=="flows"||!flowId||!occurrence)return false;graphSelection=occurrence;graphSelectionScope=occurrence.freePageFrame?"Flow Page-instance":"Event-occurrence";returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:undefined;editor.hidden=false;ensureCanonical();renderEditor();editorHost.hidden=false;workspace.hidden=true;editor.querySelector<HTMLElement>("h2")?.focus();if(path)setTimeout(()=>Array.from(editor.querySelectorAll<HTMLElement>("[data-property-id]")).find((candidate)=>candidate.dataset.propertyId===path||candidate.textContent?.includes(path))?.click(),0);return true;};
  return{render(){if(editor.hidden){graphSelection=undefined;graphSelectionScope=undefined;}renderSummary();},openGraphOccurrenceSchema};
}
