import {canonicalPropertyPath,canonicalSchemaFromJsonSchema,type CanonicalPredicate,type CanonicalPredicateOperator,type CanonicalPropertyNode,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {JsonSchema} from "./data-layer-schema-document.js";
import type {SchemaDocumentation} from "./data-layer-schema-documentation.js";

interface SavedSchemaRule {id:string;name?:string;version:number;enabled?:boolean;propertyPath?:string;operator?:string;parameters?:string;allowedValues?:readonly (string|number|boolean|null)[];severity?:string;message?:string;conditionGroup?:{operator:string;predicates:readonly {propertyPath:string;operator:string;comparison?:{value?:unknown;type?:string}}[]};}
interface SavedSchemaCanonicalSource {id:string;name:string;version:number;document:JsonSchema;attachedRules?:readonly SavedSchemaRule[];rules?:readonly SavedSchemaRule[];documentation?:SchemaDocumentation;canonicalSchema?:CanonicalSchemaDocument;}

const pointer=(path:string)=>`/${path.split(/[./]/).filter(Boolean).join("/")}`;
const clone=<T>(value:T):T=>structuredClone(value);
const jsonFacetRule=(schemaId:string,nodeId:string,kind:string)=>`json-facet:${schemaId}:${nodeId}:${kind}`;
const canonicalOperator=(operator:string):CanonicalPredicateOperator=>({"Equal":"Equals","Is greater than":"Greater than","Is at least":"At least","Is less than":"Less than","Is at most":"At most"} as const)[operator as "Equal"|"Is greater than"|"Is at least"|"Is less than"|"Is at most"]??operator as CanonicalPredicateOperator;
function canonicalRuleCondition(document:CanonicalSchemaDocument,group:SavedSchemaRule["conditionGroup"]):{complete:boolean;condition?:CanonicalPredicate}{
  if(!group)return{complete:true};
  const byPath=new Map(Object.values(document.nodes).map((node)=>[canonicalPropertyPath(document,node.id),node.id])),kind=group.operator==="All"?"all":group.operator==="Any"?"any":group.operator==="Not"?"not":undefined,children=group.predicates.map((predicate):CanonicalPredicate|undefined=>{const propertyId=byPath.get(pointer(predicate.propertyPath));if(!propertyId)return undefined;const value=predicate.comparison?.value;return{kind:"predicate",propertyId,operator:canonicalOperator(predicate.operator),...(value!==undefined?{value}:predicate.comparison?.type==="null"?{value:null}:{})};});
  if(!kind||!children.length||children.some((child)=>child===undefined)||(kind==="not"&&children.length!==1))return{complete:false};
  return{complete:true,condition:{kind,children:children as CanonicalPredicate[]}};
}

export function savedSchemaCanonicalDocument(schema:SavedSchemaCanonicalSource,id:(kind:string)=>string,target?:{id:string;contributorId:string;contributorName:string}):CanonicalSchemaDocument{
  if(schema.canonicalSchema)return clone(schema.canonicalSchema);
  const canonical=canonicalSchemaFromJsonSchema({id:target?.id??`canonical:saved:${schema.id}`,contributorId:target?.contributorId??schema.id,contributorName:target?.contributorName??schema.name,sourceIdentity:schema.id,sourceRevision:schema.version,document:schema.document as Record<string,unknown>,idFactory:id}),byPath=new Map(Object.values(canonical.nodes).map((node)=>[canonicalPropertyPath(canonical,node.id),node]));
  const definitionsByNodeId:Record<string,Record<string,unknown>>={},sourceRules=schema.attachedRules??schema.rules??[];
  const visit=(definition:JsonSchema,path:string):void=>{for(const[name,child]of Object.entries(definition.properties??{})){const childPath=`${path}/${name}`,node=byPath.get(childPath),documentation=schema.documentation?.properties?.[childPath],rich=child as JsonSchema&Record<string,unknown>;if(node){definitionsByNodeId[node.id]=clone(rich);if(definition.required?.includes(name))node.presence={mode:"required"};else if(definition.forbidden?.includes(name))node.presence={mode:"forbidden"};if(node.type==="array"&&rich.items&&typeof rich.items==="object"&&typeof rich.items.type==="string")node.itemType=rich.items.type as CanonicalPropertyNode["type"];node.allowedValues=node.allowedValues.map((entry,index)=>({...entry,id:`allowed-value:${node.id}:${index}`}));if(documentation)node.documentation={displayText:documentation.displayName,description:documentation.description||node.documentation.description,comments:documentation.comments??"",example:documentation.example?{method:documentation.example.selectionMethod==="allowed value"?"allowed-value":"custom",value:clone(documentation.example.value)}:node.documentation.example};const minimum=typeof rich.minimum==="number"?rich.minimum:undefined,maximum=typeof rich.maximum==="number"?rich.maximum:undefined,minItems=typeof rich.minItems==="number"?rich.minItems:undefined,maxItems=typeof rich.maxItems==="number"?rich.maxItems:undefined;if(typeof rich.pattern==="string")node.rules.push({id:jsonFacetRule(schema.id,node.id,"pattern"),kind:"pattern",pattern:rich.pattern,severity:"error",message:"Pattern mismatch"});if(minimum!==undefined||maximum!==undefined)node.rules.push({id:jsonFacetRule(schema.id,node.id,"range"),kind:"range",...(minimum!==undefined?{minimum}:{}),...(maximum!==undefined?{maximum}:{}),severity:"error",message:"Outside range"});if(minItems!==undefined||maxItems!==undefined)node.rules.push({id:jsonFacetRule(schema.id,node.id,"cardinality"),kind:"cardinality",...(minItems!==undefined?{minItems}:{}),...(maxItems!==undefined?{maxItems}:{}),severity:"error",message:"Outside cardinality"});}visit(child,childPath);}};visit(schema.document,"");
  const typedRuleValue=(node:CanonicalPropertyNode,value:unknown):unknown=>{if(typeof value!=="string")return clone(value);if(node.type==="number"||node.type==="integer"){const parsed=Number(value);return Number.isFinite(parsed)?parsed:value;}if(node.type==="boolean"&&["true","false"].includes(value.toLowerCase()))return value.toLowerCase()==="true";if(node.type==="null"&&value==="null")return null;return value;};
  for(const rule of sourceRules){
    const node=byPath.get(pointer(rule.propertyPath??""));if(!node)continue;
    const operator=rule.operator?.replaceAll("_","-").replaceAll(" ","-").toLowerCase(),bounds=rule.parameters?.split(",")??[],number=(value:string|undefined)=>value!==undefined&&value!==""&&Number.isFinite(Number(value))?Number(value):undefined,minimum=number(bounds[0]),maximum=number(bounds[1]),kind=operator==="pattern"||operator==="regular-expression"?"pattern":operator==="range"||operator==="numeric-range"?"range":operator==="cardinality"||operator==="item-count"?"cardinality":"custom",conditionMapping=canonicalRuleCondition(canonical,rule.conditionGroup),mappedFacet=operator==="exact-value"||operator==="allowed-values"||operator==="required",sourceMetadata=mappedFacet?{name:rule.name??rule.id,revision:rule.version,operator,provenance:{source:"saved-schema" as const,sourceId:schema.id,revision:schema.version}}:{};
    node.rules.push({id:rule.id,kind,...(kind==="pattern"&&rule.parameters?{pattern:rule.parameters}:{}),...(kind==="range"&&minimum!==undefined?{minimum}:{}),...(kind==="range"&&maximum!==undefined?{maximum}:{}),...(kind==="cardinality"&&minimum!==undefined?{minItems:minimum}:{}),...(kind==="cardinality"&&maximum!==undefined?{maxItems:maximum}:{}),...(conditionMapping.condition?{condition:conditionMapping.condition}:{}),severity:rule.severity==="warning"?"warning":"error",...(rule.message!==undefined?{message:rule.message}:{}),...(typeof rule.enabled==="boolean"?{enabled:rule.enabled}:{}),...sourceMetadata,...(rule.id.startsWith("rule:")&&!mappedFacet?{reusableRuleId:rule.id}:{})});
    if(rule.enabled===false)continue;
    if(operator==="required"){if(conditionMapping.complete)node.presence=conditionMapping.condition?{mode:"required-when",condition:conditionMapping.condition}:{mode:"required"};continue;}
    if(rule.conditionGroup)continue;
    if(operator==="exact-value"&&rule.parameters!==undefined)node.expectedValue=typedRuleValue(node,rule.parameters);
    if(operator==="allowed-values"){const values=rule.allowedValues??bounds.map((value)=>value.trim()).filter(Boolean);node.allowedValues=values.map((value,index)=>({id:`allowed-value:${node.id}:rule:${rule.id}:${index}`,value:typedRuleValue(node,value)}));}
  }
  canonical.sourceContent={document:clone(schema.document as Record<string,unknown>),rules:clone(sourceRules as unknown as readonly Record<string,unknown>[]),documentation:clone(schema.documentation??{}),examples:[],definitionsByNodeId};return canonical;
}
