import {createCanonicalProjectEnvelope,type CanonicalProjectEnvelope} from "./data-layer-specification-engine.js";
import type {ProjectState} from "./data-layer-specification-project.js";

export const CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY="my-chrome-utilities.specification-project.v1";
export interface PersistedCanonicalProject extends CanonicalProjectEnvelope{draft:ProjectState["draft"];history:ProjectState["history"]}
export interface ProjectStorage{getItem(key:string):string|null;setItem(key:string,value:string):void}

const clone=<T>(value:T):T=>structuredClone(value);
function entityRevisions(state:ProjectState,previous?:PersistedCanonicalProject):Record<string,number>{const prior=previous?.entityRevisions??{};return Object.fromEntries((Object.values(state.project.collections) as {id:string}[][]).flat().map(({id})=>[id,prior[id]??1]));}
function envelopeFor(state:ProjectState,revision:number,previous?:PersistedCanonicalProject):PersistedCanonicalProject{const base=createCanonicalProjectEnvelope(state.project,state.draft?.id??`release:${state.project.currentRelease??"unpublished"}`);return{...base,revision,entityRevisions:entityRevisions(state,previous),draft:clone(state.draft),history:clone(state.history)};}
export function restoreCanonicalProjectEnvelope(serialized:string|null):PersistedCanonicalProject|undefined{if(!serialized)return undefined;const parsed=JSON.parse(serialized) as PersistedCanonicalProject|ProjectState;if("format"in parsed&&parsed.format==="my-chrome-utilities.canonical-specification-project")return clone(parsed);if("project"in parsed)return envelopeFor(parsed as ProjectState,0);throw new Error("Unsupported Specification Project storage format.");}
export function restoreCanonicalProjectState(serialized:string|null):ProjectState|undefined{const envelope=restoreCanonicalProjectEnvelope(serialized);return envelope?{project:clone(envelope.project),...(envelope.draft?{draft:clone(envelope.draft)}:{}),history:clone(envelope.history??{undo:[],redo:[]})}:undefined;}
export type CanonicalCommitResult={status:"committed";key:string;revision:number;envelope:PersistedCanonicalProject}|{status:"conflict";key:string;revision:number;current:ProjectState;pending:ProjectState;pendingLabel:string};
export function commitCanonicalProjectState(storage:ProjectStorage,next:ProjectState,options?:{expectedRevision?:number;pendingLabel?:string}):CanonicalCommitResult{const key=CANONICAL_SPECIFICATION_PROJECT_STORAGE_KEY,previous=restoreCanonicalProjectEnvelope(storage.getItem(key)),revision=previous?.revision??0;if(options?.expectedRevision!==undefined&&options.expectedRevision!==revision){const current=restoreCanonicalProjectState(storage.getItem(key));if(!current)throw new Error("The canonical project disappeared while resolving a stale command.");return{status:"conflict",key,revision,current,pending:clone(next),pendingLabel:options.pendingLabel??"Unsaved edit"};}const envelope=envelopeFor(next,revision+1,previous);storage.setItem(key,JSON.stringify(envelope));return{status:"committed",key,revision:envelope.revision,envelope};}
