import {canonicalConceptIndex,canonicalConstraints,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import {compileLayeredSchema,type CompiledLayeredSchema,type LayerConstraint,type LayerContributor,type LayerContext,type LayerScope} from "./data-layer-layered-schema.js";
import {orderedPageGroupIds} from "./data-layer-page-group-membership.js";
import {transactProject,type Condition,type ProjectEntity,type ProjectState} from "./data-layer-specification-project.js";
import {selectiveProfileContribution,type ProfileInheritanceRecipe} from "./data-layer-selective-profile-inheritance.js";
import {applyLayerConstraintStructures,structureDeletesPath,type FlowPageInstanceStructureCommand} from "./flow-graph/page-instance-structure.js";

export interface LayeredContributorPath {profileId?:string;profileIds?:string[];eventId?:string;pageGroupId?:string;pageGroupIds?:string[];pageId?:string;flowId?:string;pageFrameId?:string;occurrenceId?:string;}
export type AssignmentContributorKind="Shared Profile"|"Property Set"|"Page Group"|"Page"|"Event"|"Flow Page instance";
export interface AssignmentContributorTarget {id:string;name:string;kind:AssignmentContributorKind;flowId?:string;}
export function projectCanonicalConcepts(state:ProjectState):string[]{
  const entities=[...(Object.values(state.project.collections) as ProjectEntity[][]).flat(),...Object.values(state.project.documentationFlowGraphs??{}).flatMap((graph)=>[...((graph as {pageFrames?:ProjectEntity[]}).pageFrames??[]),...((graph as {occurrences?:ProjectEntity[]}).occurrences??[])])],documents=entities.flatMap(({canonicalSchema})=>canonicalSchema?[canonicalSchema as CanonicalSchemaDocument]:[]),constraintConcepts=entities.flatMap((entity)=>[...((entity.schemaConstraints as LayerConstraint[]|undefined)??[]),...((entity.localSchemaContributions as LayerConstraint[]|undefined)??[])].map(({concept})=>concept).filter((value):value is string=>typeof value==="string"));
  return canonicalConceptIndex([...documents,...(constraintConcepts.length?[{nodes:Object.fromEntries(constraintConcepts.map((concept,index)=>[String(index),{concept}]))} as unknown as CanonicalSchemaDocument]:[])]);
}

const contributionFor=(entity:ProjectEntity,scope:LayerScope):LayerContributor=>{
  const canonical=entity.canonicalSchema as CanonicalSchemaDocument|undefined;
  const requirements=((entity.requirements as Record<string,unknown>[]|undefined)??[]).map((requirement)=>({...requirement,...(requirement.required?{presence:"required"}:requirement.forbidden?{presence:"forbidden"}:{})})) as LayerConstraint[];
  const base=canonical?canonicalConstraints(canonical):((entity.schemaConstraints as LayerConstraint[]|undefined)??requirements),sparse=(entity.localSchemaContributions as LayerConstraint[]|undefined)??[];
  return{id:entity.id,name:entity.name,scope,revision:Number(entity.revision??entity.version??1),constraints:[...base,...sparse],...(scope==="Shared Profile"?{peerGroup:"shared-profiles"}:{}),...(canonical?.onlyDefinedFields!==undefined?{onlyDefinedFields:canonical.onlyDefinedFields}:typeof entity.onlyDefinedFields==="boolean"?{onlyDefinedFields:entity.onlyDefinedFields}:{})};
};
const referencedId=(entity:Record<string,unknown>,key:string):string|undefined=>typeof entity[key]==="string"?String(entity[key]):undefined;
const propertySets=(state:ProjectState):ProjectEntity[]=>((state.project.collections as typeof state.project.collections&{propertySets?:ProjectEntity[]}).propertySets??state.project.collections.pageGroups);
const orderedPropertySetIds=(state:ProjectState,pageId:string|undefined):string[]=>{
  if(!pageId)return[];const page=state.project.collections.pages.find(({id})=>id===pageId),applications=page?.propertySetApplications;
  return Array.isArray(applications)?applications.map((application)=>String((application as ProjectEntity).propertySetId)):orderedPageGroupIds(state.project,pageId);
};
const referencedProfileIds=(entity:ProjectEntity|undefined):string[]=>entity?[...new Set([...(referencedId(entity,"profileId")?[referencedId(entity,"profileId")!]:[]),...((entity.profileIds as string[]|undefined)??[]).filter((value):value is string=>typeof value==="string"&&Boolean(value))])]:[];
const profileInheritanceRecipes=(entity:ProjectEntity|undefined,profileId:string):ProfileInheritanceRecipe[]=>((entity?.profileInheritanceRecipes as ProfileInheritanceRecipe[]|undefined)??[]).filter((recipe)=>recipe.profileId===profileId);
const referencedProfileId=(state:ProjectState,entity:ProjectEntity):string|undefined=>{
  const direct=referencedId(entity,"profileId")??((entity.profileIds as string[]|undefined)?.length===1?String((entity.profileIds as string[])[0]):undefined);
  if(direct)return direct;
  const page=state.project.collections.pages.find(({id})=>id===referencedId(entity,"pageId")),pageDirect=page&&referencedId(page,"profileId"),pageProfiles=(page?.profileIds as string[]|undefined)??[];
  return pageDirect??(pageProfiles.length===1?pageProfiles[0]:state.project.collections.profiles.length===1?state.project.collections.profiles[0]!.id:undefined);
};
const same=(left:unknown,right:unknown):boolean=>JSON.stringify(left)===JSON.stringify(right);
function conditionMatches(condition:Condition|undefined,observation:Record<string,unknown>):boolean{if(!condition)return true;if(condition.kind==="predicate"){const actual=observation[condition.field];if(condition.operator==="equals")return same(actual,condition.value);if(condition.operator==="does not equal")return!same(actual,condition.value);if(condition.operator==="exists")return actual!==undefined;if(condition.operator==="does not exist")return actual===undefined;if(condition.operator==="contains")return String(actual??"").includes(String(condition.value??""));if(condition.operator==="matches pattern"||condition.operator==="regex")try{return new RegExp(String(condition.pattern??condition.value??"")).test(String(actual??""));}catch{return false;}return false;}if(condition.kind==="all")return condition.conditions.every((child)=>conditionMatches(child,observation));if(condition.kind==="any")return condition.conditions.some((child)=>conditionMatches(child,observation));return!condition.conditions.some((child)=>conditionMatches(child,observation));}

export function flowPageFrameContributor(state:ProjectState,flowId:string,pageFrameId:string):ProjectEntity|undefined{
  const graph=(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>|undefined)?.[flowId],frame=graph?.pageFrames?.find(({id})=>id===pageFrameId);if(!frame)return;
  const page=state.project.collections.pages.find(({id})=>id===frame.pageId),flow=state.project.collections.flows.find(({id})=>id===flowId);
  return{...frame,name:typeof frame.name==="string"&&frame.name.trim()?frame.name:`${page?.name??"Page"} in ${flow?.name??"Flow"}`};
}

export function layeredContributorPath(state:ProjectState,entity:ProjectEntity,scope:LayerScope,flowId?:string):LayeredContributorPath{
  const selectedFlowId=flowId??referencedId(entity,"flowId"),flowGraph=selectedFlowId?(state.project.documentationFlowGraphs as Record<string,{pageGroupIds?:string[];pageFrames?:ProjectEntity[]}>|undefined)?.[selectedFlowId]:undefined,flowPageGroupIds=flowGraph?.pageGroupIds??[],referencedFrameId=referencedId(entity,"pageFrameId")??(scope==="Flow Page-instance"?entity.id:undefined),referencedFrame=flowGraph?.pageFrames?.find(({id})=>id===referencedFrameId),flowPageGroupId=referencedId(referencedFrame??entity,"pageGroupId")??(flowPageGroupIds.length===1?flowPageGroupIds[0]:undefined),flowPageGroup=propertySets(state).find(({id})=>id===flowPageGroupId),flowPageIds=(flowPageGroup?.pageIds as string[]|undefined)??[],flowPageId=referencedId(referencedFrame??entity,"pageId")??(flowPageIds.length===1?flowPageIds[0]:undefined),pageId=referencedId(entity,"pageId")??referencedId(referencedFrame??{},"pageId")??(scope==="Page"?entity.id:scope==="Flow Page-instance"?flowPageId:undefined),selectedPage=pageId?state.project.collections.pages.find(({id})=>id===pageId):undefined,profileId=scope==="Shared Profile"?entity.id:referencedProfileId(state,entity)??(selectedPage?referencedProfileId(state,selectedPage):undefined),profileIds=[...new Set([...(scope==="Shared Profile"?[entity.id]:referencedProfileIds(entity)),...referencedProfileIds(selectedPage)])],pageGroupIds=pageId?orderedPropertySetIds(state,pageId):scope==="Page Group"?[entity.id]:[],pageGroupId=referencedId(referencedFrame??{},"pageGroupId")??referencedId(entity,"pageGroupId")??(scope==="Page Group"?entity.id:pageGroupIds.length===1?pageGroupIds[0]:scope==="Flow Page-instance"?flowPageGroupId:undefined),contextBinding=((selectedPage?.contextEventBindings as ProjectEntity[]|undefined)??[]).find(({id})=>id===entity.contextBindingId),eventId=referencedId(entity,"eventId")??referencedId(contextBinding??{id:"",name:""},"eventId")??(scope==="Event"?entity.id:undefined);
  return{...(profileId?{profileId}:{}),...(profileIds.length&&(profileIds.length!==1||profileIds[0]!==profileId)?{profileIds}:{}),...(eventId?{eventId}:{}),...(pageGroupId?{pageGroupId}:{}),...(pageGroupIds.length?{pageGroupIds}:{}),...(pageId?{pageId}:{}),...(selectedFlowId?{flowId:selectedFlowId}:{}),...(referencedFrame?{pageFrameId:referencedFrame.id}:{}),...(scope==="Event-occurrence"?{occurrenceId:entity.id}:{})};
}

export function layeredContributorsForPath(state:ProjectState,path:LayeredContributorPath,observation?:Record<string,unknown>):LayerContributor[]{
  const graph=path.flowId?(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences?:ProjectEntity[]}>|undefined)?.[path.flowId]:undefined,pageFrame=graph?.pageFrames?.find(({id})=>id===path.pageFrameId),occurrence=graph?.occurrences?.find(({id})=>id===path.occurrenceId),page=state.project.collections.pages.find(({id})=>id===path.pageId),flowFrame=path.flowId&&path.pageFrameId?flowPageFrameContributor(state,path.flowId,path.pageFrameId):undefined;
  const one=(entities:ProjectEntity[],id:string|undefined,scope:LayerScope)=>id?entities.filter((entity)=>entity.id===id).map((entity)=>contributionFor(entity,scope)):[];
  const pageApplications=(page?.propertySetApplications as ProjectEntity[]|undefined)??[],groupIds=path.pageGroupIds??(path.pageGroupId?[path.pageGroupId]:[]),groupRecords=groupIds.flatMap((groupId)=>propertySets(state).filter(({id})=>id===groupId).map((group)=>{const contributor=contributionFor(group,"Page Group"),application=pageApplications.find(({propertySetId})=>propertySetId===groupId),applicabilityId=application?.applicabilitySetId??group.applicabilitySetId,applicability=(state.project.collections.applicabilitySets??[]).find(({id})=>id===applicabilityId),conditional=Boolean(applicability),evaluated=observation!==undefined,active=!evaluated||conditionMatches(applicability?.condition as Condition|undefined,observation);return{group,active,contributor:{...contributor,...(conditional?{applicabilityConditional:true,applicabilitySetId:applicability!.id,applicabilitySetName:applicability!.name,applicabilityCondition:structuredClone(applicability!.condition as Record<string,unknown>),...(evaluated?{active,...(!active?{exclusionReason:`${applicability!.name} did not match`}:{})}:{})}:{})} as LayerContributor};}));
  const directProfileIds=[...new Set([...(path.profileIds??[]),...(path.profileId?[path.profileId]:[])])],routes=new Map<string,string[]>(),downstreamNames=[...(page?[page.name]:[]),...(flowFrame?[flowFrame.name]:[])],addRoute=(profileId:string,names:string[])=>{const profile=state.project.collections.profiles.find(({id})=>id===profileId);if(!profile)return;const route=[profile.name,...names.filter((name)=>name!==profile.name)].join(" → "),known=routes.get(profileId)??[];if(!known.includes(route))routes.set(profileId,[...known,route]);};
  const directTargetNames=downstreamNames.length?downstreamNames:path.pageGroupId?[propertySets(state).find(({id})=>id===path.pageGroupId)?.name??path.pageGroupId]:path.eventId?[state.project.collections.events.find(({id})=>id===path.eventId)?.name??path.eventId]:[];
  for(const profileId of directProfileIds)addRoute(profileId,directTargetNames);
  for(const {group,active} of groupRecords)if(active)for(const profileId of referencedProfileIds(group))addRoute(profileId,[group.name,...downstreamNames]);
  const emitted=new Set<string>(),profileContributor=(profileId:string):LayerContributor|undefined=>{if(emitted.has(profileId))return;const profile=state.project.collections.profiles.find(({id})=>id===profileId),inheritanceRoutes=routes.get(profileId);if(!profile||!inheritanceRoutes?.length)return;emitted.add(profileId);const base=contributionFor(profile,"Shared Profile"),recipeTargets=[...(directProfileIds.includes(profileId)?[page,state.project.collections.events.find(({id})=>id===path.eventId)]:[]),...groupRecords.filter(({active,group})=>active&&referencedProfileIds(group).includes(profileId)).map(({group})=>group)].filter((target):target is ProjectEntity=>Boolean(target)),recipes=recipeTargets.flatMap((target)=>profileInheritanceRecipes(target,profileId)),canonical=profile.canonicalSchema as CanonicalSchemaDocument|undefined;if(!recipes.length||!canonical)return{...base,inheritanceRoutes};const filtered=recipes.map((recipe)=>selectiveProfileContribution(canonical,recipe)),constraints=filtered.flatMap(({constraints})=>constraints).filter((constraint,index,all)=>all.findIndex((candidate)=>JSON.stringify(candidate)===JSON.stringify(constraint))===index),inheritanceConflicts=filtered.flatMap(({conflicts})=>conflicts);return{...base,constraints,inheritanceRoutes,...(inheritanceConflicts.length?{inheritanceConflicts}:{})};},contributors:LayerContributor[]=[];
  for(const profileId of directProfileIds){const profile=profileContributor(profileId);if(profile)contributors.push(profile);}
  for(const record of groupRecords){if(record.active)for(const profileId of referencedProfileIds(record.group)){const profile=profileContributor(profileId);if(profile)contributors.push(profile);}contributors.push(record.contributor);}
  return[...contributors,...one(state.project.collections.pages,path.pageId,"Page"),...(pageFrame?[contributionFor(pageFrame,"Flow Page-instance")]:[]),...one(state.project.collections.events,path.eventId,"Event"),...(occurrence?[contributionFor(occurrence,occurrence.freePageFrame?"Flow Page-instance":"Event-occurrence")]:[])];
}

export function assignmentContributorTargets(state:ProjectState):AssignmentContributorTarget[]{
  const collection=(entities:readonly ProjectEntity[],kind:AssignmentContributorKind)=>entities.map(({id,name})=>({id,name,kind}));
  const frames=Object.entries(state.project.documentationFlowGraphs??{}).flatMap(([flowId,graph])=>((graph as {pageFrames?:ProjectEntity[]}).pageFrames??[]).map(({id,name})=>({id,name,kind:"Flow Page instance" as const,flowId})));
  return[...collection(state.project.collections.profiles,"Shared Profile"),...collection(((state.project.collections as typeof state.project.collections&{propertySets?:ProjectEntity[]}).propertySets??state.project.collections.pageGroups),"Property Set"),...collection(state.project.collections.pages,"Page"),...collection(state.project.collections.events,"Event"),...frames];
}

export function compileAssignmentContributorTarget(state:ProjectState,assignment:ProjectEntity,context:LayerContext,observation:Record<string,unknown>={}):{target:AssignmentContributorTarget;contributors:LayerContributor[];compiled:CompiledLayeredSchema}{
  const assignmentKind=assignment.targetKind==="Page Group"?"Property Set":assignment.targetKind,target=assignmentContributorTargets(state).find(({id,kind})=>id===assignment.targetId&&kind===assignmentKind);if(!target)throw new Error(`Assignment ${assignment.name} has an unavailable contributor target.`);
  const source=target.kind==="Shared Profile"?state.project.collections.profiles.find(({id})=>id===target.id):target.kind==="Property Set"||target.kind==="Page Group"?((state.project.collections as typeof state.project.collections&{propertySets?:ProjectEntity[]}).propertySets??state.project.collections.pageGroups).find(({id})=>id===target.id):target.kind==="Page"?state.project.collections.pages.find(({id})=>id===target.id):target.kind==="Event"?state.project.collections.events.find(({id})=>id===target.id):flowPageFrameContributor(state,target.flowId!,target.id),scope:LayerScope=target.kind==="Flow Page instance"?"Flow Page-instance":target.kind==="Property Set"?"Page Group":target.kind;
  if(!source)throw new Error(`Contributor target ${target.id} is unavailable.`);const path=layeredContributorPath(state,source,scope,target.flowId),contributors=layeredContributorsForPath(state,path,observation);return{target,contributors,compiled:compileLayeredSchema(contributors,context)};
}

export function layeredContributionDetails(state:ProjectState,entity:ProjectEntity,scope:LayerScope,flowId?:string){
  return layeredContributorsForPath(state,layeredContributorPath(state,entity,scope,flowId)).flatMap((contributor)=>contributor.constraints.map((constraint)=>({contributorId:contributor.id,contributorName:contributor.name,scope:contributor.scope,path:constraint.path,target:constraint.target??"all",condition:constraint.condition?JSON.stringify(constraint.condition):"Always",enforcement:constraint.enforcement??"not set",usedById:entity.id,usedByName:entity.name,usedByScope:scope})));
}

export function saveFlowPageInstanceLocalFacets(state:ProjectState,flowId:string,pageFrameId:string,path:string,facets:Omit<LayerConstraint,"path">):ProjectState{
  const graph=(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>)[flowId],frame=graph?.pageFrames?.find(({id})=>id===pageFrameId);if(!frame)throw new Error(`Flow Page instance ${pageFrameId} is unavailable.`);const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!==""));
  return transactProject(state,`Override ${path} at Flow Page instance`,(project)=>{const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>;return{...project,documentationFlowGraphs:{...graphs,[flowId]:{...graphs[flowId],pageFrames:graphs[flowId]!.pageFrames!.map((candidate)=>candidate.id===pageFrameId?{...candidate,localSchemaContributions:[...((candidate.localSchemaContributions as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[{path,...structuredClone(sparse)}]:[])],compiledTargetsStale:true}:candidate)}}};});
}

export function saveFlowPageInstanceLocalFacetsAndStructures(state:ProjectState,flowId:string,pageFrameId:string,path:string,facets:Omit<LayerConstraint,"path">,commands:readonly FlowPageInstanceStructureCommand[],id:(kind:string)=>string):ProjectState{
  const graph=(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>)[flowId],frame=graph?.pageFrames?.find(({id:frameId})=>frameId===pageFrameId);if(!frame)throw new Error(`Flow Page instance ${pageFrameId} is unavailable.`);
  const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!==""));
  return transactProject(state,`Save ${commands.length+1} Flow Page-instance schema changes`,(project)=>{const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>,current=graphs[flowId]!,frames=current.pageFrames??[];return{...project,documentationFlowGraphs:{...graphs,[flowId]:{...current,pageFrames:frames.map((candidate)=>{if(candidate.id!==pageFrameId)return candidate;const existing=(candidate.localSchemaContributions as LayerConstraint[]|undefined)??[],focused={path,...structuredClone(sparse)},seeded=commands.length?[...existing.filter((constraint)=>constraint.path!==path),focused]:existing,structured=applyLayerConstraintStructures(seeded,commands,id),next=commands.length?structured.filter((constraint)=>Object.keys(constraint).length>1):[...existing.filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[focused]:[])];return{...candidate,localSchemaContributions:structureDeletesPath(commands,path)?next.filter((constraint)=>constraint.path!==path):next,compiledTargetsStale:true};})}}};});
}

export function resetFlowPageInstanceLocalProperty(state:ProjectState,flowId:string,pageFrameId:string,path:string):ProjectState{
  const graph=(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>)[flowId],frame=graph?.pageFrames?.find(({id})=>id===pageFrameId);if(!frame)throw new Error(`Flow Page instance ${pageFrameId} is unavailable.`);
  return transactProject(state,`Reset ${path} to parents at Flow Page instance`,(project)=>{const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[]}>;return{...project,documentationFlowGraphs:{...graphs,[flowId]:{...graphs[flowId],pageFrames:graphs[flowId]!.pageFrames!.map((candidate)=>candidate.id===pageFrameId?{...candidate,localSchemaContributions:((candidate.localSchemaContributions as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),compiledTargetsStale:true}:candidate)}}};});
}
