import {transactProject,type ProjectState,type Requirement} from "./data-layer-specification-project.js";
import {canonicalSchemaWithConstraint,createCanonicalSchema} from "./data-layer-canonical-schema.js";
export type BulkFormat="json"|"json-schema"|"csv"|"template"|"paste";
export interface StagedBulkRow extends Requirement{id:string;selected:boolean}
export interface StagedBulkRequirements{format:BulkFormat;rows:StagedBulkRow[];errors:{rowId:string;field:string;message:string}[];source:string}
const supported=new Set(["string","number","boolean","object","array"]);
function flattenSchema(document:any,path=""):Requirement[]{const rows:Requirement[]=[];for(const[name,property]of Object.entries<any>(document?.properties??{})){const child=`${path}/${name}`,required=(document.required??[]).includes(name);if(property.type==="object"&&property.properties)rows.push(...flattenSchema(property,child));else rows.push({path:child,type:property.type??"string",required,...(property.enum?{allowedValues:property.enum}:{}),...(property.description?{description:property.description}:{}),...(property.examples?{examples:property.examples}:{})});}return rows;}
function delimited(source:string,delimiter:string):Requirement[]{const lines=source.split(/\r?\n/).filter(Boolean),header=lines[0]?.toLowerCase().includes("path")?lines.shift()!.split(delimiter).map((field)=>field.trim()):["path","type","required"];return lines.map((line)=>{const values=line.split(delimiter).map((value)=>value.trim()),record=Object.fromEntries(header.map((field,index)=>[field,values[index]??""])) as Record<string,string>;return{path:String(record.path??""),type:String(record.type||"string"),required:/^(true|required|yes)$/i.test(String(record.required??"")),...(record.allowedvalues?{allowedValues:record.allowedvalues.split("|")}:{})};});}
export function stageBulkRequirements(format:BulkFormat,source:string):StagedBulkRequirements{let requirements:Requirement[]=[];if(format==="json")requirements=JSON.parse(source) as Requirement[];else if(format==="json-schema")requirements=flattenSchema(JSON.parse(source));else if(format==="csv")requirements=delimited(source,",");else if(format==="paste")requirements=delimited(source,"\t");else requirements=Array.from({length:100},(_,index)=>({path:`/property_${index+1}`,type:"string"}));const rows=requirements.map((requirement,index)=>({...structuredClone(requirement),id:`staged:${index+1}`,selected:false})),errors=rows.flatMap((row)=>[...(!row.path.startsWith("/")?[{rowId:row.id,field:"path",message:"Use a canonical /path"}]:[]),...(!supported.has(row.type??"")?[{rowId:row.id,field:"type",message:"Choose a supported type"}]:[])]);return{format,rows,errors,source};}
export function applyStagedBulkAction(staged:StagedBulkRequirements,rowIds:readonly string[],update:Partial<Requirement>):StagedBulkRequirements{const selected=new Set(rowIds);return{...staged,rows:staged.rows.map((row)=>selected.has(row.id)?{...row,...structuredClone(update),selected:true}:row)};}
export function windowStagedBulkRows(staged:StagedBulkRequirements,range:{offset:number;limit:number}):StagedBulkRow[]{return staged.rows.slice(Math.max(0,range.offset),Math.max(0,range.offset)+Math.max(0,range.limit));}
export function commitStagedBulkRequirements(state:ProjectState,profileId:string,staged:StagedBulkRequirements):ProjectState{if(staged.errors.length)throw new Error(`Repair ${staged.errors.length} staged fields before commit.`);const profile=state.project.collections.profiles.find(({id})=>id===profileId);if(!profile)throw new Error(`Unknown Profile ${profileId}.`);let canonical=profile.canonicalSchema??createCanonicalSchema({id:`canonical:${profile.id}`,contributorId:profile.id,contributorName:profile.name}),sequence=0;for(const{id:selectedId,selected,...requirement}of staged.rows)canonical=canonicalSchemaWithConstraint(canonical,requirement,(kind)=>`${kind}:${profile.id}:staged:${++sequence}`);return transactProject(state,`Commit ${staged.rows.length} staged canonical properties`,(project)=>({...project,collections:{...project.collections,profiles:project.collections.profiles.map((candidate)=>candidate.id===profileId?{...candidate,canonicalSchema:canonical,requirements:[]}:candidate)}}));}
