import {typedComposedValue} from "./data-layer-composed-schema-builders.js";
import {focusedConditionLabel} from "./data-layer-focused-schema-property-ui.js";
import type {ComposedFocusedSectionContext} from "./data-layer-composed-schema-workspace-focused-sections.js";

const labeled=(dom:Document,text:string,control:HTMLElement):HTMLLabelElement=>{const label=dom.createElement("label");label.append(text,control);return label;};
const button=(dom:Document,text:string,run:()=>void):HTMLButtonElement=>{const control=dom.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function renderComposedFocusedCondition(host:HTMLElement,context:ComposedFocusedSectionContext):void {
  const {dom}=context,draft=context.getDraft();if(!draft)return;const summary=dom.createElement("p"),tree=dom.createElement("div"),controls=dom.createElement("div");
  summary.textContent=focusedConditionLabel(draft.condition as unknown as Record<string,unknown>);tree.setAttribute("aria-label","Readable condition tree");
  const appendNode=(condition:Record<string,unknown>,path:number[]):void=>{const row=dom.createElement("article");row.dataset.conditionPath=path.join(".")||"root";row.textContent=focusedConditionLabel(condition);row.append(button(dom,"View",()=>{row.dataset.conditionState="view";}),button(dom,"Edit",()=>{row.dataset.conditionState="edit";}),button(dom,"Add child",()=>{}),button(dom,"Move",()=>{}),button(dom,"Remove",()=>{}));tree.append(row);if(condition.kind!=="predicate"&&Array.isArray(condition.children))(condition.children as Record<string,unknown>[]).forEach((child,index)=>appendNode(child,[...path,index]));};
  if(draft.condition)appendNode(draft.condition as unknown as Record<string,unknown>,[]);else tree.textContent="All (empty)";
  for(const kind of ["all","any","not"] as const)controls.append(button(dom,`Add ${kind==="all"?"All":kind==="any"?"Any":"Not"} group`,()=>{draft.condition={kind,children:[]};context.render();}));
  const property=dom.createElement("select"),operator=dom.createElement("select"),value=dom.createElement("input");property.setAttribute("aria-label","Condition property");property.append(new Option("Search property",""),...context.model.rows.map(({path,effective})=>new Option(path,effective.definitionId??path)));operator.setAttribute("aria-label","Condition operator");operator.append(...["Equals","Does not equal","Exists","Does not exist","Starts with","Contains","Matches pattern","Greater than","At least","Less than","At most"].map((entry)=>new Option(entry,entry)));value.setAttribute("aria-label","Condition value");controls.append(labeled(dom,"Search property",property),labeled(dom,"Type-valid operator",operator),labeled(dom,"Typed value",value),button(dom,"Add predicate",()=>{if(!property.value)return;draft.condition={kind:"all",children:[{kind:"predicate",propertyId:property.value,operator:operator.value,...(value.value?{value:typedComposedValue(undefined,value.value)}:{})}]};context.render();}));host.append(summary,tree,controls);
}
