import {createCanonicalSchema} from "./data-layer-canonical-schema.js";
import {addProjectEntity,transactProject,type IdFactory,type ProjectEntity,type ProjectEntityKind,type ProjectState,type SpecificationProject} from "./data-layer-specification-project.js";

export interface ProjectCollectionDefinition {kind:ProjectEntityKind;overview:string;singular:string;addAction:string;purpose:string;example:string;prerequisites:string[];consumers:string[];}
export interface ProjectEntityDependency {kind:ProjectEntityKind|"flowGraph";id:string;name:string;relationship:string;}
export interface ProjectEntityRemovalReview {kind:ProjectEntityKind;id:string;name:string;dependencies:ProjectEntityDependency[];blocked:boolean;summary:string;}

export const projectCollectionDefinitions:Record<ProjectEntityKind,ProjectCollectionDefinition>={
  profiles:{kind:"profiles",overview:"Shared Profiles",singular:"Shared Profile",addAction:"Add Shared Profile",purpose:"reusable schema rules and documentation",example:"Sitewide",prerequisites:["project Draft"],consumers:["Pages","Page Groups","Events","Flows"]},
  pageGroups:{kind:"pageGroups",overview:"Page Groups",singular:"Page Group",addAction:"Add Page Group",purpose:"shared Page context and inherited requirements",example:"Checkout",prerequisites:["optional Shared Profiles"],consumers:["Pages","Flow lanes"]},
  pages:{kind:"pages",overview:"Pages",singular:"Page",addAction:"Add Page",purpose:"observable Page context and specific requirements",example:"Cart",prerequisites:["optional Page Groups"],consumers:["Flows","Fixtures"]},
  events:{kind:"events",overview:"Events",singular:"Event",addAction:"Add Event",purpose:"reusable interaction or context-setting event",example:"Purchase",prerequisites:["optional Schemas"],consumers:["Flows","Assignments","Fixtures"]},
  applicabilitySets:{kind:"applicabilitySets",overview:"Applicability",singular:"Applicability Set",addAction:"Add Applicability Set",purpose:"named observation matching and assignment eligibility",example:"Retail checkout",prerequisites:["observable context fields"],consumers:["Pages","Events","Assignments"]},
  flows:{kind:"flows",overview:"Flows",singular:"Flow",addAction:"Add Flow",purpose:"documentary journey topology",example:"Checkout journey",prerequisites:["Pages","Events"],consumers:["documentation","Fixtures"]},
  fixtures:{kind:"fixtures",overview:"Fixtures",singular:"Fixture",addAction:"Add Fixture",purpose:"saved per-Event validation evidence",example:"Valid purchase",prerequisites:["Events","optional Flows"],consumers:["preflight","release evidence"]},
  schemaDrafts:{kind:"schemaDrafts",overview:"Schemas",singular:"Schema",addAction:"Add Schema",purpose:"canonical payload definition and Draft lineage",example:"Purchase payload",prerequisites:["project Draft"],consumers:["Events","Assignments"]},
  assignments:{kind:"assignments",overview:"Assignments",singular:"Assignment",addAction:"Add Assignment",purpose:"production schema selection for matching observations",example:"Retail Purchase",prerequisites:["Schema","Event","Applicability Set"],consumers:["production evaluator"]},
};

const containsIdentity=(value:unknown,identity:string):boolean=>{if(value===identity)return true;if(Array.isArray(value))return value.some((entry)=>containsIdentity(entry,identity));if(value&&typeof value==="object")return Object.values(value as Record<string,unknown>).some((entry)=>containsIdentity(entry,identity));return false;};
export function projectEntityDependencies(project:SpecificationProject,kind:ProjectEntityKind,identity:string):ProjectEntityDependency[]{const dependencies:ProjectEntityDependency[]=[];for(const[collection,entities]of Object.entries(project.collections) as [ProjectEntityKind,ProjectEntity[]][])for(const entity of entities)if(entity.id!==identity&&containsIdentity(entity,identity))dependencies.push({kind:collection,id:entity.id,name:entity.name,relationship:`${projectCollectionDefinitions[collection].singular} ${entity.name} references ${projectCollectionDefinitions[kind].singular}`});for(const[flowId,graph]of Object.entries(project.documentationFlowGraphs??{})){if(!containsIdentity(graph,identity))continue;const flow=project.collections.flows.find(({id})=>id===flowId);if(!dependencies.some(({id})=>id===flowId))dependencies.push({kind:"flowGraph",id:flowId,name:flow?.name??flowId,relationship:`Flow ${flow?.name??flowId} topology references ${projectCollectionDefinitions[kind].singular}`});}return dependencies;}
export function inspectProjectEntityRemoval(state:ProjectState,kind:ProjectEntityKind,identity:string):ProjectEntityRemovalReview{const entity=(state.project.collections[kind] as ProjectEntity[]).find(({id})=>id===identity);if(!entity)throw new Error(`Unknown ${projectCollectionDefinitions[kind].singular} ${identity}.`);const dependencies=projectEntityDependencies(state.project,kind,identity);return{kind,id:identity,name:entity.name,dependencies,blocked:Boolean(dependencies.length),summary:`${entity.name} · one ${projectCollectionDefinitions[kind].singular} removal · ${dependencies.length} dependent reference${dependencies.length===1?"":"s"} · project remains Draft and evidence becomes stale.`};}
export function removeProjectCollectionEntity(state:ProjectState,kind:ProjectEntityKind,identity:string):ProjectState{const review=inspectProjectEntityRemoval(state,kind,identity);if(review.blocked)throw new Error(`Remove ${review.name} is blocked by ${review.dependencies.map(({name})=>name).join(", ")}.`);return transactProject(state,`Remove ${review.name}`,(project)=>({...project,collections:{...project.collections,[kind]:(project.collections[kind] as ProjectEntity[]).filter(({id})=>id!==identity)}} as SpecificationProject));}

const firstId=(project:SpecificationProject,kind:ProjectEntityKind):string|undefined=>project.collections[kind][0]?.id;
export function createProjectCollectionEntity(state:ProjectState,kind:ProjectEntityKind,name:string,id:IdFactory):ProjectState{const clean=name.trim();if(!clean)throw new Error(`${projectCollectionDefinitions[kind].singular} name is required.`);if((state.project.collections[kind] as ProjectEntity[]).some((entity)=>entity.name.toLowerCase()===clean.toLowerCase()))throw new Error(`${projectCollectionDefinitions[kind].singular} name must be unique in this project.`);const event=state.project.collections.events[0],eventId=event?.id,pageId=firstId(state.project,"pages"),flowId=firstId(state.project,"flows"),schemaId=firstId(state.project,"schemaDrafts"),applicabilitySetId=firstId(state.project,"applicabilitySets"),defaults:Record<ProjectEntityKind,Record<string,unknown>>={profiles:{requirements:[],canonicalSchema:createCanonicalSchema({id:id("canonical-schema"),contributorId:"",contributorName:clean})},pageGroups:{pageIds:[]},pages:{pageGroupIds:[]},events:{eventName:clean.toLowerCase().replace(/[^a-z0-9]+/g,"_"),sourceId:"event-history",target:"payload",role:"interaction",...(schemaId?{schemaDraftId:schemaId}:{})},applicabilitySets:{priority:0,condition:{kind:"all",conditions:[]}},flows:{steps:eventId?[{id:id("flow-step"),name:`${clean} event`,eventId}]:[]},fixtures:{mode:"event",observations:[],expected:{},releasePolicy:"required",...(eventId?{eventId}:{}),...(pageId?{pageId}:{}),...(flowId?{flowId}:{})},schemaDrafts:{published:false,version:0,document:{type:"object",properties:{}},workingDraft:{document:{type:"object",properties:{}},pendingChanges:[]},canonicalSchema:createCanonicalSchema({id:id("canonical-schema"),contributorId:"",contributorName:clean})},assignments:{...(schemaId?{schemaDraftId:schemaId,schemaId}:{}),...(eventId?{eventId,eventName:event?.eventName??event?.name}:{}),...(applicabilitySetId?{applicabilitySetId}:{}),sourceId:"event-history",target:"payload",priority:10,versionPolicy:"follow latest"}};return addProjectEntity(state,kind,{name:clean,...defaults[kind]},id);}
