import {canonicalConstraints,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {EffectiveProperty,LayerConstraint,LayerScope} from "./data-layer-layered-schema.js";
import {transactProject,type ProjectEntity,type ProjectEntityKind,type ProjectState} from "./data-layer-specification-project.js";
import {composedSchemaWorkspace} from "./composed-schema/workspace-model.js";
import {composedCanonicalSchema,resetCanonicalRow} from "./composed-schema/canonical-workspace.js";
import {applyLayerConstraintStructures,type FlowPageInstanceStructureCommand} from "./flow-graph/page-instance-structure.js";
export {composedSchemaWorkspace,composedCanonicalSchema};
export type ComposedSchemaRowState="ready"|"warning"|"blocked";
export interface ComposedSchemaProvenance {contributorId:string;contributorName:string;scope:LayerScope;state:"inherited"|"shadowed"|"effective";}
export interface ComposedSchemaRepair {contributorId:string;contributorName:string;label:string;}
export interface ComposedSchemaRow {path:string;inherited?:EffectiveProperty;local:LayerConstraint;effective:EffectiveProperty;source:string;validationState:ComposedSchemaRowState;message:string;action:"override"|"reset"|"remove";provenance:ComposedSchemaProvenance[];repairs:ComposedSchemaRepair[];}
export interface ComposedSchemaWorkspace {heading:string;status:"ready"|"blocked";rows:ComposedSchemaRow[];conflictSummary:string;}
const clone=<T>(value:T):T=>structuredClone(value);
function updateEntity(state:ProjectState,kind:ProjectEntityKind,entityId:string,label:string,update:(entity:ProjectEntity)=>ProjectEntity):ProjectState{return transactProject(state,label,(project)=>({...project,collections:{...project.collections,[kind]:(project.collections[kind] as ProjectEntity[]).map((entity)=>entity.id===entityId?update(entity):entity)}} as typeof project));}
const sparseFacetKeys=(constraint:LayerConstraint):LayerConstraint=>Object.fromEntries(Object.entries(constraint).filter(([key])=>!["path","origins","superseded","expectedContributor"].includes(key))) as LayerConstraint;
const sparseAgainst=(constraint:LayerConstraint,inherited:EffectiveProperty|undefined):LayerConstraint=>{const result:Record<string,unknown>={path:constraint.path},parent:Partial<LayerConstraint>=inherited?sparseFacetKeys(inherited):{};for(const[key,value]of Object.entries(sparseFacetKeys(constraint))){if(key==="definitionId"&&inherited&&!inherited.definitionId)continue;if(key==="allowedValueIds"&&inherited&&!inherited.allowedValueIds&&JSON.stringify(constraint.allowedValues)===JSON.stringify(inherited.allowedValues)&&!(constraint.allowedValueProvenance??[]).some(({state})=>state!=="inherited"))continue;if(key==="target"&&inherited&&value==="all"&&parent.target===undefined)continue;if(value!==undefined&&JSON.stringify(value)!==JSON.stringify(parent[key as keyof LayerConstraint]))result[key]=clone(value);}return result as unknown as LayerConstraint;};
export function saveComposedCanonicalDocument(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,document:CanonicalSchemaDocument):ProjectState{const entity=(state.project.collections[kind] as ProjectEntity[]).find(({id})=>id===entityId);if(!entity)throw new Error(`${kind==="pages"?"Page":"Page Group"} ${entityId} is unavailable.`);const scope=kind==="pages"?"Page":"Page Group",workspace=composedSchemaWorkspace(state,entity,scope),parents=new Map(workspace.rows.map(({path,inherited})=>[path,inherited])),constraints=canonicalConstraints(document).map((constraint)=>sparseAgainst(constraint,parents.get(constraint.path))).filter((constraint)=>Object.keys(constraint).length>1);return updateEntity(state,kind,entityId,`Save effective canonical schema for ${entity.name}`,(current)=>{const next:ProjectEntity={...current,localSchemaContributions:constraints,compiledTargetsStale:true};delete next.canonicalSchema;delete next.schemaConstraints;return next;});}
export function saveComposedSchemaLocalFacets(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string,facets:Omit<LayerConstraint,"path">):ProjectState{const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!=="")) as Omit<LayerConstraint,"path">;return updateEntity(state,kind,entityId,`Override ${path} at ${kind==="pages"?"Page":"Page Group"}`,(entity)=>{const existing=(entity.localSchemaContributions as LayerConstraint[]|undefined)??[],next=[...existing.filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[{path,...clone(sparse)}]:[])];return{...entity,localSchemaContributions:next,compiledTargetsStale:true};});}
export function saveComposedSchemaLocalFacetsAndStructures(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string,facets:Omit<LayerConstraint,"path">,commands:readonly FlowPageInstanceStructureCommand[],id:(kind:string)=>string):ProjectState{const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!=="")) as Omit<LayerConstraint,"path">;return updateEntity(state,kind,entityId,`Save ${commands.length+1} ${kind==="pages"?"Page":"Page Group"} schema changes`,(entity)=>{const existing=(entity.localSchemaContributions as LayerConstraint[]|undefined)??[],structured=applyLayerConstraintStructures(existing,commands,id),next=[...structured.filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[{path,...clone(sparse)}]:[])];return{...entity,localSchemaContributions:next,compiledTargetsStale:true};});}
export function resetComposedSchemaLocalProperty(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string):ProjectState{return updateEntity(state,kind,entityId,`Reset ${path} to parents`,(entity)=>{const next:ProjectEntity={...entity,localSchemaContributions:((entity.localSchemaContributions as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),schemaConstraints:((entity.schemaConstraints as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),compiledTargetsStale:true};return resetCanonicalRow(entity.canonicalSchema as CanonicalSchemaDocument|undefined,path,next);});}
