import {canonicalPropertyPath,canonicalSchemaFromJsonSchema,type CanonicalPredicate,type CanonicalPredicateOperator,type CanonicalPropertyNode,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import {normalizeCanonicalSchemaDocument} from "./data-layer-schema-canonical-document.js";
import type {JsonSchema} from "./data-layer-schema-document.js";
import type {SchemaDocumentation,SchemaPropertyDocumentation} from "./data-layer-schema-documentation.js";

interface SavedSchemaConditionPredicate {propertyPath:string;operator:string;comparison?:{value?:unknown;type?:string};comparisons?:readonly {value?:unknown;type?:string}[];detectedType?:string;}
interface SavedSchemaConditionGroup {operator:string;predicates:readonly SavedSchemaConditionPredicate[];}
interface SavedSchemaRule {id:string;name?:string;version:number;enabled?:boolean;propertyPath?:string;operator?:string;parameters?:string;allowedValues?:readonly (string|number|boolean|null)[];severity?:string;message?:string;conditionGroup?:SavedSchemaConditionGroup;}
interface SavedSchemaCanonicalSource {id:string;name:string;version:number;document:JsonSchema;attachedRules?:readonly SavedSchemaRule[];rules?:readonly SavedSchemaRule[];documentation?:SchemaDocumentation;canonicalSchema?:CanonicalSchemaDocument;}
interface CanonicalProjectionRule {id:string;name?:string;version:number;enabled?:boolean;propertyPath?:string;operator?:string;parameters?:string;allowedValues?:readonly (string|number|boolean|null)[];severity?:string;message?:string;conditionGroup?:SavedSchemaConditionGroup}
interface CanonicalProjectionSource {id:string;name:string;version:number;document:JsonSchema;assignments:readonly unknown[];attachedRules?:readonly CanonicalProjectionRule[];documentation?:SchemaDocumentation;canonicalSchema?:CanonicalSchemaDocument}

const pointer=(path:string)=>`/${path.split(/[./]/).filter(Boolean).join("/")}`;
const clone=<T>(value:T):T=>structuredClone(value);
const stableValueIdentity=(owner:string,value:unknown):string=>{let hash=2166136261;for(const char of JSON.stringify(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return `allowed-value:${owner}:${(hash>>>0).toString(16)}`;};
const jsonFacetRule=(schemaId:string,nodeId:string,kind:string)=>`json-facet:${schemaId}:${nodeId}:${kind}`;
const pointerSegments=(path:string):string[]=>path.split("/").filter(Boolean).map((segment)=>segment.replaceAll("~1","/").replaceAll("~0","~"));
const sourcePropertyAtPath=(document:Record<string,unknown>,path:string):{definition:Record<string,unknown>;container:Record<string,unknown>;name:string}|undefined=>{
  const directProperties=document.properties;
  if(directProperties&&typeof directProperties==="object"&&!Array.isArray(directProperties)){
    const directDefinition=(directProperties as Record<string,unknown>)[path];
    if(directDefinition&&typeof directDefinition==="object"&&!Array.isArray(directDefinition))return{definition:directDefinition as Record<string,unknown>,container:document,name:path};
  }
  const segments=pointerSegments(path);if(!segments.length)return undefined;
  let current=document;
  for(let index=0;index<segments.length-1;index+=1){const segment=segments[index]!;if(segment==="*"){const items=current.items;if(!items||typeof items!=="object"||Array.isArray(items))return undefined;current=items as Record<string,unknown>;continue;}const properties=current.properties;if(!properties||typeof properties!=="object"||Array.isArray(properties))return undefined;const child=(properties as Record<string,unknown>)[segment];if(!child||typeof child!=="object"||Array.isArray(child))return undefined;current=child as Record<string,unknown>;}
  const name=segments.at(-1)!;if(name==="*")return undefined;const properties=current.properties;if(!properties||typeof properties!=="object"||Array.isArray(properties))return undefined;const definition=(properties as Record<string,unknown>)[name];return definition&&typeof definition==="object"&&!Array.isArray(definition)?{definition:definition as Record<string,unknown>,container:current,name}:undefined;
};
const canonicalOperator=(operator:string):CanonicalPredicateOperator=>({"Equal":"Equals","Is greater than":"Greater than","Is at least":"At least","Is less than":"Less than","Is at most":"At most"} as const)[operator as "Equal"|"Is greater than"|"Is at least"|"Is less than"|"Is at most"]??operator as CanonicalPredicateOperator;
const comparisonValue=(comparison:{value?:unknown;type?:string}|undefined):unknown=>comparison?.value!==undefined?clone(comparison.value):comparison?.type==="null"?null:undefined;
function canonicalRuleCondition(document:CanonicalSchemaDocument,group:SavedSchemaRule["conditionGroup"]):{complete:boolean;condition?:CanonicalPredicate}{
  if(!group)return{complete:true};
  if(!Array.isArray(group.predicates))return{complete:false};
  const byPath=new Map(Object.values(document.nodes).map((node)=>[canonicalPropertyPath(document,node.id),node.id])),kind=group.operator==="All"?"all":group.operator==="Any"?"any":group.operator==="Not"?"not":undefined,children=group.predicates.map((predicate):CanonicalPredicate|undefined=>{const propertyId=byPath.get(pointer(predicate.propertyPath));if(!propertyId)return undefined;const operator=canonicalOperator(predicate.operator),value=operator==="Is one of"&&predicate.comparisons?predicate.comparisons.map(comparisonValue):comparisonValue(predicate.comparison);return{kind:"predicate",propertyId,operator,...(value!==undefined?{value}:{})};});
  if(!kind||!children.length||children.some((child)=>child===undefined)||(kind==="not"&&children.length!==1))return{complete:false};
  return{complete:true,condition:{kind,children:children as CanonicalPredicate[]}};
}

const legacyOperator=(operator:CanonicalPredicateOperator):string=>({"Greater than":"Is greater than","At least":"Is at least","Less than":"Is less than","At most":"Is at most"} as const)[operator as "Greater than"|"At least"|"Less than"|"At most"]??operator;
const legacyConditionOperators=new Set<CanonicalPredicateOperator>(["Equals","Does not equal","Exists","Does not exist","Starts with","Contains","Is one of","Matches pattern","Greater than","At least","Less than","At most"]);
const typedComparison=(value:unknown):{value:string|number|boolean|null;type:"string"|"number"|"boolean"|"null"}|undefined=>value===null?{type:"null",value:null}:typeof value==="string"?{type:"string",value}:typeof value==="number"?{type:"number",value}:typeof value==="boolean"?{type:"boolean",value}:undefined;
const sameValue=(left:unknown,right:unknown):boolean=>Object.is(left,right)||Array.isArray(left)&&Array.isArray(right)&&left.length===right.length&&left.every((value,index)=>sameValue(value,right[index]));
const conditionValue=(predicate:SavedSchemaConditionPredicate):unknown=>canonicalOperator(predicate.operator)==="Is one of"&&predicate.comparisons?predicate.comparisons.map(comparisonValue):comparisonValue(predicate.comparison);
function legacyRuleCondition(document:CanonicalSchemaDocument,condition:CanonicalPredicate|undefined,prior?:SavedSchemaConditionGroup,previous?:CanonicalSchemaDocument):SavedSchemaConditionGroup|undefined{
  if(!condition||(condition.kind!=="all"&&condition.kind!=="any")||!condition.children.length||condition.children.some(({kind})=>kind!=="predicate"))return undefined;
  const operator=condition.kind==="all"?"All":"Any",sourcePaths=new Map(Object.entries(document.sourceContent?.pathsByNodeId??{}).map(([id,path])=>[pointer(path),id])),currentPaths=new Map(Object.values(document.nodes).map((node)=>[canonicalPropertyPath(document,node.id),node.id])),previousPaths=new Map(Object.values(previous?.nodes??{}).map((node)=>[canonicalPropertyPath(previous!,node.id),node.id])),priorPredicates=prior?.operator===operator&&prior.predicates.length===condition.children.length?prior.predicates:[];
  const predicates:SavedSchemaConditionPredicate[]=[];
  for(const[index,entry]of condition.children.entries()){
    if(entry.kind!=="predicate"||!legacyConditionOperators.has(entry.operator))return undefined;
    const node=document.nodes[entry.propertyId];if(!node)return undefined;
    const candidate=priorPredicates[index],candidatePropertyId=candidate?(currentPaths.get(pointer(candidate.propertyPath))??sourcePaths.get(pointer(candidate.propertyPath))??previousPaths.get(pointer(candidate.propertyPath))):undefined,candidateMatches=Boolean(candidate&&candidatePropertyId===entry.propertyId&&canonicalOperator(candidate.operator)===entry.operator&&(["Exists","Does not exist"].includes(entry.operator)||sameValue(conditionValue(candidate),entry.value))),currentPath=canonicalPropertyPath(document,entry.propertyId),base=candidateMatches?clone(candidate!):undefined,{comparison:_comparison,comparisons:_comparisons,...metadata}=base??{},propertyPath=base&&pointer(base.propertyPath)===currentPath?base.propertyPath:currentPath,predicate:SavedSchemaConditionPredicate={...metadata,propertyPath,operator:base?.operator??legacyOperator(entry.operator)};
    if(entry.operator==="Is one of"){
      if(!Array.isArray(entry.value))return undefined;const comparisons=entry.value.map(typedComparison);if(comparisons.some((value)=>value===undefined))return undefined;predicate.comparisons=comparisons as NonNullable<SavedSchemaConditionPredicate["comparisons"]>;
    }else if(entry.operator!=="Exists"&&entry.operator!=="Does not exist"){
      const comparison=typedComparison(entry.value);if(!comparison)return undefined;predicate.comparison=comparison;
    }
    if(!base)predicate.detectedType=node.type==="integer"?"number":node.type;
    predicates.push(predicate);
  }
  return{operator,predicates};
}
const attachedRuleKey=(rule:Pick<CanonicalProjectionRule,"id"|"propertyPath">):string=>`${rule.id}\u0000${pointer(rule.propertyPath??"")}`;
const projectionOnlyJsonMetadata=(projected:JsonSchema,source:JsonSchema):JsonSchema=>{
  const next=clone(projected);
  for(const key of["typeMismatchTreatment","propertyOrigin"] as const){if(source[key]!==undefined)next[key]=source[key] as never;else delete next[key];}
  for(const[name,child]of Object.entries(next.properties??{})){const sourceChild=source.properties?.[name];if(sourceChild)next.properties![name]=projectionOnlyJsonMetadata(child,sourceChild);}
  if(next.items&&source.items)next.items=projectionOnlyJsonMetadata(next.items,source.items);
  return next;
};

export function savedSchemaCanonicalDocument(schema:SavedSchemaCanonicalSource,id:(kind:string)=>string,target?:{id:string;contributorId:string;contributorName:string}):CanonicalSchemaDocument{
  if(schema.canonicalSchema)return clone(schema.canonicalSchema);
  const canonical=canonicalSchemaFromJsonSchema({id:target?.id??`canonical:saved:${schema.id}`,contributorId:target?.contributorId??schema.id,contributorName:target?.contributorName??schema.name,sourceIdentity:schema.id,sourceRevision:schema.version,document:schema.document as Record<string,unknown>,idFactory:id}),byPath=new Map(Object.values(canonical.nodes).map((node)=>[canonicalPropertyPath(canonical,node.id),node]));
  const definitionsByNodeId:Record<string,Record<string,unknown>>={},pathsByNodeId:Record<string,string>={},sourceRules=schema.attachedRules??schema.rules??[];
  for(const[path,node]of byPath){const source=sourcePropertyAtPath(schema.document as Record<string,unknown>,path);if(!source)continue;const{definition:rich,container,name}=source,documentation=schema.documentation?.properties?.[path],siblings=container.properties as Record<string,unknown>;node.order=Object.keys(siblings).indexOf(name);definitionsByNodeId[node.id]=clone(rich);pathsByNodeId[node.id]=path;if(Array.isArray(container.required)&&container.required.includes(name))node.presence={mode:"required"};else if(Array.isArray(container.forbidden)&&container.forbidden.includes(name))node.presence={mode:"forbidden"};if(node.type==="array"&&rich.items&&typeof rich.items==="object"&&!Array.isArray(rich.items)&&typeof (rich.items as Record<string,unknown>).type==="string")node.itemType=(rich.items as Record<string,unknown>).type as CanonicalPropertyNode["type"];node.allowedValues=node.allowedValues.map((entry)=>({...entry,id:entry.id??stableValueIdentity(node.id,entry.value)}));if(documentation)node.documentation={displayText:documentation.displayName,description:documentation.description||node.documentation.description,comments:documentation.comments??"",example:documentation.example?{method:documentation.example.selectionMethod==="allowed value"?"allowed-value":"custom",value:clone(documentation.example.value)}:node.documentation.example};const minimum=typeof rich.minimum==="number"?rich.minimum:undefined,maximum=typeof rich.maximum==="number"?rich.maximum:undefined,minItems=typeof rich.minItems==="number"?rich.minItems:undefined,maxItems=typeof rich.maxItems==="number"?rich.maxItems:undefined;if(typeof rich.pattern==="string")node.rules.push({id:jsonFacetRule(schema.id,node.id,"pattern"),kind:"pattern",pattern:rich.pattern,severity:"error",message:"Pattern mismatch"});if(minimum!==undefined||maximum!==undefined)node.rules.push({id:jsonFacetRule(schema.id,node.id,"range"),kind:"range",...(minimum!==undefined?{minimum}:{}),...(maximum!==undefined?{maximum}:{}),severity:"error",message:"Outside range"});if(minItems!==undefined||maxItems!==undefined)node.rules.push({id:jsonFacetRule(schema.id,node.id,"cardinality"),kind:"cardinality",...(minItems!==undefined?{minItems}:{}),...(maxItems!==undefined?{maxItems}:{}),severity:"error",message:"Outside cardinality"});}canonical.rootIds=Object.values(canonical.nodes).filter(({parentId})=>!parentId).sort((left,right)=>left.order-right.order).map(({id})=>id);if(canonical.rootIds[0])canonical.selectedPropertyId=canonical.rootIds[0];
  const typedRuleValue=(node:CanonicalPropertyNode,value:unknown):unknown=>{if(typeof value!=="string")return clone(value);if(node.type==="number"||node.type==="integer"){const parsed=Number(value);return Number.isFinite(parsed)?parsed:value;}if(node.type==="boolean"&&["true","false"].includes(value.toLowerCase()))return value.toLowerCase()==="true";if(node.type==="null"&&value==="null")return null;return value;};
  for(const rule of sourceRules){
    const node=byPath.get(pointer(rule.propertyPath??""));if(!node)continue;
    const operator=rule.operator?.replaceAll("_","-").replaceAll(" ","-").toLowerCase(),bounds=rule.parameters?.split(",")??[],number=(value:string|undefined)=>value!==undefined&&value!==""&&Number.isFinite(Number(value))?Number(value):undefined,minimum=number(bounds[0]),maximum=number(bounds[1]),kind=operator==="pattern"||operator==="regular-expression"?"pattern":operator==="range"||operator==="numeric-range"?"range":operator==="cardinality"||operator==="item-count"?"cardinality":"custom",conditionMapping=canonicalRuleCondition(canonical,rule.conditionGroup),mappedFacet=operator==="exact-value"||operator==="allowed-values"||operator==="required",sourceMetadata=mappedFacet?{name:rule.name??rule.id,revision:rule.version,operator,provenance:{source:"saved-schema" as const,sourceId:schema.id,revision:schema.version}}:{};
    node.rules.push({id:rule.id,kind,...(kind==="pattern"&&rule.parameters?{pattern:rule.parameters}:{}),...(kind==="range"&&minimum!==undefined?{minimum}:{}),...(kind==="range"&&maximum!==undefined?{maximum}:{}),...(kind==="cardinality"&&minimum!==undefined?{minItems:minimum}:{}),...(kind==="cardinality"&&maximum!==undefined?{maxItems:maximum}:{}),...(conditionMapping.condition?{condition:conditionMapping.condition}:{}),severity:rule.severity==="warning"?"warning":"error",...(rule.message!==undefined?{message:rule.message}:{}),...(typeof rule.enabled==="boolean"?{enabled:rule.enabled}:{}),...sourceMetadata,...(rule.id.startsWith("rule:")&&!mappedFacet?{reusableRuleId:rule.id}:{})});
    if(rule.enabled===false)continue;
    if(operator==="required"){if(conditionMapping.complete)node.presence=conditionMapping.condition?{mode:"required-when",condition:conditionMapping.condition}:{mode:"required"};continue;}
    if(rule.conditionGroup)continue;
    if(operator==="exact-value"&&rule.parameters!==undefined)node.expectedValue=typedRuleValue(node,rule.parameters);
    if(operator==="allowed-values"){const values=rule.allowedValues??bounds.map((value)=>value.trim()).filter(Boolean);node.allowedValues=values.map((value)=>{const typed=typedRuleValue(node,value);return{id:stableValueIdentity(`${node.id}:rule:${rule.id}`,typed),value:typed};});}
  }
  canonical.sourceContent={document:clone(schema.document as Record<string,unknown>),rules:clone(sourceRules as unknown as readonly Record<string,unknown>[]),documentation:clone(schema.documentation??{}),examples:[],definitionsByNodeId,pathsByNodeId};return canonical;
}

const orderedChildren=(document:CanonicalSchemaDocument,parentId?:string):CanonicalPropertyNode[]=>Object.values(document.nodes).filter((node)=>node.parentId===parentId).sort((left,right)=>left.order-right.order||left.id.localeCompare(right.id));
const savedRuleOwnsFacet=(node:CanonicalPropertyNode,operator:string):boolean=>node.rules.some((rule)=>rule.enabled!==false&&rule.operator===operator&&rule.provenance?.source==="saved-schema");
const sourceOwnsPresence=(document:CanonicalSchemaDocument,node:CanonicalPropertyNode,mode:"required"|"forbidden"):boolean=>{
  const path=document.sourceContent?.pathsByNodeId?.[node.id];if(!path)return false;
  const source=sourcePropertyAtPath(document.sourceContent?.document??{},path),members=source?.container[mode];return Array.isArray(members)&&members.includes(source!.name);
};
const materializedPresence=(document:CanonicalSchemaDocument,node:CanonicalPropertyNode,mode:"required"|"forbidden"):boolean=>{
  if(savedRuleOwnsFacet(node,mode))return sourceOwnsPresence(document,node,mode);
  return node.presence.mode===mode;
};
const sourceDocumentationAtNode=(document:CanonicalSchemaDocument,node:CanonicalPropertyNode):SchemaPropertyDocumentation|undefined=>{
  const documentation=document.sourceContent?.documentation as SchemaDocumentation|undefined,sourcePath=document.sourceContent?.pathsByNodeId?.[node.id],paths=[canonicalPropertyPath(document,node.id),...(sourcePath?[pointer(sourcePath)]:[])];
  return paths.map((path)=>documentation?.properties?.[path]).find(Boolean);
};
const withoutRootDeclaredPolicy=(document:JsonSchema):JsonSchema=>{const next=clone(document);delete next.additionalProperties;return next;};
const losslessSourceRepresentation=(source:JsonSchema,projected:JsonSchema,onlyDefinedFields:boolean):JsonSchema=>{
  const sourceMeaning=normalizeCanonicalSchemaDocument(withoutRootDeclaredPolicy(source)),projectedMeaning=normalizeCanonicalSchemaDocument(withoutRootDeclaredPolicy(projected));
  if(JSON.stringify(sourceMeaning)!==JSON.stringify(projectedMeaning))return projected;
  const preserved=clone(source);if(onlyDefinedFields)preserved.additionalProperties=false;else delete preserved.additionalProperties;return preserved;
};
function jsonDefinition(document:CanonicalSchemaDocument,node:CanonicalPropertyNode,currentDocument:JsonSchema,previousCanonical?:CanonicalSchemaDocument):JsonSchema{
  const currentPaths=[canonicalPropertyPath(document,node.id),...(previousCanonical?.nodes[node.id]?[canonicalPropertyPath(previousCanonical,node.id)]:[]),...(document.sourceContent?.pathsByNodeId?.[node.id]?[document.sourceContent.pathsByNodeId[node.id]!]:[])],currentDefinition=currentPaths.map((path)=>sourcePropertyAtPath(currentDocument as Record<string,unknown>,path)?.definition).find(Boolean),sourceDefinition=document.sourceContent?.definitionsByNodeId?.[node.id],base=clone(currentDefinition??sourceDefinition??{}) as Record<string,unknown>,sourceDocumentation=sourceDocumentationAtNode(document,node),children=orderedChildren(document,node.id),definition:Record<string,unknown>={...base,type:node.type};
  if(!currentDefinition&&!sourceDefinition&&node.provenance.some(({source})=>source==="created"))definition.propertyOrigin="manual";
  for(const key of["properties","required","forbidden","enum","description","examples","pattern","minimum","maximum","minItems","maxItems"])delete definition[key];
  if(node.type==="array"&&node.itemType){const prior=base.items&&typeof base.items==="object"&&!Array.isArray(base.items)?clone(base.items as Record<string,unknown>):undefined;definition.items=prior?.type===node.itemType?prior:{type:node.itemType};}else delete definition.items;
  if(children.length){const container=node.type==="array"&&node.itemType==="object"?definition.items as Record<string,unknown>:definition;container.properties=Object.fromEntries(children.map((child)=>[child.name,jsonDefinition(document,child,currentDocument,previousCanonical)]));delete container.required;delete container.forbidden;const required=children.filter((child)=>materializedPresence(document,child,"required")).map(({name})=>name),forbidden=children.filter((child)=>materializedPresence(document,child,"forbidden")).map(({name})=>name);if(required.length)container.required=required;if(forbidden.length)container.forbidden=forbidden;}
  const sourceEnum=Array.isArray(base.enum)?base.enum:undefined;if(savedRuleOwnsFacet(node,"allowed-values")){if(sourceEnum)definition.enum=clone(sourceEnum);}else if(node.allowedValues.length)definition.enum=node.allowedValues.map(({value})=>clone(value));if(sourceDocumentation?.description){if(base.description!==undefined)definition.description=clone(base.description);}else if(node.documentation.description)definition.description=node.documentation.description;if(sourceDocumentation?.example){if(base.examples!==undefined)definition.examples=clone(base.examples);}else if(node.documentation.example.method!=="blank")definition.examples=[clone(node.documentation.example.value)];
  for(const rule of node.rules.filter(({id})=>id.startsWith("json-facet:"))){if(rule.kind==="pattern"&&rule.pattern)definition.pattern=rule.pattern;if(rule.kind==="range"){if(rule.minimum!==undefined)definition.minimum=rule.minimum;if(rule.maximum!==undefined)definition.maximum=rule.maximum;}if(rule.kind==="cardinality"){if(rule.minItems!==undefined)definition.minItems=rule.minItems;if(rule.maxItems!==undefined)definition.maxItems=rule.maxItems;}}
  return definition as JsonSchema;
}
export function savedSchemaFromCanonical<T>(schema:T&CanonicalProjectionSource,canonical:CanonicalSchemaDocument):T{
  const roots=orderedChildren(canonical),previousCanonical=schema.canonicalSchema,root=clone(schema.document??canonical.sourceContent?.document??{}) as Record<string,unknown>;for(const key of["properties","required","forbidden","additionalProperties"])delete root[key];root.type="object";root.properties=Object.fromEntries(roots.map((node)=>[node.name,jsonDefinition(canonical,node,schema.document,previousCanonical)]));if(canonical.onlyDefinedFields)root.additionalProperties=false;const rootRequired=roots.filter((node)=>materializedPresence(canonical,node,"required")).map(({name})=>name),rootForbidden=roots.filter((node)=>materializedPresence(canonical,node,"forbidden")).map(({name})=>name);if(rootRequired.length)root.required=rootRequired;if(rootForbidden.length)root.forbidden=rootForbidden;const document=root as JsonSchema,attachedRules:CanonicalProjectionRule[]=[],properties:Record<string,NonNullable<NonNullable<CanonicalProjectionSource["documentation"]>["properties"]>[string]>={},sourceAttachments=[...(schema.attachedRules??[])],consumedSourceRules=new Set<number>(),projectedRuleKeys=new Set<string>(),outputOrder=new Map<string,number>(),canonicalPaths=new Set(Object.values(canonical.nodes).map((node)=>canonicalPropertyPath(canonical,node.id))),sourcePathByNodeId=canonical.sourceContent?.pathsByNodeId??{};
  const priorRule=(id:string,nodeId:string,path:string):{rule:CanonicalProjectionRule;index:number}|undefined=>{const candidates=sourceAttachments.map((rule,index)=>({rule,index})).filter(({rule,index})=>rule.id===id&&!consumedSourceRules.has(index)),sourcePath=sourcePathByNodeId[nodeId],previousPath=previousCanonical?.nodes[nodeId]?canonicalPropertyPath(previousCanonical,nodeId):undefined,expectedPaths=new Set([path,...(sourcePath?[pointer(sourcePath)]:[]),...(previousPath?[previousPath]:[])]),match=candidates.find(({rule})=>expectedPaths.has(pointer(rule.propertyPath??"")));if(match)consumedSourceRules.add(match.index);return match;};
  for(const node of Object.values(canonical.nodes)){
    const path=canonicalPropertyPath(canonical,node.id),priorDocumentation=schema.documentation?.properties?.[path],example=node.documentation.example.method==="blank"?undefined:{value:structuredClone(node.documentation.example.value) as string|number|boolean|null,selectionMethod:node.documentation.example.method==="allowed-value"?"allowed value" as const:"custom" as const},sourceRules=canonical.sourceContent?.definitionsByNodeId?.[node.id]?.rules,embeddedRuleIds=new Set(Array.isArray(sourceRules)?sourceRules.flatMap((rule)=>rule&&typeof rule==="object"&&"id"in rule&&typeof rule.id==="string"?[rule.id]:[]):[]);
    if(node.documentation.displayText||node.documentation.description||node.documentation.comments||priorDocumentation||example)properties[path]={displayName:node.documentation.displayText,description:node.documentation.description,...(node.documentation.comments?{comments:node.documentation.comments}:{}),...(example?{example}:{})};
    for(const rule of node.rules){if(rule.id.startsWith("json-facet:"))continue;const priorMatch=priorRule(rule.id,node.id,path),prior=priorMatch?.rule;if(!prior&&embeddedRuleIds.has(rule.id))continue;const operator=rule.kind==="pattern"?(prior?.operator??"regular-expression"):rule.kind==="range"?"numeric-range":rule.kind==="cardinality"?"item-count":prior?.operator??rule.kind,parameters=rule.kind==="pattern"?rule.pattern:rule.kind==="range"?`${rule.minimum??""},${rule.maximum??""}`:rule.kind==="cardinality"?`${rule.minItems??""},${rule.maxItems??""}`:prior?.parameters,propertyPath=prior?.propertyPath&&pointer(prior.propertyPath)===path?prior.propertyPath:path,{conditionGroup:_legacyConditionGroup,...priorWithoutLegacyCondition}=prior??{},projectedCondition=legacyRuleCondition(canonical,rule.condition,prior?.conditionGroup,previousCanonical),opaqueCondition=!rule.condition&&prior?.conditionGroup&&!canonicalRuleCondition(canonical,prior.conditionGroup).complete?clone(prior.conditionGroup):undefined,conditionGroup=projectedCondition??opaqueCondition,projected={...priorWithoutLegacyCondition,id:rule.id,version:prior?.version??1,propertyPath,operator,...(parameters!==undefined?{parameters}:{}),severity:rule.severity,...(rule.message!==undefined?{message:rule.message}:{}),...(conditionGroup?{conditionGroup}:{})},key=attachedRuleKey(projected);if(projectedRuleKeys.has(key))continue;projectedRuleKeys.add(key);attachedRules.push(projected);if(priorMatch)outputOrder.set(key,priorMatch.index);}
  }
  for(const[ruleIndex,rule]of sourceAttachments.entries()){if(consumedSourceRules.has(ruleIndex)||canonicalPaths.has(pointer(rule.propertyPath??"")))continue;const key=attachedRuleKey(rule);if(projectedRuleKeys.has(key))continue;projectedRuleKeys.add(key);attachedRules.push(clone(rule));outputOrder.set(key,ruleIndex);}
  attachedRules.sort((left,right)=>(outputOrder.get(attachedRuleKey(left))??Number.MAX_SAFE_INTEGER)-(outputOrder.get(attachedRuleKey(right))??Number.MAX_SAFE_INTEGER));
  const clean=(value:JsonSchema):JsonSchema=>{const next=structuredClone(value) as JsonSchema&{attachedRules?:unknown};delete next.attachedRules;if(next.required&&!next.required.length)delete next.required;for(const child of Object.values(next.properties??{}))clean(child);return next;};
  const documentation={...(schema.documentation?.description?{description:schema.documentation.description}:{}),...(Object.keys(properties).length?{properties}:{})};
  const projectedDocument=clean(projectionOnlyJsonMetadata(document,schema.document)),losslessDocument=losslessSourceRepresentation(schema.document,projectedDocument,canonical.onlyDefinedFields===true),{attachedRules:_attachedRules,documentation:_documentation,canonicalSchema:_canonicalSchema,...current}=schema;return{...current,document:losslessDocument,...(attachedRules.length?{attachedRules}:{}),...(Object.keys(documentation).length?{documentation}:{}),canonicalSchema:clone(canonical)} as unknown as T;
}
