import {addCanonicalProperty,createCanonicalSchema} from "./data-layer-canonical-schema.js";
import {migrateLegacyProfile} from "./canonical-schema/migration-plan.js";
export {hasLegacySchemaRepresentation,migrateLegacyProfile} from "./canonical-schema/migration-plan.js";
import {canonicalPredicateWithStableIds} from "./data-layer-canonical-predicate-identity.js";
import type {CanonicalDocumentation,CanonicalIdFactory,CanonicalPredicate,CanonicalPropertyNode,CanonicalPropertyType,CanonicalProvenance,CanonicalRule,CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";

export type CanonicalMigrationFacet="type"|"item type"|"presence"|"allowed values"|"rules"|"display text"|"description"|"comments"|"example"|"expected value"|"enforcement"|"target"|"override references";
export interface CanonicalMigrationChoice {id:string;label:string;value:unknown;}
export interface CanonicalMigrationConflict {id:string;path:string;facet:CanonicalMigrationFacet;message:string;propertyId:string;choices:CanonicalMigrationChoice[];}
export interface CanonicalMigrationPlan {profileId:string;document:CanonicalSchemaDocument;byPath:Record<string,string>;conflicts:CanonicalMigrationConflict[];legacyKeys:string[];}
export interface CanonicalLegacyProfile {id:string;name:string;requirements?:unknown;structuredSchema?:unknown;structuredDraft?:unknown;schemaConstraints?:unknown;}
const clone=<T>(value:T):T=>structuredClone(value);
const emptyDocumentation=():CanonicalDocumentation=>({displayText:"",description:"",comments:"",example:{method:"blank"}});
const typeOf=(value:unknown):CanonicalPropertyType=>value===null?"null":Array.isArray(value)?"array":typeof value==="number"?"number":typeof value==="boolean"?"boolean":typeof value==="object"?"object":"string";


export function resolveCanonicalMigrationConflict(plan:CanonicalMigrationPlan,conflictId:string,choiceId:string):CanonicalMigrationPlan{
  const conflict=plan.conflicts.find(({id})=>id===conflictId),choice=conflict?.choices.find(({id})=>id===choiceId);if(!conflict||!choice)throw new Error("Choose an available canonical migration resolution.");const next=clone(plan),target=next.conflicts.find(({id})=>id===conflictId)!,node=next.document.nodes[target.propertyId]!,value=clone(choice.value);
  if(target.facet==="type")node.type=value as CanonicalPropertyType;else if(target.facet==="item type")node.itemType=value as CanonicalPropertyType;else if(target.facet==="presence"){const presence=value as CanonicalPropertyNode["presence"],condition=canonicalPredicateWithStableIds(presence.condition,kind=>`${kind}:${target.propertyId}`);node.presence=condition?{...presence,condition}:{...presence};}else if(target.facet==="allowed values")node.allowedValues=(value as unknown[]).map((entry,index)=>({id:`migration-allowed:${encodeURIComponent(target.path)}:${index}`,value:entry}));else if(target.facet==="rules"){const replacement=value as CanonicalRule,condition=canonicalPredicateWithStableIds(replacement.condition,kind=>`${kind}:${replacement.id}`),nextRule:CanonicalRule=condition?{...replacement,condition}:{...replacement};node.rules=[...node.rules.filter(({id})=>id!==replacement.id),nextRule];}else if(target.facet==="display text")node.documentation.displayText=String(value);else if(target.facet==="description")node.documentation.description=String(value);else if(target.facet==="comments")node.documentation.comments=String(value);else if(target.facet==="example")node.documentation.example=value as CanonicalDocumentation["example"];else if(target.facet==="expected value")node.expectedValue=value;else if(target.facet==="enforcement")node.enforcement=value as NonNullable<CanonicalPropertyNode["enforcement"]>;else if(target.facet==="target")node.target=String(value);else node.overrideReferences=value as string[];
  next.conflicts=next.conflicts.filter(({id})=>id!==conflictId);return next;
}

export function canonicalSchemaFromJsonSchema(input:{id:string;contributorId:string;contributorName:string;sourceIdentity:string;sourceRevision:number;document:Record<string,unknown>;idFactory:CanonicalIdFactory}):CanonicalSchemaDocument{const profile:CanonicalLegacyProfile={id:input.contributorId,name:input.contributorName,structuredSchema:input.document},plan=migrateLegacyProfile(profile,{id:input.idFactory}),firstRootId=plan.document.rootIds[0],document={...plan.document,id:input.id,source:{identity:input.sourceIdentity,revision:input.sourceRevision,provenance:"saved-schema-library" as const},...(firstRootId?{selectedPropertyId:firstRootId}:{})};for(const node of Object.values(document.nodes)){const presenceCondition=canonicalPredicateWithStableIds(node.presence.condition,input.idFactory);node.presence=presenceCondition?{...node.presence,condition:presenceCondition}:{...node.presence};node.rules=node.rules.map((rule)=>{const condition=canonicalPredicateWithStableIds(rule.condition,input.idFactory);return condition?{...rule,condition}:{...rule};});node.provenance=node.provenance.map(()=>({source:"saved-schema",sourceId:input.sourceIdentity,revision:input.sourceRevision}));}return document;}

export function canonicalNodeFromValue(name:string,value:unknown,input:{id:CanonicalIdFactory;parentId?:string;order:number}):CanonicalPropertyNode{return{id:input.id("property"),name,...(input.parentId?{parentId:input.parentId}:{}),order:input.order,type:typeOf(value),presence:{mode:"optional"},allowedValues:[],rules:[],documentation:emptyDocumentation(),provenance:[{source:"created"}],overrideReferences:[]};}
