import {canonicalConstraints,canonicalPropertyPath,type CanonicalItemSchema,type CanonicalPredicate,type CanonicalPropertyNode,type CanonicalRule,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {LayerConstraint} from "./data-layer-layered-schema.js";
import type {ProjectState} from "./data-layer-specification-project.js";

export type ProfileInheritanceStartingPoint="everything"|"concepts"|"properties"|"empty";
export interface ProfileInheritanceRuleReplacement{sourceRuleId:string;propertyId:string;rule:CanonicalRule}
export interface ProfileInheritancePresenceReplacement{sourceRuleId:string;propertyId:string;presence:"required"|"optional"|"forbidden"}
export interface ProfileInheritanceSourceSnapshot{revision:number;effectivePropertyIds:string[];propertyPaths:Record<string,string>;ruleFingerprints:Record<string,string>;definitionFingerprints?:Record<string,string>;missingRuleDependencyKeys:string[]}
export interface ProfileInheritanceImpact{addedEffectivePropertyIds:string[];removedPropertyIds:string[];changedPaths:{propertyId:string;before:string;after:string}[];changedDefinitionPropertyIds:string[];changedRuleIds:string[];newMissingRuleDependencies:ProfileInheritanceSelection["missingRuleDependencies"];stale:boolean}
export interface ProfileInheritanceRecipe{
  id:string;profileId:string;targetId:string;startingPoint:ProfileInheritanceStartingPoint;sourceRevision:number;
  conceptSelections:string[];propertySelections:string[];excludedPropertyIds:string[];includedDependencyPropertyIds:string[];
  excludedRuleIds:string[];ruleReplacements:ProfileInheritanceRuleReplacement[];presenceReplacements:ProfileInheritancePresenceReplacement[];
  sourceSnapshot?:ProfileInheritanceSourceSnapshot;sourceImpact?:ProfileInheritanceImpact;
}
export interface ProfileInheritanceSelection{
  directPropertyIds:string[];structuralPropertyIds:string[];ruleDependencyPropertyIds:string[];effectivePropertyIds:string[];
  missingPropertyIds:string[];missingRuleDependencies:{propertyId:string;sourcePropertyId:string;sourceRuleId:string}[];
}
export interface SelectiveProfileContribution{constraints:LayerConstraint[];selection:ProfileInheritanceSelection;conflicts:{path:string;sourceRuleId:string;dependencyPropertyId:string}[]}
export interface ProfileInheritanceFilters{query:string;concept:string;type:string;required:"any"|"required"|"optional";selection:"any"|"selected"|"unselected"}

const clone=<T>(value:T):T=>structuredClone(value);
const orderedChildren=(document:CanonicalSchemaDocument,parentId?:string):CanonicalPropertyNode[]=>Object.values(document.nodes).filter((node)=>node.parentId===parentId).sort((left,right)=>left.order-right.order||left.id.localeCompare(right.id));
const orderedIds=(document:CanonicalSchemaDocument,parentId?:string):string[]=>orderedChildren(document,parentId).flatMap((node)=>[node.id,...orderedIds(document,node.id)]);
const predicatePropertyIds=(predicate:CanonicalPredicate|undefined):string[]=>predicate?predicate.kind==="predicate"?[predicate.propertyId]:predicate.children.flatMap(predicatePropertyIds):[];
const stableUnique=(values:readonly string[]):string[]=>[...new Set(values)];
const structuralItemShape=(item:CanonicalItemSchema):CanonicalItemSchema=>({id:item.id,...(item.type?{type:item.type}:{}),...(item.items?{items:structuralItemShape(item.items)}:{})});
const structuralDefinitionShape=(node:CanonicalPropertyNode)=>({type:node.type,...(node.itemType?{itemType:node.itemType}:{}),...(node.itemSchema?{itemSchema:structuralItemShape(node.itemSchema)}:{})});
const dependencyRulesFor=(node:CanonicalPropertyNode,recipe:ProfileInheritanceRecipe):{id:string;condition?:CanonicalPredicate}[]=>{
  const presenceId=`presence:${node.id}`,presence=recipe.presenceReplacements.some(({sourceRuleId})=>sourceRuleId===presenceId)||recipe.excludedRuleIds.includes(presenceId)?[]:node.presence.condition?[{id:presenceId,condition:node.presence.condition}]:[];
  const rules=node.rules.flatMap((rule)=>{if(rule.enforcement==="invariant")return[{id:rule.id,...(rule.condition?{condition:rule.condition}:{})}];const replacements=recipe.ruleReplacements.filter(({sourceRuleId,propertyId})=>sourceRuleId===rule.id&&propertyId===node.id);if(replacements.length)return replacements.map(({rule:replacement})=>({id:rule.id,...(replacement.condition?{condition:replacement.condition}:{})}));if(recipe.excludedRuleIds.includes(rule.id))return[];return[{id:rule.id,...(rule.condition?{condition:rule.condition}:{})}];});
  return[...presence,...rules];
};
const effectiveRulesFor=(node:CanonicalPropertyNode,recipe:ProfileInheritanceRecipe):CanonicalRule[]=>node.rules.flatMap((rule)=>{if(rule.enforcement==="invariant")return[clone(rule)];const replacements=recipe.ruleReplacements.filter(({sourceRuleId,propertyId})=>sourceRuleId===rule.id&&propertyId===node.id);if(replacements.length)return replacements.map(({rule:replacement})=>clone(replacement));return recipe.excludedRuleIds.includes(rule.id)?[]:[clone(rule)];});
const applyDerivedRuleFacets=(constraint:LayerConstraint,rules:readonly CanonicalRule[]):void=>{delete constraint.patterns;delete constraint.minimum;delete constraint.maximum;delete constraint.minItems;delete constraint.maxItems;const ordinary=rules.filter(({enabled,condition,arrayScope})=>enabled!==false&&!condition&&!arrayScope?.boundaries.length),patterns=ordinary.flatMap(({kind,pattern})=>kind==="pattern"&&pattern?[pattern]:[]),minimums=ordinary.flatMap(({kind,minimum})=>kind==="range"&&minimum!==undefined?[minimum]:[]),maximums=ordinary.flatMap(({kind,maximum})=>kind==="range"&&maximum!==undefined?[maximum]:[]),minItems=ordinary.flatMap(({kind,minItems})=>kind==="cardinality"&&minItems!==undefined?[minItems]:[]),maxItems=ordinary.flatMap(({kind,maxItems})=>kind==="cardinality"&&maxItems!==undefined?[maxItems]:[]);if(patterns.length)constraint.patterns=stableUnique(patterns);if(minimums.length)constraint.minimum=Math.max(...minimums);if(maximums.length)constraint.maximum=Math.min(...maximums);if(minItems.length)constraint.minItems=Math.max(...minItems);if(maxItems.length)constraint.maxItems=Math.min(...maxItems);};

export function createProfileInheritanceRecipe(input:{id:string;profileId:string;targetId:string;startingPoint:ProfileInheritanceStartingPoint;sourceRevision:number}):ProfileInheritanceRecipe{
  return{...input,conceptSelections:[],propertySelections:[],excludedPropertyIds:[],includedDependencyPropertyIds:[],excludedRuleIds:[],ruleReplacements:[],presenceReplacements:[]};
}

export function selectProfileInheritanceBranch(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe,propertyId:string):ProfileInheritanceRecipe{
  if(!document.nodes[propertyId])return clone(recipe);return{...clone(recipe),propertySelections:stableUnique([...recipe.propertySelections,propertyId,...orderedIds(document,propertyId)])};
}

export function profileInheritanceSelection(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):ProfileInheritanceSelection{
  const order=orderedIds(document),excluded=new Set(recipe.excludedPropertyIds),missingPropertyIds=recipe.propertySelections.filter((id)=>!document.nodes[id]),direct=new Set<string>();
  for(const id of order){const node=document.nodes[id]!;if(excluded.has(id))continue;if(recipe.startingPoint==="everything"||recipe.propertySelections.includes(id)||Boolean(node.concept&&recipe.conceptSelections.includes(node.concept)))direct.add(id);}
  const dependencyIds=new Set<string>(),missingRuleDependencies:ProfileInheritanceSelection["missingRuleDependencies"]=[],queued=[...direct],processed=new Set<string>(),missingKeys=new Set<string>();
  while(queued.length){const sourcePropertyId=queued.shift()!;if(processed.has(sourcePropertyId))continue;processed.add(sourcePropertyId);const node=document.nodes[sourcePropertyId];if(!node)continue;for(const rule of dependencyRulesFor(node,recipe))for(const propertyId of predicatePropertyIds(rule.condition)){if(direct.has(propertyId)||dependencyIds.has(propertyId))continue;if(recipe.includedDependencyPropertyIds.includes(propertyId)&&document.nodes[propertyId]&&!excluded.has(propertyId)){dependencyIds.add(propertyId);queued.push(propertyId);continue;}const key=`${sourcePropertyId}\0${rule.id}\0${propertyId}`;if(!missingKeys.has(key)){missingKeys.add(key);missingRuleDependencies.push({propertyId,sourcePropertyId,sourceRuleId:rule.id});}}}
  const selected=new Set([...direct,...dependencyIds]),structural=new Set<string>();for(const id of selected){let parent=document.nodes[id]?.parentId;while(parent){if(!selected.has(parent))structural.add(parent);parent=document.nodes[parent]?.parentId;}}
  const inOrder=(ids:Set<string>)=>order.filter((id)=>ids.has(id));return{directPropertyIds:inOrder(direct),structuralPropertyIds:inOrder(structural),ruleDependencyPropertyIds:inOrder(dependencyIds),effectivePropertyIds:order.filter((id)=>direct.has(id)||dependencyIds.has(id)||structural.has(id)),missingPropertyIds:stableUnique(missingPropertyIds),missingRuleDependencies};
}

export function selectiveProfileContribution(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):SelectiveProfileContribution{
  const selection=profileInheritanceSelection(document,recipe),direct=new Set(selection.directPropertyIds),dependencies=new Set(selection.ruleDependencyPropertyIds),structural=new Set(selection.structuralPropertyIds),byId=new Map(canonicalConstraints(document).map((constraint)=>[constraint.definitionId!,constraint]));
  const constraints=selection.effectivePropertyIds.flatMap((propertyId)=>{const source=byId.get(propertyId),node=document.nodes[propertyId];if(!source||!node)return[];if(structural.has(propertyId))return[{path:source.path,...structuralDefinitionShape(node),definitionId:propertyId,selectionReason:"structural"} as LayerConstraint];const constraint=clone(source),nextRules=effectiveRulesFor(node,recipe);constraint.rules=nextRules as unknown as Record<string,unknown>[];applyDerivedRuleFacets(constraint,nextRules);
    const presenceId=`presence:${propertyId}`,presenceReplacement=recipe.presenceReplacements.find(({sourceRuleId,propertyId:replacementPropertyId})=>sourceRuleId===presenceId&&replacementPropertyId===propertyId);if(recipe.excludedRuleIds.includes(presenceId)){delete constraint.presence;delete constraint.condition;}if(presenceReplacement){constraint.presence=presenceReplacement.presence;delete constraint.condition;}
    return[{...constraint,selectionReason:direct.has(propertyId)?"direct":dependencies.has(propertyId)?"rule-dependency":"structural"} as LayerConstraint];});
  return{constraints,selection,conflicts:selection.missingRuleDependencies.map(({sourcePropertyId,sourceRuleId,propertyId})=>({path:canonicalPropertyPath(document,sourcePropertyId),sourceRuleId,dependencyPropertyId:propertyId}))};
}

export function profileInheritanceSummary(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe){const selection=profileInheritanceSelection(document,recipe);return{direct:selection.directPropertyIds.length,structural:selection.structuralPropertyIds.length,ruleDependencies:selection.ruleDependencyPropertyIds.length,missingDependencies:selection.missingRuleDependencies.length,conflicts:selection.missingRuleDependencies.length,effective:selection.effectivePropertyIds.length,synchronizedConcepts:recipe.conceptSelections.length,fixedProperties:recipe.propertySelections.filter((id)=>document.nodes[id]&&!recipe.excludedPropertyIds.includes(id)).length,exclusions:recipe.excludedPropertyIds.length,ruleOverrides:recipe.excludedRuleIds.length+recipe.ruleReplacements.length+recipe.presenceReplacements.length,missingSelections:selection.missingPropertyIds.length};}

export function searchProfileInheritanceProperties(document:CanonicalSchemaDocument,filters:ProfileInheritanceFilters,recipe:ProfileInheritanceRecipe):CanonicalPropertyNode[]{const selected=new Set(profileInheritanceSelection(document,recipe).directPropertyIds),query=filters.query.trim().toLocaleLowerCase();return orderedIds(document).map((id)=>document.nodes[id]!).filter((node)=>{const text=[node.name,canonicalPropertyPath(document,node.id),node.documentation.displayText,node.documentation.description,node.documentation.comments,node.documentation.example.value].map((value)=>String(value??"").toLocaleLowerCase()).join(" "),required=node.presence.mode.startsWith("required"),isSelected=selected.has(node.id);return(!query||text.includes(query))&&(filters.concept==="all"||node.concept===filters.concept)&&(filters.type==="all"||node.type===filters.type)&&(filters.required==="any"||(filters.required==="required"?required:!required))&&(filters.selection==="any"||(filters.selection==="selected"?isSelected:!isSelected));});}

export function copyProfileInheritanceRecipe(recipe:ProfileInheritanceRecipe,input:{id:string;targetId:string}):ProfileInheritanceRecipe{return{...clone(recipe),...input};}

const missingDependencyKey=({propertyId,sourcePropertyId,sourceRuleId}:ProfileInheritanceSelection["missingRuleDependencies"][number]):string=>`${sourcePropertyId}\0${sourceRuleId}\0${propertyId}`;
const sourceRuleValues=(document:CanonicalSchemaDocument,propertyIds:readonly string[]):Record<string,unknown>=>Object.fromEntries(propertyIds.flatMap((propertyId)=>{const node=document.nodes[propertyId];if(!node)return[];return[...(node.presence.condition?[[`presence:${propertyId}`,node.presence] as const]:[]),...node.rules.map((rule)=>[rule.id,rule] as const)];}));
const definitionDigest=(value:unknown):string=>{const text=JSON.stringify(value);let left=0x811c9dc5,right=0x9e3779b9;for(let index=0;index<text.length;index+=1){const code=text.charCodeAt(index);left=Math.imul(left^code,0x01000193);right=Math.imul(right^code,0x85ebca6b);}return`digest-v1:${(left>>>0).toString(16).padStart(8,"0")}${(right>>>0).toString(16).padStart(8,"0")}`;};
const sourceRuleFingerprints=(document:CanonicalSchemaDocument,propertyIds:readonly string[]):Record<string,string>=>Object.fromEntries(Object.entries(sourceRuleValues(document,propertyIds)).map(([id,value])=>[id,definitionDigest(value)]));
const sourceDefinitionValues=(document:CanonicalSchemaDocument,selection:ProfileInheritanceSelection):Record<string,unknown>=>{const structural=new Set(selection.structuralPropertyIds);return Object.fromEntries(selection.effectivePropertyIds.flatMap((propertyId)=>{const node=document.nodes[propertyId];if(!node)return[];if(structural.has(propertyId))return[[propertyId,structuralDefinitionShape(node)]];const{id:_,name:__,parentId:___,order:____,rules:_____,provenance:______,structureOwned:_______,localDefinitionFacets:________,inheritedDefinition:_________,...definitionFacets}=node;return[[propertyId,definitionFacets]];}));};
const sourceDefinitionFingerprints=(document:CanonicalSchemaDocument,selection:ProfileInheritanceSelection):Record<string,string>=>Object.fromEntries(Object.entries(sourceDefinitionValues(document,selection)).map(([id,value])=>[id,definitionDigest(value)]));
export function profileInheritanceSourceSnapshot(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):ProfileInheritanceSourceSnapshot{const selection=profileInheritanceSelection(document,recipe),ruleBearingPropertyIds=stableUnique([...selection.directPropertyIds,...selection.ruleDependencyPropertyIds]);return{revision:document.revision,effectivePropertyIds:[...selection.effectivePropertyIds],propertyPaths:Object.fromEntries(selection.effectivePropertyIds.flatMap((propertyId)=>document.nodes[propertyId]?[[propertyId,canonicalPropertyPath(document,propertyId)]]:[])),ruleFingerprints:sourceRuleFingerprints(document,ruleBearingPropertyIds),definitionFingerprints:sourceDefinitionFingerprints(document,selection),missingRuleDependencyKeys:selection.missingRuleDependencies.map(missingDependencyKey)};}
export function profileInheritanceRecipeApplied(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):ProfileInheritanceRecipe{const applied={...clone(recipe),sourceRevision:document.revision,sourceSnapshot:profileInheritanceSourceSnapshot(document,recipe)};delete applied.sourceImpact;return applied;}
export function profileInheritanceCurrentImpact(document:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):ProfileInheritanceImpact{const snapshot=recipe.sourceSnapshot,selection=profileInheritanceSelection(document,recipe);if(!snapshot)return{addedEffectivePropertyIds:[],removedPropertyIds:selection.missingPropertyIds,changedPaths:[],changedDefinitionPropertyIds:[],changedRuleIds:[],newMissingRuleDependencies:selection.missingRuleDependencies,stale:document.revision!==recipe.sourceRevision||Boolean(selection.missingPropertyIds.length||selection.missingRuleDependencies.length)};const effective=new Set(selection.effectivePropertyIds),prior=new Set(snapshot.effectivePropertyIds),addedEffectivePropertyIds=selection.effectivePropertyIds.filter((id)=>!prior.has(id)),removedPropertyIds=snapshot.effectivePropertyIds.filter((id)=>!effective.has(id)),changedPaths=snapshot.effectivePropertyIds.flatMap((propertyId)=>{const before=snapshot.propertyPaths[propertyId],node=document.nodes[propertyId];if(!before||!node)return[];const after=canonicalPropertyPath(document,propertyId);return before===after?[]:[{propertyId,before,after}];}),sameEffectiveSet=!addedEffectivePropertyIds.length&&!removedPropertyIds.length,reorderedPropertyIds=sameEffectiveSet?selection.effectivePropertyIds.filter((id,index)=>snapshot.effectivePropertyIds[index]!==id):[],currentDefinitions=sourceDefinitionFingerprints(document,selection),fingerprintedDefinitionChanges=snapshot.definitionFingerprints?stableUnique([...Object.keys(snapshot.definitionFingerprints),...Object.keys(currentDefinitions)]).filter((id)=>snapshot.definitionFingerprints?.[id]!==currentDefinitions[id]&&prior.has(id)&&effective.has(id)):document.revision!==snapshot.revision?selection.effectivePropertyIds.filter((id)=>prior.has(id)):[],changedDefinitionPropertyIds=stableUnique([...fingerprintedDefinitionChanges,...reorderedPropertyIds]),ruleBearingPropertyIds=stableUnique([...selection.directPropertyIds,...selection.ruleDependencyPropertyIds]),currentValues=sourceRuleValues(document,ruleBearingPropertyIds),currentRules=sourceRuleFingerprints(document,ruleBearingPropertyIds),changedRuleIds=stableUnique([...Object.keys(snapshot.ruleFingerprints),...Object.keys(currentRules)]).filter((id)=>{const before=snapshot.ruleFingerprints[id],after=currentRules[id];if(before===after)return false;return currentValues[id]===undefined||before!==JSON.stringify(currentValues[id]);}),knownMissing=new Set(snapshot.missingRuleDependencyKeys),newMissingRuleDependencies=selection.missingRuleDependencies.filter((dependency)=>!knownMissing.has(missingDependencyKey(dependency))),stale=Boolean(addedEffectivePropertyIds.length||removedPropertyIds.length||changedPaths.length||changedDefinitionPropertyIds.length||changedRuleIds.length||newMissingRuleDependencies.length);return{addedEffectivePropertyIds,removedPropertyIds,changedPaths,changedDefinitionPropertyIds,changedRuleIds,newMissingRuleDependencies,stale};}
export function markProfileInheritanceTargetStale<T extends Record<string,unknown>>(target:T,profileId:string,before:CanonicalSchemaDocument,after:CanonicalSchemaDocument):T{const recipes=((target.profileInheritanceRecipes as ProfileInheritanceRecipe[]|undefined)??[]),affected=recipes.some((recipe)=>recipe.profileId===profileId);if(!affected)return target;const nextRecipes=recipes.map((recipe)=>{if(recipe.profileId!==profileId)return recipe;const impact=recipe.sourceSnapshot?profileInheritanceCurrentImpact(after,recipe):profileInheritanceImpact(before,after,recipe);return{...clone(recipe),sourceImpact:impact};}),stale=nextRecipes.some((recipe)=>recipe.profileId===profileId&&recipe.sourceImpact?.stale);return{...target,profileInheritanceRecipes:nextRecipes,...(stale?{compiledTargetsStale:true,validationStale:true,testCasesStale:true,documentationStale:true,exportStale:true}:{})};}
export function markProfileInheritanceConsumersForSourceChange(project:ProjectState["project"],profileId:string,before:CanonicalSchemaDocument,after:CanonicalSchemaDocument):ProjectState["project"]{return{...project,collections:{...project.collections,pages:project.collections.pages.map((entity)=>markProfileInheritanceTargetStale(entity,profileId,before,after)),pageGroups:project.collections.pageGroups.map((entity)=>markProfileInheritanceTargetStale(entity,profileId,before,after)),events:project.collections.events.map((entity)=>markProfileInheritanceTargetStale(entity,profileId,before,after))}};}
export function profileInheritanceImpact(before:CanonicalSchemaDocument,after:CanonicalSchemaDocument,recipe:ProfileInheritanceRecipe):ProfileInheritanceImpact{const priorRecipe=profileInheritanceRecipeApplied(before,recipe),impact=profileInheritanceCurrentImpact(after,priorRecipe),referenced=stableUnique([...recipe.propertySelections,...recipe.excludedPropertyIds,...recipe.includedDependencyPropertyIds]),removedPinned=referenced.filter((id)=>before.nodes[id]&&!after.nodes[id]);return{...impact,removedPropertyIds:stableUnique([...impact.removedPropertyIds,...removedPinned])};}
