import {openIndexedDbProjectRepository,type DurableDraftCommand,type DurableProjectRepository,type DurableStorageDiagnostics} from "./data-layer-durable-project-repository.js";

interface DurableRecoveryInput{kind?:"project"|"saved-schema";projectId?:string;projectName:string;command:Pick<DurableDraftCommand,"label">;retry:()=>Promise<void>;exportUnsaved:()=>void;originControl?:HTMLElement;}
export interface DurableProjectRepositoryUi{repository:DurableProjectRepository;refresh():Promise<void>;reportSaveFailure(input:DurableRecoveryInput,error:unknown):Promise<void>;}

const q=<T extends Element>(root:ParentNode,selector:string):T=>{const element=root.querySelector<T>(selector);if(!element)throw new Error(`Missing durable repository control ${selector}.`);return element;};
const text=(error:unknown)=>error instanceof Error?error.message:String(error);
const humanBytes=(value:number)=>value<1024?`${value} B`:`${(value/1024).toFixed(1)} KiB`;

export function installDurableRepositoryStartupFailure(root:Document,error:unknown):void{
  const message=`Durable project storage unavailable: ${text(error)}`;
  const projects=q<HTMLElement>(root,"#data-layer-panel-projects"),status=q<HTMLOutputElement>(root,"#durable-repository-status"),libraryStatus=q<HTMLOutputElement>(root,"#project-library-status"),open=q<HTMLButtonElement>(root,"#open-storage-recovery"),dialog=q<HTMLDialogElement>(root,"#durable-storage-recovery"),close=q<HTMLButtonElement>(root,"#close-storage-recovery"),result=q<HTMLOutputElement>(root,"#durable-recovery-result"),explanation=q<HTMLElement>(root,"#durable-storage-explanation");
  root.querySelectorAll<HTMLElement>('[role="tabpanel"]').forEach((panel)=>{panel.hidden=panel!==projects;});
  const tab=root.querySelector<HTMLElement>("#data-layer-view-projects");if(tab){tab.setAttribute("aria-selected","true");tab.tabIndex=0;}
  projects.querySelectorAll<HTMLButtonElement|HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("button,input,select,textarea").forEach((control)=>{control.disabled=true;});
  status.textContent=message;libraryStatus.textContent=`Projects are unavailable. ${message}`;explanation.textContent=`${message}. No project was loaded and Web Storage was not used as canonical fallback.`;result.textContent=message;
  open.disabled=false;close.disabled=false;open.addEventListener("click",()=>{dialog.showModal();q<HTMLElement>(dialog,"#durable-storage-recovery-title").focus();});close.addEventListener("click",()=>{dialog.close();open.focus();});
}

function renderDiagnostics(root:ParentNode,diagnostics:DurableStorageDiagnostics):void{
  q<HTMLElement>(root,"#durable-last-saved").textContent=diagnostics.lastSavedAt;
  q<HTMLElement>(root,"#durable-published-revision").textContent=String(diagnostics.publishedRevision);
  q<HTMLElement>(root,"#durable-unsaved-command").textContent=diagnostics.unsavedCommand??"None";
  q<HTMLElement>(root,"#durable-project-size").textContent=humanBytes(diagnostics.projectEntityBytes);
  q<HTMLElement>(root,"#durable-release-size").textContent=humanBytes(diagnostics.releaseBytes);
  q<HTMLElement>(root,"#durable-fixture-size").textContent=humanBytes(diagnostics.fixtureBytes);
  q<HTMLElement>(root,"#durable-migration-backup-size").textContent=humanBytes(diagnostics.migrationBackupBytes);
  q<HTMLElement>(root,"#durable-browser-estimate").textContent=diagnostics.browserEstimate?`${humanBytes(diagnostics.browserEstimate.usage)} used of ${humanBytes(diagnostics.browserEstimate.quota)}`:"Browser estimate unavailable";
  q<HTMLElement>(root,"#durable-storage-explanation").textContent=diagnostics.explanation;
}

export async function mountDurableProjectRepositoryUi(root:ParentNode,factory:IDBFactory=globalThis.indexedDB,existing?:DurableProjectRepository):Promise<DurableProjectRepositoryUi>{
  const repository=existing??await openIndexedDbProjectRepository(factory),status=q<HTMLOutputElement>(root,"#durable-repository-status"),open=q<HTMLButtonElement>(root,"#open-storage-recovery"),dialog=q<HTMLDialogElement>(root,"#durable-storage-recovery"),close=q<HTMLButtonElement>(root,"#close-storage-recovery"),retry=q<HTMLButtonElement>(root,"#retry-durable-save"),exportUnsaved=q<HTMLButtonElement>(root,"#export-unsaved-draft"),exportBackup=q<HTMLButtonElement>(root,"#export-repository-backup"),diagnose=q<HTMLButtonElement>(root,"#open-storage-diagnostics"),reviewDeleteBackup=q<HTMLButtonElement>(root,"#review-delete-migration-backup"),deleteBackupReview=q<HTMLElement>(root,"#delete-migration-backup-review"),cancelDeleteBackup=q<HTMLButtonElement>(root,"#cancel-delete-migration-backup"),confirmDeleteBackup=q<HTMLButtonElement>(root,"#confirm-delete-migration-backup"),result=q<HTMLOutputElement>(root,"#durable-recovery-result");let failure:DurableRecoveryInput|undefined,returnFocus:HTMLElement|undefined;
  const estimate=async()=>{const value=await navigator.storage?.estimate?.();return typeof value?.usage==="number"&&typeof value?.quota==="number"?{usage:value.usage,quota:value.quota}:undefined;};
  const refresh=async(includeDiagnostics=false)=>{const projects=await repository.listProjectMetadata(),active=projects.find(({active})=>active),backup=includeDiagnostics?await repository.migrationBackup():undefined;if(!failure)status.textContent=`Durable project storage ready · ${projects.length} project${projects.length===1?"":"s"}${active?` · Active ${active.name}`:""}`;open.disabled=!active&&!failure;reviewDeleteBackup.disabled=backup?backup.sources.length===0:false;if(active&&includeDiagnostics)renderDiagnostics(root,await repository.storageDiagnostics(active.projectId,await estimate(),failure?.command.label));};
  const show=async(origin:HTMLElement)=>{returnFocus=origin;await refresh(true);dialog.showModal();q<HTMLElement>(dialog,"#durable-storage-recovery-title").focus();};
  open.addEventListener("click",()=>void show(open));close.addEventListener("click",()=>{dialog.close();returnFocus?.focus();});
  diagnose.addEventListener("click",async()=>{await refresh(true);result.textContent="Storage diagnostics refreshed without deleting project data.";result.focus();});
  retry.addEventListener("click",async()=>{const activeFailure=failure;if(!activeFailure)return;try{await activeFailure.retry();result.textContent=activeFailure.kind==="saved-schema"?`${activeFailure.command.label} committed to the Saved Schema Library.`:`${activeFailure.command.label} saved. Project switching and publication are available.`;failure=undefined;retry.disabled=true;exportUnsaved.disabled=true;await refresh(true);}catch(error){result.textContent=activeFailure.kind==="saved-schema"?`Retry was not committed; the durable Saved Schema Library remains unchanged. ${text(error)}`:`Retry was not committed; the last Saved Draft remains unchanged. ${text(error)}`;}result.focus();});
  exportUnsaved.addEventListener("click",()=>{failure?.exportUnsaved();result.textContent=failure?failure.kind==="saved-schema"?`Exported the exact unsaved schema batch for ${failure.projectName}.`:`Exported unsaved Draft for ${failure.projectName}.`:"There is no unsaved operation to export.";result.focus();});
  exportBackup.addEventListener("click",async()=>{const bundle=await repository.exportRepositoryRecoveryBundle(),serialized=JSON.stringify(bundle),link=document.createElement("a");link.href=URL.createObjectURL(new Blob([serialized],{type:"application/json"}));link.download="durable-repository-recovery.json";link.click();URL.revokeObjectURL(link.href);result.textContent=`Exported parseable recovery data for ${bundle.projects instanceof Array?bundle.projects.length:0} projects, all saved schemas, immutable revisions, fixtures, releases, and migration sources.`;result.focus();});
  reviewDeleteBackup.addEventListener("click",()=>{deleteBackupReview.hidden=false;q<HTMLElement>(deleteBackupReview,"#delete-migration-backup-title").focus();});
  cancelDeleteBackup.addEventListener("click",()=>{deleteBackupReview.hidden=true;result.textContent="Cancelled. The retained legacy migration backup remains available; current projects are unchanged.";result.focus();});
  confirmDeleteBackup.addEventListener("click",async()=>{try{const deleted=await repository.deleteMigrationBackup({backupId:"legacy-v1",label:"Delete retained legacy migration backup"});deleteBackupReview.hidden=true;result.textContent=deleted?"Deleted only the retained legacy migration backup. Current projects, saved schemas, fixtures, releases, and Published revisions are unchanged.":"No retained legacy migration backup was present; current projects are unchanged.";await refresh(true);}catch(error){deleteBackupReview.hidden=false;result.textContent=`Migration backup deletion was not committed. The retained backup and current projects remain unchanged. ${text(error)}`;}result.focus();});
  const ui:DurableProjectRepositoryUi={repository,refresh,async reportSaveFailure(input,error){failure=input;const schema=input.kind==="saved-schema";status.textContent=schema?`Save failed for ${input.projectName}: ${input.command.label}. The durable Saved Schema Library is unchanged. ${text(error)}`:`Save failed for ${input.projectName}: ${input.command.label}. Last Saved Draft is unchanged. ${text(error)}`;retry.disabled=false;exportUnsaved.disabled=false;if(input.projectId)renderDiagnostics(root,await repository.storageDiagnostics(input.projectId,await estimate(),input.command.label));await show(input.originControl??status);q<HTMLElement>(dialog,"#durable-recovery-result").textContent=schema?`${input.command.label} was not committed. Retry the exact batch or export it for recovery.`:`${input.command.label} was not committed. Retry or export the unsaved Draft.`;}};repository.subscribe(()=>{void refresh();});repository.subscribeProjectMetadata(()=>{void refresh();});repository.subscribeActiveContext(()=>{void refresh();});await refresh();return ui;
}
