import type {CanonicalPropertyNode,CanonicalSchemaDocument,CanonicalSchemaInput} from "./data-layer-canonical-schema.js";

const clone=<T>(value:T):T=>structuredClone(value);
const orderWithin=(document:CanonicalSchemaDocument,parentId?:string):CanonicalPropertyNode[]=>Object.values(document.nodes).filter((node)=>node.parentId===parentId).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));
const orderedIds=(document:CanonicalSchemaDocument,parentId?:string):string[]=>orderWithin(document,parentId).flatMap((node)=>[node.id,...orderedIds(document,node.id)]);
export function createCanonicalSchema(input:CanonicalSchemaInput):CanonicalSchemaDocument{return{id:input.id,revision:0,state:"Draft",contributorId:input.contributorId,contributorName:input.contributorName,rootIds:[],nodes:{},view:"tree",changes:[],...(input.source?{source:clone(input.source)}:{})};}
const propertySegments=(document:CanonicalSchemaDocument,propertyId:string):{name:string;arrayBoundaries:number}[]=>{const parts:{name:string;arrayBoundaries:number}[]=[];let node=document.nodes[propertyId],guard=0;while(node&&guard<Object.keys(document.nodes).length+1){let arrayBoundaries=node.type==="array"?1:0,item=node.itemSchema;while(item?.type==="array"){arrayBoundaries+=1;item=item.items;}parts.unshift({name:node.name,arrayBoundaries});node=node.parentId?document.nodes[node.parentId]:undefined;guard+=1;}if(!parts.length)throw new Error(`Canonical property ${propertyId} is unavailable.`);return parts;};
export function canonicalPropertyPath(document:CanonicalSchemaDocument,propertyId:string):string{const parts=propertySegments(document,propertyId),segments=parts.flatMap(({name,arrayBoundaries},index)=>[name.replaceAll("~","~0").replaceAll("/","~1"),...(index<parts.length-1?Array.from({length:arrayBoundaries},()=>"*"):[])]);return`/${segments.join("/")}`;}
export function canonicalFriendlyPropertyPath(document:CanonicalSchemaDocument,propertyId:string):string{return propertySegments(document,propertyId).map(({name,arrayBoundaries},index,parts)=>`${name}${index<parts.length-1?"[]".repeat(arrayBoundaries):""}`).join(".");}
export function canonicalTableRows(document:CanonicalSchemaDocument){return orderedIds(document).map((id)=>{const node=document.nodes[id]!;let depth=0,parent=node.parentId;while(parent){depth+=1;parent=document.nodes[parent]?.parentId;}return{id,node,path:canonicalPropertyPath(document,id),friendlyPath:canonicalFriendlyPropertyPath(document,id),depth,selected:id===document.selectedPropertyId,condition:node.presence.condition,validationState:"valid" as const};});}
export function canonicalConceptIndex(documents:readonly CanonicalSchemaDocument[]):string[]{const values=new Map<string,string>();for(const document of documents)for(const {concept} of Object.values(document.nodes)){const display=concept?.trim();if(display&&!values.has(display.toLocaleLowerCase()))values.set(display.toLocaleLowerCase(),display);}return[...values.values()].sort((left,right)=>left.localeCompare(right,undefined,{sensitivity:"base"}));}
export function canonicalConceptSortedRows(document:CanonicalSchemaDocument):ReturnType<typeof canonicalTableRows>{return canonicalTableRows(document).sort((left,right)=>{const leftConcept=left.node.concept?.trim(),rightConcept=right.node.concept?.trim();if(Boolean(leftConcept)!==Boolean(rightConcept))return leftConcept?-1:1;return(leftConcept??"").localeCompare(rightConcept??"",undefined,{sensitivity:"base"})||left.path.localeCompare(right.path);});}
export {canonicalJsonSchemaDocument} from "./data-layer-canonical-array-items.js";
