import {addCanonicalProperty,createCanonicalSchema} from "./data-layer-canonical-schema.js";
import type {CanonicalDocumentation,CanonicalIdFactory,CanonicalPredicate,CanonicalPropertyNode,CanonicalPropertyType,CanonicalProvenance,CanonicalRule,CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";

const clone=<T>(value:T):T=>structuredClone(value);
const emptyDocumentation=():CanonicalDocumentation=>({displayText:"",description:"",comments:"",example:{method:"blank"}});
const supported=new Set<CanonicalPropertyType>(["string","number","integer","boolean","null","object","array"]);
const typeOf=(value:unknown):CanonicalPropertyType=>value===null?"null":Array.isArray(value)?"array":typeof value==="number"?"number":typeof value==="boolean"?"boolean":typeof value==="object"?"object":"string";
function definitionAtPath(definitions:Map<string,{definition:Record<string,unknown>;provenance:CanonicalProvenance}[]>,path:string,definition:Record<string,unknown>,provenance:CanonicalProvenance){const values=definitions.get(path)??[];values.push({definition,provenance});definitions.set(path,values);}
function collectStructured(definitions:Map<string,{definition:Record<string,unknown>;provenance:CanonicalProvenance}[]>,document:Record<string,unknown>,source:CanonicalProvenance["source"],parent=""){const properties=document.properties as Record<string,Record<string,unknown>>|undefined,required=new Set((document.required as string[]|undefined)??[]);for(const[name,definition]of Object.entries(properties??{})){const path=`${parent}/${name}`,normalized=required.has(name)?{...definition,required:true}:definition;definitionAtPath(definitions,path,normalized,{source});if(definition.type==="object"||definition.properties)collectStructured(definitions,definition,source,path);}}
export type CanonicalMigrationFacet="type"|"item type"|"presence"|"allowed values"|"rules"|"display text"|"description"|"comments"|"example"|"expected value"|"enforcement"|"target"|"override references";
export interface CanonicalMigrationChoice {id:string;label:string;value:unknown;}
export interface CanonicalMigrationConflict {id:string;path:string;facet:CanonicalMigrationFacet;message:string;propertyId:string;choices:CanonicalMigrationChoice[];}
export interface CanonicalMigrationPlan {profileId:string;document:CanonicalSchemaDocument;byPath:Record<string,string>;conflicts:CanonicalMigrationConflict[];legacyKeys:string[];}
export interface CanonicalLegacyProfile {id:string;name:string;requirements?:unknown;structuredSchema?:unknown;structuredDraft?:unknown;schemaConstraints?:unknown;}
const semanticallyPopulated=(value:unknown):boolean=>{if(value===undefined||value===null)return false;if(Array.isArray(value))return value.some(semanticallyPopulated);if(typeof value==="string")return value.trim().length>0;if(typeof value!=="object")return true;return Object.entries(value as Record<string,unknown>).some(([key,entry])=>{if(key==="type"&&entry==="object")return false;if(key==="properties"&&entry&&typeof entry==="object"&&!Array.isArray(entry))return Object.keys(entry as Record<string,unknown>).length>0;return semanticallyPopulated(entry);});};
export function hasLegacySchemaRepresentation(profile:CanonicalLegacyProfile):boolean{return semanticallyPopulated(profile.requirements)||semanticallyPopulated(profile.structuredSchema)||semanticallyPopulated((profile.structuredDraft as {document?:unknown}|undefined)?.document)||semanticallyPopulated(profile.schemaConstraints);}
export function migrateLegacyProfile(profile:CanonicalLegacyProfile,options:{id:CanonicalIdFactory}):CanonicalMigrationPlan{
  const definitions=new Map<string,{definition:Record<string,unknown>;provenance:CanonicalProvenance}[]>();
  for(const requirement of (profile.requirements as Record<string,unknown>[]|undefined)??[])definitionAtPath(definitions,String(requirement.path),requirement,{source:"requirements"});
  const structured=profile.structuredSchema as Record<string,unknown>|undefined;if(structured)collectStructured(definitions,structured,"structured-schema");
  const draft=(profile.structuredDraft as {document?:Record<string,unknown>}|undefined)?.document;if(draft)collectStructured(definitions,draft,"structured-draft");
  for(const constraint of (profile.schemaConstraints as Record<string,unknown>[]|undefined)??[])definitionAtPath(definitions,String(constraint.path),constraint,{source:"path-constraint"});
  let document=createCanonicalSchema({id:options.id("canonical-schema"),contributorId:profile.id,contributorName:profile.name}),revision=0;const byPath:Record<string,string>={},conflicts:CanonicalMigrationPlan["conflicts"]=[];
  const same=(left:unknown,right:unknown)=>JSON.stringify(left)===JSON.stringify(right),shown=(value:unknown)=>{const serialized=JSON.stringify(value);return serialized===undefined?String(value):serialized;};
  const explicit=<T>(defs:{definition:Record<string,unknown>;provenance:CanonicalProvenance}[],read:(definition:Record<string,unknown>)=>T|undefined)=>{const values:{value:T;sources:string[]}[]=[];for(const{definition,provenance}of defs){const value=read(definition);if(value===undefined)continue;const prior=values.find((candidate)=>same(candidate.value,value)),source=provenance.source;if(prior)prior.sources.push(source);else values.push({value:clone(value),sources:[source]});}return values;};
  const addConflict=(path:string,propertyId:string,facet:CanonicalMigrationFacet,values:{value:unknown;sources:string[]}[])=>{if(values.length<2)return;conflicts.push({id:`migration-conflict:${encodeURIComponent(path)}:${facet.replaceAll(" ","-")}`,path,facet,propertyId,message:`Conflicting ${facet} facet from ${values.flatMap(({sources})=>sources).join(", ")}`,choices:values.map(({value,sources},index)=>({id:String(index),label:`Use ${shown(value)} from ${sources.join(" + ")}`,value:clone(value)}))});};
  const canonicalRules=(definition:Record<string,unknown>,path:string,source:string):CanonicalRule[]=>{const given=((definition.rules??definition["x-rules"]) as CanonicalRule[]|undefined)??[],patterns=[...(definition.patterns as string[]|undefined)??[],...(typeof definition.pattern==="string"?[definition.pattern]:[])],facetId=(kind:string,index?:number)=>`json-facet:${profile.id}:${encodeURIComponent(path)}:${source}:${kind}${index===undefined?"":`:${index}`}`,range=definition.minimum!==undefined||definition.maximum!==undefined?[{id:facetId("range"),kind:"range" as const,severity:"error" as const,message:"Outside migrated range",...(typeof definition.minimum==="number"?{minimum:definition.minimum}:{}),...(typeof definition.maximum==="number"?{maximum:definition.maximum}:{})}]:[],cardinality=definition.minItems!==undefined||definition.maxItems!==undefined?[{id:facetId("cardinality"),kind:"cardinality" as const,severity:"error" as const,message:"Outside migrated cardinality",...(typeof definition.minItems==="number"?{minItems:definition.minItems}:{}),...(typeof definition.maxItems==="number"?{maxItems:definition.maxItems}:{})}]:[];return[...given.map(clone),...patterns.map((pattern,index)=>({id:facetId("pattern",index),kind:"pattern" as const,pattern,severity:"error" as const,message:"Pattern mismatch"})),...range,...cardinality];};
  const paths=[...definitions.keys()].filter((path)=>path.startsWith("/")).sort((a,b)=>a.split("/").length-b.split("/").length||a.localeCompare(b));
  for(const path of paths){const segments=path.split("/").filter(Boolean);let parentId:string|undefined,current="";for(const segment of segments){current+=`/${segment}`;if(!byPath[current]){const defs=definitions.get(current)??[],types=explicit(defs,(definition)=>{const value=String(definition.type??"");return supported.has(value as CanonicalPropertyType)?value as CanonicalPropertyType:undefined;}),type=types[0]?.value??(defs.length?"string":"object"),stablePropertyId=`property:${profile.id}:${encodeURIComponent(current)}`,result=addCanonicalProperty(document,{baseRevision:revision,name:segment,type,...(parentId?{parentId}:{}),id:(kind)=>kind==="property"?stablePropertyId:options.id(kind)});if(result.status!=="applied")throw new Error("Canonical migration could not add a property.");document=result.document;revision=document.revision;const propertyId=document.selectedPropertyId!;byPath[current]=propertyId;const node=document.nodes[propertyId]!;node.provenance=defs.map(({provenance})=>provenance);
      const itemTypes=explicit(defs,(definition)=>{const value=String(definition.itemType??(definition.items as Record<string,unknown>|undefined)?.type??"");return supported.has(value as CanonicalPropertyType)?value as CanonicalPropertyType:undefined;}),presences=explicit(defs,(definition)=>{const raw=definition.presence;if(raw==="required"||definition.required===true)return{mode:"required" as const,...(definition.condition?{condition:clone(definition.condition) as CanonicalPredicate}:{})};if(raw==="forbidden"||definition.forbidden===true)return{mode:"forbidden" as const,...(definition.condition?{condition:clone(definition.condition) as CanonicalPredicate}:{})};if(raw==="optional"||raw==="permitted")return{mode:"optional" as const};return undefined;}),allowed=explicit(defs,(definition)=>(definition.allowedValues??definition.enum) as unknown[]|undefined),displayTexts=explicit(defs,(definition)=>typeof definition.displayText==="string"?definition.displayText:undefined),descriptions=explicit(defs,(definition)=>typeof (definition.description??definition.documentation)==="string"?String(definition.description??definition.documentation):undefined),comments=explicit(defs,(definition)=>typeof definition.comments==="string"?definition.comments:undefined),examples=explicit(defs,(definition)=>Array.isArray(definition.examples)&&definition.examples.length?{method:"custom" as const,value:clone(definition.examples[0])}:undefined),expected=explicit(defs,(definition)=>definition.expectedValue),enforcement=explicit(defs,(definition)=>definition.enforcement as "invariant"|"overridable"|undefined),targets=explicit(defs,(definition)=>typeof definition.target==="string"?definition.target:undefined),overrideReferences=explicit(defs,(definition)=>definition.overrideReferences as string[]|undefined);
      const rules:CanonicalRule[]=[];for(const{definition,provenance}of defs)for(const rule of canonicalRules(definition,current,provenance.source)){const prior=rules.find(({id})=>id===rule.id);if(prior&&!same(prior,rule))addConflict(current,propertyId,"rules",[{value:prior,sources:["earlier legacy definition"]},{value:rule,sources:[provenance.source]}]);else if(!prior)rules.push(rule);}node.rules=rules;node.presence=presences[0]?.value??{mode:"optional"};node.allowedValues=(allowed[0]?.value??[]).map((value)=>({id:options.id("allowed-value"),value:clone(value)}));node.documentation={displayText:displayTexts[0]?.value??"",description:descriptions[0]?.value??"",comments:comments[0]?.value??"",example:examples[0]?.value??{method:"blank"}};if(itemTypes[0])node.itemType=itemTypes[0].value;if(expected[0])node.expectedValue=clone(expected[0].value);if(enforcement[0])node.enforcement=enforcement[0].value;if(targets[0])node.target=targets[0].value;if(overrideReferences[0])node.overrideReferences=clone(overrideReferences[0].value);
      addConflict(current,propertyId,"type",types);addConflict(current,propertyId,"item type",itemTypes);addConflict(current,propertyId,"presence",presences);addConflict(current,propertyId,"allowed values",allowed);addConflict(current,propertyId,"display text",displayTexts);addConflict(current,propertyId,"description",descriptions);addConflict(current,propertyId,"comments",comments);addConflict(current,propertyId,"example",examples);addConflict(current,propertyId,"expected value",expected);addConflict(current,propertyId,"enforcement",enforcement);addConflict(current,propertyId,"target",targets);addConflict(current,propertyId,"override references",overrideReferences);
    }parentId=byPath[current];}}
  document.revision=1;document.changes=[{revision:1,propertyIds:Object.keys(document.nodes),kind:"add"}];return{profileId:profile.id,document,byPath,conflicts,legacyKeys:["requirements","structuredSchema","structuredDraft","schemaConstraints"]};
}

export function resolveCanonicalMigrationConflict(plan:CanonicalMigrationPlan,conflictId:string,choiceId:string):CanonicalMigrationPlan{
  const conflict=plan.conflicts.find(({id})=>id===conflictId),choice=conflict?.choices.find(({id})=>id===choiceId);if(!conflict||!choice)throw new Error("Choose an available canonical migration resolution.");const next=clone(plan),target=next.conflicts.find(({id})=>id===conflictId)!,node=next.document.nodes[target.propertyId]!,value=clone(choice.value);
  if(target.facet==="type")node.type=value as CanonicalPropertyType;else if(target.facet==="item type")node.itemType=value as CanonicalPropertyType;else if(target.facet==="presence")node.presence=value as CanonicalPropertyNode["presence"];else if(target.facet==="allowed values")node.allowedValues=(value as unknown[]).map((entry,index)=>({id:`migration-allowed:${encodeURIComponent(target.path)}:${index}`,value:entry}));else if(target.facet==="rules"){const replacement=value as CanonicalRule;node.rules=[...node.rules.filter(({id})=>id!==replacement.id),replacement];}else if(target.facet==="display text")node.documentation.displayText=String(value);else if(target.facet==="description")node.documentation.description=String(value);else if(target.facet==="comments")node.documentation.comments=String(value);else if(target.facet==="example")node.documentation.example=value as CanonicalDocumentation["example"];else if(target.facet==="expected value")node.expectedValue=value;else if(target.facet==="enforcement")node.enforcement=value as NonNullable<CanonicalPropertyNode["enforcement"]>;else if(target.facet==="target")node.target=String(value);else node.overrideReferences=value as string[];
  next.conflicts=next.conflicts.filter(({id})=>id!==conflictId);return next;
}

export function canonicalSchemaFromJsonSchema(input:{id:string;contributorId:string;contributorName:string;sourceIdentity:string;sourceRevision:number;document:Record<string,unknown>;idFactory:CanonicalIdFactory}):CanonicalSchemaDocument{const profile:CanonicalLegacyProfile={id:input.contributorId,name:input.contributorName,structuredSchema:input.document},plan=migrateLegacyProfile(profile,{id:input.idFactory}),firstRootId=plan.document.rootIds[0],document={...plan.document,id:input.id,source:{identity:input.sourceIdentity,revision:input.sourceRevision,provenance:"saved-schema-library" as const},...(firstRootId?{selectedPropertyId:firstRootId}:{})};for(const node of Object.values(document.nodes))node.provenance=node.provenance.map(()=>({source:"saved-schema",sourceId:input.sourceIdentity,revision:input.sourceRevision}));return document;}

export function canonicalNodeFromValue(name:string,value:unknown,input:{id:CanonicalIdFactory;parentId?:string;order:number}):CanonicalPropertyNode{return{id:input.id("property"),name,...(input.parentId?{parentId:input.parentId}:{}),order:input.order,type:typeOf(value),presence:{mode:"optional"},allowedValues:[],rules:[],documentation:emptyDocumentation(),provenance:[{source:"created"}],overrideReferences:[]};}
