import {canonicalTableRows,type CanonicalPropertyNode} from "./data-layer-canonical-schema.js";
import type {CanonicalSchemaRenderContext} from "./data-layer-canonical-schema-render.js";

const input=(dom:Document,name:string,value="",type="text"):HTMLInputElement=>{const control=dom.createElement("input");control.name=name;control.type=type;control.value=value;return control;};
const labeled=(dom:Document,text:string,control:HTMLElement):HTMLLabelElement=>{const label=dom.createElement("label");label.append(text,control);return label;};
const button=(dom:Document,text:string,run:()=>void):HTMLButtonElement=>{const control=dom.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function renderCanonicalNavigator(context:CanonicalSchemaRenderContext):HTMLElement {
  const {dom,document}=context,navigator=dom.createElement("section"),search=dom.createElement("input"),filter=dom.createElement("select"),tree=dom.createElement("div"),rootName=input(dom,"newRootPropertyName","property"),addRoot=button(dom,"Add root property",()=>{const name=rootName.value.trim();if(name)context.command({kind:"add",baseRevision:document.revision,name,type:"string",id:context.options.id});});navigator.setAttribute("aria-label","Canonical property navigator");search.type="search";search.setAttribute("aria-label","Canonical property search");search.placeholder="Search properties";search.value=context.query;search.addEventListener("input",()=>{context.setQuery(search.value);context.render();});filter.name="propertyFilter";filter.append(...["All properties","With conditions","With documentation","With issues"].map((entry)=>new Option(entry,entry)));tree.setAttribute("aria-label","Canonical property search results");
  for(const row of canonicalTableRows(document).filter(({node})=>node.name.toLowerCase().includes(context.query.toLowerCase()))){const article=dom.createElement("article"),choose=button(dom,`${"› ".repeat(row.depth)}${row.node.name} · ${row.path} · ${row.node.type}`,()=>context.openProperty(row.node,choose));choose.dataset.propertyId=row.id;choose.setAttribute("aria-current",String((context.activePropertyId??document.selectedPropertyId)===row.id));article.dataset.propertyRow="true";article.dataset.propertyId=row.id;const actions=button(dom,"Property actions",()=>{context.setMenuPropertyId(row.id);context.openProperty(row.node,actions);});actions.setAttribute("aria-label",`Property actions for ${row.path}`);actions.dataset.propertyActionsPath=row.path;article.append(choose,actions);if(context.menuPropertyId===row.id)article.append(context.renderMenu(row.node));tree.append(article);}
  const body=dom.createElement("tbody");for(const article of Array.from(tree.children)){const row=dom.createElement("tr"),cell=dom.createElement("td");cell.append(article);row.append(cell);body.append(row);}if(document.view==="table"){tree.replaceChildren(body);tree.setAttribute("role","table");tree.dataset.canonicalView="table";}else{tree.setAttribute("role","tree");tree.dataset.canonicalView="tree";}
  navigator.append(search,filter,tree,labeled(dom,"New root property name",rootName),addRoot);navigator.prepend(button(dom,"Table",()=>{context.command({kind:"view",baseRevision:document.revision,view:"table"});context.render();}),button(dom,"Tree",()=>{context.command({kind:"view",baseRevision:document.revision,view:"tree"});context.render();}));return navigator;
}
