import {composedFacetDraft,composedFacetDraftWithoutRemovedItems,overrideComposedRule,sparseComposedFacets,type ComposedFacetDraft} from "./data-layer-composed-schema-builders.js";
import type {ComposedSchemaRepair,ComposedSchemaRow,ComposedSchemaWorkspace} from "./data-layer-composed-schema-workspace.js";
import type {FocusedPropertySection} from "./data-layer-focused-schema-property-ui.js";
import {renderComposedRows} from "./data-layer-composed-schema-workspace-rows.js";
import type {LayerConstraint} from "./data-layer-layered-schema.js";
import type {FlowPageInstanceStructureCommand,FlowPageInstanceStructureKind} from "./flow-graph/page-instance-structure.js";

interface ComposedSchemaWorkspaceUiOptions {host:HTMLElement;model:ComposedSchemaWorkspace;effectiveText:(row:ComposedSchemaRow)=>string;onSave:(row:ComposedSchemaRow,facets:Omit<LayerConstraint,"path">,structure?:readonly FlowPageInstanceStructureCommand[])=>void;onReset:(row:ComposedSchemaRow)=>void;onRepair?:(repair:ComposedSchemaRepair)=>void;onStructure?:(kind:FlowPageInstanceStructureKind,path:string,name?:string)=>void;includeConditionEvaluation?:boolean;includeConflictSummary?:boolean;schemaContributorId?:string;schemaContributorScope?:string;rowPathDataset?:string;compact?:boolean;}
const button=(text:string,run:()=>void):HTMLButtonElement=>{const control=document.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function mountComposedSchemaWorkspace(options:ComposedSchemaWorkspaceUiOptions):HTMLElement {
  const section=document.createElement("section"),heading=document.createElement("h2"),summary=document.createElement("p"),columns=document.createElement("div"),filterControls=document.createElement("div"),filter=document.createElement("input"),sort=document.createElement("select"),addControls=document.createElement("div"),choice=document.createElement("select"),add=document.createElement("button"),rows=document.createElement("div");
  let activePath:string|undefined,activeSection:FocusedPropertySection="definition",draft:ComposedFacetDraft|undefined,removed=false,confirmedAction:"reset"|"remove"|undefined,removedRuleIds=new Set<string>(),removedValueIds=new Set<string>(),restoredRuleIds=new Set<string>(),restoredValueIds=new Set<string>(),stagedLocalValueIds=new Set<string>(),overriddenRuleIds=new Set<string>(),pendingStructure:FlowPageInstanceStructureCommand[]=[],pendingAction:"reset"|"remove"|undefined,originFocus:HTMLElement|undefined,originPath:string|undefined,query="",sortMode="path";
  section.className=options.compact?"composed-schema-workspace compact-schema-workspace":"composed-schema-workspace";section.setAttribute("aria-label",options.model.heading);section.dataset.schemaStatus=options.model.status;section.dataset.schemaPresentation=options.compact?"compact-side-panel":"focused-property";if(options.schemaContributorId)section.dataset.schemaContributorId=options.schemaContributorId;if(options.schemaContributorScope)section.dataset.schemaContributorScope=options.schemaContributorScope;
  heading.textContent=options.model.heading;summary.setAttribute("role","status");summary.className=options.model.status==="blocked"?"error":"status-text";summary.textContent=`${options.model.status==="blocked"?"Blocked":"Ready"} · ${options.model.rows.length} effective properties${options.includeConflictSummary===false?"":` · ${options.model.conflictSummary}`}`;
  columns.className="composed-schema-columns";columns.setAttribute("aria-hidden","true");columns.hidden=Boolean(options.compact);for(const label of["Property","Effective definition","Source","Local state","Validation state","Actions"])columns.append(Object.assign(document.createElement("strong"),{textContent:label}));
  filter.type="search";filter.placeholder="Filter properties";filter.setAttribute("aria-label","Filter schema properties");sort.setAttribute("aria-label","Sort schema properties");sort.append(new Option("Tree order","path"),new Option("Source","source"),new Option("Validation","validation"));filterControls.setAttribute("aria-label","Schema property navigation controls");filterControls.append(filter,sort);
  addControls.setAttribute("aria-label","Add local property");choice.setAttribute("aria-label","Choose inherited property to override");choice.append(new Option("Choose a property",""),...options.model.rows.filter(({inherited})=>Boolean(inherited)).map(({path})=>new Option(path,path)));add.type="button";add.textContent="Add local property";add.addEventListener("click",()=>{const row=options.model.rows.find(({path})=>path===choice.value)||options.model.rows.find(({inherited})=>Boolean(inherited));if(row)open(row,add);});addControls.append(choice,add);rows.setAttribute("role","table");rows.setAttribute("aria-label",`${options.model.heading} rows`);
  const visibleModel=():ComposedSchemaWorkspace=>{const needle=query.trim().toLowerCase(),rows=options.model.rows.filter((row)=>!needle||row.path.toLowerCase().includes(needle)||row.source.toLowerCase().includes(needle)||options.effectiveText(row).toLowerCase().includes(needle)).sort((left,right)=>sortMode==="source"?left.source.localeCompare(right.source)||left.path.localeCompare(right.path):sortMode==="validation"?left.validationState.localeCompare(right.validationState)||left.path.localeCompare(right.path):left.path.localeCompare(right.path));return{...options.model,rows};};
  const rerender=():void=>renderComposedRows(rows,{dom:document,model:visibleModel(),effectiveText:options.effectiveText,...(options.onRepair?{onRepair:options.onRepair}:{}),...(options.onStructure?{onStructure:(kind,path,name)=>{pendingStructure.push({kind,path,...(name===undefined?{}:{name})});rerender();}}:{}),...(options.rowPathDataset?{rowPathDataset:options.rowPathDataset}:{}),activePath,activeSection,draft,removed,confirmedAction,removedRuleIds,removedValueIds,restoredRuleIds,restoredValueIds,stagedLocalValueIds,overriddenRuleIds,overrideRule,pendingAction,pendingStructure,beginAction,cancelAction,confirmAction,open,close,save,render:rerender,setActiveSection:(value)=>{activeSection=value;}});
  const overrideRule=(index:number):void=>{if(!draft)return;const id=`rule:${crypto.randomUUID()}`,next=overrideComposedRule(draft,index,id);if(next===draft)return;draft=next;overriddenRuleIds.add(id);rerender();};
  const open=(row:ComposedSchemaRow,focus?:HTMLElement,sectionName:FocusedPropertySection="definition"):void=>{activePath=row.path;activeSection=sectionName;draft=composedFacetDraft(row.local,row.effective);removed=false;confirmedAction=undefined;removedRuleIds=new Set();removedValueIds=new Set();restoredRuleIds=new Set();restoredValueIds=new Set();stagedLocalValueIds=new Set();overriddenRuleIds=new Set();pendingStructure=[];pendingAction=undefined;if(focus){originFocus=focus;originPath=row.path;}rerender();};
  const close=():void=>{const restorePath=originPath;activePath=undefined;activeSection="definition";draft=undefined;removed=false;confirmedAction=undefined;removedRuleIds=new Set();removedValueIds=new Set();restoredRuleIds=new Set();restoredValueIds=new Set();stagedLocalValueIds=new Set();overriddenRuleIds=new Set();pendingStructure=[];pendingAction=undefined;rerender();const target=originFocus?.isConnected?originFocus:restorePath?rows.querySelector<HTMLElement>(`[aria-label="Property actions for ${CSS.escape(restorePath)}"]`):undefined;originFocus=undefined;originPath=undefined;if(target)queueMicrotask(()=>target.focus({preventScroll:true}));};
  const beginAction=(row:ComposedSchemaRow,focus?:HTMLElement):void=>{open(row,focus);pendingAction=row.action==="reset"?"reset":"remove";rerender();};
  const cancelAction=():void=>{pendingAction=undefined;removed=false;confirmedAction=undefined;rerender();};
  const confirmAction=(_row:ComposedSchemaRow):void=>{confirmedAction=pendingAction;pendingAction=undefined;removed=true;rerender();};
  const save=(row:ComposedSchemaRow):void=>{if(!draft)return;if(removed){options.onReset(row);close();return;}const staged=composedFacetDraftWithoutRemovedItems(draft,removedRuleIds,removedValueIds);options.onSave(row,sparseComposedFacets(staged,row.inherited??{path:row.path}),pendingStructure);close();};
  filter.addEventListener("input",()=>{query=filter.value;rerender();});sort.addEventListener("change",()=>{sortMode=sort.value;rerender();});section.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&activePath){event.preventDefault();close();}});rerender();section.append(heading,summary,filterControls,columns,addControls,rows);options.host.append(section);return section;
}
