import {compileLayeredSchema,type LayerContributor} from "./data-layer-layered-schema.js";
import {flowPageFrameContributor,layeredContributorPath,layeredContributorsForPath} from "./data-layer-layered-schema-project.js";
import {compileFlowDocumentationSnapshot,orderFlowDocumentationOccurrenceIds,type FlowDocumentationContextInput,type FlowDocumentationSnapshot} from "./data-layer-flow-table-documentation-export.js";
import {documentaryFlowGraph} from "./utilities/data-layer/flow-graph.js";
import type {ProjectState} from "./utilities/data-layer/schemas.js";

const stableRevision=(value:unknown):number=>{const bytes=new TextEncoder().encode(JSON.stringify(value));let hash=2166136261;for(const byte of bytes)hash=Math.imul(hash^byte,16777619);return hash>>>0;};
const graphRevisionFor=(graph:ReturnType<typeof documentaryFlowGraph>):number=>stableRevision({pageGroupIds:graph.pageGroupIds,pageFrames:graph.pageFrames,occurrences:graph.occurrences.map(({canonicalSchema:_canonicalSchema,schemaConstraints:_schemaConstraints,...occurrence})=>occurrence),relationships:graph.relationships});
const schemaRevisionFor=(state:ProjectState,contributors:readonly LayerContributor[],contextId:string):number=>{
  const ids=new Set(contributors.map(({id})=>id)),effective=contributors.map(({id,revision,constraints,onlyDefinedFields,active,inheritanceRoutes,peerGroup})=>({id,revision:Number(revision??0),constraints,onlyDefinedFields,active,inheritanceRoutes,peerGroup})),targets=((state.project.layeredSchemaTargets as {occurrenceId?:string;contributorId?:string;revision?:number}[]|undefined)??[]).filter((target)=>target.occurrenceId===contextId||ids.has(String(target.contributorId??""))).map(({occurrenceId,contributorId,revision})=>({occurrenceId,contributorId,revision:Number(revision??0)}));
  return stableRevision({effective,targets:targets.sort((left,right)=>String(left.contributorId??left.occurrenceId).localeCompare(String(right.contributorId??right.occurrenceId)))});
};
const emptyCompiled=()=>({status:"ready" as const,properties:{},conflicts:[],provenance:[],exclusions:[]});

export function flowDocumentationSnapshotFromState(state:ProjectState,flowId:string,generatedAt=new Date().toISOString(),revision=0):FlowDocumentationSnapshot {
  const flow=state.project.collections.flows.find(({id})=>id===flowId);if(!flow)throw new Error(`Unknown Flow ${flowId}`);
  const graph=documentaryFlowGraph(state.project,flowId),pageById=new Map(state.project.collections.pages.map((page)=>[page.id,page])),frameById=new Map(graph.pageFrames.map((frame)=>[frame.id,frame])),groupById=new Map(state.project.collections.propertySets.map((group)=>[group.id,group])),ordered=orderFlowDocumentationOccurrenceIds(graph.pageFrames,graph.relationships,graph.pageGroupIds),frameOrder=ordered.ids.length?ordered.ids:graph.pageFrames.map(({id})=>id);
  const frameContexts:FlowDocumentationContextInput[]=frameOrder.flatMap((frameId,index)=>{const frame=frameById.get(frameId);if(!frame)return[];const page=pageById.get(String(frame.pageId)),frameEntity=flowPageFrameContributor(state,flowId,frame.id);if(!frameEntity)return[];const path=layeredContributorPath(state,frameEntity,"Flow Page-instance",flowId),contributors=layeredContributorsForPath(state,path),eventName=String(page?.eventName??"pageview"),compiled=contributors.length?compileLayeredSchema(contributors,{eventId:eventName,eventRole:"context"}):emptyCompiled();return[{id:`context:frame:${frame.id}`,kind:"page-instance",pageFrameId:frame.id,pageName:page?.name??"Unresolved Page",eventName,stepLabel:ordered.labels[frame.id]??String(index+1),effectiveRevision:schemaRevisionFor(state,contributors,frame.id),compiled,...(!page?{unresolved:[{path:"/context/page",issue:`Unresolved Page ${String(frame.pageId)}`,repair:"Open Page reference"}]}:{})}];});
  const occurrenceContexts:FlowDocumentationContextInput[]=frameOrder.flatMap((frameId,frameIndex)=>graph.occurrences.filter(({pageFrameId})=>pageFrameId===frameId).map((occurrence,occurrenceIndex)=>{const frame=frameById.get(frameId),page=pageById.get(String(occurrence.pageId??frame?.pageId)),eventId=String(occurrence.eventId??""),event=state.project.collections.events.find(({id})=>id===eventId),pageGroupId=String(occurrence.pageGroupId??frame?.pageGroupId??""),pageGroup=groupById.get(pageGroupId),occurrenceEntity={...occurrence,name:String(occurrence.name??event?.name??occurrence.id)},path=layeredContributorPath(state,occurrenceEntity,"Event-occurrence",flowId),declaredUnresolved=[occurrence,event,page].flatMap((entity)=>((entity?.unresolvedReferences as {path?:string;issue?:string;repair?:string}[]|undefined)??[])),unresolved=[...(!frame?[{path:"/context/page-frame",issue:`Unresolved Page frame ${String(occurrence.pageFrameId??"")}`,repair:"Open Flow Page frame"}]:[]),...(!page?[{path:"/context/page",issue:`Unresolved Page ${String(occurrence.pageId??frame?.pageId??"")}`,repair:"Open Page reference"}]:[]),...(!event?[{path:"/context/event",issue:`Unresolved Event ${eventId}`,repair:"Open Event reference"}]:[]),...(pageGroupId&&!pageGroup?[{path:"/context/page-group",issue:`Unresolved Property Set ${pageGroupId}`,repair:"Open Property Set membership"}]:[]),...declaredUnresolved.map((item)=>({path:item.path??"/context/reference",issue:item.issue??"Unresolved context reference",repair:item.repair??"Open context reference"}))],contributors=layeredContributorsForPath(state,path),compiled=contributors.length?compileLayeredSchema(contributors,{eventId,eventRole:"interaction",occurrenceId:occurrence.id}):emptyCompiled(),parentLabel=ordered.labels[frameId]??String(frameIndex+1);return{id:`context:${occurrence.id}`,kind:"interaction" as const,pageFrameId:frameId,occurrenceId:occurrence.id,pageName:page?.name??"Unresolved Page",eventName:String(event?.eventName??event?.name??"Unresolved Event"),stepLabel:`${parentLabel}${String.fromCharCode(97+occurrenceIndex)}`,effectiveRevision:schemaRevisionFor(state,contributors,occurrence.id),compiled,...(unresolved.length?{unresolved}:{})};}));
  const contexts=frameOrder.flatMap((frameId)=>[...frameContexts.filter(({pageFrameId})=>pageFrameId===frameId),...occurrenceContexts.filter(({pageFrameId})=>pageFrameId===frameId)]),endpointIds=new Set(graph.pageFrames.map(({id})=>id));graph.relationships.forEach((relationship,index)=>{const source=String(relationship.sourceEndpoint?.id??relationship.sourceNodeId??""),target=String(relationship.targetEndpoint?.id??relationship.targetNodeId??""),missing=[...(!endpointIds.has(source)?[`source ${source||"(empty)"}`]:[]),...(!endpointIds.has(target)?[`target ${target||"(empty)"}`]:[])];if(!missing.length||!contexts.length)return;const frameAnchor=graph.pageFrames.find(({id})=>id===source||id===target)?.id,contextId=`context:frame:${frameAnchor??frameOrder[0]}`,contextIndex=Math.max(0,contexts.findIndex(({id})=>id===contextId)),context=contexts[contextIndex]!;contexts[contextIndex]={...context,unresolved:[...(context.unresolved??[]),{path:`/relationships/${String(relationship.id??index)}`,issue:`Dangling Flow relationship: unresolved ${missing.join(" and ")}`,repair:"Open Flow relationship"}]};});
  return compileFlowDocumentationSnapshot({projectId:state.project.id,projectName:state.project.name,flowId,flowName:flow.name,graphRevision:graphRevisionFor(graph),sourceState:state.draft?"draft":"published",generatedAt,contexts});
}
