import {applyCanonicalCommand,canonicalConstraints,canonicalTableRows,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {EffectiveProperty,LayerConstraint,LayerScope} from "./data-layer-layered-schema.js";
import {transactProject,type ProjectEntity,type ProjectEntityKind,type ProjectState} from "./data-layer-specification-project.js";
import {composedSchemaWorkspace} from "./composed-schema/workspace-model.js";
import {composedCanonicalSchema,resetCanonicalRow} from "./composed-schema/canonical-workspace.js";
import {applyLayerConstraintStructures,structureDeletesPath,type FlowPageInstanceStructureCommand} from "./flow-graph/page-instance-structure.js";
export {composedSchemaWorkspace,composedCanonicalSchema};
export type ComposedSchemaRowState="ready"|"warning"|"blocked";
export interface ComposedSchemaProvenance {contributorId:string;contributorName:string;scope:LayerScope;state:"inherited"|"shadowed"|"effective";}
export interface ComposedSchemaRepair {contributorId:string;contributorName:string;label:string;}
export interface ComposedSchemaRow {path:string;inherited?:EffectiveProperty;local:LayerConstraint;effective:EffectiveProperty;source:string;validationState:ComposedSchemaRowState;message:string;action:"override"|"reset"|"remove";provenance:ComposedSchemaProvenance[];repairs:ComposedSchemaRepair[];}
export interface ComposedSchemaWorkspace {heading:string;status:"ready"|"blocked";rows:ComposedSchemaRow[];conflictSummary:string;}
const clone=<T>(value:T):T=>structuredClone(value);
function updateEntity(state:ProjectState,kind:ProjectEntityKind,entityId:string,label:string,update:(entity:ProjectEntity)=>ProjectEntity):ProjectState{return transactProject(state,label,(project)=>({...project,collections:{...project.collections,[kind]:(project.collections[kind] as ProjectEntity[]).map((entity)=>entity.id===entityId?update(entity):entity)}} as typeof project));}
const sparseFacetKeys=(constraint:LayerConstraint):LayerConstraint=>Object.fromEntries(Object.entries(constraint).filter(([key])=>!["path","origins","superseded","expectedContributor"].includes(key))) as LayerConstraint;
const sparseAgainst=(constraint:LayerConstraint,inherited:EffectiveProperty|undefined):LayerConstraint=>{const result:Record<string,unknown>={path:constraint.path},parent:Partial<LayerConstraint>=inherited?sparseFacetKeys(inherited):{},rules=(constraint.rules??[]).filter((rule)=>{const state=(rule.provenance as Record<string,unknown>|undefined)?.state;return state==="local"||state==="effective"||state==="overridden"||(!state&&!(inherited?.rules??[]).some((candidate)=>String(candidate.id??"")===String(rule.id??"")));}),localValueOwnership=(constraint.allowedValueProvenance??[]).filter(({state})=>state!=="inherited"),candidate:Record<string,unknown>={...constraint};if(rules.length)candidate.rules=rules;else delete candidate.rules;if(localValueOwnership.length)candidate.allowedValueProvenance=localValueOwnership;else delete candidate.allowedValueProvenance;for(const[key,value]of Object.entries(sparseFacetKeys(candidate as unknown as LayerConstraint))){if(key==="definitionId"&&inherited&&!inherited.definitionId)continue;if((key==="allowedValues"||key==="allowedValueIds")&&inherited&&JSON.stringify(constraint.allowedValues)===JSON.stringify(inherited.allowedValues)&&!localValueOwnership.length)continue;if(key==="target"&&inherited&&value==="all"&&parent.target===undefined)continue;if(value!==undefined&&JSON.stringify(value)!==JSON.stringify(parent[key as keyof LayerConstraint]))result[key]=clone(value);}return result as unknown as LayerConstraint;};
const sparseCanonicalConstraints=(document:CanonicalSchemaDocument,parents:ReadonlyMap<string,EffectiveProperty|undefined>):LayerConstraint[]=>{const structureOwned=new Map(canonicalTableRows(document).map(({path,node})=>[path,node.structureOwned===true]));return canonicalConstraints(document).map((constraint)=>{const candidate=clone(constraint),parent=parents.get(constraint.path);if(parent&&structureOwned.get(constraint.path)!==true)delete candidate.definitionId;return sparseAgainst(candidate,parent);}).filter((constraint)=>Object.keys(constraint).length>1);};
export function saveComposedCanonicalDocument(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,document:CanonicalSchemaDocument):ProjectState{const entity=(state.project.collections[kind] as ProjectEntity[]).find(({id})=>id===entityId);if(!entity)throw new Error(`${kind==="pages"?"Page":"Page Group"} ${entityId} is unavailable.`);const scope=kind==="pages"?"Page":"Page Group",workspace=composedSchemaWorkspace(state,entity,scope),parents=new Map(workspace.rows.map(({path,inherited})=>[path,inherited])),constraints=sparseCanonicalConstraints(document,parents);return updateEntity(state,kind,entityId,`Save effective canonical schema for ${entity.name}`,(current)=>{const next:ProjectEntity={...current,localSchemaContributions:constraints,onlyDefinedFields:document.onlyDefinedFields===true,compiledTargetsStale:true};delete next.canonicalSchema;delete next.schemaConstraints;return next;});}
export function saveComposedEventCanonicalDocument(state:ProjectState,entityId:string,document:CanonicalSchemaDocument):ProjectState{const entity=state.project.collections.events.find(({id})=>id===entityId);if(!entity)throw new Error(`Event ${entityId} is unavailable.`);const workspace=composedSchemaWorkspace(state,entity,"Event"),parents=new Map(workspace.rows.map(({path,inherited})=>[path,inherited])),constraints=sparseCanonicalConstraints(document,parents);return updateEntity(state,"events",entityId,`Save effective canonical schema for ${entity.name}`,(current)=>({...current,localSchemaContributions:constraints,onlyDefinedFields:document.onlyDefinedFields===true,compiledTargetsStale:true}));}
function saveFlowComposedCanonicalDocument(state:ProjectState,flowId:string,entityId:string,field:"pageFrames"|"occurrences",scope:"Flow Page-instance"|"Event-occurrence",document:CanonicalSchemaDocument):ProjectState{
  const graph=(state.project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences?:ProjectEntity[]}>)[flowId],entity=graph?.[field]?.find(({id})=>id===entityId);if(!entity)throw new Error(`${scope} ${entityId} is unavailable.`);const workspace=composedSchemaWorkspace(state,entity,scope,undefined,flowId),parents=new Map(workspace.rows.map(({path,inherited})=>[path,inherited])),constraints=sparseCanonicalConstraints(document,parents);
  return transactProject(state,`Save effective canonical schema for ${entity.name}`,(project)=>{const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences?:ProjectEntity[]}>,current=graphs[flowId]!,entries=current[field]??[];return{...project,documentationFlowGraphs:{...graphs,[flowId]:{...current,[field]:entries.map((candidate)=>{if(candidate.id!==entityId)return candidate;const next:ProjectEntity={...candidate,localSchemaContributions:constraints,onlyDefinedFields:document.onlyDefinedFields===true,compiledTargetsStale:true};delete next.canonicalSchema;delete next.schemaConstraints;return next;})}}};});
}
export const saveFlowPageInstanceCanonicalDocument=(state:ProjectState,flowId:string,entityId:string,document:CanonicalSchemaDocument):ProjectState=>saveFlowComposedCanonicalDocument(state,flowId,entityId,"pageFrames","Flow Page-instance",document);
export const saveEventOccurrenceCanonicalDocument=(state:ProjectState,flowId:string,entityId:string,document:CanonicalSchemaDocument):ProjectState=>saveFlowComposedCanonicalDocument(state,flowId,entityId,"occurrences","Event-occurrence",document);
export function saveComposedSchemaLocalFacets(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string,facets:Omit<LayerConstraint,"path">):ProjectState{const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!=="")) as Omit<LayerConstraint,"path">;return updateEntity(state,kind,entityId,`Override ${path} at ${kind==="pages"?"Page":"Page Group"}`,(entity)=>{const existing=(entity.localSchemaContributions as LayerConstraint[]|undefined)??[],next=[...existing.filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[{path,...clone(sparse)}]:[])];return{...entity,localSchemaContributions:next,compiledTargetsStale:true};});}
const entityWithSchemaPolicy=(entity:ProjectEntity,onlyDefinedFields:boolean):ProjectEntity=>{const canonical=entity.canonicalSchema as CanonicalSchemaDocument|undefined;if(!canonical)return{...entity,onlyDefinedFields,compiledTargetsStale:true};const result=applyCanonicalCommand(canonical,{kind:"policy",baseRevision:canonical.revision,onlyDefinedFields});if(result.status!=="applied"&&result.status!=="rebased")throw new Error("The canonical defined-fields policy changed before it could be saved.");const next:ProjectEntity={...entity,canonicalSchema:result.document,compiledTargetsStale:true};delete next.onlyDefinedFields;return next;};
export function saveComposedSchemaPolicy(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,onlyDefinedFields:boolean):ProjectState{return updateEntity(state,kind,entityId,`Change defined-fields policy at ${kind==="pages"?"Page":"Page Group"}`,(entity)=>entityWithSchemaPolicy(entity,onlyDefinedFields));}
export function saveComposedEntitySchemaPolicy(state:ProjectState,kind:"pages"|"pageGroups"|"events",entityId:string,onlyDefinedFields:boolean):ProjectState{return updateEntity(state,kind,entityId,`Change defined-fields policy at ${kind==="pages"?"Page":kind==="pageGroups"?"Page Group":"Event"}`,(entity)=>entityWithSchemaPolicy(entity,onlyDefinedFields));}
export function saveFlowContributorSchemaPolicy(state:ProjectState,flowId:string,field:"pageFrames"|"occurrences",entityId:string,onlyDefinedFields:boolean):ProjectState{return transactProject(state,`Change defined-fields policy at ${field==="pageFrames"?"Flow Page instance":"Event occurrence"}`,(project)=>{const graphs=project.documentationFlowGraphs as Record<string,{pageFrames?:ProjectEntity[];occurrences?:ProjectEntity[]}>,graph=graphs[flowId]!,entries=graph[field]??[];return{...project,documentationFlowGraphs:{...graphs,[flowId]:{...graph,[field]:entries.map((entity)=>entity.id===entityId?entityWithSchemaPolicy(entity,onlyDefinedFields):entity)}}};});}
export function saveFlowPageInstanceSchemaPolicy(state:ProjectState,flowId:string,pageFrameId:string,onlyDefinedFields:boolean):ProjectState{return saveFlowContributorSchemaPolicy(state,flowId,"pageFrames",pageFrameId,onlyDefinedFields);}
export function saveComposedSchemaLocalFacetsAndStructures(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string,facets:Omit<LayerConstraint,"path">,commands:readonly FlowPageInstanceStructureCommand[],id:(kind:string)=>string):ProjectState{const sparse=Object.fromEntries(Object.entries(facets).filter(([,value])=>value!==undefined&&value!=="")) as Omit<LayerConstraint,"path">;return updateEntity(state,kind,entityId,`Save ${commands.length+1} ${kind==="pages"?"Page":"Page Group"} schema changes`,(entity)=>{const existing=(entity.localSchemaContributions as LayerConstraint[]|undefined)??[],focused:{path:string}&Omit<LayerConstraint,"path">={path,...clone(sparse)},seeded=commands.length?[...existing.filter((constraint)=>constraint.path!==path),focused]:existing,structured=applyLayerConstraintStructures(seeded,commands,id),next=commands.length?structured.filter((constraint)=>Object.keys(constraint).length>1):[...existing.filter((constraint)=>constraint.path!==path),...(Object.keys(sparse).length?[focused]:[])];return{...entity,localSchemaContributions:structureDeletesPath(commands,path)?next.filter((constraint)=>constraint.path!==path):next,compiledTargetsStale:true};});}
export function resetComposedSchemaLocalProperty(state:ProjectState,kind:"pages"|"pageGroups",entityId:string,path:string):ProjectState{return updateEntity(state,kind,entityId,`Reset ${path} to parents`,(entity)=>{const next:ProjectEntity={...entity,localSchemaContributions:((entity.localSchemaContributions as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),schemaConstraints:((entity.schemaConstraints as LayerConstraint[]|undefined)??[]).filter((constraint)=>constraint.path!==path),compiledTargetsStale:true};return resetCanonicalRow(entity.canonicalSchema as CanonicalSchemaDocument|undefined,path,next);});}
