import type {ProjectEntity,ProjectState,SpecificationProject} from "./data-layer-specification-project.js";
import type {ProjectNavigation} from "./data-layer-project-library.js";

export const DURABLE_PROJECT_DATABASE="my-chrome-utilities.project-repository";
export const DURABLE_PROJECT_DATABASE_VERSION=4;
export const LEGACY_PROJECT_KEYS={library:"my-chrome-utilities.specification-project-library.v1",active:"my-chrome-utilities.specification-project.v1",navigation:"my-chrome-utilities.specification-project-navigation.v1",schemas:"my-chrome-utilities.schema-library.v1"} as const;

export const DURABLE_PROJECT_STORES=["projectMetadata","projectRoots","projectEntityMetadata","projectEntities","savedSchemas","flowGraphs","fixtures","releases","projectRevisions","settings","migrationReceipts","migrationBackups"] as const;
export type DurableProjectStore=typeof DURABLE_PROJECT_STORES[number];
export interface DurableRecordIdentity{store:DurableProjectStore;key:string;}
export interface DurableTraceEntry extends DurableRecordIdentity{operation:"read"|"write"|"delete";}
export interface DurableProjectMetadata{projectId:string;name:string;site:string;owner:string;draftToken:string;draftSequence:number;publishedRevision:number;lastSavedAt:string;fieldVersions:Record<string,number>;active:boolean;draft?:ProjectState["draft"];navigation?:ProjectNavigation;}
interface DurableRootRecord{project:Omit<SpecificationProject,"collections"|"documentationFlowGraphs"|"releases">;collectionKinds:string[];hasDocumentationFlowGraphs:boolean;}
export interface DurableLoadedProject{state:ProjectState;draftToken:string;draftSequence:number;publishedRevision:number;lastSavedAt:string;navigation?:ProjectNavigation;}
export interface DurablePatch{store:Extract<DurableProjectStore,"projectRoots"|"projectEntityMetadata"|"projectEntities"|"flowGraphs"|"fixtures"|"releases">;key:string;path:string[];before:unknown;after:unknown;}
export interface DurableDraftCommand{projectId:string;baseToken:string;baseSequence:number;commandId:string;label:string;patches:DurablePatch[];pendingState:ProjectState;}
export interface DurableCommittedDraft{status:"committed"|"rebased";projectId:string;draftToken:string;draftSequence:number;publishedRevision:number;changedRecords:DurableRecordIdentity[];notification:DurableProjectNotification;}
export interface DurableDraftConflict{status:"conflict";projectId:string;baseToken:string;currentToken:string;commandId:string;label:string;pendingFields:string[];currentFields:string[];conflictingFields:string[];currentValues:Record<string,unknown>;pendingValues:Record<string,unknown>;}
export type DurableDraftResult=DurableCommittedDraft|DurableDraftConflict;
export interface DurableProjectNotification{type:"durable-project-change";projectId:string;draftToken:string;draftSequence:number;commandId:string;changedRecords:DurableRecordIdentity[];}
export interface DurableActiveContextNotification{type:"durable-active-context-change";projectId:string;token:string;}
export interface DurableProjectMetadataNotification{type:"durable-project-metadata-change";projectId:string;draftToken:string;changeToken:string;}
export type DurableFailure="quota exceeded"|"transaction aborted"|"repository unavailable"|"corrupt record"|"verification failure";
export interface DurableStorageDiagnostics{lastSavedAt:string;publishedRevision:number;unsavedCommand?:string;projectEntityBytes:number;releaseBytes:number;fixtureBytes:number;migrationBackupBytes:number;browserEstimate?:{usage:number;quota:number;label:"Browser storage estimate"};explanation:string;}
export interface DurablePublishedRevision{projectId:string;revision:number;publicationId:string;publishedAt:string;sourceDraftToken:string;state:ProjectState;}
export interface DurableSavedSchemaRecord{schema:Record<string,unknown>;token:string;revision:number;lastSavedAt:string;}
export type DurableSavedSchemaResult={status:"committed";schemaId:string;token:string;revision:number}|{status:"conflict";schemaId:string;baseToken:string|undefined;currentToken:string;current:Record<string,unknown>;pending:Record<string,unknown>};
export type DurableSavedSchemaBatchResult={status:"committed";changes:{schemaId:string;token:string;deleted:boolean}[]}|{status:"conflict";schemaId:string;baseToken:string|undefined;currentToken:string;current:Record<string,unknown>;pending:Record<string,unknown>|undefined};
export interface DurableProjectRoute{collectionKind?:string;collectionKinds?:readonly string[];entityId?:string;includeFlowGraphs?:boolean;includeFixtures?:boolean;includeReleases?:boolean;}
export function durableProjectRouteForWorkspace(collectionKind:string,entityId?:string):DurableProjectRoute{const dependencies:Record<string,readonly string[]>={pages:["profiles","pageGroups","applicabilitySets","assignments","schemaDrafts"],pageGroups:["profiles","pages","applicabilitySets","assignments","schemaDrafts"],events:["profiles","applicabilitySets","assignments","flows","schemaDrafts"],flows:["profiles","pages","pageGroups","events","applicabilitySets","assignments","schemaDrafts"],profiles:["applicabilitySets","assignments","schemaDrafts"],fixtures:["profiles","pages","pageGroups","events","flows"]};return{collectionKind,...(entityId?{entityId}:{}),collectionKinds:dependencies[collectionKind]??[],includeFlowGraphs:collectionKind==="flows",includeFixtures:collectionKind==="fixtures"};}

interface DurableTransaction{get<T>(store:DurableProjectStore,key:string):Promise<T|undefined>;getAll<T>(store:DurableProjectStore):Promise<{key:string;value:T}[]>;getPrefix<T>(store:DurableProjectStore,prefix:string):Promise<{key:string;value:T}[]>;put<T>(store:DurableProjectStore,key:string,value:T):Promise<void>;delete(store:DurableProjectStore,key:string):Promise<void>;}
interface DurableBackend{transaction<T>(stores:readonly DurableProjectStore[],mode:"readonly"|"readwrite",operation:(transaction:DurableTransaction)=>Promise<T>):Promise<T>;trace():{reads:DurableTraceEntry[];writes:DurableTraceEntry[]};clearTrace():void;}

const clone=<T>(value:T):T=>structuredClone(value);
const comparable=(value:unknown):unknown=>Array.isArray(value)?value.map(comparable):record(value)?Object.fromEntries(Object.keys(value).sort().map(key=>[key,comparable(value[key])])):value;
const same=(left:unknown,right:unknown):boolean=>JSON.stringify(comparable(left))===JSON.stringify(comparable(right));
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const bytes=(value:unknown):number=>new TextEncoder().encode(JSON.stringify(value)).byteLength;
const projectPrefix=(projectId:string)=>`${projectId}:`;
const fieldFor=(patch:DurablePatch)=>{const path=["entity","graph","release"].includes(patch.path[0]??"")?patch.path.slice(1):patch.path;return`${patch.store}/${patch.key}${path.length?`/${path.join("/")}`:""}`;};
const overlaps=(left:string,right:string)=>left===right||left.startsWith(`${right}/`)||right.startsWith(`${left}/`);

async function checksum(value:string):Promise<string>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest),(byte)=>byte.toString(16).padStart(2,"0")).join("");}
function changed(base:unknown,next:unknown,path:string[]=[]):{path:string[];before:unknown;after:unknown}[]{
  if(same(base,next))return[];
  if(record(base)&&record(next)){const keys=new Set([...Object.keys(base),...Object.keys(next)]);return[...keys].flatMap((key)=>changed(base[key],next[key],[...path,key]));}
  return[{path,before:clone(base),after:clone(next)}];
}
function putPath(value:unknown,path:string[],replacement:unknown):unknown{
  if(!path.length)return replacement===undefined?undefined:clone(replacement);
  const root=record(value)?clone(value):{},target=root as Record<string,unknown>;let cursor=target;
  for(const part of path.slice(0,-1)){const child=cursor[part];cursor[part]=record(child)?clone(child):{};cursor=cursor[part] as Record<string,unknown>;}
  const last=path.at(-1)!;if(replacement===undefined)delete cursor[last];else cursor[last]=clone(replacement);return root;
}
function projectParts(state:ProjectState):Map<string,{identity:DurableRecordIdentity;value:unknown}>{
  const project=clone(state.project),{collections,documentationFlowGraphs,releases=[],...rootProject}=project,parts=new Map<string,{identity:DurableRecordIdentity;value:unknown}>(),projectId=project.id,add=(store:DurableProjectStore,key:string,value:unknown)=>parts.set(`${store}/${key}`,{identity:{store,key},value:clone(value)});
  add("projectRoots",projectId,{project:rootProject,collectionKinds:Object.keys(collections),hasDocumentationFlowGraphs:documentationFlowGraphs!==undefined} satisfies DurableRootRecord);
  for(const[kind,entries]of Object.entries(collections) as [string,ProjectEntity[]][]){for(const entity of entries){const key=`${projectId}:${kind}:${entity.id}`,store=kind==="fixtures"?"fixtures":"projectEntities";add("projectEntityMetadata",key,{projectId,kind,id:entity.id,name:entity.name});add(store,key,{projectId,kind,entity});}}
  for(const[flowId,graph]of Object.entries((documentationFlowGraphs??{}) as Record<string,unknown>))add("flowGraphs",`${projectId}:${flowId}`,{projectId,flowId,graph});
  for(const release of releases)add("releases",`${projectId}:${release.id}`,{projectId,release});
  return parts;
}
function patchesBetween(base:ProjectState,next:ProjectState):DurablePatch[]{
  if(base.project.id!==next.project.id)throw new Error("A Draft command cannot replace project identity.");const before=projectParts(base),after=projectParts(next),keys=new Set([...before.keys(),...after.keys()]),patches:DurablePatch[]=[];
  for(const key of keys){const prior=before.get(key),later=after.get(key),identity=(later??prior)!.identity as DurablePatch extends {store:infer _Store}?DurableRecordIdentity:never;for(const difference of changed(prior?.value,later?.value))patches.push({store:identity.store as DurablePatch["store"],key:identity.key,...difference});}
  return patches;
}
export function durableDraftCommand(base:DurableLoadedProject,next:ProjectState,input:{commandId:string;label:string}):DurableDraftCommand{return{projectId:base.state.project.id,baseToken:base.draftToken,baseSequence:base.draftSequence,commandId:input.commandId,label:input.label,patches:patchesBetween(base.state,next),pendingState:clone(next)};}

class MemoryBackend implements DurableBackend{
  private stores=new Map<DurableProjectStore,Map<string,unknown>>(DURABLE_PROJECT_STORES.map((store)=>[store,new Map()]));private reads:DurableTraceEntry[]=[];private writes:DurableTraceEntry[]=[];
  async transaction<T>(stores:readonly DurableProjectStore[],mode:"readonly"|"readwrite",operation:(transaction:DurableTransaction)=>Promise<T>):Promise<T>{const working=new Map([...this.stores].map(([store,values])=>[store,new Map([...values].map(([key,value])=>[key,clone(value)]))])),read=(store:DurableProjectStore,key:string)=>{this.reads.push({store,key,operation:"read"});return working.get(store)!.get(key);},transaction:DurableTransaction={get:async<T>(store:DurableProjectStore,key:string):Promise<T|undefined>=>{const value=read(store,key);return value===undefined?undefined:clone(value) as T;},getAll:async<T>(store:DurableProjectStore):Promise<{key:string;value:T}[]>=>{this.reads.push({store,key:"*",operation:"read"});return[...working.get(store)!.entries()].map(([key,value])=>({key,value:clone(value) as T}));},getPrefix:async<T>(store:DurableProjectStore,prefix:string):Promise<{key:string;value:T}[]>=>{this.reads.push({store,key:`prefix:${prefix}`,operation:"read"});return[...working.get(store)!.entries()].filter(([key])=>key.startsWith(prefix)).map(([key,value])=>({key,value:clone(value) as T}));},put:async<T>(store:DurableProjectStore,key:string,value:T):Promise<void>=>{if(mode!=="readwrite"||!stores.includes(store))throw new Error(`Store ${store} is not writable in this transaction.`);working.get(store)!.set(key,clone(value));this.writes.push({store,key,operation:"write"});},delete:async(store:DurableProjectStore,key:string):Promise<void>=>{if(mode!=="readwrite"||!stores.includes(store))throw new Error(`Store ${store} is not writable in this transaction.`);working.get(store)!.delete(key);this.writes.push({store,key,operation:"delete"});}};const result=await operation(transaction);if(mode==="readwrite")this.stores=working;return result;}
  trace(){return{reads:clone(this.reads),writes:clone(this.writes)};}clearTrace(){this.reads=[];this.writes=[];}
}

class IndexedDbBackend implements DurableBackend{
  private reads:DurableTraceEntry[]=[];private writes:DurableTraceEntry[]=[];constructor(private readonly database:IDBDatabase){}
  async transaction<T>(stores:readonly DurableProjectStore[],mode:"readonly"|"readwrite",operation:(transaction:DurableTransaction)=>Promise<T>):Promise<T>{const native=this.database.transaction([...stores],mode),request=<T>(value:IDBRequest<T>)=>new Promise<T>((resolve,reject)=>{value.onsuccess=()=>resolve(value.result);value.onerror=()=>reject(value.error??new Error("IndexedDB request failed."));}),prefixEntries=<T>(store:DurableProjectStore,prefix:string)=>new Promise<{key:string;value:T}[]>((resolve,reject)=>{const entries:{key:string;value:T}[]=[],range=IDBKeyRange.bound(prefix,`${prefix}\uffff`),cursor=native.objectStore(store).openCursor(range);cursor.onerror=()=>reject(cursor.error??new Error("IndexedDB prefix read failed."));cursor.onsuccess=()=>{const current=cursor.result;if(!current){resolve(entries);return;}entries.push({key:String(current.key),value:clone(current.value as T)});current.continue();};}),adapter:DurableTransaction={get:async<T>(store:DurableProjectStore,key:string):Promise<T|undefined>=>{this.reads.push({store,key,operation:"read"});const value=await request(native.objectStore(store).get(key));return value===undefined?undefined:clone(value as T);},getAll:async<T>(store:DurableProjectStore):Promise<{key:string;value:T}[]>=>{this.reads.push({store,key:"*",operation:"read"});const keys=await request(native.objectStore(store).getAllKeys()),values=await request(native.objectStore(store).getAll());return values.map((value,index)=>({key:String(keys[index]),value:clone(value as T)}));},getPrefix:async<T>(store:DurableProjectStore,prefix:string):Promise<{key:string;value:T}[]>=>{this.reads.push({store,key:`prefix:${prefix}`,operation:"read"});return prefixEntries<T>(store,prefix);},put:async<T>(store:DurableProjectStore,key:string,value:T):Promise<void>=>{this.writes.push({store,key,operation:"write"});await request(native.objectStore(store).put(clone(value),key));},delete:async(store:DurableProjectStore,key:string):Promise<void>=>{this.writes.push({store,key,operation:"delete"});await request(native.objectStore(store).delete(key));}};let result:T;try{result=await operation(adapter);}catch(error){native.abort();throw error;}await new Promise<void>((resolve,reject)=>{native.oncomplete=()=>resolve();native.onabort=()=>reject(native.error??new DOMException("IndexedDB transaction aborted.","AbortError"));native.onerror=()=>reject(native.error??new Error("IndexedDB transaction failed."));});return result;}
  trace(){return{reads:clone(this.reads),writes:clone(this.writes)};}clearTrace(){this.reads=[];this.writes=[];}
}

const allStores=[...DURABLE_PROJECT_STORES];
const replaceableProjectStores=["projectEntityMetadata","projectEntities","flowGraphs","fixtures","releases"] as const;
async function replaceProjectParts(transaction:DurableTransaction,projectId:string,parts:Map<string,{identity:DurableRecordIdentity;value:unknown}>):Promise<void>{
  const expected=new Set([...parts.values()].map(({identity})=>`${identity.store}/${identity.key}`)),prefix=projectPrefix(projectId);
  for(const store of replaceableProjectStores)for(const{key}of await transaction.getPrefix(store,prefix))if(!expected.has(`${store}/${key}`))await transaction.delete(store,key);
  for(const{identity,value}of parts.values())await transaction.put(identity.store,identity.key,value);
}
const externalLineageKeys=new Set(["sourceLineage","externalLineage"]),identityMapContainers=new Set(["nodes","documentationFlowGraphs"]);
const referenceField=(key:string):boolean=>key==="id"||key==="currentRelease"||/(?:Id|Ids|Reference|References)$/.test(key);
function projectIdentityMapping(source:SpecificationProject,targetProjectId:string):Map<string,string>{
  const ids=new Set<string>();
  const collect=(value:unknown,external=false,parentKey=""):void=>{if(Array.isArray(value)){for(const entry of value)collect(entry,external,parentKey);return;}if(!record(value))return;for(const[key,entry]of Object.entries(value)){const outside=external||externalLineageKeys.has(key);if(!outside&&key==="id"&&typeof entry==="string")ids.add(entry);if(!outside&&identityMapContainers.has(parentKey))ids.add(key);collect(entry,outside,key);}};
  collect(source);return new Map([...ids].map(old=>[old,old===source.id?targetProjectId:`${targetProjectId}:${old}`]));
}
function remapProjectReferences(value:unknown,mapping:Map<string,string>,external=false,parentKey=""):unknown{
  if(Array.isArray(value))return value.map(entry=>typeof entry==="string"&&!external&&referenceField(parentKey)?mapping.get(entry)??entry:remapProjectReferences(entry,mapping,external,parentKey));
  if(!record(value))return value;
  return Object.fromEntries(Object.entries(value).map(([key,entry])=>{const outside=external||externalLineageKeys.has(key),mappedKey=!outside&&identityMapContainers.has(parentKey)?mapping.get(key)??key:key;if(typeof entry==="string"&&!outside&&referenceField(key))return[mappedKey,mapping.get(entry)??entry];return[mappedKey,remapProjectReferences(entry,mapping,outside,key)];}));
}
export class DurableProjectRepository{
  private failure:DurableFailure|undefined;private listeners=new Set<(notification:DurableProjectNotification)=>void>();private metadataListeners=new Set<(notification:DurableProjectMetadataNotification)=>void>();private activeListeners=new Set<(notification:DurableActiveContextNotification)=>void>();private schemaListeners=new Set<(change:{schemaId:string;token:string;deleted:boolean})=>void>();
  constructor(private readonly backend:DurableBackend,private readonly options:{now:()=>string;token:()=>string}){}
  trace(){return this.backend.trace();}clearTrace(){this.backend.clearTrace();}injectFailure(failure:DurableFailure){this.failure=failure;}clearFailure(){this.failure=undefined;}
  subscribe(listener:(notification:DurableProjectNotification)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  subscribeProjectMetadata(listener:(notification:DurableProjectMetadataNotification)=>void){this.metadataListeners.add(listener);return()=>this.metadataListeners.delete(listener);}
  subscribeActiveContext(listener:(notification:DurableActiveContextNotification)=>void){this.activeListeners.add(listener);return()=>this.activeListeners.delete(listener);}
  subscribeSavedSchemas(listener:(change:{schemaId:string;token:string;deleted:boolean})=>void){this.schemaListeners.add(listener);return()=>this.schemaListeners.delete(listener);}
  private fail(label:string):void{if(!this.failure)return;const names:Record<DurableFailure,string>={"quota exceeded":"QuotaExceededError","transaction aborted":"AbortError","repository unavailable":"InvalidStateError","corrupt record":"DataError","verification failure":"OperationError"},error=new DOMException(`${label} was not committed: ${this.failure}. The last Saved Draft is unchanged.`,names[this.failure]);throw error;}
  private notify(notification:DurableProjectNotification):void{for(const listener of this.listeners)listener(clone(notification));if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-project-changes");channel.postMessage(notification);channel.close();}if(typeof chrome!=="undefined"&&chrome.runtime?.id)void chrome.runtime.sendMessage(notification).catch(()=>{});}
  async putProjectMetadataOnly(state:ProjectState,input:{draftToken?:string;draftSequence?:number;publishedRevision?:number;publishedProject?:SpecificationProject;active?:boolean;navigation?:ProjectNavigation}={}):Promise<DurableProjectMetadata>{
    const projectId=state.project.id,draftToken=input.draftToken??this.options.token(),lastSavedAt=this.options.now(),parts=projectParts(state),publishedRevision=input.publishedRevision??0,declaredRelease=state.project.releases.find(release=>release.revision===publishedRevision),publishedProject=input.publishedProject??(declaredRelease?{...clone(state.project),collections:clone(declaredRelease.snapshot),releases:state.project.releases.filter(candidate=>candidate.revision<=publishedRevision),currentRelease:declaredRelease.id}:undefined);
    if(publishedRevision>0&&(!declaredRelease||!publishedProject))throw new DOMException(`Project ${projectId} cannot claim Published revision ${publishedRevision} without a matching release snapshot.`,"DataError");
    if(publishedProject&&(publishedProject.id!==projectId||publishedProject.currentRelease!==declaredRelease?.id||!same(publishedProject.collections,declaredRelease?.snapshot)))throw new DOMException(`Published project ${projectId}:${publishedRevision} does not match its declared release identity and collections.`,"DataError");
    const metadata=await this.backend.transaction(allStores,"readwrite",async transaction=>{
      const revisionKey=`${projectId}:${publishedRevision}`,existingMetadata=await transaction.get<DurableProjectMetadata>("projectMetadata",projectId),existingRevision=publishedRevision>0?await transaction.get<DurablePublishedRevision>("projectRevisions",revisionKey):undefined;
      if(existingMetadata)throw new DOMException(`Project ${projectId} already exists; create/import cannot replace a durable project snapshot.`,"ConstraintError");
      if(existingRevision)throw new DOMException(`Published revision ${publishedRevision} for ${projectId} already exists and is immutable.`,"ConstraintError");
      const draftSequence=input.draftSequence??0;await replaceProjectParts(transaction,projectId,parts);const value:DurableProjectMetadata={projectId,name:state.project.name,site:state.project.site,owner:String(state.project.owner??""),draftToken,draftSequence,publishedRevision,lastSavedAt,fieldVersions:Object.fromEntries([...parts.keys()].map(key=>[key,draftSequence])),active:Boolean(input.active),...(state.draft?{draft:clone(state.draft)}:{}),...(input.navigation?{navigation:clone(input.navigation)}:{})};await transaction.put("projectMetadata",projectId,value);if(input.active)await transaction.put("settings","activeProjectId",projectId);
      if(publishedRevision>0&&declaredRelease&&publishedProject&&!existingRevision){const revision:DurablePublishedRevision={projectId,revision:publishedRevision,publicationId:declaredRelease.id,publishedAt:declaredRelease.createdAt,sourceDraftToken:draftToken,state:{project:clone(publishedProject),history:{undo:[],redo:[]}}};await transaction.put("projectRevisions",revisionKey,revision);}return value;
    });
    const notification:DurableProjectMetadataNotification={type:"durable-project-metadata-change",projectId,draftToken,changeToken:this.options.token()};for(const listener of this.metadataListeners)listener(clone(notification));if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-project-metadata");channel.postMessage(notification);channel.close();}return metadata;
  }
  async putProject(state:ProjectState,input:{draftToken?:string;draftSequence?:number;publishedRevision?:number;active?:boolean;navigation?:ProjectNavigation}={}):Promise<DurableLoadedProject>{await this.putProjectMetadataOnly(state,input);return this.loadProject(state.project.id);}
  async listProjectMetadata():Promise<DurableProjectMetadata[]>{return this.backend.transaction(["projectMetadata","settings"],"readonly",async transaction=>{const active=await transaction.get<string>("settings","activeProjectId"),entries=await transaction.getAll<DurableProjectMetadata>("projectMetadata");return entries.map(({value})=>({...value,active:value.projectId===active})).sort((left,right)=>left.name.localeCompare(right.name));});}
  async activeProjectId():Promise<string|undefined>{return this.backend.transaction(["settings"],"readonly",transaction=>transaction.get("settings","activeProjectId"));}
  async setProjectNavigation(projectId:string,navigation?:ProjectNavigation):Promise<void>{const changeToken=this.options.token(),metadata=await this.backend.transaction(["projectMetadata"],"readwrite",async transaction=>{const current=await transaction.get<DurableProjectMetadata>("projectMetadata",projectId);if(!current)throw new Error(`Unknown durable project ${projectId}.`);const next={...current};if(navigation)next.navigation=clone(navigation);else delete next.navigation;await transaction.put("projectMetadata",projectId,next);return next;});const notification:DurableProjectMetadataNotification={type:"durable-project-metadata-change",projectId,draftToken:metadata.draftToken,changeToken};for(const listener of this.metadataListeners)listener(clone(notification));if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-project-metadata");channel.postMessage(notification);channel.close();}}
  async setActiveProject(projectId:string):Promise<DurableActiveContextNotification>{const token=this.options.token(),notification:DurableActiveContextNotification={type:"durable-active-context-change",projectId,token};await this.backend.transaction(["projectMetadata","settings"],"readwrite",async transaction=>{if(!await transaction.get("projectMetadata",projectId))throw new Error(`Unknown durable project ${projectId}.`);await transaction.put("settings","activeProjectId",projectId);await transaction.put("settings","activeProjectChange",{projectId,token,at:this.options.now()});});for(const listener of this.activeListeners)listener(clone(notification));if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-active-context");channel.postMessage(notification);channel.close();}if(typeof chrome!=="undefined"&&chrome.runtime?.id)void chrome.runtime.sendMessage(notification).catch(()=>{});return notification;}
  async deleteProject(input:{projectId:string;baseToken:string;label:string}):Promise<void>{this.fail(input.label);await this.backend.transaction(allStores,"readwrite",async transaction=>{const active=await transaction.get<string>("settings","activeProjectId"),metadata=await transaction.get<DurableProjectMetadata>("projectMetadata",input.projectId);if(!metadata)throw new Error(`Unknown durable project ${input.projectId}.`);if(active===input.projectId)throw new Error("Switch to another project before deleting the active project.");if(metadata.draftToken!==input.baseToken)throw new DOMException(`${input.label} requires current Draft token ${metadata.draftToken}.`,"AbortError");for(const store of [...replaceableProjectStores,"projectRevisions"] as const)for(const{key}of await transaction.getPrefix(store,projectPrefix(input.projectId)))await transaction.delete(store,key);await transaction.delete("projectRoots",input.projectId);await transaction.delete("projectMetadata",input.projectId);});}
  async loadProject(projectId:string):Promise<DurableLoadedProject>{return this.backend.transaction(["projectMetadata","projectRoots","projectEntities","flowGraphs","fixtures","releases"],"readonly",async transaction=>{const metadata=await transaction.get<DurableProjectMetadata>("projectMetadata",projectId),root=await transaction.get<DurableRootRecord>("projectRoots",projectId);if(!metadata||!root)throw new Error(`Durable project ${projectId} is unavailable.`);const prefix=projectPrefix(projectId),entityRecords=await transaction.getPrefix<{projectId:string;kind:string;entity:ProjectEntity}>("projectEntities",prefix),fixtureRecords=await transaction.getPrefix<{projectId:string;kind:string;entity:ProjectEntity}>("fixtures",prefix),graphs=await transaction.getPrefix<{flowId:string;graph:unknown}>("flowGraphs",prefix),releases=await transaction.getPrefix<{release:SpecificationProject["releases"][number]}>("releases",prefix),collections=Object.fromEntries(root.collectionKinds.map(kind=>[kind,[]])) as unknown as SpecificationProject["collections"];
      for(const{value}of[...entityRecords,...fixtureRecords])((collections as unknown as Record<string,ProjectEntity[]>)[value.kind]??=[]).push(clone(value.entity));const project={...clone(root.project),collections,...(root.hasDocumentationFlowGraphs?{documentationFlowGraphs:Object.fromEntries(graphs.map(({value})=>[value.flowId,clone(value.graph)]))}:{}),releases:releases.map(({value})=>clone(value.release))} as unknown as SpecificationProject,state:ProjectState={project,...(metadata.draft?{draft:clone(metadata.draft)}:{}),history:{undo:[],redo:[]}};return{state,draftToken:metadata.draftToken,draftSequence:metadata.draftSequence??0,publishedRevision:metadata.publishedRevision,lastSavedAt:metadata.lastSavedAt,...(metadata.navigation?{navigation:clone(metadata.navigation)}:{})};});}
  async loadProjectRoute(projectId:string,route:DurableProjectRoute):Promise<DurableLoadedProject>{return this.loadVisibleProjectRoute(projectId,route);}
  async loadVisibleProjectRoute(projectId:string,route:DurableProjectRoute):Promise<DurableLoadedProject>{
    return this.backend.transaction(["projectMetadata","projectRoots","projectEntityMetadata","projectEntities","flowGraphs","fixtures","releases"],"readonly",async transaction=>{
      const metadata=await transaction.get<DurableProjectMetadata>("projectMetadata",projectId),root=await transaction.get<DurableRootRecord>("projectRoots",projectId);if(!metadata||!root)throw new Error(`Durable project ${projectId} is unavailable.`);
      const collections=Object.fromEntries(root.collectionKinds.map(kind=>[kind,[]])) as unknown as SpecificationProject["collections"],compact=await transaction.getPrefix<{kind:string;id:string;name:string}>("projectEntityMetadata",projectPrefix(projectId));for(const{value}of compact)((collections as unknown as Record<string,ProjectEntity[]>)[value.kind]??=[]).push({id:value.id,name:value.name,placeholder:true});
      const kinds=[...new Set([...(route.collectionKind?[route.collectionKind]:[]),...(route.collectionKinds??[])])];for(const kind of kinds){const store=kind==="fixtures"?"fixtures":"projectEntities",prefix=`${projectId}:${kind}:`,selected=route.entityId&&kind===route.collectionKind?await transaction.get<{kind:string;entity:ProjectEntity}>(store,`${prefix}${route.entityId}`):undefined,visible=selected?[selected]:route.entityId&&kind===route.collectionKind?[]:(await transaction.getPrefix<{kind:string;entity:ProjectEntity}>(store,prefix)).map(({value})=>value),target=(collections as unknown as Record<string,ProjectEntity[]>)[kind]??[];for(const value of visible){const index=target.findIndex(({id})=>id===value.entity.id);if(index>=0)target[index]=clone(value.entity);else target.push(clone(value.entity));}(collections as unknown as Record<string,ProjectEntity[]>)[kind]=target;}
      const graphs=route.includeFlowGraphs?await transaction.getPrefix<{flowId:string;graph:unknown}>("flowGraphs",projectPrefix(projectId)):[],fixtures=route.includeFixtures&&!kinds.includes("fixtures")?await transaction.getPrefix<{kind:string;entity:ProjectEntity}>("fixtures",projectPrefix(projectId)):[];for(const{value}of fixtures){const target=(collections as unknown as Record<string,ProjectEntity[]>)[value.kind]??=[],index=target.findIndex(({id})=>id===value.entity.id);if(index>=0)target[index]=clone(value.entity);else target.push(clone(value.entity));}const releases=route.includeReleases?await transaction.getPrefix<{release:SpecificationProject["releases"][number]}>("releases",projectPrefix(projectId)):[],project={...clone(root.project),collections,...(root.hasDocumentationFlowGraphs&&route.includeFlowGraphs?{documentationFlowGraphs:Object.fromEntries(graphs.map(({value})=>[value.flowId,clone(value.graph)]))}:{}),releases:releases.map(({value})=>clone(value.release))} as unknown as SpecificationProject;
      return{state:{project,...(metadata.draft?{draft:clone(metadata.draft)}:{}),history:{undo:[],redo:[]}},draftToken:metadata.draftToken,draftSequence:metadata.draftSequence??0,publishedRevision:metadata.publishedRevision,lastSavedAt:metadata.lastSavedAt,...(metadata.navigation?{navigation:clone(metadata.navigation)}:{})};
    });
  }
  async saveDraft(command:DurableDraftCommand):Promise<DurableDraftResult>{this.fail(command.label);const stores=["projectMetadata","projectRoots","projectEntityMetadata","projectEntities","flowGraphs","fixtures","releases"] as const,result=await this.backend.transaction(stores,"readwrite",async transaction=>{const metadata=await transaction.get<DurableProjectMetadata>("projectMetadata",command.projectId);if(!metadata)throw new Error(`Durable project ${command.projectId} is unavailable.`);const pendingFields=command.patches.map(fieldFor),stale=metadata.draftToken!==command.baseToken||metadata.draftSequence!==command.baseSequence,invalidBase=command.baseSequence>metadata.draftSequence||(command.baseSequence===metadata.draftSequence&&metadata.draftToken!==command.baseToken),currentFields=stale?(invalidBase?pendingFields:Object.entries(metadata.fieldVersions??{}).filter(([,sequence])=>sequence>command.baseSequence).map(([field])=>field)):[],conflictingFields=pendingFields.filter(field=>currentFields.some(current=>overlaps(field,current)));
      if(conflictingFields.length){const currentValues:Record<string,unknown>={},pendingValues:Record<string,unknown>={};for(const patch of command.patches.filter(patch=>conflictingFields.includes(fieldFor(patch)))){const current=await transaction.get<unknown>(patch.store,patch.key);currentValues[fieldFor(patch)]=patch.path.reduce<unknown>((value,part)=>record(value)?value[part]:undefined,current);pendingValues[fieldFor(patch)]=clone(patch.after);}return{status:"conflict" as const,projectId:command.projectId,baseToken:command.baseToken,currentToken:metadata.draftToken,commandId:command.commandId,label:command.label,pendingFields,currentFields:[...new Set(currentFields)],conflictingFields,currentValues,pendingValues};}
      const changed=new Map<string,DurableRecordIdentity>();for(const patch of command.patches){const current=await transaction.get<unknown>(patch.store,patch.key),next=putPath(current,patch.path,patch.after);if(next===undefined)await transaction.delete(patch.store,patch.key);else await transaction.put(patch.store,patch.key,next);changed.set(`${patch.store}/${patch.key}`,{store:patch.store,key:patch.key});}
      const root=await transaction.get<DurableRootRecord>("projectRoots",command.projectId);if(!root)throw new DOMException(`Draft ${command.label} did not leave a canonical project root.`,"DataError");const draftToken=this.options.token(),lastSavedAt=this.options.now(),draftSequence=(metadata.draftSequence??0)+1,fieldVersions={...(metadata.fieldVersions??{})};for(const field of pendingFields)fieldVersions[field]=draftSequence;const nextMetadata:DurableProjectMetadata={...metadata,name:String(root.project.name),site:String(root.project.site),owner:String(root.project.owner??""),draftToken,draftSequence,lastSavedAt,fieldVersions};if(command.pendingState.draft)nextMetadata.draft=clone(command.pendingState.draft);else delete nextMetadata.draft;const metadataIdentity={store:"projectMetadata" as const,key:command.projectId};await transaction.put("projectMetadata",command.projectId,nextMetadata);changed.set(`projectMetadata/${command.projectId}`,metadataIdentity);const changedRecords=[...changed.values()];return{status:stale?"rebased" as const:"committed" as const,projectId:command.projectId,draftToken,draftSequence,publishedRevision:metadata.publishedRevision,changedRecords,notification:{type:"durable-project-change" as const,projectId:command.projectId,draftToken,draftSequence,commandId:command.commandId,changedRecords}};});if(result.status!=="conflict")this.notify(result.notification);return result;}
  async publish(projectId:string,baseToken:string,input:{publicationId:string}):Promise<{draftToken:string;publishedRevision:number}>{this.fail("Publish project");const current=await this.loadProject(projectId),result=await this.backend.transaction(["projectMetadata","projectRevisions"],"readwrite",async transaction=>{const metadata=await transaction.get<DurableProjectMetadata>("projectMetadata",projectId);if(!metadata)throw new Error(`Durable project ${projectId} is unavailable.`);if(metadata.draftToken!==baseToken)throw new Error(`Publish requires current Draft token ${metadata.draftToken}.`);const publishedRevision=metadata.publishedRevision+1,release=current.state.project.releases.find(candidate=>candidate.id===input.publicationId&&candidate.revision===publishedRevision);if(!release)throw new DOMException(`Publish revision ${publishedRevision} requires matching release ${input.publicationId}.`,"DataError");const draftToken=this.options.token(),at=this.options.now(),revisionKey=`${projectId}:${publishedRevision}`,draftSequence=(metadata.draftSequence??0)+1,publishedProject={...clone(current.state.project),collections:clone(release.snapshot),releases:current.state.project.releases.filter(candidate=>candidate.revision<=publishedRevision),currentRelease:release.id},revision:DurablePublishedRevision={projectId,revision:publishedRevision,publicationId:input.publicationId,publishedAt:at,sourceDraftToken:baseToken,state:{project:publishedProject,history:{undo:[],redo:[]}}},changedRecords:DurableRecordIdentity[]=[{store:"projectRevisions",key:revisionKey},{store:"projectMetadata",key:projectId}],fieldVersions={...(metadata.fieldVersions??{}),[`projectRevisions/${revisionKey}`]:draftSequence};await transaction.put("projectRevisions",revisionKey,revision);await transaction.put("projectMetadata",projectId,{...metadata,publishedRevision,draftToken,draftSequence,lastSavedAt:at,fieldVersions});return{draftToken,draftSequence,publishedRevision,changedRecords};});this.notify({type:"durable-project-change",projectId,draftToken:result.draftToken,draftSequence:result.draftSequence,commandId:input.publicationId,changedRecords:result.changedRecords});return{draftToken:result.draftToken,publishedRevision:result.publishedRevision};}
  async loadPublishedRevision(projectId:string,revision:number):Promise<DurablePublishedRevision>{const snapshot=await this.backend.transaction(["projectRevisions"],"readonly",transaction=>transaction.get<DurablePublishedRevision>("projectRevisions",`${projectId}:${revision}`));if(!snapshot)throw new Error(`Published revision ${revision} for ${projectId} is unavailable.`);return clone(snapshot);}
  async loadCurrentPublishedProject(projectId:string):Promise<{revision:number;project:SpecificationProject}|undefined>{const metadata=(await this.listProjectMetadata()).find(entry=>entry.projectId===projectId);if(!metadata?.publishedRevision)return undefined;const snapshot=await this.loadPublishedRevision(projectId,metadata.publishedRevision);return{revision:metadata.publishedRevision,project:clone(snapshot.state.project)};}
  async hashRecord(store:DurableProjectStore,key:string):Promise<string>{const value=await this.backend.transaction([store],"readonly",transaction=>transaction.get(store,key));return checksum(JSON.stringify(value));}
  async hashProject(projectId:string):Promise<string>{const loaded=await this.loadProject(projectId);return checksum(JSON.stringify(loaded));}
  async storageDiagnostics(projectId:string,estimate?:{usage:number;quota:number},unsavedCommand?:string):Promise<DurableStorageDiagnostics>{const loaded=await this.loadProject(projectId),prefix=projectPrefix(projectId),sizes=await this.backend.transaction(["projectEntities","flowGraphs","fixtures","releases","projectRevisions","migrationBackups"],"readonly",async transaction=>{const selected=async(store:DurableProjectStore)=>(await transaction.getPrefix(store,prefix)).reduce((total,{value})=>total+bytes(value),0);return{projectEntityBytes:await selected("projectEntities")+await selected("flowGraphs"),releaseBytes:await selected("releases")+await selected("projectRevisions"),fixtureBytes:await selected("fixtures"),migrationBackupBytes:(await transaction.getAll("migrationBackups")).reduce((total,{value})=>total+bytes(value),0)};});return{lastSavedAt:loaded.lastSavedAt,publishedRevision:loaded.publishedRevision,...(unsavedCommand?{unsavedCommand}:{}),...sizes,...(estimate?{browserEstimate:{...estimate,label:"Browser storage estimate" as const}}:{}),explanation:"Unlimited storage reduces quota risk; it does not make a failed write successful or provide infinite disk."};}
  async migrationBackup():Promise<{sources:{key:string;bytes:number;checksum:string;value:string}[]}>{return this.backend.transaction(["migrationBackups"],"readonly",async transaction=>(await transaction.getAll<{sources:{key:string;bytes:number;checksum:string;value:string}[]}>("migrationBackups"))[0]?.value??{sources:[]});}
  private normalizeSavedSchema(value:Record<string,unknown>):DurableSavedSchemaRecord{if(record(value.schema)&&typeof value.token==="string"){const{tokenHistory:_tokenHistory,...current}=value;return clone(current) as unknown as DurableSavedSchemaRecord;}const token=`legacy-schema:${String(value.id)}`;return{schema:clone(value),token,revision:Number(value.version??0),lastSavedAt:"legacy"};}
  async savedSchemaRecords():Promise<DurableSavedSchemaRecord[]>{return this.backend.transaction(["savedSchemas"],"readonly",async transaction=>(await transaction.getAll<Record<string,unknown>>("savedSchemas")).map(({value})=>this.normalizeSavedSchema(value)));}
  async listSavedSchemaMetadata():Promise<{id:string;name:string;version:number;token:string}[]>{return(await this.savedSchemaRecords()).map(({schema,token})=>({id:String(schema.id),name:String(schema.name),version:Number(schema.version??0),token}));}
  async savedSchemas():Promise<Record<string,unknown>[]>{return(await this.savedSchemaRecords()).map(({schema})=>clone(schema));}
  async applySavedSchemaBatch(input:{upserts:{schema:Record<string,unknown>;baseToken?:string}[];deletes:{schemaId:string;baseToken:string}[];label:string}):Promise<DurableSavedSchemaBatchResult>{this.fail(input.label);const result=await this.backend.transaction(["savedSchemas"],"readwrite",async transaction=>{const checked=new Map<string,DurableSavedSchemaRecord|undefined>();for(const operation of input.upserts){const schemaId=String(operation.schema.id);if(!schemaId)throw new Error("A saved schema command requires an id.");const raw=await transaction.get<Record<string,unknown>>("savedSchemas",schemaId),current=raw?this.normalizeSavedSchema(raw):undefined;checked.set(schemaId,current);if(current?.token!==operation.baseToken&&Boolean(current||operation.baseToken))return{status:"conflict" as const,schemaId,baseToken:operation.baseToken,currentToken:current?.token??"missing",current:clone(current?.schema??{}),pending:clone(operation.schema)};}for(const operation of input.deletes){const raw=await transaction.get<Record<string,unknown>>("savedSchemas",operation.schemaId),current=raw?this.normalizeSavedSchema(raw):undefined;checked.set(operation.schemaId,current);if(!current||current.token!==operation.baseToken)return{status:"conflict" as const,schemaId:operation.schemaId,baseToken:operation.baseToken,currentToken:current?.token??"missing",current:clone(current?.schema??{}),pending:undefined};}const changes:{schemaId:string;token:string;deleted:boolean}[]=[];for(const operation of input.upserts){const schemaId=String(operation.schema.id),current=checked.get(schemaId),token=this.options.token(),recordValue:DurableSavedSchemaRecord={schema:clone(operation.schema),token,revision:(current?.revision??0)+1,lastSavedAt:this.options.now()};await transaction.put("savedSchemas",schemaId,recordValue);changes.push({schemaId,token,deleted:false});}for(const operation of input.deletes){const token=this.options.token();await transaction.delete("savedSchemas",operation.schemaId);changes.push({schemaId:operation.schemaId,token,deleted:true});}return{status:"committed" as const,changes};});if(result.status==="committed")for(const change of result.changes){for(const listener of this.schemaListeners)listener(clone(change));if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-saved-schemas");channel.postMessage(change);channel.close();}}return result;}
  async saveSavedSchema(input:{schema:Record<string,unknown>;baseToken?:string;label:string}):Promise<DurableSavedSchemaResult>{const result=await this.applySavedSchemaBatch({upserts:[{schema:input.schema,...(input.baseToken?{baseToken:input.baseToken}:{})}],deletes:[],label:input.label});if(result.status==="conflict")return{...result,pending:result.pending??clone(input.schema)};const change=result.changes[0]!;return{status:"committed",schemaId:change.schemaId,token:change.token,revision:Number(input.schema.version??0)+1};}
  async deleteSavedSchema(input:{schemaId:string;baseToken:string;label:string}):Promise<void>{const result=await this.applySavedSchemaBatch({upserts:[],deletes:[{schemaId:input.schemaId,baseToken:input.baseToken}],label:input.label});if(result.status==="conflict")throw new DOMException(`${input.label} requires current schema token ${result.currentToken}.`,"AbortError");}
  async claimLegacyMigration(owner:string):Promise<"claimed"|"complete"|"busy">{return this.backend.transaction(["settings","migrationReceipts"],"readwrite",async transaction=>{const receipt=await transaction.get<{verified:boolean}>("migrationReceipts","legacy-v1");if(receipt?.verified)return"complete";const lock=await transaction.get<{owner:string;expiresAt:number}>("settings","legacyMigrationLock");if(lock&&lock.expiresAt>Date.now()&&lock.owner!==owner)return"busy";await transaction.put("settings","legacyMigrationLock",{owner,at:this.options.now(),expiresAt:Date.now()+300_000});return"claimed";});}
  async legacyMigrationComplete():Promise<boolean>{return this.backend.transaction(["migrationReceipts"],"readonly",async transaction=>(await transaction.get<{verified:boolean}>("migrationReceipts","legacy-v1"))?.verified===true);}
  async waitForLegacyMigration():Promise<boolean>{if(await this.legacyMigrationComplete())return true;return new Promise<boolean>((resolve)=>{let settled=false,timer:number|undefined,channel:BroadcastChannel|undefined;const finish=(value:boolean)=>{if(settled)return;settled=true;if(timer!==undefined)clearTimeout(timer);channel?.close();resolve(value);},poll=async()=>{if(await this.legacyMigrationComplete()){finish(true);return;}const lock=await this.backend.transaction(["settings"],"readonly",transaction=>transaction.get<{expiresAt:number}>("settings","legacyMigrationLock"));if(!lock||lock.expiresAt<=Date.now()){finish(false);return;}timer=setTimeout(poll,250) as unknown as number;};if(typeof BroadcastChannel!=="undefined"){channel=new BroadcastChannel("my-chrome-utilities.durable-migration");channel.addEventListener("message",()=>void poll());(channel as unknown as {unref?:()=>void}).unref?.();}void poll();});}
  async importLegacy(owner:string,records:{projects:{state:ProjectState;revision:number;active:boolean;navigation?:ProjectNavigation}[];schemas:Record<string,unknown>[];backup:{sources:{key:string;bytes:number;checksum:string;value:string}[]}}):Promise<void>{await this.backend.transaction(allStores,"readwrite",async transaction=>{const lock=await transaction.get<{owner:string}>("settings","legacyMigrationLock");if(lock?.owner!==owner)throw new DOMException("Legacy migration lease is not owned by this context.","AbortError");for(const entry of records.projects){const draftToken=this.options.token(),parts=projectParts(entry.state),publishedRevision=Math.max(0,...entry.state.project.releases.map(({revision})=>revision));await replaceProjectParts(transaction,entry.state.project.id,parts);await transaction.put("projectMetadata",entry.state.project.id,{projectId:entry.state.project.id,name:entry.state.project.name,site:entry.state.project.site,owner:String(entry.state.project.owner??""),draftToken,draftSequence:entry.revision,publishedRevision,lastSavedAt:this.options.now(),fieldVersions:Object.fromEntries([...parts.keys()].map(key=>[key,entry.revision])),active:entry.active,...(entry.state.draft?{draft:clone(entry.state.draft)}:{}),...(entry.navigation?{navigation:clone(entry.navigation)}:{})} satisfies DurableProjectMetadata);for(const release of entry.state.project.releases){const publishedProject={...clone(entry.state.project),collections:clone(release.snapshot),releases:entry.state.project.releases.filter(candidate=>candidate.revision<=release.revision),currentRelease:release.id},revision:DurablePublishedRevision={projectId:entry.state.project.id,revision:release.revision,publicationId:release.id,publishedAt:release.createdAt,sourceDraftToken:draftToken,state:{project:publishedProject,history:{undo:[],redo:[]}}};await transaction.put("projectRevisions",`${entry.state.project.id}:${release.revision}`,revision);}if(entry.active)await transaction.put("settings","activeProjectId",entry.state.project.id);}for(const schema of records.schemas){const token=this.options.token();await transaction.put("savedSchemas",String(schema.id),{schema:clone(schema),token,revision:Number(schema.version??0),lastSavedAt:this.options.now()} satisfies DurableSavedSchemaRecord);}await transaction.put("migrationBackups","legacy-v1",records.backup);await transaction.put("migrationReceipts","legacy-v1",{version:1,projectIds:records.projects.map(({state})=>state.project.id),sourceChecksums:records.backup.sources.map(({key,checksum})=>({key,checksum})),verified:false,phase:"records-written",owner,at:this.options.now()});});}
  async verifyLegacyImport(records:{projects:{state:ProjectState;navigation?:ProjectNavigation}[];schemas:Record<string,unknown>[];backup:{sources:{key:string;checksum:string}[]}}):Promise<void>{for(const entry of records.projects){const loaded=await this.loadProject(entry.state.project.id);if(!same(loaded.state.project,entry.state.project))throw new DOMException(`Migration verification failed for ${entry.state.project.id}: ${differingFields(loaded.state.project,entry.state.project).join(", ")}.`,"OperationError");if(!same(loaded.navigation,entry.navigation))throw new DOMException(`Migration verification failed for ${entry.state.project.id} navigation.`,"OperationError");for(const release of entry.state.project.releases){const revision=await this.loadPublishedRevision(entry.state.project.id,release.revision);if(!same(revision.state.project.collections,release.snapshot))throw new DOMException(`Migration verification failed for immutable release ${release.id}.`,"OperationError");}}const schemas=await this.savedSchemas();for(const schema of records.schemas)if(!schemas.some(candidate=>String(candidate.id)===String(schema.id)&&same(candidate,schema)))throw new DOMException(`Migration verification failed for saved schema ${String(schema.id)}.`,"OperationError");const backup=await this.migrationBackup();if(!same(backup.sources.map(({key,checksum})=>({key,checksum})),records.backup.sources.map(({key,checksum})=>({key,checksum}))))throw new DOMException("Migration backup manifest verification failed.","OperationError");}
  async completeLegacyMigration(owner:string):Promise<void>{await this.backend.transaction(["settings","migrationReceipts"],"readwrite",async transaction=>{const lock=await transaction.get<{owner:string}>("settings","legacyMigrationLock"),receipt=await transaction.get<Record<string,unknown>>("migrationReceipts","legacy-v1");if(lock?.owner!==owner||!receipt)throw new DOMException("Legacy migration cannot complete without its verified lease and receipt.","AbortError");await transaction.put("migrationReceipts","legacy-v1",{...receipt,verified:true,phase:"verified",verifiedAt:this.options.now()});await transaction.delete("settings","legacyMigrationLock");});if(typeof BroadcastChannel!=="undefined"){const channel=new BroadcastChannel("my-chrome-utilities.durable-migration");channel.postMessage({status:"verified"});channel.close();}}
  async abandonLegacyMigration(owner:string):Promise<void>{await this.backend.transaction(["settings"],"readwrite",async transaction=>{const lock=await transaction.get<{owner:string}>("settings","legacyMigrationLock");if(lock?.owner===owner)await transaction.delete("settings","legacyMigrationLock");});}
  async exportProject(projectId:string):Promise<Record<string,unknown>>{const loaded=await this.loadProject(projectId),publishedProject=loaded.publishedRevision?(await this.loadPublishedRevision(projectId,loaded.publishedRevision)).state.project:undefined;return{format:"my-chrome-utilities.durable-project-bundle",version:1,sourceProjectId:projectId,sourceName:loaded.state.project.name,publishedRevision:loaded.publishedRevision,...(publishedProject?{publishedProject:clone(publishedProject)}:{}),project:clone(loaded.state.project),draft:clone(loaded.state.draft)};}
  async exportRecoveryBundle(projectId:string):Promise<Record<string,unknown>>{const project=await this.exportProject(projectId),metadata=(await this.listProjectMetadata()).find(entry=>entry.projectId===projectId),migrationBackup=await this.migrationBackup();return{format:"my-chrome-utilities.durable-recovery-bundle",version:1,createdAt:this.options.now(),project,metadata:metadata?clone(metadata):undefined,migrationBackup};}
  async exportRepositoryRecoveryBundle():Promise<Record<string,unknown>>{const metadata=await this.listProjectMetadata(),projects=await Promise.all(metadata.map(({projectId})=>this.exportProject(projectId))),savedSchemas=await this.savedSchemaRecords(),internal=await this.backend.transaction(["projectRevisions","settings","migrationReceipts","migrationBackups"],"readonly",async transaction=>({projectRevisions:await transaction.getAll("projectRevisions"),settings:await transaction.getAll("settings"),migrationReceipts:await transaction.getAll("migrationReceipts"),migrationBackups:await transaction.getAll("migrationBackups")}));return{format:"my-chrome-utilities.durable-repository-recovery-bundle",version:1,createdAt:this.options.now(),metadata:clone(metadata),projects:clone(projects),savedSchemas:clone(savedSchemas),...clone(internal)};}
  async importProject(bundle:Record<string,unknown>,input:{projectId:string;name:string}):Promise<{projectId:string;active:false}>{if(bundle.format!=="my-chrome-utilities.durable-project-bundle"||!record(bundle.project))throw new Error("Choose a durable project bundle.");const source=clone(bundle.project) as unknown as SpecificationProject,mapping=projectIdentityMapping(source,input.projectId),project=remapProjectReferences(source,mapping) as SpecificationProject;project.name=input.name;const publishedRevision=Number(bundle.publishedRevision??0);if(publishedRevision>0&&!record(bundle.publishedProject))throw new DOMException(`Imported project ${input.projectId} declares Published revision ${publishedRevision} without its immutable domain project snapshot.`,"DataError");const publishedProject=record(bundle.publishedProject)?remapProjectReferences(bundle.publishedProject,mapping) as SpecificationProject:undefined;if(publishedProject)publishedProject.name=input.name;await this.putProjectMetadataOnly({project,...(record(bundle.draft)?{draft:remapProjectReferences(bundle.draft,mapping) as NonNullable<ProjectState["draft"]>}:{}) ,history:{undo:[],redo:[]}},{publishedRevision,...(publishedProject?{publishedProject}:{}),active:false});return{projectId:input.projectId,active:false};}
}

export function createMemoryDurableProjectRepository(options:Partial<{now:()=>string;token:()=>string}>={}):DurableProjectRepository{return new DurableProjectRepository(new MemoryBackend(),{now:options.now??(()=>new Date().toISOString()),token:options.token??(()=>`draft:${crypto.randomUUID()}`)});}
export async function openIndexedDbProjectRepository(factory:IDBFactory=globalThis.indexedDB,options:Partial<{now:()=>string;token:()=>string}>={}):Promise<DurableProjectRepository>{if(!factory)throw new DOMException("IndexedDB is unavailable.","InvalidStateError");const request=factory.open(DURABLE_PROJECT_DATABASE,DURABLE_PROJECT_DATABASE_VERSION),database=await new Promise<IDBDatabase>((resolve,reject)=>{request.onupgradeneeded=()=>{if(request.result.objectStoreNames.contains("changes"))request.result.deleteObjectStore("changes");for(const store of DURABLE_PROJECT_STORES)if(!request.result.objectStoreNames.contains(store))request.result.createObjectStore(store);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error??new Error("Cannot open the durable project repository."));request.onblocked=()=>reject(new DOMException("The durable project repository upgrade is blocked.","InvalidStateError"));});return new DurableProjectRepository(new IndexedDbBackend(database),{now:options.now??(()=>new Date().toISOString()),token:options.token??(()=>`draft:${crypto.randomUUID()}`)});}

export function createPageProjectHistory(){type Entry={forward:DurableDraftCommand;inverse:DurablePatch[]};const undo:Entry[]=[],redo:Entry[]=[];return{push(command:DurableDraftCommand){undo.push({forward:clone(command),inverse:command.patches.map(patch=>({...clone(patch),before:clone(patch.after),after:clone(patch.before)}))});redo.length=0;},undo(current:DurableLoadedProject){const entry=undo.pop();if(!entry)return undefined;redo.push(entry);return{projectId:entry.forward.projectId,baseToken:current.draftToken,baseSequence:current.draftSequence,commandId:`undo:${entry.forward.commandId}`,label:`Undo ${entry.forward.label}`,patches:clone(entry.inverse),pendingState:clone(current.state)} satisfies DurableDraftCommand;},redo(current:DurableLoadedProject){const entry=redo.pop();if(!entry)return undefined;undo.push(entry);return{...clone(entry.forward),baseToken:current.draftToken,baseSequence:current.draftSequence,commandId:`redo:${entry.forward.commandId}`,label:`Redo ${entry.forward.label}`,pendingState:clone(current.state)} satisfies DurableDraftCommand;},snapshot:()=>({undo:undo.map(({forward})=>({commandId:forward.commandId,label:forward.label})),redo:redo.map(({forward})=>({commandId:forward.commandId,label:forward.label}))})};}

interface LegacyStorage{getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void;}
const differingFields=(left:unknown,right:unknown,path="project"):string[]=>{if(same(left,right))return[];if(record(left)&&record(right)){const keys=new Set([...Object.keys(left),...Object.keys(right)]);return[...keys].flatMap(key=>differingFields(left[key],right[key],`${path}.${key}`));}return[path];};
type InvalidLegacySourceReview={status:"invalid-source-review";sources:{key:string;valid:boolean;error:string;bytes:number;checksum:string;payload:string}[];actions:["Export preserved sources","Repair source and retry","Choose a valid source"]};
const legacyProjectErrors=(state:unknown,label:string):string[]=>{if(!record(state)||!record(state.project))return[`${label} does not contain a ProjectState project.`];const project=state.project;if(typeof project.id!=="string"||!record(project.collections))return[`${label} has invalid project identity or collections.`];const entities=Object.values(project.collections).flatMap(value=>Array.isArray(value)?value:[]),ids=new Set(entities.flatMap(value=>record(value)&&typeof value.id==="string"?[value.id]:[])),errors:string[]=[];for(const entity of entities){if(!record(entity)||typeof entity.id!=="string"||typeof entity.name!=="string"){errors.push(`${label} contains an entity without stable id and name.`);continue;}for(const field of["profileId","pageId","eventId","flowId","applicabilitySetId"]){const value=entity[field];if(typeof value==="string"&&value&&!ids.has(value))errors.push(`${label} ${entity.id} references missing ${field} ${value}.`);}for(const field of["profileIds","pageGroupIds"]){const values=entity[field];if(Array.isArray(values))for(const value of values)if(typeof value!=="string"||!ids.has(value))errors.push(`${label} ${entity.id} references missing ${field} ${String(value)}.`);}}return errors;};
export async function migrateLegacyProjectStorage(repository:DurableProjectRepository,storage:LegacyStorage,options:{choice?:"library"|"active"}={}):Promise<{status:"none"|"migrated";removedKeys:string[]}|{status:"review-required";projectId:string;sources:{source:"library"|"active";revision:number;checksum:string}[];conflictingFields:string[]}|InvalidLegacySourceReview>{
  const raw:{key:string;value:string}[]=Object.values(LEGACY_PROJECT_KEYS).flatMap(key=>{const value=storage.getItem(key);return value===null?[]:[{key,value}];});if(!raw.length)return{status:"none",removedKeys:[]};
  const libraryRaw=storage.getItem(LEGACY_PROJECT_KEYS.library),activeRaw=storage.getItem(LEGACY_PROJECT_KEYS.active),navigationRaw=storage.getItem(LEGACY_PROJECT_KEYS.navigation),schemasRaw=storage.getItem(LEGACY_PROJECT_KEYS.schemas),invalid=new Map<string,string>(),parse=(key:string,value:string|null):unknown=>{if(value===null)return undefined;try{return JSON.parse(value);}catch(error){invalid.set(key,error instanceof Error?error.message:String(error));return undefined;}},libraryValue=parse(LEGACY_PROJECT_KEYS.library,libraryRaw),activeValue=parse(LEGACY_PROJECT_KEYS.active,activeRaw),navigationValue=parse(LEGACY_PROJECT_KEYS.navigation,navigationRaw),schemasValue=parse(LEGACY_PROJECT_KEYS.schemas,schemasRaw);
  if(libraryValue!==undefined&&(!record(libraryValue)||!record(libraryValue.projects)))invalid.set(LEGACY_PROJECT_KEYS.library,"Project library must contain a projects object.");if(activeValue!==undefined&&(!record(activeValue)||!record(activeValue.project)))invalid.set(LEGACY_PROJECT_KEYS.active,"Active projection must contain a project object.");if(navigationValue!==undefined&&(!record(navigationValue)||typeof navigationValue.kind!=="string"||(navigationValue.id!==undefined&&typeof navigationValue.id!=="string")||(navigationValue.projectId!==undefined&&typeof navigationValue.projectId!=="string")))invalid.set(LEGACY_PROJECT_KEYS.navigation,"Project navigation must contain a route kind and optional project/entity identities.");if(schemasValue!==undefined&&!Array.isArray(schemasValue))invalid.set(LEGACY_PROJECT_KEYS.schemas,"Saved schema source must be an array.");
  const library=libraryValue as {activeProjectId?:string;projects?:Record<string,{state:ProjectState;revision:number;navigation?:ProjectNavigation}>}|undefined,active=activeValue as {project?:SpecificationProject;draft?:ProjectState["draft"];history?:ProjectState["history"];revision?:number}|undefined,navigation=navigationValue as {projectId?:string;kind:string;id?:string}|undefined,activeState=active?.project?{project:active.project,...(active.draft?{draft:active.draft}:{}),history:active.history??{undo:[],redo:[]}} as ProjectState:undefined;
  for(const[projectId,entry]of Object.entries(library?.projects??{})){for(const error of legacyProjectErrors(entry?.state,`Library project ${projectId}`))invalid.set(LEGACY_PROJECT_KEYS.library,error);}if(activeState)for(const error of legacyProjectErrors(activeState,"Active project"))invalid.set(LEGACY_PROJECT_KEYS.active,error);
  if(options.choice==="library"&&!invalid.has(LEGACY_PROJECT_KEYS.library))invalid.delete(LEGACY_PROJECT_KEYS.active);if(options.choice==="active"&&!invalid.has(LEGACY_PROJECT_KEYS.active))invalid.delete(LEGACY_PROJECT_KEYS.library);if(invalid.size)return{status:"invalid-source-review",sources:await Promise.all(raw.map(async({key,value})=>({key,valid:!invalid.has(key),error:invalid.get(key)??"Valid source preserved; choose it explicitly or repair the invalid source.",bytes:new TextEncoder().encode(value).byteLength,checksum:await checksum(value),payload:value}))),actions:["Export preserved sources","Repair source and retry","Choose a valid source"]};
  const effectiveLibrary=options.choice==="active"?undefined:library,effectiveActiveState=options.choice==="library"?undefined:activeState,effectiveActive=options.choice==="library"?undefined:active,projectIds=new Set([...Object.keys(effectiveLibrary?.projects??{}),...(effectiveActiveState?[effectiveActiveState.project.id]:[])]),selected:{state:ProjectState;revision:number;active:boolean;navigation?:ProjectNavigation}[]=[];
  for(const projectId of projectIds){const fromLibrary=effectiveLibrary?.projects?.[projectId],fromActive=effectiveActiveState?.project.id===projectId?{state:effectiveActiveState,revision:Number(effectiveActive?.revision??0)}:undefined;if(fromLibrary&&fromActive&&fromLibrary.revision===fromActive.revision&&!same(fromLibrary.state.project,fromActive.state.project)&&!options.choice){return{status:"review-required",projectId,sources:[{source:"library",revision:fromLibrary.revision,checksum:await checksum(JSON.stringify(fromLibrary.state.project))},{source:"active",revision:fromActive.revision,checksum:await checksum(JSON.stringify(fromActive.state.project))}],conflictingFields:differingFields(fromLibrary.state.project,fromActive.state.project)};}const winner=!fromLibrary?fromActive:!fromActive?fromLibrary:fromActive.revision>fromLibrary.revision?fromActive:fromLibrary,state=clone(winner!.state),standaloneNavigation=navigation&&(navigation.projectId===projectId||(!navigation.projectId&&(effectiveLibrary?.activeProjectId===projectId||effectiveActiveState?.project.id===projectId)))?{kind:navigation.kind,...(navigation.id?{id:navigation.id}:{})}:undefined,projectNavigation=standaloneNavigation??fromLibrary?.navigation;state.history={undo:[],redo:[]};selected.push({state,revision:winner!.revision,active:options.choice==="active"?effectiveActiveState?.project.id===projectId:effectiveLibrary?.activeProjectId===projectId||(options.choice===undefined&&effectiveActiveState?.project.id===projectId),...(projectNavigation?{navigation:clone(projectNavigation)}:{})});}
  const owner=crypto.randomUUID(),claim=await repository.claimLegacyMigration(owner);if(claim==="busy"){if(!await repository.waitForLegacyMigration())return migrateLegacyProjectStorage(repository,storage,options);for(const{key}of raw)storage.removeItem(key);return{status:"migrated",removedKeys:raw.map(({key})=>key)};}if(claim==="complete"){for(const{key}of raw)storage.removeItem(key);return{status:"migrated",removedKeys:raw.map(({key})=>key)};}const backup={sources:await Promise.all(raw.map(async({key,value})=>({key,bytes:new TextEncoder().encode(value).byteLength,checksum:await checksum(value),value})))},schemas=(schemasValue??[]) as Record<string,unknown>[];try{const manifest={projects:selected,schemas,backup};await repository.importLegacy(owner,manifest);await repository.verifyLegacyImport(manifest);await repository.completeLegacyMigration(owner);}catch(error){await repository.abandonLegacyMigration(owner);throw error;}for(const{key}of raw)storage.removeItem(key);return{status:"migrated",removedKeys:raw.map(({key})=>key)};
}
