import type {CanonicalPropertyNode,CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {FocusedPropertySection} from "./data-layer-focused-schema-property-ui.js";
import type {CanonicalSchemaEditorOptions} from "./data-layer-canonical-schema-ui.js";
import {renderCanonicalNavigator} from "./data-layer-canonical-schema-render-navigator.js";
import type {SchemaTableEditableFacet,SchemaTableQuickEditResult,SchemaTableSortMode} from "./data-layer-schema-table.js";
import {clearSchemaTableOverlay} from "./data-layer-schema-table.js";

export interface CanonicalSchemaRenderContext {
  dom:Document;options:CanonicalSchemaEditorOptions;document:CanonicalSchemaDocument;query:string;propertyFilter:"all"|"conditions"|"documentation"|"issues";propertySort:SchemaTableSortMode;feedback:string;activePropertyId:string|undefined;activeSection:FocusedPropertySection;menuPropertyId:string|undefined;focusedPropertyId:string|undefined;working:CanonicalPropertyNode|undefined;review:HTMLElement|undefined;tableElement?:HTMLTableElement;
  current:()=>CanonicalSchemaDocument;setQuery:(value:string)=>void;setPropertyFilter:(value:CanonicalSchemaRenderContext["propertyFilter"])=>void;setPropertySort:(value:CanonicalSchemaRenderContext["propertySort"])=>void;setFeedback:(value:string)=>void;setMenuPropertyId:(value:string|undefined)=>void;ensureWorking:(node:CanonicalPropertyNode)=>void;commitInline:(node:CanonicalPropertyNode,facet:SchemaTableEditableFacet,value:string)=>SchemaTableQuickEditResult;cancelInline:()=>void;inlineDiagnostic:(message:string)=>void;quickEditRoot:()=>ParentNode;quickEditScope:string;selectedNode:(document:CanonicalSchemaDocument)=>CanonicalPropertyNode|undefined;openProperty:(node:CanonicalPropertyNode,focus?:HTMLElement,section?:FocusedPropertySection)=>void;dismissOverlay:()=>void;command:(command:Parameters<CanonicalSchemaEditorOptions["dispatch"]>[0])=>unknown;render:()=>void;renderMenu:(node:CanonicalPropertyNode)=>HTMLElement;renderFocusedEditor:(document:CanonicalSchemaDocument,node:CanonicalPropertyNode)=>HTMLElement;
}
const button=(dom:Document,text:string,run:()=>void):HTMLButtonElement=>{const control=dom.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function renderCanonicalSchemaEditor(context:CanonicalSchemaRenderContext):void {
  const {dom,options,document}=context,priorScroll=options.host.querySelector<HTMLElement>("[data-schema-editor-scroll-region]"),retainedScroll=priorScroll?{top:priorScroll.scrollTop,left:priorScroll.scrollLeft}:undefined,retainedTable=document.view==="table"?options.host.querySelector<HTMLTableElement>('table[data-canonical-view="table"]'):null;if(retainedTable)context.tableElement=retainedTable;else delete context.tableElement;clearSchemaTableOverlay(options.host);options.host.replaceChildren();options.host.setAttribute("aria-label",`${options.surface} canonical schema editor`);options.host.dataset.canonicalSchemaId=document.id;options.host.dataset.canonicalRevision=String(document.revision);options.host.dataset.canonicalEditorMode="focused-property";
  const header=dom.createElement("header"),title=dom.createElement("h2"),status=dom.createElement("p"),undo=button(dom,"Undo",()=>options.onUndo?.()),redo=button(dom,"Redo",()=>options.onRedo?.()),policy=dom.createElement("input"),policyLabel=dom.createElement("label");title.textContent=document.contributorName;status.setAttribute("aria-label","Canonical Draft status");status.textContent=`Draft · ${document.source?`source ${document.source.identity} revision ${document.source.revision}`:"no source revision"} · lineage ${document.source?.provenance??"project-created"} · Saved · Draft token ${document.revision}`;undo.disabled=!options.onUndo;redo.disabled=!options.onRedo;policy.type="checkbox";policy.checked=document.onlyDefinedFields===true;policy.setAttribute("aria-label","Only defined fields");policy.addEventListener("change",()=>context.command({kind:"policy",baseRevision:document.revision,onlyDefinedFields:policy.checked}));policyLabel.append(policy,"Only defined fields");header.append(title,status);if(options.showOnlyDefinedFields!==false)header.append(policyLabel);header.append(undo,redo);options.host.append(header,renderCanonicalNavigator(context));
  if(document.view==="table"&&context.review)options.host.append(context.review);
  const node=context.selectedNode(document);
  const preview=dom.createElement("section"),previewHeading=dom.createElement("h3"),previewText=dom.createElement("p"),feedbackOutput=dom.createElement("output");preview.setAttribute("aria-label","Effective documentation preview");previewHeading.textContent="Effective documentation";previewText.textContent=node?[node.documentation.displayText,node.documentation.description,node.documentation.comments].filter(Boolean).join(" · ")||"No documentation yet.":"Select a property.";preview.append(previewHeading,previewText);feedbackOutput.setAttribute("aria-label","Canonical command result");feedbackOutput.textContent=context.feedback;options.host.append(preview,feedbackOutput);if(retainedScroll){const next=options.host.querySelector<HTMLElement>("[data-schema-editor-scroll-region]");if(next){next.scrollTop=retainedScroll.top;next.scrollLeft=retainedScroll.left;}}
}
