import {orderedPageGroupIds,requiresPageGroupMembershipMigration} from "./utilities/data-layer/page-group-membership.js";
import {canonicalSchemaWithConstraint,compileLayeredSchema,createCanonicalSchema,layeredContributorPath,layeredContributorsForPath,migrateLegacyProfile,transactProject,validateLayeredObservation,type CanonicalSchemaDocument,type IdFactory,type LayerConstraint,type ProjectEntity,type ProjectState,type SpecificationProject} from "./utilities/data-layer/schemas.js";

export type FlowRole="context-setting"|"interaction";
export type FlowObligation="Required"|"Optional"|"Conditional"|"Informational";
export type FlowRelationshipKind="expected_next"|"alternative"|"merge";
export type FlowPortSide="left"|"right"|"top"|"bottom";
export type FreePageRegion="before-lanes"|"after-lanes";
export type FlowEndpointKind="page-frame"|"event-occurrence";
export const FLOW_GRAPH_GEOMETRY={eventWidth:170,eventHeight:94,eventMinX:12,eventMinY:40,pageFrameMinWidth:190,pageFrameMinHeight:108,pageFrameChildRightPadding:20,pageFrameChildBottomPadding:16} as const;
export interface FlowEndpointReference {kind:FlowEndpointKind;id:string}
export interface FlowLayout {lane:string;x:number;y:number}
export interface FlowOccurrenceInput {name:string;pageFrameId?:string;pageGroupId?:string;freePageFrameId?:string;freePageFrame?:boolean;freePageRegion?:FreePageRegion;pageId:string;eventId?:string;role?:FlowRole;trigger?:string;fallbackRole?:FlowRole;obligation:FlowObligation;minimum:number;maximum:number;layout?:FlowLayout;x?:number;y?:number}
export interface FlowRelationshipInput {id?:string;toStepId:string;sourcePort:FlowPortSide;targetPort:FlowPortSide;group?:string;label?:string;documentationCondition?:string;expectation?:string}
export interface FlowNode {id:string;name:string;eventId:string;pageId:string;pageFrameId?:string;pageGroupId?:string;freePageFrameId?:string;freePageFrame?:boolean;freePageRegion?:FreePageRegion;role:FlowRole;trigger?:string;obligation:FlowObligation;expectedMinimum:number;expectedMaximum?:number;layout?:FlowLayout}
export interface FlowConnectionEndpoint extends FlowEndpointReference {name:string;pageId:string;pageGroupId?:string;freePageRegion?:FreePageRegion;layout:FlowLayout;width:number;height:number}
export interface FlowRelationship {id:string;sourceEndpoint:FlowEndpointReference;targetEndpoint:FlowEndpointReference;sourceNodeId:string;targetNodeId:string;sourcePort:FlowPortSide;targetPort:FlowPortSide;kind:FlowRelationshipKind;group?:string;label?:string;documentationCondition?:string;expectation?:string}
export interface FlowGraph {id:string;name:string;purpose:string;nodes:readonly FlowNode[];connectionEndpoints:readonly FlowConnectionEndpoint[];relationships:readonly FlowRelationship[]}
export interface FlowCatalogEntry {id:string;name:string;role?:FlowRole;[key:string]:unknown}
export interface FlowCatalog {pageGroups:readonly FlowCatalogEntry[];pages:readonly FlowCatalogEntry[];events:readonly FlowCatalogEntry[]}
export interface FlowDiagnostic {kind:"missing-event"|"missing-page"|"dangling-relationship";message:string;nodeId?:string;relationshipId?:string}
export interface FlowLaneBand {id:string;name:string;y:number;height:number}
export interface FlowGraphProjection {projectName:string;lanes:readonly FlowCatalogEntry[];laneBands:readonly FlowLaneBand[];graph:FlowGraph;catalog:FlowCatalog;diagnostics:readonly FlowDiagnostic[]}
export interface DocumentaryPageFrameRecord {id:string;pageId:string;pageGroupId?:string;freePageRegion?:FreePageRegion;position:{x?:number;y:number}}
export interface DocumentaryRelationshipRecord {id:string;sourceEndpoint?:FlowEndpointReference;targetEndpoint?:FlowEndpointReference;sourceNodeId?:string;targetNodeId?:string;sourcePort?:FlowPortSide;targetPort?:FlowPortSide;[key:string]:unknown}
export interface FlowViewState {selectedItem?:{kind:"page-frame"|"occurrence"|"relationship";id:string};viewport?:{x:number;y:number;zoom:number}}
export interface DocumentaryFlowGraph extends FlowViewState {pageGroupIds:readonly string[];pageFrames:readonly DocumentaryPageFrameRecord[];occurrences:readonly ProjectEntity[];relationships:readonly DocumentaryRelationshipRecord[]}

interface StoredDocumentaryFlowGraph extends FlowViewState {pageGroupIds:string[];pageFrames:DocumentaryPageFrameRecord[];occurrences:ProjectEntity[];relationships:DocumentaryRelationshipRecord[]}
interface LegacyBindingOccurrence extends ProjectEntity {contextBindingId:string}
type ProjectWithDocumentaryGraphs=SpecificationProject&{documentationFlowGraphs?:Record<string,StoredDocumentaryFlowGraph>};
const clone=<T>(value:T):T=>structuredClone(value);
const graphIndex=(project:SpecificationProject):Record<string,StoredDocumentaryFlowGraph>=>(project as ProjectWithDocumentaryGraphs).documentationFlowGraphs??{};
const storedGraph=(project:SpecificationProject,flowId:string):StoredDocumentaryFlowGraph=>{const stored=graphIndex(project)[flowId],legacy=project.collections.flows.find(({id})=>id===flowId)?.pageGroupIds as string[]|undefined;return{pageGroupIds:[...(stored?.pageGroupIds??legacy??[])],pageFrames:stored?.pageFrames??[],occurrences:stored?.occurrences??[],relationships:stored?.relationships??[],...(stored?.selectedItem?{selectedItem:stored.selectedItem}:{}),...(stored?.viewport?{viewport:stored.viewport}:{})};};
const saveStoredGraph=(project:SpecificationProject,flowId:string,graph:StoredDocumentaryFlowGraph):SpecificationProject=>{const{selectedItem:_selectedItem,viewport:_viewport,...semanticGraph}=graph;return{...project,documentationFlowGraphs:{...graphIndex(project),[flowId]:semanticGraph}};};
const legacyBindingOccurrence=(occurrence:ProjectEntity):occurrence is LegacyBindingOccurrence=>typeof occurrence.contextBindingId==="string"&&Boolean(occurrence.contextBindingId);
const relationshipEndpoint=(relationship:DocumentaryRelationshipRecord,side:"source"|"target"):FlowEndpointReference|undefined=>{
  const endpoint=side==="source"?relationship.sourceEndpoint:relationship.targetEndpoint;
  if(endpoint&&(endpoint.kind==="page-frame"||endpoint.kind==="event-occurrence")&&endpoint.id)return endpoint;
  const legacy=side==="source"?relationship.sourceNodeId:relationship.targetNodeId;
  return legacy?{kind:"event-occurrence",id:String(legacy)}:undefined;
};
const relationshipTouches=(relationship:DocumentaryRelationshipRecord,ids:Set<string>):boolean=>ids.has(relationshipEndpoint(relationship,"source")?.id??"")||ids.has(relationshipEndpoint(relationship,"target")?.id??"");
const flowPortSide=(value:unknown):value is FlowPortSide=>value==="left"||value==="right"||value==="top"||value==="bottom";
export function inferFlowRelationshipKind(sourcePort:FlowPortSide,targetPort:FlowPortSide):FlowRelationshipKind|undefined{
  if(sourcePort==="right"&&targetPort==="left")return"expected_next";
  if(sourcePort==="top"&&targetPort==="bottom")return"alternative";
  if(sourcePort==="bottom"&&targetPort==="top")return"merge";
  return undefined;
}
const legacyPorts=(kind:unknown):{sourcePort:FlowPortSide;targetPort:FlowPortSide}=>kind==="alternative"||kind==="parallel"?{sourcePort:"top",targetPort:"bottom"}:kind==="merge"?{sourcePort:"bottom",targetPort:"top"}:{sourcePort:"right",targetPort:"left"};
const relationshipPorts=(relationship:DocumentaryRelationshipRecord):{sourcePort:FlowPortSide;targetPort:FlowPortSide}=>flowPortSide(relationship.sourcePort)&&flowPortSide(relationship.targetPort)?{sourcePort:relationship.sourcePort,targetPort:relationship.targetPort}:legacyPorts(relationship.kind);
type ValidatedOccurrence=FlowOccurrenceInput;
const normalizedOccurrence=(input:ValidatedOccurrence):Omit<ProjectEntity,"id">=>{
  if(input.pageFrameId||input.pageGroupId||input.freePageFrameId||input.freePageFrame){const {layout,x,y,fallbackRole,role,eventId,...values}=clone(input);void layout;void fallbackRole;void role;const ownsCoordinates=Boolean(input.pageFrameId||input.freePageFrameId||input.freePageFrame);return{...values,...(eventId?{eventId}:{}),position:{...(ownsCoordinates?{x:Number(x??input.layout?.x??24)}:{}),y:Number(y??input.layout?.y??70)},optional:input.obligation==="Optional"};}
  const {layout,...values}=clone(input);if(!layout)throw new Error("An uncontained legacy Flow occurrence requires an explicit legacy layout.");return{...values,lane:layout.lane,position:{x:layout.x,y:layout.y},optional:input.obligation==="Optional"};
};

export function documentaryFlowGraph(project:SpecificationProject,flowId:string):DocumentaryFlowGraph{const graph=storedGraph(project,flowId);return{pageGroupIds:graph.pageGroupIds,pageFrames:graph.pageFrames,occurrences:graph.occurrences,relationships:graph.relationships,...(graph.selectedItem?{selectedItem:graph.selectedItem}:{}),...(graph.viewport?{viewport:graph.viewport}:{})};}
export function flowPageGroupLaneIds(project:SpecificationProject,flowId:string):readonly string[]{return storedGraph(project,flowId).pageGroupIds;}
export function flowOccurrenceEventSchema(project:SpecificationProject,flowId:string,occurrenceId:string):unknown{
  const occurrence=storedGraph(project,flowId).occurrences.find(({id})=>id===occurrenceId),event=project.collections.events.find(({id})=>id===occurrence?.eventId);return event?.id;
}
function validOccurrence(state:ProjectState,flowId:string,input:FlowOccurrenceInput):ValidatedOccurrence{
  if("contextBindingId" in input)throw new Error("A legacy Page-context binding is migration input and cannot be authored as a Flow occurrence.");
  const flow=state.project.collections.flows.find(({id})=>id===flowId);if(!flow)throw new Error("A documentary Flow graph requires an existing Flow.");if(!input.name.trim())throw new Error("A Flow occurrence requires a name.");const page=state.project.collections.pages.find(({id})=>id===input.pageId);if(!page)throw new Error("A Flow occurrence requires an existing Page.");if(!input.pageFrameId)throw new Error("A Flow occurrence requires an existing containing Page frame; legacy lane records are migration input only.");const graph=storedGraph(state.project,flowId),frame=graph.pageFrames.find(({id})=>id===input.pageFrameId);
  if(input.pageFrameId&&(!frame||frame.pageId!==page.id||(input.pageGroupId!==undefined&&String(frame.pageGroupId??"")!==String(input.pageGroupId))))throw new Error("A Flow occurrence requires its existing containing Page frame.");const effectivePageGroupId=input.pageGroupId??frame?.pageGroupId;if(effectivePageGroupId){const group=state.project.collections.pageGroups.find(({id})=>id===effectivePageGroupId),memberIds=orderedPageGroupIds(state.project,page.id);if(!group||!flowPageGroupLaneIds(state.project,flowId).includes(group.id)||!memberIds.includes(group.id))throw new Error("A Flow occurrence requires a selected Page Group containing its Page.");}
  if(input.freePageFrameId){const legacyFrame=graph.occurrences.find(({id})=>id===input.freePageFrameId);if(!legacyFrame?.freePageFrame||legacyFrame.pageId!==page.id)throw new Error("A free-page interaction requires an existing free Page frame for its Page.");}
  const event=state.project.collections.events.find(({id})=>id===input.eventId);if(!event)throw new Error("A Flow occurrence requires an existing Event.");if(input.minimum<0||input.maximum<input.minimum)throw new Error("Flow occurrence bounds are invalid.");const{fallbackRole,role,...values}=input;void fallbackRole;void role;return{...values,name:input.name.trim()};
}

export function inspectPageFrameDrop(project:SpecificationProject,flowId:string,pageId:string,targetPageGroupId:string):FlowContainmentReview{
  const page=project.collections.pages.find(({id})=>id===pageId),group=project.collections.pageGroups.find(({id})=>id===targetPageGroupId),selected=flowPageGroupLaneIds(project,flowId).includes(targetPageGroupId),memberships=orderedPageGroupIds(project,pageId),member=Boolean(group&&memberships.includes(group.id)),migrationRequired=Boolean(page&&requiresPageGroupMembershipMigration(project,pageId)),rejected=!page||!group||!selected||!member||migrationRequired,names=memberships.map((id)=>project.collections.pageGroups.find((candidate)=>candidate.id===id)?.name??id);
  return{rejected,message:rejected?`${page?.name??pageId} belongs to ${names.join(", ")||"no selected Page Group"}, not ${group?.name??targetPageGroupId}.`: `${page!.name} can be placed in ${group!.name}.`,guidance:`?kind=pages&entity=${encodeURIComponent(pageId)}&field=pageGroupIds`};
}
export function addFlowPageFrame(state:ProjectState,flowId:string,input:{pageId:string;pageGroupId:string;x?:number;y:number},id:IdFactory):ProjectState{
  const review=inspectPageFrameDrop(state.project,flowId,input.pageId,input.pageGroupId);if(review.rejected)return state;const graph=storedGraph(state.project,flowId);
  return transactProject(state,"Add Flow Page frame",(project)=>{const current=storedGraph(project,flowId),frame:DocumentaryPageFrameRecord={id:id("flow-page-frame"),pageId:input.pageId,pageGroupId:input.pageGroupId,position:{x:Math.max(20,Math.round(input.x??40+current.pageFrames.filter(({pageGroupId})=>pageGroupId===input.pageGroupId).length*240)),y:Math.max(40,Math.round(input.y))}};return saveStoredGraph(project,flowId,{...current,pageFrames:[...current.pageFrames,frame]});});
}
export function removeFlowPageFrame(state:ProjectState,flowId:string,pageFrameId:string):ProjectState{
  const graph=storedGraph(state.project,flowId),frame=graph.pageFrames.find(({id})=>id===pageFrameId);if(!frame)return state;const removedIds=new Set([pageFrameId,...graph.occurrences.filter((occurrence)=>occurrence.pageFrameId===pageFrameId).map(({id})=>id)]);return transactProject(state,"Remove Flow Page frame",(project)=>{const current=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...current,pageFrames:current.pageFrames.filter(({id})=>id!==pageFrameId),occurrences:current.occurrences.filter((occurrence)=>occurrence.pageFrameId!==pageFrameId),relationships:current.relationships.filter((relationship)=>!relationshipTouches(relationship,removedIds))});});
}
export function moveFlowPageFrame(state:ProjectState,flowId:string,pageFrameId:string,input:{pageGroupId:string;x?:number;y:number}):ProjectState{
  const graph=storedGraph(state.project,flowId),frame=graph.pageFrames.find(({id})=>id===pageFrameId);if(!frame||inspectPageFrameDrop(state.project,flowId,frame.pageId,input.pageGroupId).rejected)return state;const x=Math.max(20,Math.round(input.x??frame.position.x??40)),y=Math.max(40,Math.round(input.y));if(frame.pageGroupId===input.pageGroupId&&!frame.freePageRegion&&frame.position.x===x&&frame.position.y===y)return state;
  return transactProject(state,"Move Flow Page frame",(project)=>{const current=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...current,pageFrames:current.pageFrames.map((candidate)=>{if(candidate.id!==pageFrameId)return candidate;const moved:DocumentaryPageFrameRecord={...candidate,pageGroupId:input.pageGroupId,position:{x,y}};delete moved.freePageRegion;return moved;})});});
}
export function addEventOccurrenceToPage(state:ProjectState,flowId:string,input:{name:string;pageFrameId:string;pageGroupId?:string;pageId:string;eventId:string;role?:FlowRole;trigger?:string;obligation:FlowObligation;minimum:number;maximum:number;x?:number;y:number},id:IdFactory):ProjectState{return addGraphOccurrence(state,flowId,input,id);}
export function reorderFlowPageGroupLane(state:ProjectState,flowId:string,pageGroupId:string,delta:number):ProjectState{const lanes=[...flowPageGroupLaneIds(state.project,flowId)],from=lanes.indexOf(pageGroupId);if(from<0)return state;const to=Math.max(0,Math.min(lanes.length-1,from+delta));if(from===to)return state;lanes.splice(from,1);lanes.splice(to,0,pageGroupId);return setFlowPageGroupLanes(state,flowId,lanes);}
export function saveFlowViewState(state:ProjectState,_flowId:string,_view:FlowViewState):ProjectState{return state;}

export function addGraphOccurrence(state:ProjectState,flowId:string,input:FlowOccurrenceInput,id:IdFactory):ProjectState{
  const valid=validOccurrence(state,flowId,input);
  return transactProject(state,`Add ${valid.name} Flow occurrence`,(project)=>{const graph=storedGraph(project,flowId),occurrence={id:id("flow-occurrence"),...normalizedOccurrence(valid)} as ProjectEntity;return saveStoredGraph(project,flowId,{...graph,occurrences:[...graph.occurrences,occurrence]});});
}
export function updateGraphOccurrence(state:ProjectState,flowId:string,occurrenceId:string,input:FlowOccurrenceInput):ProjectState{
  if(!storedGraph(state.project,flowId).occurrences.some(({id})=>id===occurrenceId))throw new Error("Unknown documentary Flow occurrence.");
  const valid=validOccurrence(state,flowId,input);
  return transactProject(state,`Save Flow occurrence ${occurrenceId}`,(project)=>{const graph=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.map((occurrence)=>{if(occurrence.id!==occurrenceId)return occurrence;const {layout:discardedLayout,relationshipGroup:discardedRelationshipGroup,branch:discardedBranch,...stored}=occurrence;void discardedLayout;void discardedRelationshipGroup;void discardedBranch;return{...stored,...normalizedOccurrence(valid)};})});});
}
export function moveGraphOccurrence(state:ProjectState,flowId:string,occurrenceId:string,layout:FlowLayout|{pageGroupId?:string;x?:number;y:number}):ProjectState{
  const occurrence=storedGraph(state.project,flowId).occurrences.find(({id})=>id===occurrenceId),position=occurrence?.position as {x?:number;y?:number}|undefined;
  if(!occurrence)return state;if(occurrence.pageFrameId||occurrence.pageGroupId||occurrence.freePageFrameId||occurrence.freePageFrame){const requestedGroup="pageGroupId" in layout?layout.pageGroupId:undefined;if(requestedGroup&&requestedGroup!==occurrence.pageGroupId||Boolean(occurrence.freePageFrameId||occurrence.freePageFrame)&&requestedGroup)return state;const ownsCoordinates=Boolean(occurrence.pageFrameId||occurrence.freePageFrameId||occurrence.freePageFrame),x=Math.max(12,Math.round("x" in layout&&typeof layout.x==="number"?layout.x:position?.x??24)),y=Math.max(55,Math.round(layout.y));if((!ownsCoordinates||position?.x===x)&&position?.y===y)return state;return transactProject(state,`Move Flow occurrence ${occurrenceId}`,(project)=>{const graph=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.map((item)=>item.id===occurrenceId?{...item,position:{...(ownsCoordinates?{x}:{}),y}}:item)});});}
  const legacy=layout as FlowLayout;if(occurrence.lane===legacy.lane&&position?.x===legacy.x&&position.y===legacy.y)return state;
  return transactProject(state,`Move Flow occurrence ${occurrenceId}`,(project)=>{const graph=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.map((item)=>{if(item.id!==occurrenceId)return item;const {layout:discardedLayout,...stored}=item;void discardedLayout;return{...stored,lane:legacy.lane,position:{x:legacy.x,y:legacy.y}};})});});
}
export function reorderGraphOccurrence(state:ProjectState,flowId:string,from:number,to:number):ProjectState{
  const count=storedGraph(state.project,flowId).occurrences.length,target=Math.max(0,Math.min(to,count-1));
  if(from<0||from>=count||from===target)return state;
  return transactProject(state,"Reorder Flow occurrence",(project)=>{const graph=storedGraph(project,flowId),occurrences=[...graph.occurrences],moved=occurrences.splice(from,1)[0]!;occurrences.splice(target,0,moved);return saveStoredGraph(project,flowId,{...graph,occurrences});});
}
export function removeGraphOccurrence(state:ProjectState,flowId:string,occurrenceId:string):ProjectState{
  if(!state.project.collections.flows.some(({id})=>id===flowId)||!storedGraph(state.project,flowId).occurrences.some(({id})=>id===occurrenceId))return state;
  return transactProject(state,`Remove Flow occurrence ${occurrenceId}`,(project)=>{const graph=storedGraph(project,flowId),removed=new Set([occurrenceId]);return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.filter(({id})=>id!==occurrenceId),relationships:graph.relationships.filter((relationship)=>!relationshipTouches(relationship,removed))});});
}
export function setFlowPageGroupLanes(state:ProjectState,flowId:string,pageGroupIds:readonly string[]):ProjectState{
  const flow=state.project.collections.flows.find(({id})=>id===flowId),known=new Set(state.project.collections.pageGroups.map(({id})=>id)),graph=storedGraph(state.project,flowId);if(!flow)throw new Error(`Unknown Flow ${flowId}`);if(new Set(pageGroupIds).size!==pageGroupIds.length||pageGroupIds.some((groupId)=>!known.has(groupId)))throw new Error("Flow lanes require distinct existing Page Group references.");const removed=new Set(graph.pageGroupIds.filter((groupId)=>!pageGroupIds.includes(groupId))),affectedFrame=graph.pageFrames.find((frame)=>removed.has(String(frame.pageGroupId??""))),affectedOccurrence=graph.occurrences.find((occurrence)=>removed.has(String(occurrence.pageGroupId??""))),affectedPage=state.project.collections.pages.find(({id})=>id===(affectedFrame?.pageId??affectedOccurrence?.pageId));if(affectedFrame||affectedOccurrence)throw new Error(`${affectedPage?.name??affectedOccurrence?.name??"Contained Page"} must be reassigned or removed. Move Page frame or Remove Page frame first.`);if(JSON.stringify(graph.pageGroupIds)===JSON.stringify(pageGroupIds)&&!("pageGroupIds" in flow))return state;return transactProject(state,"Set Flow Page Group lanes",(project)=>{const current=storedGraph(project,flowId);return saveStoredGraph({...project,collections:{...project.collections,flows:project.collections.flows.map((candidate)=>{if(candidate.id!==flowId)return candidate;const{pageGroupIds:discarded,...stored}=candidate;void discarded;return stored;})}},flowId,{...current,pageGroupIds:[...pageGroupIds]});});
}
export function applyFlowPageGroupLaneSelection(state:ProjectState,flowId:string,pageGroupIds:readonly string[]|undefined):ProjectState{return pageGroupIds===undefined?state:setFlowPageGroupLanes(state,flowId,pageGroupIds);}
export interface FlowContainmentSchemaSummary {pageFrameId:string;pageName:string;status:"ready"|"blocked";propertyPaths:string[]}
export interface FlowContainmentSchemaImpact {source:FlowContainmentSchemaSummary;target:FlowContainmentSchemaSummary;addedPaths:string[];removedPaths:string[];changedPaths:string[]}
export interface FlowContainmentReview {rejected:boolean;message:string;guidance:string;impact?:FlowContainmentSchemaImpact}
export function inspectOccurrenceContainmentMove(project:SpecificationProject,flowId:string,occurrenceId:string,targetPageGroupId:string,targetPageId:string):FlowContainmentReview{
  const target=storedGraph(project,flowId).pageFrames.find(({pageId,pageGroupId})=>pageId===targetPageId&&pageGroupId===targetPageGroupId);
  return inspectOccurrencePageChange(project,flowId,occurrenceId,target?.id??"");
}
export function inspectOccurrencePageChange(project:SpecificationProject,flowId:string,occurrenceId:string,targetPageFrameId:string):FlowContainmentReview{
  const graph=storedGraph(project,flowId),occurrence=graph.occurrences.find(({id})=>id===occurrenceId),sourceFrame=graph.pageFrames.find(({id})=>id===occurrence?.pageFrameId),targetFrame=graph.pageFrames.find(({id})=>id===targetPageFrameId),sourcePage=project.collections.pages.find(({id})=>id===sourceFrame?.pageId),targetPage=project.collections.pages.find(({id})=>id===targetFrame?.pageId),rejected=!occurrence||!sourceFrame||!targetFrame||sourceFrame.id===targetFrame.id;
  if(rejected)return{rejected,message:"Choose a different existing Page frame.",guidance:targetFrame?`?kind=flow-page-instances&flow=${encodeURIComponent(flowId)}&entity=${encodeURIComponent(targetFrame.id)}`:"Open a target Flow Page frame."};
  const state={project} as ProjectState,compileAt=(frame:DocumentaryPageFrameRecord,page:ProjectEntity|undefined)=>{const candidate={...occurrence!,pageFrameId:frame.id,pageId:frame.pageId,...(frame.pageGroupId?{pageGroupId:frame.pageGroupId}:{})} as ProjectEntity;if(!frame.pageGroupId)delete candidate.pageGroupId;const contributors=layeredContributorsForPath(state,layeredContributorPath(state,candidate,"Event-occurrence",flowId)),compiled=compileLayeredSchema(contributors,{eventId:String(occurrence!.eventId??""),eventRole:"interaction",occurrenceId:occurrence!.id});return{summary:{pageFrameId:frame.id,pageName:page?.name??frame.pageId,status:compiled.status,propertyPaths:Object.keys(compiled.properties).sort()} satisfies FlowContainmentSchemaSummary,properties:compiled.properties};},source=compileAt(sourceFrame!,sourcePage),target=compileAt(targetFrame!,targetPage),sourcePaths=new Set(source.summary.propertyPaths),targetPaths=new Set(target.summary.propertyPaths),addedPaths=target.summary.propertyPaths.filter((path)=>!sourcePaths.has(path)),removedPaths=source.summary.propertyPaths.filter((path)=>!targetPaths.has(path)),changedPaths=source.summary.propertyPaths.filter((path)=>targetPaths.has(path)&&JSON.stringify(source.properties[path])!==JSON.stringify(target.properties[path])),list=(paths:string[])=>paths.length?paths.join(", "):"none",impact:FlowContainmentSchemaImpact={source:source.summary,target:target.summary,addedPaths,removedPaths,changedPaths};
  return{rejected,message:`${occurrence!.name} will move from ${source.summary.pageName} to ${target.summary.pageName}; effective-schema impact: source ${source.summary.status} with ${source.summary.propertyPaths.length} properties, target ${target.summary.status} with ${target.summary.propertyPaths.length}; added ${list(addedPaths)}; removed ${list(removedPaths)}; changed ${list(changedPaths)}.`,guidance:`?kind=flow-page-instances&flow=${encodeURIComponent(flowId)}&entity=${encodeURIComponent(targetFrame!.id)}`,impact};
}
export function reassignFlowOccurrencePage(state:ProjectState,flowId:string,occurrenceId:string,targetPageFrameId:string):ProjectState{
  const review=inspectOccurrencePageChange(state.project,flowId,occurrenceId,targetPageFrameId);if(review.rejected)return state;
  return transactProject(state,`Change Flow occurrence ${occurrenceId} Page`,(project)=>{const graph=storedGraph(project,flowId),target=graph.pageFrames.find(({id})=>id===targetPageFrameId)!;return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.map((occurrence)=>{if(occurrence.id!==occurrenceId)return occurrence;const moved={...occurrence,pageFrameId:target.id,pageId:target.pageId} as ProjectEntity;if(target.pageGroupId)moved.pageGroupId=target.pageGroupId;else delete moved.pageGroupId;delete moved.freePageFrameId;return moved;})});});
}
export function addInteractionOccurrenceToPage(state:ProjectState,flowId:string,input:{name:string;pageFrameId?:string;pageGroupId?:string;freePageFrameId?:string;pageId:string;eventId:string;obligation:FlowObligation;minimum:number;maximum:number;x?:number;y:number},id:IdFactory):ProjectState{return addGraphOccurrence(state,flowId,input,id);}
export function addFreePageFrame(state:ProjectState,flowId:string,input:{name?:string;pageId:string;region:FreePageRegion;x:number;y:number},id:IdFactory):ProjectState{
  const page=state.project.collections.pages.find(({id})=>id===input.pageId);if(!page)return state;return transactProject(state,"Add free Flow Page frame",(project)=>{const current=storedGraph(project,flowId),frame:DocumentaryPageFrameRecord={id:id("flow-page-frame"),pageId:input.pageId,freePageRegion:input.region,position:{x:Math.max(12,Math.round(input.x)),y:Math.max(55,Math.round(input.y))}};return saveStoredGraph(project,flowId,{...current,pageFrames:[...current.pageFrames,frame]});});
}
export function addUngroupedPageFrame(state:ProjectState,flowId:string,input:{name:string;pageId:string;y:number},id:IdFactory):ProjectState{return addFreePageFrame(state,flowId,{...input,region:"after-lanes",x:24},id);}
export function inspectFreePageEdgeMove(project:SpecificationProject,flowId:string,occurrenceId:string,targetRegion:FreePageRegion):FlowContainmentReview{
  const occurrence=storedGraph(project,flowId).occurrences.find(({id})=>id===occurrenceId),page=project.collections.pages.find(({id})=>id===occurrence?.pageId),flow=project.collections.flows.find(({id})=>id===flowId),rejected=!occurrence?.freePageFrame;return{rejected,message:rejected?`${page?.name??occurrence?.name??occurrenceId} remains in its Page Group lane in ${flow?.name??flowId}; it cannot move to ${targetRegion} without explicit membership changes.`:`${page?.name??occurrence.name} can move to ${targetRegion} without changing membership.`,guidance:`?kind=pages&entity=${encodeURIComponent(String(occurrence?.pageId??""))}&field=pageGroupIds`};
}
export function inspectUngroupedPageDrop(project:SpecificationProject,flowId:string,pageId:string,targetPageGroupId:string):FlowContainmentReview{const page=project.collections.pages.find(({id})=>id===pageId),group=project.collections.pageGroups.find(({id})=>id===targetPageGroupId),flow=project.collections.flows.find(({id})=>id===flowId);return{rejected:true,message:`${page?.name??pageId} is a free Page and cannot be dropped over ${group?.name??targetPageGroupId} in ${flow?.name??flowId} without explicit membership.`,guidance:`?kind=pages&entity=${encodeURIComponent(pageId)}&field=pageGroupIds`};}
export function moveFreePageFrame(state:ProjectState,flowId:string,frameId:string,presentation:{region:FreePageRegion;x:number;y:number}):ProjectState{
  const frame=storedGraph(state.project,flowId).pageFrames.find(({id})=>id===frameId),position=frame?.position;if(!frame)return state;const next={region:presentation.region,x:Math.max(12,Math.round(presentation.x)),y:Math.max(55,Math.round(presentation.y))};if(frame.freePageRegion===next.region&&position?.x===next.x&&position.y===next.y)return state;return transactProject(state,`Move free Page frame ${frameId}`,(project)=>{const graph=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...graph,pageFrames:graph.pageFrames.map((item)=>{if(item.id!==frameId)return item;const moved:DocumentaryPageFrameRecord={...item,freePageRegion:next.region,position:{x:next.x,y:next.y}};delete moved.pageGroupId;return moved;})});});
}

export interface FlowExampleIssue {path:string;code:"REQUIRED_EXAMPLE"|"TYPE"|"CONFLICT"|string;message:string;editHref:string}
export interface FlowOccurrenceExample {status:"Complete"|"Incomplete"|"Invalid"|"Blocked";payload:Record<string,unknown>;formattedJson:string;provenance:Record<string,string>;issues:FlowExampleIssue[]}
export interface FlowOccurrenceExampleEditorRow {path:string;type?:string;value:unknown}
const pointerParts=(path:string):string[]=>path.split("/").filter(Boolean).map((part)=>part.replaceAll("~1","/").replaceAll("~0","~"));
const setAtPath=(payload:Record<string,unknown>,path:string,value:unknown):void=>{const parts=pointerParts(path);if(!parts.length)return;let parent=payload;for(const part of parts.slice(0,-1)){const next=parent[part];if(!next||typeof next!=="object"||Array.isArray(next))parent[part]={};parent=parent[part] as Record<string,unknown>;}parent[parts.at(-1)!]=clone(value);};
const valueAtPath=(payload:Record<string,unknown>,path:string):unknown=>pointerParts(path).reduce<unknown>((value,part)=>value&&typeof value==="object"&&!Array.isArray(value)?(value as Record<string,unknown>)[part]:undefined,payload);
const applicableExample=(constraint:LayerConstraint,occurrence:ProjectEntity,eventId:string,role:FlowRole):boolean=>!constraint.target||constraint.target==="all"||constraint.target===occurrence.id||constraint.target===eventId||constraint.target===(role==="context-setting"?"context":"interaction");
const exampleEditHref=(flowId:string,occurrenceId:string,path:string)=>`?kind=flow-page-instances&flow=${encodeURIComponent(flowId)}&entity=${encodeURIComponent(occurrenceId)}&field=${encodeURIComponent(`canonicalSchema.properties${path}.example`)}`;

export function setFlowOccurrenceExample(state:ProjectState,flowId:string,occurrenceId:string,path:string,value:unknown,id:IdFactory):ProjectState{
  const occurrence=storedGraph(state.project,flowId).occurrences.find(({id:candidateId})=>candidateId===occurrenceId);if(!occurrence||!path.startsWith("/"))return state;
  const contributorPath=layeredContributorPath(state,occurrence,"Event-occurrence",flowId),contributors=layeredContributorsForPath(state,contributorPath),effective=compileLayeredSchema(contributors,{eventId:String(occurrence.eventId??""),eventRole:"interaction",occurrenceId}).properties[path],legacy=Boolean(occurrence.schemaConstraints||occurrence.localSchemaContributions),canonical=(occurrence.canonicalSchema as CanonicalSchemaDocument|undefined)??(legacy?migrateLegacyProfile(occurrence,{id}).document:createCanonicalSchema({id:id("canonical-schema"),contributorId:occurrence.id,contributorName:occurrence.name})),next=canonicalSchemaWithConstraint(canonical,{path,...(effective?.type?{type:effective.type}:{}),examples:[clone(value)]},id);
  return transactProject(state,`Save Flow occurrence example ${path}`,(project)=>{const graph=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...graph,occurrences:graph.occurrences.map((candidate)=>{if(candidate.id!==occurrenceId)return candidate;const updated={...candidate,canonicalSchema:next,schemaInstanceExamplePaths:[...new Set([...((candidate.schemaInstanceExamplePaths as string[]|undefined)??[]),path])]} as ProjectEntity;delete updated.schemaConstraints;delete updated.localSchemaContributions;return updated;})});});
}

export function deriveFlowOccurrenceExample(project:SpecificationProject,flowId:string,occurrenceId:string):FlowOccurrenceExample{
  const occurrence=storedGraph(project,flowId).occurrences.find(({id})=>id===occurrenceId);if(!occurrence)return{status:"Blocked",payload:{},formattedJson:"{}",provenance:{},issues:[{path:"/",code:"CONFLICT",message:"The Event occurrence is unavailable.",editHref:exampleEditHref(flowId,occurrenceId,"/")}]};
  const state={project} as ProjectState,path=layeredContributorPath(state,occurrence,"Event-occurrence",flowId),contributors=layeredContributorsForPath(state,path),compiled=compileLayeredSchema(contributors,{eventId:String(occurrence.eventId??""),eventRole:"interaction",occurrenceId}),payload:Record<string,unknown>={},provenance:Record<string,string>={};
  for(const[propertyPath,property]of Object.entries(compiled.properties)){
    if(property.presence==="forbidden")continue;
    let configured:{value:unknown;source:string}|undefined;
    if(property.expectedValue!==undefined)configured={value:property.expectedValue,source:property.expectedContributor??property.origins.at(-1)?.contributorName??occurrence.name};
    else for(const contributor of [...contributors].reverse()){const constraint=[...contributor.constraints].reverse().find((candidate)=>candidate.path===propertyPath&&applicableExample(candidate,occurrence,String(occurrence.eventId??""),"interaction")&&(candidate.examples?.length??0)>0);if(constraint){configured={value:constraint.examples![0],source:contributor.scope==="Event-occurrence"&&!/occurrence$/i.test(contributor.name)?`${contributor.name} occurrence`:contributor.name};break;}}
    if(configured!==undefined){setAtPath(payload,propertyPath,configured.value);provenance[propertyPath]=configured.source;}
  }
  const edit=(propertyPath:string)=>exampleEditHref(flowId,occurrenceId,propertyPath);
  if(compiled.status==="blocked"){const issues=compiled.conflicts.map(({path:propertyPath,message})=>({path:propertyPath,code:"CONFLICT" as const,message,editHref:edit(propertyPath)}));return{status:"Blocked",payload,formattedJson:JSON.stringify(payload,null,2),provenance,issues};}
  const validation=validateLayeredObservation({targetId:occurrenceId,targetName:occurrence.name,revision:Number((occurrence.canonicalSchema as CanonicalSchemaDocument|undefined)?.revision??0),compiled},payload),issues:FlowExampleIssue[]=validation.issues.map((issue)=>({path:issue.path,code:issue.code==="REQUIRED"?"REQUIRED_EXAMPLE":issue.code,message:issue.code==="REQUIRED"?"Required property has no configured example.":`${issue.code} example does not satisfy ${JSON.stringify(issue.expected)}.`,editHref:edit(issue.path)})),invalid=issues.some(({code})=>code!=="REQUIRED_EXAMPLE"),incomplete=issues.some(({code})=>code==="REQUIRED_EXAMPLE"),status:FlowOccurrenceExample["status"]=invalid?"Invalid":incomplete?"Incomplete":"Complete";
  return{status,payload,formattedJson:JSON.stringify(payload,null,2),provenance,issues};
}

export function deriveFlowPageFrameExample(project:SpecificationProject,flowId:string,pageFrameId:string):FlowOccurrenceExample{
  const frame=storedGraph(project,flowId).pageFrames.find(({id})=>id===pageFrameId),page=project.collections.pages.find(({id})=>id===frame?.pageId);if(!frame||!page)return{status:"Blocked",payload:{},formattedJson:"{}",provenance:{},issues:[{path:"/",code:"CONFLICT",message:"The Page frame is unavailable.",editHref:exampleEditHref(flowId,pageFrameId,"/")}]};
  const frameEntity={...frame,name:`${page.name} Page frame`} as ProjectEntity,state={project} as ProjectState,path=layeredContributorPath(state,frameEntity,"Flow Page-instance",flowId),contributors=layeredContributorsForPath(state,path),eventName=String(page.eventName??"pageview"),compiled=compileLayeredSchema(contributors,{eventId:eventName,eventRole:"context"}),payload:Record<string,unknown>={},provenance:Record<string,string>={};
  for(const[propertyPath,property]of Object.entries(compiled.properties)){
    if(property.presence==="forbidden")continue;
    let configured:{value:unknown;source:string}|undefined;
    if(property.expectedValue!==undefined)configured={value:property.expectedValue,source:property.expectedContributor??property.origins.at(-1)?.contributorName??page.name};
    else for(const contributor of [...contributors].reverse()){const constraint=[...contributor.constraints].reverse().find((candidate)=>candidate.path===propertyPath&&applicableExample(candidate,frameEntity,eventName,"context-setting")&&(candidate.examples?.length??0)>0);if(constraint){configured={value:constraint.examples![0],source:contributor.name};break;}}
    if(configured!==undefined){setAtPath(payload,propertyPath,configured.value);provenance[propertyPath]=configured.source;}
  }
  const edit=(propertyPath:string)=>exampleEditHref(flowId,pageFrameId,propertyPath);
  if(compiled.status==="blocked"){const issues=compiled.conflicts.map(({path:propertyPath,message})=>({path:propertyPath,code:"CONFLICT" as const,message,editHref:edit(propertyPath)}));return{status:"Blocked",payload,formattedJson:JSON.stringify(payload,null,2),provenance,issues};}
  const validation=validateLayeredObservation({targetId:pageFrameId,targetName:page.name,revision:Number(frameEntity.revision??0),compiled},payload),issues:FlowExampleIssue[]=validation.issues.map((issue)=>({path:issue.path,code:issue.code==="REQUIRED"?"REQUIRED_EXAMPLE":issue.code,message:issue.code==="REQUIRED"?"Required property has no configured example.":`${issue.code} example does not satisfy ${JSON.stringify(issue.expected)}.`,editHref:edit(issue.path)})),invalid=issues.some(({code})=>code!=="REQUIRED_EXAMPLE"),incomplete=issues.some(({code})=>code==="REQUIRED_EXAMPLE"),status:FlowOccurrenceExample["status"]=invalid?"Invalid":incomplete?"Incomplete":"Complete";
  return{status,payload,formattedJson:JSON.stringify(payload,null,2),provenance,issues};
}

export function flowOccurrenceExampleEditorRows(project:SpecificationProject,flowId:string,occurrenceId:string):FlowOccurrenceExampleEditorRow[]{
  const occurrence=storedGraph(project,flowId).occurrences.find(({id})=>id===occurrenceId);if(!occurrence)return[];const state={project} as ProjectState,path=layeredContributorPath(state,occurrence,"Event-occurrence",flowId),contributors=layeredContributorsForPath(state,path),compiled=compileLayeredSchema(contributors,{eventId:String(occurrence.eventId??""),eventRole:"interaction",occurrenceId}),example=deriveFlowOccurrenceExample(project,flowId,occurrenceId);return Object.entries(compiled.properties).map(([propertyPath,property])=>({path:propertyPath,...(property.type?{type:property.type}:{}),value:valueAtPath(example.payload,propertyPath)}));
}

export interface LegacyFlowContextMigrationItem {flowId:string;occurrenceId:string;flowName:string;occurrenceName:string;pageName:string;eventName:string;trigger:string}
export interface LegacyFlowContextMigrationBlocker {flowId:string;occurrenceId:string;flowName:string;occurrenceName:string;message:string}
export interface LegacyFlowContextMigrationReview {items:LegacyFlowContextMigrationItem[];blockers:LegacyFlowContextMigrationBlocker[]}
export function reviewLegacyFlowContextMigration(project:SpecificationProject,flowId:string):LegacyFlowContextMigrationReview{
  void flowId;const items:LegacyFlowContextMigrationItem[]=[],blockers:LegacyFlowContextMigrationBlocker[]=[];
  for(const [candidateFlowId,graph] of Object.entries(graphIndex(project))){const flow=project.collections.flows.find(({id})=>id===candidateFlowId),flowName=flow?.name??"Unknown Flow";for(const occurrence of graph.occurrences){if(!legacyBindingOccurrence(occurrence))continue;const occurrenceName=typeof occurrence.name==="string"&&occurrence.name.trim()?occurrence.name.trim():"Unnamed occurrence",base={flowId:candidateFlowId,occurrenceId:occurrence.id,flowName,occurrenceName},page=project.collections.pages.find(({id})=>id===occurrence.pageId);if(!page){blockers.push({...base,message:`${occurrenceName} in ${flowName} has a missing Page.`});continue;}const binding=((page.contextEventBindings as ProjectEntity[]|undefined)??[]).find(({id})=>id===occurrence.contextBindingId);if(!binding){blockers.push({...base,message:`${occurrenceName} in ${flowName} has a missing Page binding on ${page.name}.`});continue;}const event=project.collections.events.find(({id})=>id===binding.eventId);if(!event){blockers.push({...base,message:`${occurrenceName} in ${flowName} has a missing Event on ${page.name}.`});continue;}items.push({...base,pageName:page.name,eventName:event.name,trigger:String(binding.trigger??binding.name??"")});}}
  return{items,blockers};
}
export function migrateLegacyFlowContextBindings(state:ProjectState,flowId:string):ProjectState{
  const review=reviewLegacyFlowContextMigration(state.project,flowId);if(review.blockers.length||!review.items.length)return state;
  return transactProject(state,"Migrate legacy Flow Page context bindings",(project)=>{const eventsById=new Map(project.collections.events.map((event)=>[event.id,event])),primaryBindingByPage=new Map<string,string>(),pages=project.collections.pages.map((page)=>{const bindings=(page.contextEventBindings as ProjectEntity[]|undefined)??[],primary=bindings[0],event=eventsById.get(String(primary?.eventId??""));if(primary)primaryBindingByPage.set(page.id,primary.id);const{contextEventBindings,...stored}=page;void contextEventBindings;return{...stored,...(event?{eventName:String(event.eventName??event.name)}:{})} as ProjectEntity;}),pagesById=new Map(project.collections.pages.map((page)=>[page.id,page])),documentationFlowGraphs=Object.fromEntries(Object.entries(graphIndex(project)).map(([candidateFlowId,graph])=>{const occurrenceFrameIds=new Map(graph.occurrences.flatMap((occurrence)=>typeof occurrence.pageFrameId==="string"?[[occurrence.id,occurrence.pageFrameId] as const]:[])),removed=new Set(graph.occurrences.filter((occurrence)=>legacyBindingOccurrence(occurrence)&&primaryBindingByPage.get(String(occurrence.pageId))===occurrence.contextBindingId).map(({id})=>id)),occurrences=graph.occurrences.flatMap((occurrence)=>{const{role:discardedRole,...roleFree}=occurrence;void discardedRole;if(removed.has(occurrence.id))return[];if(!legacyBindingOccurrence(occurrence))return[roleFree];const page=pagesById.get(String(occurrence.pageId)),binding=((page?.contextEventBindings as ProjectEntity[]|undefined)??[]).find(({id})=>id===occurrence.contextBindingId),event=eventsById.get(String(binding?.eventId??""));if(!binding||!event)return[roleFree];const{contextBindingId,eventId:discardedEventId,trigger:discardedTrigger,...stored}=roleFree;void contextBindingId;void discardedEventId;void discardedTrigger;return[{...stored,eventId:event.id,trigger:String(binding.trigger??binding.name??"")}];}),migrateEndpoint=(endpoint:FlowEndpointReference|undefined):FlowEndpointReference|undefined=>endpoint?.kind==="event-occurrence"&&occurrenceFrameIds.has(endpoint.id)?{kind:"page-frame",id:occurrenceFrameIds.get(endpoint.id)!}:endpoint,relationships=graph.relationships.map((relationship)=>{const sourceEndpoint=migrateEndpoint(relationshipEndpoint(relationship,"source")),targetEndpoint=migrateEndpoint(relationshipEndpoint(relationship,"target"));if(!sourceEndpoint||!targetEndpoint)return relationship;const{sourceNodeId:discardedSource,targetNodeId:discardedTarget,...stored}=relationship;void discardedSource;void discardedTarget;return{...stored,sourceEndpoint,targetEndpoint};});return[candidateFlowId,{...graph,occurrences,relationships}];})),events=project.collections.events.map((event)=>{const{role,...stored}=event;void role;return stored as ProjectEntity;});return{...project,collections:{...project.collections,pages,events},documentationFlowGraphs};});
}
export function migrateLegacyFlowRelationshipKinds(state:ProjectState,flowId:string):ProjectState{
  const graph=storedGraph(state.project,flowId),requiresMigration=graph.relationships.some((relationship)=>relationship.kind==="parallel");
  if(!requiresMigration)return state;
  return transactProject(state,"Migrate legacy Flow relationship kinds",(project)=>{const current=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...current,relationships:current.relationships.map((relationship)=>relationship.kind==="parallel"?{...relationship,...relationshipPorts(relationship),kind:"alternative"}:relationship)});});
}
export function saveGraphRelationship(state:ProjectState,flowId:string,fromOccurrenceId:string,input:FlowRelationshipInput,id:IdFactory):ProjectState{
  const graph=storedGraph(state.project,flowId),frameIds=new Set(graph.pageFrames.map(({id})=>id)),endpoint=(endpointId:string):FlowEndpointReference|undefined=>frameIds.has(endpointId)?{kind:"page-frame",id:endpointId}:undefined,sourceEndpoint=endpoint(fromOccurrenceId),targetEndpoint=endpoint(input.toStepId);if(fromOccurrenceId===input.toStepId)return state;if(!state.project.collections.flows.some(({id})=>id===flowId)||!sourceEndpoint||!targetEndpoint)throw new Error("A Flow relationship requires existing source and target Page frames.");const kind=inferFlowRelationshipKind(input.sourcePort,input.targetPort);if(!kind)return state;
  return transactProject(state,`Save Flow relationship ${input.id??"new"}`,(project)=>{const current=storedGraph(project,flowId),relationship:DocumentaryRelationshipRecord={id:input.id??id("flow-relationship"),sourceEndpoint,targetEndpoint,sourcePort:input.sourcePort,targetPort:input.targetPort,kind,...(input.group?{group:input.group}:{}),...(input.label?{label:input.label}:{}),...(input.documentationCondition?{documentationCondition:input.documentationCondition}:{}),...(input.expectation?{expectation:input.expectation}:{})};return saveStoredGraph(project,flowId,{...current,relationships:current.relationships.some(({id})=>id===relationship.id)?current.relationships.map((candidate)=>candidate.id===relationship.id?relationship:candidate):[...current.relationships,relationship]});});
}
export function removeFlowRelationship(state:ProjectState,flowId:string,relationshipId:string):ProjectState{
  if(!storedGraph(state.project,flowId).relationships.some(({id})=>id===relationshipId))return state;
  return transactProject(state,`Delete Flow relationship ${relationshipId}`,(project)=>{const current=storedGraph(project,flowId);return saveStoredGraph(project,flowId,{...current,relationships:current.relationships.filter(({id})=>id!==relationshipId)});});
}

export function flowRelationshipText(graph:FlowGraph,relationship:FlowRelationship):string{const source=graph.connectionEndpoints.find(({id,kind})=>id===relationship.sourceEndpoint.id&&kind===relationship.sourceEndpoint.kind),target=graph.connectionEndpoints.find(({id,kind})=>id===relationship.targetEndpoint.id&&kind===relationship.targetEndpoint.kind);return[source?.name??"Missing endpoint",relationship.kind,target?.name??"Missing endpoint",relationship.group,relationship.label,relationship.documentationCondition,relationship.expectation].filter((value)=>value!==undefined&&value!=="").join(" · ");}
export function inspectFlowGraph(graph:FlowGraph,catalog:FlowCatalog):FlowDiagnostic[]{const diagnostics:FlowDiagnostic[]=[],endpointKeys=new Set(graph.connectionEndpoints.map(({kind,id})=>`${kind}:${id}`));for(const node of graph.nodes){if(!catalog.events.some(({id})=>id===node.eventId))diagnostics.push({kind:"missing-event",message:`${node.name} has no resolved Event`,nodeId:node.id});if(!catalog.pages.some(({id})=>id===node.pageId))diagnostics.push({kind:"missing-page",message:`${node.name} has no resolved Page`,nodeId:node.id});}for(const relationship of graph.relationships)if(!endpointKeys.has(`${relationship.sourceEndpoint.kind}:${relationship.sourceEndpoint.id}`)||!endpointKeys.has(`${relationship.targetEndpoint.kind}:${relationship.targetEndpoint.id}`))diagnostics.push({kind:"dangling-relationship",message:`Relationship ${relationship.id} has a missing endpoint`,relationshipId:relationship.id});return diagnostics;}
export function flowOutline(graph:FlowGraph):{nodeId:string;name:string;role:FlowRole;obligation:FlowObligation;expectedMinimum:number;expectedMaximum?:number;relationshipIds:string[]}[]{return graph.nodes.map((node)=>({nodeId:node.id,name:node.name,role:node.role,obligation:node.obligation,expectedMinimum:node.expectedMinimum,...(node.expectedMaximum!==undefined?{expectedMaximum:node.expectedMaximum}:{}),relationshipIds:graph.relationships.filter(({sourceNodeId})=>sourceNodeId===node.id).map(({id})=>id)}));}
export function projectFlowGraph(project:SpecificationProject,flowId:string):FlowGraphProjection{
  const flow=project.collections.flows.find(({id})=>id===flowId);if(!flow)throw new Error(`Unknown Flow ${flowId}`);
  const laneIds=flowPageGroupLaneIds(project,flowId),lanes=laneIds.map((groupId)=>project.collections.pageGroups.find(({id})=>id===groupId)).filter((group):group is ProjectEntity=>Boolean(group)).map(clone),stored=storedGraph(project,flowId),frameById=new Map(stored.pageFrames.map((frame)=>[frame.id,frame])),freeFrames=stored.pageFrames.filter(({freePageRegion})=>Boolean(freePageRegion)),legacyFreeFrames=stored.occurrences.filter(({freePageFrame})=>freePageFrame),hasBefore=[...freeFrames,...legacyFreeFrames].some(({freePageRegion})=>freePageRegion==="before-lanes"),laneOffset=hasBefore?200:0,freeFrameById=new Map([...freeFrames,...legacyFreeFrames].map((frame)=>[frame.id,frame])),frameSize=(frame:DocumentaryPageFrameRecord)=>{const children=stored.occurrences.filter(({pageFrameId})=>pageFrameId===frame.id),width=Math.max(FLOW_GRAPH_GEOMETRY.pageFrameMinWidth,...children.map((child)=>Number((child.position as {x?:number}|undefined)?.x??24)+FLOW_GRAPH_GEOMETRY.eventWidth+FLOW_GRAPH_GEOMETRY.pageFrameChildRightPadding)),height=Math.max(FLOW_GRAPH_GEOMETRY.pageFrameMinHeight,...children.map((child)=>Number((child.position as {y?:number}|undefined)?.y??70)+FLOW_GRAPH_GEOMETRY.eventHeight+FLOW_GRAPH_GEOMETRY.pageFrameChildBottomPadding));return{width,height};},laneBands:FlowLaneBand[]=[];
  let nextBandY=20;for(const [index,lane]of lanes.entries()){const frames=stored.pageFrames.filter(({pageGroupId,freePageRegion})=>pageGroupId===lane.id&&!freePageRegion),height=Math.max(240,...frames.map((frame)=>Number(frame.position.y??40)+frameSize(frame).height+40));laneBands.push({id:lane.id,name:lane.name,y:nextBandY,height});nextBandY+=height+24;void index;}
  const bandById=new Map(laneBands.map((band)=>[band.id,band])),namedWidth=Math.max(900,...stored.pageFrames.filter(({freePageRegion})=>!freePageRegion).map((frame)=>Number(frame.position.x??40)+frameSize(frame).width+60));
  const frameEndpoints:FlowConnectionEndpoint[]=stored.pageFrames.map((frame)=>{const page=project.collections.pages.find(({id})=>id===frame.pageId),size=frameSize(frame),band=frame.pageGroupId?bandById.get(frame.pageGroupId):undefined,region=(frame.freePageRegion??"after-lanes") as FreePageRegion,x=frame.freePageRegion?(region==="before-lanes"?Number(frame.position.x??24):laneOffset+namedWidth+Number(frame.position.x??24)):laneOffset+Number(frame.position.x??40),y=frame.freePageRegion?Number(frame.position.y??55):Number(band?.y??20)+Number(frame.position.y??40),lane=frame.freePageRegion?region:band?.name??String(frame.pageGroupId??"unplaced"),siblings=stored.pageFrames.filter(({pageId})=>pageId===frame.pageId),instance=siblings.findIndex(({id})=>id===frame.id)+1,baseName=page?.name??frame.pageId,name=siblings.length>1?`${baseName} instance ${instance}`:baseName;return{kind:"page-frame",id:frame.id,name,pageId:frame.pageId,...(frame.pageGroupId?{pageGroupId:frame.pageGroupId}:{}),...(frame.freePageRegion?{freePageRegion:frame.freePageRegion}:{}),layout:{lane,x,y},width:size.width,height:size.height};}),frameEndpointById=new Map(frameEndpoints.map((endpoint)=>[endpoint.id,endpoint]));
  const nodes:FlowNode[]=stored.occurrences.filter(({freePageFrame})=>!freePageFrame).map((occurrence)=>{
    const page=project.collections.pages.find(({id})=>id===occurrence.pageId),binding=legacyBindingOccurrence(occurrence)?((page?.contextEventBindings as ProjectEntity[]|undefined)??[]).find(({id})=>id===occurrence.contextBindingId):undefined,eventId=String(binding?.eventId??occurrence.eventId??""),event=project.collections.events.find(({id})=>id===eventId),position=occurrence.position as {x?:number;y?:number}|undefined,containingFrame=frameById.get(String(occurrence.pageFrameId??"")),containingEndpoint=frameEndpointById.get(String(occurrence.pageFrameId??"")),pageGroupId=typeof containingFrame?.pageGroupId==="string"?containingFrame.pageGroupId:typeof occurrence.pageGroupId==="string"?occurrence.pageGroupId:undefined,parentFree=freeFrameById.get(String(occurrence.pageFrameId??occurrence.freePageFrameId??"")),freePageRegion=(parentFree?.freePageRegion??"after-lanes") as FreePageRegion,laneIndex=pageGroupId?laneIds.indexOf(pageGroupId):-1,layout=position&&typeof position.y==="number"?(containingEndpoint?{lane:containingEndpoint.layout.lane,x:containingEndpoint.layout.x+Number(position.x??24),y:containingEndpoint.layout.y+position.y}:parentFree?{lane:freePageRegion,x:Number(position.x??30),y:position.y}:laneIndex>=0?{lane:String(lanes[laneIndex]?.name??pageGroupId),x:laneOffset+30+laneIndex*200,y:position.y}:typeof occurrence.lane==="string"?{lane:occurrence.lane,x:Number(position.x??30),y:position.y}:undefined):undefined;
    return{id:occurrence.id,name:String(event?.name??occurrence.name),eventId,pageId:String(occurrence.pageId??""),...(occurrence.pageFrameId?{pageFrameId:String(occurrence.pageFrameId)}:{}),...(pageGroupId?{pageGroupId}:{}),...(parentFree?{freePageFrameId:parentFree.id,freePageRegion}:{}),role:"interaction",...(typeof occurrence.trigger==="string"?{trigger:occurrence.trigger}:binding?.trigger?{trigger:String(binding.trigger)}:{}),obligation:(typeof occurrence.obligation==="string"?occurrence.obligation:occurrence.optional?"Optional":"Required") as FlowObligation,expectedMinimum:Number(occurrence.minimum??1),...(occurrence.maximum!==undefined?{expectedMaximum:Number(occurrence.maximum)}:{}),...(layout?{layout}:{})};
  }),connectionEndpoints=[...frameEndpoints],relationships:FlowRelationship[]=stored.relationships.flatMap((edge)=>{const sourceEndpoint=relationshipEndpoint(edge,"source"),targetEndpoint=relationshipEndpoint(edge,"target");if(sourceEndpoint?.kind!=="page-frame"||targetEndpoint?.kind!=="page-frame")return[];const{sourcePort,targetPort}=relationshipPorts(edge),kind=inferFlowRelationshipKind(sourcePort,targetPort)??"expected_next";return[{id:edge.id,sourceEndpoint,targetEndpoint,sourceNodeId:sourceEndpoint.id,targetNodeId:targetEndpoint.id,sourcePort,targetPort,kind,...(typeof edge.group==="string"?{group:edge.group}:{}),...(typeof edge.label==="string"&&edge.label?{label:edge.label}:{}),...(typeof edge.documentationCondition==="string"?{documentationCondition:edge.documentationCondition}:{}),...(typeof edge.expectation==="string"?{expectation:edge.expectation}:{})}];}),graph:FlowGraph={id:flow.id,name:flow.name,purpose:String(flow.purpose??flow.description??""),nodes,connectionEndpoints,relationships},catalog:FlowCatalog={pageGroups:project.collections.pageGroups.map((group)=>clone(group)),pages:project.collections.pages.map((page)=>clone(page)),events:project.collections.events.map((event)=>clone(event))};return{projectName:project.name,lanes,laneBands,graph,catalog,diagnostics:inspectFlowGraph(graph,catalog)};
}
