import {addPropertySetApplication,createFlowSection,inspectSectionRemovalWithContents,moveFlowSection,movePageFrameToSection,orderedPropertySetApplications,removeFlowSection,removeFlowSectionWithContents,removePropertySetApplication,renameAndResizeFlowSection,reorderPropertySetApplication,type FlowSection,type FlowSectionBounds} from "./data-layer-property-set-flow-section.js";
import type {IdFactory,ProjectEntity,ProjectState} from "./data-layer-specification-project.js";

export interface FlowSectionWorkspaceOptions {host:HTMLElement;state:ProjectState;flowId:string;id:IdFactory;onSave:(state:ProjectState)=>void;}
export interface PropertyCompositionWorkspaceOptions {host:HTMLElement;state:ProjectState;pageId:string;id:IdFactory;onSave:(state:ProjectState)=>void;onOpen?:(propertySetId:string)=>void;}
type SectionGraph={sections?:FlowSection[];pageFrames?:ProjectEntity[]};
const number=(value:unknown,fallback:number):number=>Number.isFinite(Number(value))?Number(value):fallback;
const graphFor=(state:ProjectState,flowId:string):SectionGraph=>((state.project.documentationFlowGraphs as Record<string,SectionGraph>|undefined)?.[flowId]??{});

export function mountPropertyCompositionWorkspace({host,state,pageId,id,onSave,onOpen}:PropertyCompositionWorkspaceOptions):HTMLElement{
  const page=state.project.collections.pages.find(({id})=>id===pageId);if(!page)throw new Error(`Unknown Page ${pageId}.`);const propertySets=((state.project.collections as typeof state.project.collections&{propertySets?:ProjectEntity[]}).propertySets??state.project.collections.pageGroups),byId=new Map(propertySets.map((set)=>[set.id,set])),workspace=document.createElement("section"),heading=document.createElement("h2"),guidance=document.createElement("p"),search=document.createElement("input"),results=document.createElement("div"),list=document.createElement("ol");workspace.className="property-composition-workspace";workspace.dataset.propertyComposition=page.id;workspace.setAttribute("aria-label",`Property composition for ${page.name}`);heading.textContent="Property composition";guidance.textContent="Applied Property Sets in general-to-specific order. Each application owns its optional Applicability Set; Shared Profile source inheritance remains selective and separately managed.";search.type="search";search.setAttribute("aria-label","Search Property Sets to apply");results.setAttribute("aria-label","Property Set search results");list.setAttribute("aria-label","Applied Property Sets");
  const renderResults=()=>{const query=search.value.trim().toLocaleLowerCase(),applied=new Set(orderedPropertySetApplications(state.project,page.id).map(({propertySetId})=>propertySetId));results.replaceChildren(...propertySets.filter((set)=>!applied.has(set.id)&&set.name.toLocaleLowerCase().includes(query)).map((set)=>{const button=document.createElement("button");button.type="button";button.textContent=`Apply ${set.name}`;button.setAttribute("aria-label",`Apply Property Set ${set.name} to ${page.name}`);button.addEventListener("click",()=>onSave(addPropertySetApplication(state,page.id,set.id,undefined,id)));return button;}));};search.addEventListener("input",renderResults);renderResults();
  const applications=orderedPropertySetApplications(state.project,page.id);for(const[order,application]of applications.entries()){const set=byId.get(application.propertySetId),row=document.createElement("li"),summary=document.createElement("p"),open=document.createElement("button"),earlier=document.createElement("button"),later=document.createElement("button"),remove=document.createElement("button");row.dataset.propertySetApplicationId=application.id;summary.textContent=`${set?.name??application.propertySetId} · applicability ${application.applicabilitySetId??"Always"} · complete effective contribution · provenance Property Set ${set?.name??application.propertySetId}`;for(const control of[open,earlier,later,remove])control.type="button";open.textContent="Open Property Set";open.setAttribute("aria-label",`Open Property Set ${set?.name??application.propertySetId}`);earlier.textContent="Move earlier";later.textContent="Move later";remove.textContent="Remove application";earlier.disabled=order===0;later.disabled=order===applications.length-1;open.addEventListener("click",()=>onOpen?.(application.propertySetId));earlier.addEventListener("click",()=>onSave(reorderPropertySetApplication(state,page.id,application.propertySetId,-1)));later.addEventListener("click",()=>onSave(reorderPropertySetApplication(state,page.id,application.propertySetId,1)));remove.addEventListener("click",()=>onSave(removePropertySetApplication(state,page.id,application.propertySetId)));row.append(summary,open,earlier,later,remove);list.append(row);}workspace.append(heading,guidance,search,results,list);host.append(workspace);return workspace;
}

export function mountFlowSectionWorkspace({host,state,flowId,id,onSave}:FlowSectionWorkspaceOptions):HTMLElement{
  const graph=graphFor(state,flowId),workspace=document.createElement("section"),heading=document.createElement("h2"),guidance=document.createElement("p"),createForm=document.createElement("form"),name=document.createElement("input"),add=document.createElement("button"),list=document.createElement("div"),placement=document.createElement("fieldset"),placementLegend=document.createElement("legend"),frameSelect=document.createElement("select"),sectionSelect=document.createElement("select"),place=document.createElement("button"),outside=document.createElement("button"),status=document.createElement("output");
  workspace.className="flow-section-workspace";workspace.dataset.flowSectionWorkspace=flowId;workspace.setAttribute("aria-label","Flow Sections");heading.textContent="Sections";guidance.textContent="Flow-owned presentation containers. Section changes never change Property composition, applicability, schema provenance, validation, or Assignment targets.";name.required=true;name.placeholder="Section name";name.setAttribute("aria-label","New Section name");add.type="submit";add.textContent="Add Section";createForm.append(name,add);list.setAttribute("aria-label","Section outline");
  createForm.addEventListener("submit",(event)=>{event.preventDefault();try{onSave(createFlowSection(state,flowId,{name:name.value,bounds:{x:24,y:48+(graph.sections?.length??0)*220,width:640,height:190}},id));}catch(error){status.textContent=error instanceof Error?error.message:String(error);}});
  for(const section of [...(graph.sections??[])].sort((left,right)=>left.order-right.order)){
    const row=document.createElement("article"),title=document.createElement("h3"),rename=document.createElement("input"),x=document.createElement("input"),y=document.createElement("input"),width=document.createElement("input"),height=document.createElement("input"),save=document.createElement("button"),move=document.createElement("button"),remove=document.createElement("button"),destructive=document.createElement("button"),review=document.createElement("section");
    row.dataset.flowSectionId=section.id;title.textContent=section.name;rename.value=section.name;rename.setAttribute("aria-label",`Section name ${section.name}`);for(const[control,label,value]of[[x,"Section x",section.bounds.x],[y,"Section y",section.bounds.y],[width,"Section width",section.bounds.width],[height,"Section height",section.bounds.height]] as const){control.type="number";control.value=String(value);control.setAttribute("aria-label",`${label} ${section.name}`);}for(const control of[save,move,remove,destructive])control.type="button";save.textContent="Save name and size";move.textContent="Move Section";remove.textContent="Remove Section and retain Page frames";destructive.textContent="Review remove Section with contents";review.hidden=true;review.setAttribute("aria-label",`Remove ${section.name} with contents review`);
    const bounds=():FlowSectionBounds=>({x:number(x.value,section.bounds.x),y:number(y.value,section.bounds.y),width:number(width.value,section.bounds.width),height:number(height.value,section.bounds.height)});save.addEventListener("click",()=>onSave(renameAndResizeFlowSection(state,flowId,section.id,{name:rename.value,bounds:bounds()})));move.addEventListener("click",()=>onSave(moveFlowSection(state,flowId,section.id,{x:number(x.value,section.bounds.x),y:number(y.value,section.bounds.y)})));remove.addEventListener("click",()=>onSave(removeFlowSection(state,flowId,section.id)));destructive.addEventListener("click",()=>{const impact=inspectSectionRemovalWithContents(state.project,flowId,section.id),summary=document.createElement("p"),confirm=document.createElement("button"),cancel=document.createElement("button");summary.textContent=`Remove Page frames: ${impact.pageFrames.map(({name})=>name).join(", ")||"none"}. Remove relationships: ${impact.relationships.map(({name})=>name).join(", ")||"none"}. Nothing changes until confirmed.`;confirm.type=cancel.type="button";confirm.textContent="Confirm remove Section with contents";cancel.textContent="Cancel";confirm.addEventListener("click",()=>onSave(removeFlowSectionWithContents(state,flowId,section.id,impact)));cancel.addEventListener("click",()=>{review.hidden=true;review.replaceChildren();destructive.focus();});review.replaceChildren(summary,confirm,cancel);review.hidden=false;confirm.focus();});row.append(title,rename,x,y,width,height,save,move,remove,destructive,review);list.append(row);
  }
  placementLegend.textContent="Organize Page frames";frameSelect.setAttribute("aria-label","Page frame to organize");sectionSelect.setAttribute("aria-label","Destination Section");frameSelect.append(new Option("Choose Page frame",""),...(graph.pageFrames??[]).map((frame)=>new Option(frame.name,frame.id)));sectionSelect.append(new Option("Choose Section",""),...(graph.sections??[]).map((section)=>new Option(section.name,section.id)));place.type=outside.type="button";place.textContent="Place in Section";outside.textContent="Move outside every Section";place.addEventListener("click",()=>{if(frameSelect.value&&sectionSelect.value)onSave(movePageFrameToSection(state,flowId,frameSelect.value,sectionSelect.value));});outside.addEventListener("click",()=>{if(frameSelect.value)onSave(movePageFrameToSection(state,flowId,frameSelect.value));});placement.append(placementLegend,frameSelect,sectionSelect,place,outside);workspace.append(heading,guidance,createForm,list,placement,status);host.append(workspace);return workspace;
}
