import type { SourceAdapter } from "./data-layer-source.js";
export interface ReplayTemplate { id:string; name:string; version:number; sourceId:string; destination:string; payload:unknown; }
export interface ReplayStep { id:string; templateId:string; templateVersion:number; enabled:boolean; destination:string; delayMs:number; breakpoint:boolean; payloadOverride?:unknown; }
export interface ReplaySequence { id:string; name:string; steps:readonly ReplayStep[]; originatingSessionId:string; }
export interface ExecutionStep { stepId:string; templateId:string; templateVersion:number; sourceId:string; destination:string; payload:unknown; timestamp:string; result:string; }
export interface ExecutionRecord { id:string; sequenceId:string; pageUrl:string; result:string; steps:readonly ExecutionStep[]; immutable:true; }
const clone=<T>(value:T):T=>structuredClone(value);
export function createSequence(id:string,name:string,sessionId:string,templates:readonly ReplayTemplate[]):ReplaySequence { return {id,name,originatingSessionId:sessionId,steps:templates.map((t,index)=>({id:`step:${index+1}`,templateId:t.id,templateVersion:t.version,enabled:true,destination:t.destination,delayMs:0,breakpoint:false}))}; }
export function updateStep(sequence:ReplaySequence,id:string,change:Partial<ReplayStep>):ReplaySequence { return {...sequence,steps:sequence.steps.map(step=>step.id===id?{...step,...clone(change)}:step)}; }
export function reorderStep(sequence:ReplaySequence,from:number,to:number):ReplaySequence { const steps=[...sequence.steps]; const [step]=steps.splice(from,1); if(!step) return sequence; steps.splice(to,0,step); return {...sequence,steps}; }
export function duplicateStep(sequence:ReplaySequence,id:string):ReplaySequence { const step=sequence.steps.find(item=>item.id===id); return step?{...sequence,steps:[...sequence.steps,{...step,id:`${step.id}:copy`}] }:sequence; }
export function removeStep(sequence:ReplaySequence,id:string):ReplaySequence { return {...sequence,steps:sequence.steps.filter(step=>step.id!==id)}; }
export function readiness(sequence:ReplaySequence,templates:readonly ReplayTemplate[],adapters:readonly SourceAdapter[]):{runnable:boolean; blocked:readonly string[]} { const tm=new Map(templates.map(t=>[t.id,t])); const am=new Map(adapters.map(a=>[a.id,a])); const blocked=sequence.steps.filter(s=>s.enabled).flatMap(s=>{const t=tm.get(s.templateId);const a=t&&am.get(t.sourceId);return !t||!a||!a.enabled||a.destination!==s.destination||!a.capabilities.includes("push")?[s.id]:[]}); return {runnable:blocked.length===0,blocked}; }
export function runSequence(sequence:ReplaySequence,templates:readonly ReplayTemplate[],adapters:readonly SourceAdapter[],pageUrl:string,action:"Run step"|"Run all",now=()=>new Date().toISOString()):ExecutionRecord { const ready=readiness(sequence,templates,adapters); if(!ready.runnable) throw new Error(`Not runnable: ${ready.blocked.join(", ")}`); const tm=new Map(templates.map(t=>[t.id,t])); const steps=sequence.steps.filter(s=>s.enabled).slice(0,action==="Run step"?1:undefined).map(step=>{const t=tm.get(step.templateId) as ReplayTemplate;return {stepId:step.id,templateId:t.id,templateVersion:step.templateVersion,sourceId:t.sourceId,destination:step.destination,payload:clone(step.payloadOverride??t.payload),timestamp:now(),result:"completed"};}); return Object.freeze({id:`execution:${sequence.id}:${steps.length}`,sequenceId:sequence.id,pageUrl,result:"completed",steps:Object.freeze(steps),immutable:true}); }
export function updatePinnedVersion(sequence:ReplaySequence,stepId:string,version:number):ReplaySequence{return updateStep(sequence,stepId,{templateVersion:version});}
