import type {CanonicalPropertyNode,CanonicalRule} from "./data-layer-canonical-schema.js";
import {focusedRuleFields} from "./data-layer-focused-schema-property-ui.js";

export interface CanonicalFocusedRuleAddContext {dom:Document;getWorking:()=>CanonicalPropertyNode|undefined;id:(kind:string)=>string;render:()=>void;feedback:(message:string)=>void;}
const labeled=(dom:Document,text:string,control:HTMLElement):HTMLLabelElement=>{const label=dom.createElement("label");label.append(text,control);return label;};
const input=(dom:Document,name:string,value="",type="text"):HTMLInputElement=>{const control=dom.createElement("input");control.name=name;control.type=type;control.value=value;return control;};
const button=(dom:Document,text:string,run:()=>void):HTMLButtonElement=>{const control=dom.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function renderCanonicalRuleAddPanel(host:HTMLElement,context:CanonicalFocusedRuleAddContext):void {
  const {dom}=context,working=context.getWorking();if(!working)return;const panel=dom.createElement("fieldset"),legend=dom.createElement("legend"),kind=dom.createElement("select"),fields=dom.createElement("div");legend.textContent="Add rule";kind.name="ruleKind";kind.append(new Option("Choose rule kind",""),...(["pattern","range","cardinality","condition","custom"] as const).map((entry)=>new Option(entry,entry)));
  const renderFields=()=>{fields.replaceChildren();if(!kind.value)return;for(const field of focusedRuleFields(kind.value)){if(field==="condition")continue;if(field==="reusableRuleId"){const search=input(dom,"reusableRuleSearch");search.type="search";search.placeholder="Search reusable rules by name";const reusable=dom.createElement("select");reusable.name="newRuleReusableRuleId";reusable.setAttribute("aria-label","Reusable rule name");reusable.append(new Option("No reusable rule",""),...working.rules.filter(({reusableRuleId},index,array)=>reusableRuleId&&array.findIndex((candidate)=>candidate.reusableRuleId===reusableRuleId)===index).map((candidate)=>new Option(candidate.name??candidate.reusableRuleId!,candidate.reusableRuleId!)));fields.append(labeled(dom,"Search reusable rules",search),labeled(dom,"Reusable rule",reusable));continue;}fields.append(labeled(dom,field,input(dom,`newRule${field[0]!.toUpperCase()+field.slice(1)}`,"",["minimum","maximum","minItems","maxItems"].includes(field)?"number":"text")));}};
  kind.addEventListener("change",renderFields);renderFields();
  panel.append(legend,labeled(dom,"Rule kind",kind),fields,button(dom,"Add rule",()=>{const next=context.getWorking();if(!next||!kind.value)return;const rule:CanonicalRule={id:context.id("rule"),kind:kind.value as CanonicalRule["kind"],severity:"error",message:""};for(const field of ["pattern","minimum","maximum","minItems","maxItems"]){const control=fields.querySelector<HTMLInputElement>(`[name="newRule${field[0]!.toUpperCase()+field.slice(1)}"]`);if(control?.value)Object.assign(rule,{[field]:field.includes("Items")||["minimum","maximum"].includes(field)?Number(control.value):control.value});}const message=fields.querySelector<HTMLInputElement>("[name=\"newRuleMessage\"]");if(message)rule.message=message.value;const reusable=fields.querySelector<HTMLSelectElement>("[name=\"newRuleReusableRuleId\"]");if(reusable?.value)rule.reusableRuleId=reusable.value;next.rules=[...next.rules,rule];context.feedback("Staged rule addition.");context.render();}));
  host.append(panel);
}
