export {compileLayeredSchema} from "./layered-schema/compile.js";
export {exportLayeredSchema} from "./layered-schema/export.js";
export {validateLayeredObservation} from "./layered-schema/validation.js";
export {layeredConditionMatches,resolveConditionalLayeredSchema} from "./layered-schema/conditional-rules.js";
export {resolveLayeredTarget,type LayerPredicate,type LayerResolution,type LayerTarget} from "./layered-schema/targets.js";
export type LayerScope="Shared Profile"|"Event"|"Page Group"|"Page"|"Flow Page-instance"|"Event-occurrence";
export type LayerPresence="required"|"optional"|"forbidden"|"permitted";
export type LayerActivation="automatic"|"manual"|"documentation-only";
export interface LayerValueProvenance{id:string;state:"inherited"|"local"|"overridden";contributorId?:string;source?:string;}
export interface LayerPeerFacetResolution{selectedContributorId:string;selectedFacet:keyof LayerConstraint;rejectedContributorId:string;rejectedFacet:keyof LayerConstraint;}
export interface LayerItemSchema{id:string;type?:string;items?:LayerItemSchema;allowedValues?:readonly unknown[]}
export interface LayerConstraint{path:string;concept?:string;type?:string;nullable?:boolean;onlyDefinedFields?:boolean;itemType?:string;itemSchema?:LayerItemSchema;allowedValues?:readonly unknown[];allowedValueIds?:readonly string[];allowedValueProvenance?:readonly LayerValueProvenance[];presence?:LayerPresence;protectedFacets?:readonly ("type"|"presence")[];patterns?:readonly string[];minimum?:number;maximum?:number;minItems?:number;maxItems?:number;rules?:readonly Record<string,unknown>[];reusableRules?:readonly Record<string,unknown>[];expectedValue?:unknown;enforcement?:"invariant"|"overridable";target?:string;condition?:Record<string,unknown>;displayText?:string;documentation?:string;comments?:string;examples?:readonly unknown[];definitionId?:string;overrideReferences?:readonly string[];peerFacetResolutions?:readonly LayerPeerFacetResolution[];selectionReason?:"direct"|"structural"|"rule-dependency"}
export interface LayerOrigin{contributorId:string;contributorName:string;scope:LayerScope;inheritanceRoutes?:readonly string[]}
export interface LayerPeerContribution{contributorId:string;contributorName:string;constraint:LayerConstraint}
export interface LayerDownstreamContribution extends LayerPeerContribution{scope:LayerScope;inheritanceRoutes?:readonly string[];parallelPair?:boolean}
export interface LayerContributor{id:string;name:string;scope:LayerScope;revision?:number;constraints:readonly LayerConstraint[];onlyDefinedFields?:boolean;active?:boolean;applicabilityConditional?:boolean;applicabilitySetId?:string;applicabilitySetName?:string;applicabilityCondition?:Record<string,unknown>;exclusionReason?:string;inheritanceRoutes?:readonly string[];inheritanceConflicts?:readonly {path:string;sourceRuleId:string;dependencyPropertyId:string}[];peerGroup?:string}
export interface LayerContext{eventId:string;eventRole:"context"|"interaction";occurrenceId?:string}
export type LayerConflictFacet="Type"|"Presence"|"Allowed values"|"Expected value"|"Pattern rule"|"Range rule"|"Cardinality rule"|"Conditional rule dependency"|"Array item definition"|"Structure";
export type LayerConflictSection="Definition"|"Rules"|"Structure";
export interface EffectiveProperty extends LayerConstraint{origins:LayerOrigin[];superseded:{contributorId:string;contributorName:string;value:unknown}[];facetSources?:Partial<Record<"type"|"presence"|"allowedValues"|"expectedValue"|"itemSchema"|"patterns"|"range"|"cardinality",LayerOrigin>>;expectedContributor?:string;expectedContributors?:string[];peerContributions?:LayerPeerContribution[];downstreamContributions?:LayerDownstreamContribution[]}
export interface LayerConflict{path:string;message:string;contributors:string[];contributorIds?:string[];facet?:LayerConflictFacet;section?:LayerConflictSection;sourceContributor?:string;sourceContributorId?:string;sourceValue?:unknown;sourceFacet?:keyof LayerConstraint;sourceFacetProtected?:boolean;sourceRuleId?:string;sourceRuleInvariant?:boolean;localContributor?:string;localContributorId?:string;localValue?:unknown;localFacet?:keyof LayerConstraint;localFacetProtected?:boolean;localRuleId?:string;localRuleInvariant?:boolean}
export interface CompiledLayeredSchema{status:"ready"|"blocked";properties:Record<string,EffectiveProperty>;conflicts:LayerConflict[];provenance:LayerOrigin[];exclusions:{contributorId:string;contributorName:string;path:string;target:string}[];onlyDefinedFields?:boolean}
