import {canonicalRequirements} from "./data-layer-canonical-schema.js";
import {compileLayeredSchema,type CompiledLayeredSchema} from "./data-layer-layered-schema.js";
import {layeredContributorPath,layeredContributorsForPath} from "./data-layer-layered-schema-project.js";
import {captureMatrixTable,configureFlowDocumentationTable,flowValueMapTable,type FlowDocumentationSnapshot} from "./data-layer-flow-table-documentation-export.js";
import {flowDocumentationSnapshotFromState,type FlowDocumentationExportPorts} from "./data-layer-flow-table-documentation-export-ui.js";
import {
  compileProjectDocumentationSnapshot,
  createProjectDocumentationSet,
  createProjectDocumentationTheme,
  projectDocumentationSnapshotStale,
  renderProjectDocumentationClipboard,
  selectProjectDocumentationTables,
  themeFingerprint,
  writeProjectDocumentationWorkbook,
  type ProjectDocumentationDiagnostic,
  type ProjectDocumentationSection,
  type ProjectDocumentationSelection,
  type ProjectDocumentationSet,
  type ProjectDocumentationSnapshot,
  type ProjectDocumentationTable,
  type ProjectDocumentationTheme,
} from "./data-layer-project-documentation-workspace.js";
import type {Profile,ProjectEntity,ProjectState} from "./data-layer-specification-project.js";

interface Options {
  state:()=>ProjectState|undefined;
  revision:()=>number;
  save:(documentation:{sets:ProjectDocumentationSet[];themes:ProjectDocumentationTheme[]},label:string)=>void;
  ports?:FlowDocumentationExportPorts;
}
const button=(text:string,action:()=>void):HTMLButtonElement=>{const value=document.createElement("button");value.type="button";value.textContent=text;value.addEventListener("click",action);return value;};
const labelled=(text:string,control:HTMLElement):HTMLLabelElement=>{const value=document.createElement("label");value.append(control,` ${text}`);return value;};
const stableRevision=(value:unknown):number=>{let hash=2166136261;for(const byte of new TextEncoder().encode(JSON.stringify(value)))hash=Math.imul(hash^byte,16777619);return hash>>>0;};
const defaultPorts=():FlowDocumentationExportPorts=>({writePlain:async(value)=>navigator.clipboard.writeText(value),writeRich:async(html,plain)=>{if(globalThis.ClipboardItem&&navigator.clipboard.write){await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([plain],{type:"text/plain"})})]);return;}await navigator.clipboard.writeText(plain);},download:(name,bytes,type)=>{const url=URL.createObjectURL(new Blob([Uint8Array.from(bytes).buffer],{type})),link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}});
const defaultTheme=(id:string,name="Project theme"):ProjectDocumentationTheme=>createProjectDocumentationTheme({id,name,clientName:"",logo:"",colors:{heading:"#222222",accent:"#336699",stripe:"#f4f4f4"},typography:{family:"Arial",headingSize:16,bodySize:11},density:"comfortable",borders:true,striping:true,highlightedHeadings:true,columnWidths:{Property:28,Description:48},headerText:"",footerText:""});
const profileTable=(section:ProjectDocumentationSection,profile:Profile):ProjectDocumentationTable=>{
  const requirements=profile.canonicalSchema?canonicalRequirements(profile.canonicalSchema):profile.requirements;
  return{id:section.id,title:section.name,headings:["Property","Description","Required","Allowed values","Example","Comments"],rows:requirements.map((item)=>[item.path,item.description??"",item.forbidden?"Not expected":item.required?"Yes":"No",item.allowedValues?.map(String).join(", ")??"",item.examples?.map(String).join(", ")??"",""])};
};
const contextHeading=(context:FlowDocumentationSnapshot["contexts"][number]):string=>`${context.pageName} / ${context.eventName}`;
const flowSourceRevision=(snapshot:FlowDocumentationSnapshot):number=>stableRevision({graphRevision:snapshot.graphRevision,contexts:snapshot.contexts.map(({id,effectiveRevision})=>({id,effectiveRevision}))});
interface MatrixContext {id:string;label:string;searchText:string;effectiveRevision:number;compiled:CompiledLayeredSchema;sourceId:string;flowSnapshot?:FlowDocumentationSnapshot}
const matrixState=(context:MatrixContext,path:string):string=>{
  if(context.compiled.conflicts.some((conflict)=>conflict.path===path))return"Blocked";const property=context.compiled.properties[path];if(!property)return"Not defined";if(property.presence==="forbidden")return"Not expected";if(property.condition)return"Conditional";return property.presence==="required"?"Mandatory":"Optional";
};

export function installProjectDocumentationWorkspaceUi(options:Options):{render(host:HTMLElement):void}{
  const ports=options.ports??defaultPorts();let selectedSetId="",selectedSectionId="",selectedExportIds=new Set<string>(),snapshot:ProjectDocumentationSnapshot|undefined,feedback="",confirmedIncomplete=false,exportScope:"current"|"selected"|"complete"="current";
  const currentDocumentation=()=>options.state()?.project.documentation??{sets:[],themes:[]};
  const persist=(documentation:{sets:ProjectDocumentationSet[];themes:ProjectDocumentationTheme[]},label:string)=>{options.save(documentation,label);};
  const replaceSet=(next:ProjectDocumentationSet,label:string)=>{const documentation=currentDocumentation();persist({...documentation,sets:documentation.sets.some(({id})=>id===next.id)?documentation.sets.map((value)=>value.id===next.id?next:value):[...documentation.sets,next]},label);};
  const replaceTheme=(next:ProjectDocumentationTheme,label:string)=>{const documentation=currentDocumentation();persist({...documentation,themes:documentation.themes.some(({id})=>id===next.id)?documentation.themes.map((value)=>value.id===next.id?next:value):[...documentation.themes,next]},label);};
  const active=()=>{const documentation=currentDocumentation(),set=documentation.sets.find(({id})=>id===selectedSetId)??documentation.sets[0],theme=set?documentation.themes.find(({id})=>id===set.themeId):undefined;return{documentation,set,theme};};
  const sources=()=>{const state=options.state();if(!state)return{flows:[] as {entity:ProjectEntity;snapshot:FlowDocumentationSnapshot}[],matrixContexts:[] as MatrixContext[]};const flows=state.project.collections.flows.map((entity)=>({entity,snapshot:flowDocumentationSnapshotFromState(state,entity.id,new Date().toISOString(),options.revision())})),direct=(entities:readonly ProjectEntity[],scope:"Page"|"Event"):MatrixContext[]=>entities.map((entity)=>{const contributors=layeredContributorsForPath(state,layeredContributorPath(state,entity,scope)),compiled=compileLayeredSchema(contributors,{eventId:entity.id,eventRole:scope==="Page"?"context":"interaction"}),label=`${scope} ${scope==="Event"?String(entity.eventName??entity.name):entity.name}`;return{id:`context:${scope.toLowerCase()}:${entity.id}`,label,searchText:label,effectiveRevision:stableRevision({entity,compiled}),compiled,sourceId:entity.id};}),instances=flows.flatMap(({entity,snapshot})=>snapshot.contexts.map((context)=>({id:context.id,label:`${context.kind==="page-instance"?"Flow Page instance":"Event occurrence"} ${entity.name} / ${contextHeading(context)}`,searchText:`${entity.name} ${context.pageName} ${context.eventName}`,effectiveRevision:context.effectiveRevision,compiled:context.compiled,sourceId:entity.id,flowSnapshot:snapshot})));return{flows,matrixContexts:[...direct(state.project.collections.pages,"Page"),...direct(state.project.collections.events,"Event"),...instances]};};
  const compile=():ProjectDocumentationSnapshot|undefined=>{const state=options.state(),{set,theme}=active();if(!state||!set||!theme)return;const available=sources(),tables:ProjectDocumentationTable[]=[],diagnostics:ProjectDocumentationDiagnostic[]=[],revisions:Record<string,number>={project:options.revision(),[set.id]:stableRevision(set),[theme.id]:stableRevision(theme)};
    for(const section of set.sections.filter(({selected})=>selected)){
      if(section.kind==="overview"){tables.push({id:section.id,title:section.name,headings:["Project","Value"],rows:[["Name",state.project.name],["Purpose",state.project.description],["Website",state.project.site]]});continue;}
      if(section.kind==="flow"){const source=available.flows.find(({entity})=>entity.id===section.targetId);if(!source){diagnostics.push({sectionId:section.id,message:`Flow ${section.name} is unavailable.`,repair:"Select an available Flow"});continue;}revisions[source.entity.id]=flowSourceRevision(source.snapshot);tables.push({...configureFlowDocumentationTable(source.snapshot,"values",section.configuration?.paths?{selectedPaths:section.configuration.paths}:{}),id:section.id,title:section.name});diagnostics.push(...source.snapshot.diagnostics.map((item)=>({sectionId:section.id,message:`${item.contextName}: ${item.issue}`,repair:item.repair})));continue;}
      if(section.kind==="profile"){const profile=state.project.collections.profiles.find(({id})=>id===section.targetId);if(!profile){diagnostics.push({sectionId:section.id,message:`Site Profile ${section.name} is unavailable.`,repair:"Select an available Site Profile"});continue;}revisions[profile.id]=stableRevision(profile);tables.push(profileTable(section,profile));continue;}
      const ids=section.configuration?.contextIds??[],byId=new Map(available.matrixContexts.map((context)=>[context.id,context])),selected=ids.flatMap((id)=>byId.has(id)?[byId.get(id)!]:[]),paths=[...new Set(selected.flatMap(({compiled})=>[...Object.keys(compiled.properties),...compiled.conflicts.map(({path})=>path)]))];for(const context of selected)revisions[context.sourceId]=context.flowSnapshot?flowSourceRevision(context.flowSnapshot):context.effectiveRevision;tables.push({id:section.id,title:"Data capture matrix",headings:["Property",...selected.map(({label})=>label)],rows:paths.map((path)=>[path,...selected.map((context)=>matrixState(context,path))]),legend:"Mandatory · Optional · Conditional · Not expected · Not defined · Blocked"});
    }
    return compileProjectDocumentationSnapshot({projectId:state.project.id,projectName:state.project.name,set,theme,sourceRevisions:revisions,generatedAt:new Date().toISOString(),tables,diagnostics});
  };
  const selection=(scope:string):ProjectDocumentationSelection=>{const {set}=active(),fallback=set?.sections[0]?.id??"";return scope==="current"?{scope:"current",currentSectionId:selectedSectionId||fallback}:scope==="selected"?{scope:"selected",selectedSectionIds:[...selectedExportIds]}:{scope:"complete"};};
  const mutateSection=(sectionId:string,update:(section:ProjectDocumentationSection)=>ProjectDocumentationSection,label:string)=>{const {set}=active();if(!set)return;replaceSet(createProjectDocumentationSet({...set,sections:set.sections.map((section)=>section.id===sectionId?update(section):section)}),label);};

  function render(host:HTMLElement):void{
    const state=options.state(),{documentation,set,theme}=active();host.replaceChildren();const root=document.createElement("section"),heading=document.createElement("h1");root.setAttribute("aria-label","Project Documentation workspace");heading.textContent="Documentation";root.append(heading);if(!state){root.append("Open a project to create documentation.");host.append(root);return;}
    if(!set||!theme){const name=document.createElement("input"),themeName=document.createElement("input"),create=button("Create Documentation Set",()=>{const themeId=`documentation-theme:${crypto.randomUUID()}`,setId=`documentation-set:${crypto.randomUUID()}`,nextTheme=defaultTheme(themeId,themeName.value.trim()||"Project theme"),nextSet=createProjectDocumentationSet({id:setId,name:name.value.trim()||"Client specification",themeId,sections:[{id:`${setId}:overview`,kind:"overview",name:"Overview",selected:true},{id:`${setId}:matrix`,kind:"matrix",name:"Data capture matrix",selected:true,configuration:{contextIds:[]}}]});selectedSetId=setId;selectedSectionId=nextSet.sections[0]!.id;persist({sets:[...documentation.sets,nextSet],themes:[...documentation.themes,nextTheme]},"Create Documentation Set");});name.setAttribute("aria-label","Documentation Set name");themeName.setAttribute("aria-label","Theme name");root.append(labelled("Set name",name),labelled("Theme name",themeName),create);host.append(root);return;}
    selectedSetId=set.id;if(!selectedSectionId||!set.sections.some(({id})=>id===selectedSectionId))selectedSectionId=set.sections[0]?.id??"";const available=sources();
    const setRegion=document.createElement("section"),content=document.createElement("section"),configure=document.createElement("section"),themeRegion=document.createElement("section"),preview=document.createElement("section"),exportRegion=document.createElement("section");for(const[region,title]of[[setRegion,"Set"],[content,"Content"],[configure,"Configure"],[themeRegion,"Theme"],[preview,"Preview"],[exportRegion,"Export"]] as const)region.append(Object.assign(document.createElement("h2"),{textContent:title}));
    const setChoice=document.createElement("select");setChoice.setAttribute("aria-label","Documentation Set");for(const candidate of documentation.sets)setChoice.append(new Option(candidate.name,candidate.id));setChoice.value=set.id;setChoice.addEventListener("change",()=>{selectedSetId=setChoice.value;snapshot=undefined;render(host);});setRegion.append(setChoice);
    const outline=document.createElement("ol");outline.setAttribute("aria-label","Documentation section outline");for(const section of set.sections){const item=document.createElement("li"),choose=button(`${section.name} · ${section.kind}`,()=>{selectedSectionId=section.id;render(host);});choose.setAttribute("aria-current",String(section.id===selectedSectionId));item.append(choose,button("Move earlier",()=>{const index=set.sections.findIndex(({id})=>id===section.id);if(index<=0)return;const sections=[...set.sections];[sections[index-1],sections[index]]=[sections[index]!,sections[index-1]!];replaceSet(createProjectDocumentationSet({...set,sections}),`Reorder ${section.name}`);}),button("Move later",()=>{const index=set.sections.findIndex(({id})=>id===section.id);if(index<0||index===set.sections.length-1)return;const sections=[...set.sections];[sections[index],sections[index+1]]=[sections[index+1]!,sections[index]!];replaceSet(createProjectDocumentationSet({...set,sections}),`Reorder ${section.name}`);}));outline.append(item);}setRegion.append(outline);
    const flowSearch=document.createElement("input"),profileSearch=document.createElement("input"),contextSearch=document.createElement("input");flowSearch.type=profileSearch.type=contextSearch.type="search";flowSearch.setAttribute("aria-label","Search Flows");profileSearch.setAttribute("aria-label","Search Site Profiles");contextSearch.setAttribute("aria-label","Search capture-matrix schema contexts");content.append(flowSearch,profileSearch,contextSearch);
    const selectors=document.createElement("div");const refreshSelectors=()=>{selectors.replaceChildren();for(const {entity} of available.flows.filter(({entity})=>entity.name.toLowerCase().includes(flowSearch.value.toLowerCase()))){const existing=set.sections.find((section)=>section.kind==="flow"&&section.targetId===entity.id),check=document.createElement("input");check.type="checkbox";check.checked=Boolean(existing);check.addEventListener("change",()=>{const sections=check.checked?[...set.sections,{id:`section:flow:${entity.id}`,kind:"flow" as const,name:entity.name,targetId:entity.id,selected:true}]:set.sections.filter(({id})=>id!==existing?.id);replaceSet(createProjectDocumentationSet({...set,sections}),`${check.checked?"Select":"Remove"} Flow ${entity.name}`);});selectors.append(labelled(`Flow value map ${entity.name}`,check));}for(const profile of state.project.collections.profiles.filter(({name})=>name.toLowerCase().includes(profileSearch.value.toLowerCase()))){const existing=set.sections.find((section)=>section.kind==="profile"&&section.targetId===profile.id),check=document.createElement("input");check.type="checkbox";check.checked=Boolean(existing);check.addEventListener("change",()=>{const sections=check.checked?[...set.sections,{id:`section:profile:${profile.id}`,kind:"profile" as const,name:profile.name,targetId:profile.id,selected:true}]:set.sections.filter(({id})=>id!==existing?.id);replaceSet(createProjectDocumentationSet({...set,sections}),`${check.checked?"Select":"Remove"} Site Profile ${profile.name}`);});selectors.append(labelled(`Site Profile ${profile.name}`,check));}const matrix=set.sections.find(({kind})=>kind==="matrix");for(const context of available.matrixContexts.filter(({searchText})=>searchText.toLowerCase().includes(contextSearch.value.toLowerCase()))){const check=document.createElement("input");check.type="checkbox";check.checked=matrix?.configuration?.contextIds?.includes(context.id)??false;check.addEventListener("change",()=>{if(!matrix)return;const current=matrix.configuration?.contextIds??[],contextIds=check.checked?[...current,context.id]:current.filter((id)=>id!==context.id);mutateSection(matrix.id,(section)=>({...section,configuration:{...section.configuration,contextIds}}),`${check.checked?"Select":"Remove"} matrix context ${context.label}`);});selectors.append(labelled(`Matrix context ${context.label}`,check));}};for(const input of[flowSearch,profileSearch,contextSearch])input.addEventListener("input",refreshSelectors);refreshSelectors();content.append(selectors);
    const selectedSection=set.sections.find(({id})=>id===selectedSectionId);if(selectedSection){configure.append(Object.assign(document.createElement("h3"),{textContent:`Configure ${selectedSection.name}`}),Object.assign(document.createElement("p"),{textContent:selectedSection.kind==="flow"?"Flow value-map contexts, property rows, metadata columns, documentation labels, and ordering.":selectedSection.kind==="matrix"?"Project-wide Page, Event, Flow Page-instance, and Event-occurrence columns.":selectedSection.kind==="profile"?"Property order and Property, Description, Required, Allowed values, Example, Comments columns.":"Project name, purpose, and website."}));}
    const themeName=document.createElement("input"),clientName=document.createElement("input");themeName.value=theme.name;clientName.value=theme.clientName;themeName.setAttribute("aria-label","Project-local theme name");clientName.setAttribute("aria-label","Theme client name");const saveTheme=button("Save theme",()=>replaceTheme(createProjectDocumentationTheme({...theme,name:themeName.value,clientName:clientName.value}),"Save project documentation theme"));themeRegion.append(themeName,clientName);for(const group of["Brand","Typography","Table","Header and footer"]){const details=document.createElement("details"),summary=document.createElement("summary");summary.textContent=group;details.append(summary,Object.assign(document.createElement("p"),{textContent:`${group} settings for preview, Excel, and rich clipboard output.`}));themeRegion.append(details);}const sample=document.createElement("table");sample.dataset.themeFingerprint=themeFingerprint(theme);sample.innerHTML="<thead><tr><th>Property</th><th>Description</th></tr></thead><tbody><tr><td>page_name</td><td>Page name</td></tr></tbody>";themeRegion.append(saveTheme,sample);
    const refresh=button("Refresh preview",()=>{snapshot=compile();feedback=snapshot?`Preview refreshed · ${snapshot.snapshotHash}`:"Preview unavailable";render(host);});preview.append(refresh);if(snapshot){const stale=projectDocumentationSnapshotStale(snapshot,compile()?.sourceRevisions??{});if(stale.stale)preview.append(Object.assign(document.createElement("p"),{textContent:`Preview stale — changed sources: ${stale.changedSources.join(", ")}.`,role:"alert"}));const selected=selectProjectDocumentationTables(snapshot,{scope:"complete"});for(const table of selected){const tableElement=document.createElement("table");tableElement.dataset.themeFingerprint=themeFingerprint(theme);const header=document.createElement("tr");header.append(...table.headings.map((value)=>Object.assign(document.createElement("th"),{textContent:value})));const body=table.rows.map((row)=>{const value=document.createElement("tr");value.append(...row.map((cell)=>Object.assign(document.createElement("td"),{textContent:cell})));return value;});tableElement.append(header,...body);preview.append(Object.assign(document.createElement("h3"),{textContent:table.title}),tableElement);}if(snapshot.diagnostics.length){const diagnostics=document.createElement("ul");diagnostics.setAttribute("aria-label","Documentation export preflight");for(const issue of snapshot.diagnostics)diagnostics.append(Object.assign(document.createElement("li"),{textContent:`${issue.message} · ${issue.repair}`}));preview.append(diagnostics);}}
    const scope=document.createElement("select");scope.setAttribute("aria-label","Documentation export scope");scope.append(new Option("Current section","current"),new Option("Selected sections","selected"),new Option("Complete Documentation Set","complete"));scope.value=exportScope;scope.addEventListener("change",()=>{exportScope=scope.value as typeof exportScope;});for(const section of set.sections){const check=document.createElement("input");check.type="checkbox";check.checked=selectedExportIds.has(section.id);check.addEventListener("change",()=>check.checked?selectedExportIds.add(section.id):selectedExportIds.delete(section.id));exportRegion.append(labelled(`Export ${section.name}`,check));}const confirm=document.createElement("input");confirm.type="checkbox";confirm.checked=confirmedIncomplete;const liveStale=snapshot?projectDocumentationSnapshotStale(snapshot,compile()?.sourceRevisions??{}).stale:false,blocked=!snapshot||liveStale||(snapshot.incomplete&&!confirmedIncomplete),copy=button("Copy rich documentation",()=>{if(!snapshot){feedback="Refresh preview before export.";render(host);return;}const stale=projectDocumentationSnapshotStale(snapshot,compile()?.sourceRevisions??{});if(stale.stale){feedback="Refresh the stale preview before export.";render(host);return;}try{const value=renderProjectDocumentationClipboard(snapshot,{...selection(exportScope),confirmIncomplete:confirmedIncomplete});void ports.writeRich(value.html,value.plain).then(()=>{feedback="Rich documentation copied with plain-text fallback.";render(host);});}catch(error){feedback=error instanceof Error?error.message:String(error);render(host);}}),download=button("Download Excel workbook",()=>{if(!snapshot){feedback="Refresh preview before export.";render(host);return;}try{const bytes=writeProjectDocumentationWorkbook(snapshot,{...selection(exportScope),confirmIncomplete:confirmedIncomplete});ports.download(`${set.name.toLowerCase().replace(/[^a-z0-9]+/gu,"-")}.xlsx`,bytes,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");feedback="Excel workbook downloaded.";render(host);}catch(error){feedback=error instanceof Error?error.message:String(error);render(host);}});confirm.addEventListener("change",()=>{confirmedIncomplete=confirm.checked;copy.disabled=download.disabled=!snapshot||liveStale||(snapshot.incomplete&&!confirmedIncomplete);});copy.disabled=download.disabled=blocked;exportRegion.append(scope,labelled("Confirm incomplete export",confirm),copy,download,Object.assign(document.createElement("output"),{textContent:feedback}));
    root.append(setRegion,content,configure,themeRegion,preview,exportRegion);host.append(root);
  }
  return{render};
}
