import {createCanonicalSchema} from "./data-layer-canonical-schema.js";
import {addProjectEntity,transactProject,type IdFactory,type ProjectEntity,type ProjectEntityKind,type ProjectState,type SpecificationProject} from "./data-layer-specification-project.js";

export interface ProjectCollectionDefinition {kind:ProjectEntityKind;overview:string;singular:string;addAction:string;purpose:string;example:string;prerequisites:string[];consumers:string[];}
export interface ProjectCollectionCreationField {key:string;label:string;control?:"text"|"number"|"textarea"|"checkbox"|"select";collection?:ProjectEntityKind;multiple?:boolean;options?:readonly {value:string;label:string}[];defaultValue?:string|number|boolean;}
export interface ProjectEntityDependency {kind:ProjectEntityKind|"flowGraph";id:string;name:string;relationship:string;}
export interface ProjectEntityRemovalReview {kind:ProjectEntityKind;id:string;name:string;dependencies:ProjectEntityDependency[];blocked:boolean;summary:string;}

export const projectCollectionDefinitions:Record<ProjectEntityKind,ProjectCollectionDefinition>={
  profiles:{kind:"profiles",overview:"Shared Profiles",singular:"Shared Profile",addAction:"Add Shared Profile",purpose:"reusable complete schemas for generic or event-specific variables",example:"Sitewide",prerequisites:["project Draft"],consumers:["Pages","Page Groups","Events","Flows"]},
  pageGroups:{kind:"pageGroups",overview:"Page Groups",singular:"Page Group",addAction:"Add Page Group",purpose:"shared Page context and inherited requirements",example:"Checkout",prerequisites:["optional Shared Profiles"],consumers:["Pages","Flow lanes"]},
  pages:{kind:"pages",overview:"Pages",singular:"Page",addAction:"Add Page",purpose:"observable Page context and specific requirements",example:"Cart",prerequisites:["optional Page Groups"],consumers:["Flows","Fixtures"]},
  events:{kind:"events",overview:"Events",singular:"Event",addAction:"Add Event",purpose:"reusable interaction events within Pages",example:"Purchase",prerequisites:["optional Shared Profiles"],consumers:["Flows","Assignments","Fixtures"]},
  applicabilitySets:{kind:"applicabilitySets",overview:"Applicability",singular:"Applicability Set",addAction:"Add Applicability Set",purpose:"named observation matching and assignment eligibility",example:"Retail checkout",prerequisites:["observable context fields"],consumers:["Pages","Events","Assignments"]},
  flows:{kind:"flows",overview:"Flows",singular:"Flow",addAction:"Add Flow",purpose:"documentary journey topology",example:"Checkout journey",prerequisites:["Pages","Events"],consumers:["documentation","Fixtures"]},
  fixtures:{kind:"fixtures",overview:"Fixtures",singular:"Fixture",addAction:"Add Fixture",purpose:"saved per-Event validation evidence",example:"Valid purchase",prerequisites:["Events","optional Flows"],consumers:["preflight","release evidence"]},
  assignments:{kind:"assignments",overview:"Assignments",singular:"Assignment",addAction:"Add Assignment",purpose:"production contributor selection for matching observations",example:"Retail Purchase",prerequisites:["canonical contributor","Event","optional Applicability Set"],consumers:["production evaluator"]},
};

export const projectCollectionCreationFields:Record<ProjectEntityKind,readonly ProjectCollectionCreationField[]>={
  profiles:[{key:"description",label:"Profile purpose",control:"textarea"}],
  pageGroups:[{key:"matcher",label:"Membership matcher"}],
  pages:[{key:"eventName",label:"Observed event name"},{key:"pathname",label:"Path matcher"},{key:"pageGroupIds",label:"Page Groups",control:"select",collection:"pageGroups",multiple:true}],
  events:[{key:"eventName",label:"Canonical event name"}],
  applicabilitySets:[{key:"priority",label:"Priority",control:"number",defaultValue:0},{key:"fallback",label:"Fallback",control:"checkbox",defaultValue:false}],
  flows:[{key:"correlationField",label:"Correlation field"}],
  fixtures:[{key:"mode",label:"Fixture mode",control:"select",options:[{value:"event",label:"Event"},{value:"flow",label:"Flow"}],defaultValue:"event"},{key:"eventId",label:"Event",control:"select",collection:"events"},{key:"pageId",label:"Page",control:"select",collection:"pages"},{key:"flowId",label:"Flow",control:"select",collection:"flows"},{key:"releasePolicy",label:"Release policy",control:"select",options:[{value:"required",label:"Required"},{value:"optional",label:"Optional"}],defaultValue:"required"}],
  assignments:[{key:"targetKind",label:"Contributor kind",control:"select",options:[{value:"Shared Profile",label:"Shared Profile"},{value:"Page Group",label:"Page Group"},{value:"Page",label:"Page"},{value:"Event",label:"Event"},{value:"Flow Page instance",label:"Flow Page instance"}],defaultValue:"Shared Profile"},{key:"targetId",label:"Contributor target",control:"select"},{key:"eventId",label:"Event",control:"select",collection:"events"},{key:"applicabilitySetId",label:"Applicability Set",control:"select",collection:"applicabilitySets"},{key:"priority",label:"Priority",control:"number",defaultValue:10}],
};

export function hasSavedSchemaAdoptionActions(kind:ProjectEntityKind,selectedId:string|undefined):boolean{return kind==="profiles"&&!selectedId;}
export function projectInspectorTogglePresentation(open:boolean):{label:string;expanded:"true"|"false"}{return{label:open?"Hide Inspector":"Show Inspector",expanded:open?"true":"false"};}
export function projectCollectionCreationRoute(kind:ProjectEntityKind):{kind:ProjectEntityKind;heading:string;label:string;backAction:string}{const definition=projectCollectionDefinitions[kind];return{kind,heading:`Create ${definition.singular}`,label:`Create ${definition.singular} for ${definition.overview}`,backAction:`Back to ${definition.overview}`};}
export function projectEntityWorkspaceRoute(kind:ProjectEntityKind,entityId:string,name:string):{kind:ProjectEntityKind;entityId:string;heading:string;label:string;backAction:string}{const definition=projectCollectionDefinitions[kind];return{kind,entityId,heading:`${definition.singular}: ${name}`,label:`${definition.singular} workspace for ${name}`,backAction:`Back to ${definition.overview}`};}

const containsIdentity=(value:unknown,identity:string):boolean=>{if(value===identity)return true;if(Array.isArray(value))return value.some((entry)=>containsIdentity(entry,identity));if(value&&typeof value==="object")return Object.values(value as Record<string,unknown>).some((entry)=>containsIdentity(entry,identity));return false;};
export function projectEntityDependencies(project:SpecificationProject,kind:ProjectEntityKind,identity:string):ProjectEntityDependency[]{const dependencies:ProjectEntityDependency[]=[];for(const[collection,entities]of Object.entries(project.collections) as [ProjectEntityKind,ProjectEntity[]][])for(const entity of entities)if(entity.id!==identity&&containsIdentity(entity,identity))dependencies.push({kind:collection,id:entity.id,name:entity.name,relationship:`${projectCollectionDefinitions[collection].singular} ${entity.name} references ${projectCollectionDefinitions[kind].singular}`});for(const[flowId,graph]of Object.entries(project.documentationFlowGraphs??{})){if(!containsIdentity(graph,identity))continue;const flow=project.collections.flows.find(({id})=>id===flowId);if(!dependencies.some(({id})=>id===flowId))dependencies.push({kind:"flowGraph",id:flowId,name:flow?.name??flowId,relationship:`Flow ${flow?.name??flowId} topology references ${projectCollectionDefinitions[kind].singular}`});}return dependencies;}
export function inspectProjectEntityRemoval(state:ProjectState,kind:ProjectEntityKind,identity:string):ProjectEntityRemovalReview{const entity=(state.project.collections[kind] as ProjectEntity[]).find(({id})=>id===identity);if(!entity)throw new Error(`Unknown ${projectCollectionDefinitions[kind].singular} ${identity}.`);const dependencies=projectEntityDependencies(state.project,kind,identity);return{kind,id:identity,name:entity.name,dependencies,blocked:Boolean(dependencies.length),summary:`${entity.name} · one ${projectCollectionDefinitions[kind].singular} removal · ${dependencies.length} dependent reference${dependencies.length===1?"":"s"} · project remains Draft and evidence becomes stale.`};}
export function removeProjectCollectionEntity(state:ProjectState,kind:ProjectEntityKind,identity:string):ProjectState{const review=inspectProjectEntityRemoval(state,kind,identity);if(review.blocked)throw new Error(`Remove ${review.name} is blocked by ${review.dependencies.map(({name})=>name).join(", ")}.`);return transactProject(state,`Remove ${review.name}`,(project)=>({...project,collections:{...project.collections,[kind]:(project.collections[kind] as ProjectEntity[]).filter(({id})=>id!==identity)}} as SpecificationProject));}

const firstId=(project:SpecificationProject,kind:ProjectEntityKind):string|undefined=>project.collections[kind][0]?.id;
function projectCreationAttributes(state:ProjectState,kind:ProjectEntityKind,values:Readonly<Record<string,unknown>>):Record<string,unknown>{const attributes:Record<string,unknown>={};for(const field of projectCollectionCreationFields[kind]){const value=values[field.key];if(value===undefined)continue;if(field.multiple){const identities=Array.isArray(value)?value.map(String).filter(Boolean):[];if(field.collection){const known=new Set(state.project.collections[field.collection].map(({id})=>id));if(identities.some((identity)=>!known.has(identity)))throw new Error(`${field.label} contains an unknown project reference.`);}attributes[field.key]=identities;continue;}if(field.control==="checkbox"){attributes[field.key]=Boolean(value);continue;}if(field.control==="number"){const numeric=Number(value);if(!Number.isFinite(numeric))throw new Error(`${field.label} must be a number.`);attributes[field.key]=numeric;continue;}const text=String(value).trim();if(!text)continue;if(field.collection&&!state.project.collections[field.collection].some(({id})=>id===text))throw new Error(`${field.label} does not exist in this project.`);if(field.options&&!field.options.some(({value:option})=>option===text))throw new Error(`${field.label} has an unsupported value.`);attributes[field.key]=text;}if(kind==="assignments"){const targetKind=String(attributes.targetKind??""),targetId=String(attributes.targetId??"");if(!targetId||!assignmentTargetExists(state.project,targetKind,targetId))throw new Error("Contributor target does not exist in this project.");if(typeof attributes.eventId==="string"){const selectedEvent=state.project.collections.events.find(({id})=>id===attributes.eventId);attributes.eventName=selectedEvent?.eventName??selectedEvent?.name;}}return attributes;}
function assignmentTargetExists(project:SpecificationProject,targetKind:string,targetId:string):boolean{const collection=targetKind==="Shared Profile"?project.collections.profiles:targetKind==="Page Group"?project.collections.pageGroups:targetKind==="Page"?project.collections.pages:targetKind==="Event"?project.collections.events:targetKind==="Flow Page instance"?Object.values(project.documentationFlowGraphs??{}).flatMap((graph)=>((graph as {pageFrames?:ProjectEntity[]}).pageFrames??[])):[];return collection.some(({id})=>id===targetId);}
export function createProjectCollectionEntity(state:ProjectState,kind:ProjectEntityKind,name:string,id:IdFactory,values:Readonly<Record<string,unknown>>={}):ProjectState{const clean=name.trim();if(!clean)throw new Error(`${projectCollectionDefinitions[kind].singular} name is required.`);if((state.project.collections[kind] as ProjectEntity[]).some((entity)=>entity.name.toLowerCase()===clean.toLowerCase()))throw new Error(`${projectCollectionDefinitions[kind].singular} name must be unique in this project.`);const event=state.project.collections.events[0],eventId=event?.id,pageId=firstId(state.project,"pages"),flowId=firstId(state.project,"flows"),applicabilitySetId=firstId(state.project,"applicabilitySets"),attributes=projectCreationAttributes(state,kind,values),canonicalSchema=(["profiles","pageGroups","pages"] as ProjectEntityKind[]).includes(kind)?createCanonicalSchema({id:id("canonical-schema"),contributorId:"",contributorName:clean}):undefined;if(kind==="pages"&&!attributes.eventName)throw new Error("Observed event name is required for a Page.");const canonicalDefault=canonicalSchema?{canonicalSchema}:{},defaults:Record<ProjectEntityKind,Record<string,unknown>>={profiles:{requirements:[],...canonicalDefault},pageGroups:{pageIds:[],...canonicalDefault},pages:{pageGroupIds:[],...canonicalDefault},events:{eventName:clean.toLowerCase().replace(/[^a-z0-9]+/g,"_"),sourceId:"event-history",target:"payload"},applicabilitySets:{priority:0,condition:{kind:"all",conditions:[]}},flows:{steps:[]},fixtures:{mode:"event",observations:[],expected:{},releasePolicy:"required",...(eventId?{eventId}:{}),...(pageId?{pageId}:{}),...(flowId?{flowId}:{})},assignments:{...(eventId?{eventId,eventName:event?.eventName??event?.name}:{}),...(applicabilitySetId?{applicabilitySetId}:{}),sourceId:"event-history",target:"payload",priority:10}};return addProjectEntity(state,kind,{name:clean,...defaults[kind],...attributes},id);}
