import {canonicalPropertyPath,canonicalTableRows,type CanonicalPropertyNode,type CanonicalSchemaDocument} from "./data-layer-canonical-schema.js";
import type {FocusedPropertySection} from "./data-layer-focused-schema-property-ui.js";
import type {CanonicalSchemaEditorOptions} from "./data-layer-canonical-schema-ui.js";

export interface CanonicalSchemaRenderContext {
  dom:Document;options:CanonicalSchemaEditorOptions;document:CanonicalSchemaDocument;query:string;feedback:string;activePropertyId:string|undefined;activeSection:FocusedPropertySection;menuPropertyId:string|undefined;working:CanonicalPropertyNode|undefined;review:HTMLElement|undefined;
  current:()=>CanonicalSchemaDocument;setQuery:(value:string)=>void;setFeedback:(value:string)=>void;setMenuPropertyId:(value:string|undefined)=>void;ensureWorking:(node:CanonicalPropertyNode)=>void;selectedNode:(document:CanonicalSchemaDocument)=>CanonicalPropertyNode|undefined;openProperty:(node:CanonicalPropertyNode,focus?:HTMLElement,section?:FocusedPropertySection)=>void;command:(command:Parameters<CanonicalSchemaEditorOptions["dispatch"]>[0])=>unknown;render:()=>void;renderMenu:(node:CanonicalPropertyNode)=>HTMLElement;renderFocusedEditor:(document:CanonicalSchemaDocument,node:CanonicalPropertyNode)=>HTMLElement;
}

const input=(dom:Document,name:string,value="",type="text"):HTMLInputElement=>{const control=dom.createElement("input");control.name=name;control.type=type;control.value=value;return control;};
const labeled=(dom:Document,text:string,control:HTMLElement):HTMLLabelElement=>{const label=dom.createElement("label");label.append(text,control);return label;};
const button=(dom:Document,text:string,run:()=>void):HTMLButtonElement=>{const control=dom.createElement("button");control.type="button";control.textContent=text;control.addEventListener("click",run);return control;};

export function renderCanonicalSchemaEditor(context:CanonicalSchemaRenderContext):void {
  const {dom,options,document}=context;options.host.replaceChildren();options.host.setAttribute("aria-label",`${options.surface} canonical schema editor`);options.host.dataset.canonicalSchemaId=document.id;options.host.dataset.canonicalRevision=String(document.revision);options.host.dataset.canonicalEditorMode="focused-property";
  const header=dom.createElement("header"),title=dom.createElement("h2"),status=dom.createElement("p"),undo=button(dom,"Undo",()=>options.onUndo?.()),redo=button(dom,"Redo",()=>options.onRedo?.());title.textContent=document.contributorName;status.setAttribute("aria-label","Canonical Draft status");status.textContent=`Draft · ${document.source?`source ${document.source.identity} revision ${document.source.revision}`:"no source revision"} · lineage ${document.source?.provenance??"project-created"} · Saved · Draft token ${document.revision}`;undo.disabled=!options.onUndo;redo.disabled=!options.onRedo;header.append(title,status,undo,redo);
  const navigator=dom.createElement("section"),search=dom.createElement("input"),filter=dom.createElement("select"),tree=dom.createElement("div"),rootName=input(dom,"newRootPropertyName","property"),addRoot=button(dom,"Add root property",()=>{const name=rootName.value.trim();if(name)context.command({kind:"add",baseRevision:document.revision,name,type:"string",id:options.id});});navigator.setAttribute("aria-label","Canonical property navigator");search.type="search";search.setAttribute("aria-label","Canonical property search");search.placeholder="Search properties";search.value=context.query;search.addEventListener("input",()=>{context.setQuery(search.value);context.render();});filter.name="propertyFilter";filter.append(...["All properties","With conditions","With documentation","With issues"].map((entry)=>new Option(entry,entry)));tree.setAttribute("aria-label","Canonical property search results");for(const row of canonicalTableRows(document).filter(({node})=>node.name.toLowerCase().includes(context.query.toLowerCase()))){const article=dom.createElement("article"),choose=button(dom,`${"› ".repeat(row.depth)}${row.node.name} · ${row.path} · ${row.node.type}`,()=>context.openProperty(row.node,choose));choose.dataset.propertyId=row.id;choose.setAttribute("aria-current",String((context.activePropertyId??document.selectedPropertyId)===row.id));article.dataset.propertyRow="true";article.dataset.propertyId=row.id;const actions=button(dom,"Property actions",()=>{context.setMenuPropertyId(row.id);context.openProperty(row.node,actions);});actions.setAttribute("aria-label",`Property actions for ${row.path}`);actions.dataset.propertyActionsPath=row.path;article.append(choose,actions);if(context.menuPropertyId===row.id)article.append(context.renderMenu(row.node));tree.append(article);}
  navigator.append(search,filter,tree,labeled(dom,"New root property name",rootName),addRoot);options.host.append(header,navigator);
  const body=dom.createElement("tbody");for(const article of Array.from(tree.children)){const row=dom.createElement("tr"),cell=dom.createElement("td");cell.append(article);row.append(cell);body.append(row);}tree.replaceChildren(body);tree.setAttribute("role","table");
  navigator.prepend(button(dom,"Table",()=>{}),button(dom,"Tree",()=>{}));
  const node=context.selectedNode(document);if(node&&context.activePropertyId===node.id){context.ensureWorking(node);options.host.append(context.renderFocusedEditor(document,node));if(context.review)options.host.append(context.review);}
  const preview=dom.createElement("section"),previewHeading=dom.createElement("h3"),previewText=dom.createElement("p"),feedbackOutput=dom.createElement("output");preview.setAttribute("aria-label","Effective documentation preview");previewHeading.textContent="Effective documentation";previewText.textContent=node?[node.documentation.displayText,node.documentation.description,node.documentation.comments].filter(Boolean).join(" · ")||"No documentation yet.":"Select a property.";preview.append(previewHeading,previewText);feedbackOutput.setAttribute("aria-label","Canonical command result");feedbackOutput.textContent=context.feedback;options.host.append(preview,feedbackOutput);
}
