import type {CanonicalPropertyNode} from "../data-layer-canonical-schema.js";
import type {CanonicalFocusedSectionContext} from "../data-layer-canonical-schema-focused-sections.js";
import {button,input,labeled} from "./dom.js";

export const applyStructure=(context:CanonicalFocusedSectionContext,operation:Parameters<CanonicalFocusedSectionContext["stageStructure"]>[0]):void=>context.stageStructure(operation);

export const renderCanonicalStructuralControls=(dom:Document,context:CanonicalFocusedSectionContext,working:CanonicalPropertyNode):HTMLElement[]=>{const document=context.current(),siblings=Object.values(document.nodes).filter(({parentId})=>parentId===working.parentId).sort((left,right)=>left.order-right.order||left.id.localeCompare(right.id)),index=siblings.findIndex(({id})=>id===working.id),earlier=button(dom,"Move earlier",()=>{if(index<=0)return;const afterId=index>1?siblings[index-2]!.id:undefined;applyStructure(context,{kind:"move",propertyId:working.id,...(working.parentId?{parentId:working.parentId}:{}),...(afterId?{afterId}:{})});}),later=button(dom,"Move later",()=>{if(index<0||index>=siblings.length-1)return;applyStructure(context,{kind:"move",propertyId:working.id,...(working.parentId?{parentId:working.parentId}:{}),afterId:siblings[index+1]!.id});}),toRoot=button(dom,"Move to root",()=>{if(!working.parentId)return;applyStructure(context,{kind:"move",propertyId:working.id});}),duplicate=button(dom,"Duplicate",()=>applyStructure(context,{kind:"duplicate",propertyId:working.id,id:context.id})),remove=button(dom,"Delete property",()=>applyStructure(context,{kind:"delete",propertyId:working.id}));earlier.disabled=index<=0;later.disabled=index<0||index>=siblings.length-1;toRoot.disabled=!working.parentId;return[earlier,later,toRoot,duplicate,remove];};

export function renderStructureFacet(host:HTMLElement,context:CanonicalFocusedSectionContext,working:CanonicalPropertyNode):void {
  const {dom}=context,name=input(dom,"structureName",working.name),newName=input(dom,"newStructureName","property"),terminalItem=(()=>{let item=working.itemSchema;while(item?.type==="array")item=item.items;return item?.type??working.itemType;})();name.addEventListener("input",()=>{const next=context.getWorking();if(next)next.name=name.value;});
  let childControls:HTMLElement[]=[];
  if(working.type==="array"&&terminalItem==="object"){
    const itemName=input(dom,"itemPropertyName","property"),add=button(dom,"Add item property",()=>applyStructure(context,{kind:"add",propertyId:working.id,parentId:working.id,name:itemName.value.trim()||"property",type:"string",id:context.id}));
    childControls=[labeled(dom,"Item property name",itemName),add];
  }else if(working.type!=="array")childControls=[button(dom,"Add child",()=>applyStructure(context,{kind:"add",propertyId:working.id,parentId:working.id,name:"child",type:"string",id:context.id}))];
  const removable=(candidate:CanonicalPropertyNode):boolean=>candidate.structureOwned===true||!candidate.inheritedDefinition,localRemoval=removable(working)?[button(dom,`Remove local ${working.name}`,()=>applyStructure(context,{kind:"delete",propertyId:working.id}))]:[],localSiblingRemovals=Object.values(context.current().nodes).filter((candidate)=>candidate.id!==working.id&&candidate.parentId===working.parentId&&removable(candidate)).map((candidate)=>button(dom,`Remove local ${candidate.name}`,()=>applyStructure(context,{kind:"delete",propertyId:candidate.id})));
  host.append(Object.assign(dom.createElement("p"),{textContent:`Stable identity ${working.id} · ${context.current().id}`}),labeled(dom,"Name",name),...childControls,labeled(dom,"New local property name",newName),button(dom,"Add sibling",()=>applyStructure(context,{kind:"add",propertyId:working.id,...(working.parentId?{parentId:working.parentId}:{}),afterId:working.id,name:newName.value.trim()||"property",type:"string",id:context.id})),...localRemoval,...localSiblingRemovals,...renderCanonicalStructuralControls(dom,context,working));
}
